### ISSUE TITLE
Editor not correctly displayed in modal forms

### ISSUE THREAD

**Issue by flp-gpc** [JiHong88/SunEditor#1]
Hello,

I have an issue when I try to display the editor in a modal form: 

![image](https://cloud.githubusercontent.com/assets/1489018/26286438/bdaaddd2-3e65-11e7-8e70-e280ea01b582.png)

When I inspect the element in DOM, it seems it is not displayed: (I didn't put the style, it was dynamically rendered by suneditor).

`<textarea id="textedit" style="display: none;">Hello World!</textarea>`

Even when I call the .show() after the load, the element is still not correctly rendered. Any idea ?

**Comment by JiHong88** [comment]
Hi
The suneditor will render with the height and width of the target <textarea>
If "display: none", width will be zero.
In such cases, you can use the "width" and "height" properties.
EX) `var suneditor = SUNEDITOR.create('id',{width:'100%', height:'auto'})`
And fixed the style to be applied correctly when created with display: none,
And when rendering suneditor with "display: none"
when calling ".show ()", add an option value called "display" to enter the display value of style
Thank you^^

**Comment by flp-gpc** [comment]
Hi, it works indeed with `SUNEDITOR.create('id',{width:'100%', height:'auto'})`

Thank you for your quick reply, your editor is really nice !
