### ISSUE TITLE
Please use fonts (like fontawesome fonts) instead of images

### ISSUE THREAD

**Issue by drnkwati** [JiHong88/SunEditor#10]
Hi I wanted to suggest that you use fonts instead of images to improve http request performance
I suggest Fontawesome fonts or you can combine the images into a single sprite or svg file

**Comment by JiHong88** [comment]
Hi! I wanted use fontawesome but, 
I did not use it because I wanted to maintain a pure JavaScript-based identity.
I will use single sprite or svg file after modularization.
What do you think?

**Comment by drnkwati** [comment]
SVG is a great option, so it scales proportionately

**Comment by JiHong88** [comment]
Hi~
I processed converted png file to svg and modified icon css.
The icon path and so on can be found in the suneditor.css file.

**Comment by drnkwati** [comment]
The icons are separate files. I was thinking a sprite will be better.

**Comment by JiHong88** [comment]
I did not apply it because I did not know how to merge svg files
I will merge soon :)

**Comment by JiHong88** [comment]
Hi ~

merged svg files and applied them as web fonts.

now suneditor do not download many files : )

v1.10.3
