### ISSUE TITLE
Drag-drop or copy-pasted images break the editor 

### ISSUE THREAD

**Issue by DeZZar** [JiHong88/SunEditor#100]
Hi @JiHong88,

I have found a couple of issues with images.

First is that any images that are either copy-pasted or dragged and dropped into the editor appear to break all the standard image functionality. I.e. none of the resize works or any other image features.  To replicate just find any online content that contains an image, copy it and paste it into the editor. You'll find attempting to resize to say 25% wont work.

Second is that you dont seem to be able to place the cursor at the beginning of the image and move it down. When an image is inserted as the first thing into the editor an empty pararaph is created on top of the image (I suspect as a way to allow the cursor to be placed above the image for new lines) which cannot be removed (unless you direct edit HTML).  However, it would be far better to remove the auto addition of the paragraph and allow the user to place the cursor at the start of the image where pressing enter would move the image down (create paragraphs above).

Regards,
Derrick

**Comment by JiHong88** [comment]
Hi @DeZZar 

Thank you very much for your feedback.

Fixed in [v2.15.3](https://github.com/JiHong88/SunEditor/releases/tag/2.15.3)

Thank you.
