### ISSUE TITLE
Select Span as a single element

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/suneditor#1000]
I have the ability for users to insert some meta data (e.g. the day).  it goes into the edit like this...

`<span class="metaData">Wednesday </span>`

there could be user text on either side of the span e.g.
`
My favourite day of the week is <span class="metaData">Wednesday </span> becuase I have PE at school.`

I want to make it so the metaData span is treated as a single "lump", e.g. if they click anywhere in it, it highlights the entire span. If they overwrite it, it gets rid of the entire span, etc.

Hopefully, this makes sense. ANy pointers would be much appriciated

**Comment by sdraper69** [comment]
I have managed to solve this, doing the following...


```
  this.editor.onClick = function (e, core) {
        let range, selection;
        let element = $(event.target);
        if(element.hasClass("metaData")){
            if (window.getSelection && document.createRange) {
                selection = window.getSelection();
                range = document.createRange();
                range.selectNodeContents(element[0]);
                selection.removeAllRanges();
                selection.addRange(range);
            } else if (document.selection && document.body.createTextRange) {
                range = document.body.createTextRange();
                range.moveToElementText(element[0]);
                range.select();
            }
      }
   }
```

**Comment by JiHong88** [comment]
Thanks for sharing your solution.

**Comment by sdraper69** [comment]
whilst this works, one problem I cant over come, if i do have the following in the editor...

`My favourite day of the week is <span class="metaData">Wednesday </span> becuase I have PE at school.`

When the user clicks anywhere in the word Wednesday, the whole span now gets clicked, that is the behavior I want. However, if the user starts typing, hence overwriting that range, it still keeps the span metaData. So I could end up with 

My favourite day of the week is <span class="metaData">user typed</span> becuase I have PE at school.

whereas I want it to be 
`
My favourite day of the week is user typed becuase I have PE at school.`

How can I make it so the span is completely overwritten/removed when the user types within it?

**Comment by JiHong88** [comment]
In a simple implementation, you can do something like this:
```
this.editor.onClick = function (e, core) {
    const element = event.target
    if(core.util.hasClass(element, "metaData")){
        const a = core.util.createTextNode(core.util.zeroWidthSpace);
        const a1 = core.util.createTextNode(core.util.zeroWidthSpace);
        element.parentNode.insertBefore(a, element);
        element.parentNode.insertBefore(a1, element.nextSibling);
        core.setRange(a, 0, a1, 1);
    }
}
```

**Comment by sdraper69** [comment]
Great that does it thanks alot

**Comment by sdraper69** [comment]
Worth noting that whilst the above works, every time you click in you get a zero width space, so you can end up with a lot if you are not careful. Would be great if there was a cleaner way of achieving this

**Comment by JiHong88** [comment]
```javascript
editorInstance.onClick = (event, core) => {
    const element = event.target
    if(core.util.hasClass(element, "metaData")){
        core.setRange(element, 0, element, 1);
    }
}

editorInstance.onKeyDown = (event, core) => {
    const range = core.getRange();
    if(core.util.hasClass(range.commonAncestorContainer, "metaData")){
        core.util.removeItem(range.commonAncestorContainer);
    }
}

```

**Comment by sdraper69** [comment]
Since someone else also asked for this. One further question..

This all works great, if you click in the span itself. But doesn't work if you delete backwards from outside.

If you are outside of the span, and use the backspace key, it won't recognize that you are deleting the range, instead just delete the character as normal. Is there any way to detect, when pressing backpass that you will be deleting the span as technically i don't think where the cursor is ever has the class i am looking for

**Comment by sdraper69** [comment]
one possible solution for anyone interested...

```
editorInstance.onKeyDown = (event, core) => {
   if (event.keyCode === 37 || event.keyCode === 39 || event.keyCode === 38 || event.keyCode === 40 || event.keyCode === 16) { // ARROWS or SHIFT key
            return;
        }
   
        let range = core.getRange();
        if (core.util.hasClass(range.commonAncestorContainer, "metaData")) {
            core.util.removeItem(range.commonAncestorContainer);
        }

      
        let el = range.startContainer.parentElement
        if (el.classList.contains('metaData')) {
            // Check if we are exactly at the end of the metaData element
            if (range.startOffset == range.endOffset && range.endOffset == el.textContent.length) {
                if (event.keyCode == 8) {
                    event.preventDefault();
                   //code to highlight or delete span
                } 
            }
        }
}
```

**Comment by sdraper69** [comment]
whilst the above seems to work, the removeItem seems to delete the span from the div with classes "se-wrapper-inner se-wrapper-wysiwyg sun-editor-editable" which is the visible thing you see on screen, it is keeping the span in , i am finding that it still is present in the <textarea> that sits above it and is hidden.

@JiHong88 any suggestions? 

Should core.util.removeItem remove from both places?
