### ISSUE TITLE
How to Handle Tab Stops

### ISSUE THREAD

**Issue by s-ashwin** [JiHong88/suneditor#1005]
**How to Handle Tab Stops**
Tab key by default inserts four `&nbsp;` elements. This Behaviour might not properly align different text content

**To Reproduce**
1. Open a blank document
2. Type `Name`, hit TAB key twice, type `:`
3. Enter New Line
4. Type `Age`, hit TAB key twice, type `:`

**Current Behavior**
<img width="108" alt="Screenshot 2022-05-18 at 1 49 57 PM" src="https://user-images.githubusercontent.com/47049152/169000654-f1fe53f1-cee0-4c25-a915-3827289dcd89.png">

**Expected Behavior**
<img width="108" alt="Screenshot 2022-05-18 at 1 52 36 PM" src="https://user-images.githubusercontent.com/47049152/169000603-b27e233d-17fc-4a1e-9129-2e053d25eb6f.png">

**Desktop:**
 - OS: macOS Monterey
 - Browser: Chrome, Firefox

**Comment by JiHong88** [comment]
The tab key inserts `<space>&nbsp;<space>&nbsp;`.
It does not adjust the space of the tab key based on the character in the upper line.
<img width="274" alt="스크린샷 2022-05-19 오후 8 35 07" src="https://user-images.githubusercontent.com/13191953/169284194-4ff632f5-7b37-4619-87db-9db335532f38.png">

**Comment by s-ashwin** [comment]
Thanks for your reply @JiHong88. I’d like to know if there are any possible ways to achieve it

**Comment by JiHong88** [comment]
yes it seems possible
But time is running out.😢
I will add it in version 3.0.0.
