### ISSUE TITLE
Reopen #927 Formatting combinations is not disabled

### ISSUE THREAD

**Issue by kapraltv** [JiHong88/SunEditor#1007]
Describe the bug
The formatting doesn`t work as it is supposed to.

To Reproduce

Go to 'Options' tab of the SunEditor site
Click on the shortcutsDisable parameter
Create a new configuration
Write text and click on formatting [combinations]

@JiHong88 Hi, 
Could you also add a combination of italics and underscores like you did for the bold combination in https://github.com/JiHong88/SunEditor/issues/927 ? Thanks in advance!

**Comment by JiHong88** [comment]
"shortcutsDisable" is an option to disable shortcuts.
```
{
   shortcutsDisable ['underline', 'italic']
}
```

**Comment by kapraltv** [comment]
If I add 'underline', 'italic' in shortcutsDisable array, I can still change a text style like 'underline' or 'italic' using combination but it shouldn't be. I hope that I understand correctly this behavior.

**Comment by JiHong88** [comment]
Um.. Also, remove "underline" and "italic" from the button list.

**Comment by kapraltv** [comment]
Unfortunately, it doesn't help(
My options contaions the following parameters:

shortcutsDisable: ['bold', 'underline', 'italic'],
buttonList: [
['undo', 'redo'],
['font', 'fontSize', 'formatBlock'],
['paragraphStyle', 'blockquote'],
['strike', 'subscript', 'superscript'],
[
':t-More Text-default.more_text',
'fontColor',
'hiliteColor',
'textStyle'
],
'/', 
['outdent', 'indent'],
['align', 'horizontalRule', 'list', 'lineHeight'],
['table', 'link', 'image', 'video', 'audio' /** ,'math' */],
['removeFormat'],
['fullScreen', 'showBlocks', 'codeView'],
[
'-left',
'preview',
'print',
'save'
],
['template']
],

**Comment by JiHong88** [comment]
It seems to be a shortcut function of the browser.
It will be fixed in the next version.

**Comment by kapraltv** [comment]
Thanks!

**Comment by JiHong88** [comment]
The [2.43.6](https://github.com/JiHong88/SunEditor/releases/tag/2.43.6) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
