### ISSUE TITLE
Set custom width for table cells / columns

### ISSUE THREAD

**Issue by s-ashwin** [JiHong88/suneditor#1010]
Is there any possible ways to customise the cell/column width of the table? At present it has only fixed column width option

**Comment by JiHong88** [comment]
It will be added in version 3.0.0.

**Comment by SergiuPlesco** [comment]
Hi @JiHong88, 
can you, please, point me to an example on how to use this feature of resizing cell/column width of the table? 
Or, is the equal size cells/columns that feature?
