### ISSUE TITLE
Is there any plugin/feature available for setting editor behave on some string treat as a single entity?

### ISSUE THREAD

**Issue by amansharmaagami** [JiHong88/SunEditor#1019]
## Version
suneditor - 2.42.0
suneditor-react - 3.4.0,

## Additional context

I want to make a template editor in our SaaS which will be handlebars template.
the behaviour I wanted is to treat ```{{ var }}``` as a single entity.

**Comment by vijaygawariya** [comment]
+1

**Comment by JiHong88** [comment]
What "single entity" do you mean?

**Comment by amansharmaagami** [comment]
Single entity like a Single character,
if we press backspace it should delete whole string ```{{ var }}```

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/issues/1000#issuecomment-1140273726
Take advantage of this issue.
If you put span tag and separate key codes, you can implement it.

**Comment by vijaygawariya** [comment]
Thank You @JiHong88.
it's working for me.

I found a simple solution also.
<span contenteditable='false' style="margin: 0px 5px">{{key}}</span>

It's working for me.
