### ISSUE TITLE
Set content / Default content - Text align styles doesn't apply

### ISSUE THREAD

**Issue by josedaesbar** [JiHong88/SunEditor#1026]
## **Version**
suneditor - 2.43.8
suneditor-react - 3.4.0,

Setting a default value with setContents or defaultValue for the editor applies all styles, but does not apply text alignment, for example:
 `defaultValue='<p style="text-align: center;">'`
 `setContents='<p style="text-align: center;">'`

The default values in the example are the ones I store from the editor when I edit and get the code produced.

## **Additional context**
Example of the issue: https://codesandbox.io/s/suneditor-issue-uxhcq9?file=/src/App.js

**Comment by JiHong88** [comment]
The [2.43.9](https://github.com/JiHong88/SunEditor/releases/tag/2.43.9) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
