### ISSUE TITLE
onPaste with list

### ISSUE THREAD

**Issue by KimseungMoo** [JiHong88/SunEditor#1027]
**Describe the bug**

**To Reproduce**
1. ul태그에서 붙여넣기
2. ul태그가 ol태그로, p태그가 전부 li태그로 바뀜 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Version [크롬 101.0.4951.64, macOS Monterey 12.4]

**Additional context**

https://user-images.githubusercontent.com/77320847/172575017-1e7274cd-fd6e-4b2b-9d6f-44546b37222e.mov

아래 사이트 본문 내용으로 확인하실 수 있습니다.
https://blog.naver.com/wajchu1120/222763285861

**Comment by JiHong88** [comment]
리스트에 붙여넣을때 의도된 동작 입니다.

**Comment by KimseungMoo** [comment]
붙여넣기한 element만 따로 확인할 방법이 있을까요?
onPaste 매개변수로 전달되는 e.path를 보니까 리스트가 변형되기 이전의 element를 받아오는 것 같아요

**Comment by JiHong88** [comment]
`core.insertHTML()` 메소드 에서 변형하는거라 onPaste에서는 확인할 수 없습니다.
도움이 될지 모르겠지만 아래 코드가 리스트에 붙여넣을때 변형하는 코드입니다.
```javascript
if (util.isListCell(util.getFormatElement(core.getSelectionNode(), null))) {
  const dom = _d.createRange().createContextualFragment(html);
  const domTree = dom.childNodes;
  if (core._isFormatData(domTree)) html = core._convertListCell(domTree);
}
```
