### ISSUE TITLE
이미지 삽입후 line-break-component 추가후 타이핑 에러

### ISSUE THREAD

**Issue by moljin** [JiHong88/SunEditor#1031]
이미지 없이 타이핑할 때와, 이미지 삽입후 영문 타이핑에서는 영상과 같은 에러가 없습니다.
유독 이미지 삽입후 line-break-component 추가후 첫 한글 타이핑에서만 동일한 에러가 발생하고 있습니다.
===첫타이핑인 "ㄱ"(기억자)가 지워집니다. 
뭔가 충돌이 일어나는 거 같은데....이유를   ##모르겠습니다.

https://user-images.githubusercontent.com/84114031/173177478-370b187d-d754-4449-b5d7-21c2f01d9c9a.mp4

**Comment by JiHong88** [comment]
The [2.43.10](https://github.com/JiHong88/SunEditor/releases/tag/2.43.10) 버전이 업데이트 되었습니다.
이슈가 해결되지 않은 경우 이 이슈를 다시 열어주세요.
감사합니다.
