### ISSUE TITLE
CodeMirror 6 support

### ISSUE THREAD

**Issue by a-tonchev** [JiHong88/SunEditor#1032]
First of all thanks for the perfect editor! We use it already in our SaaS. 

I know that CodeMirror 6 is quite new, but what do you think, when will be possible to have CodeMirror 6 support on the suneditor?

I like the documentation of CodeMirror 6 better.

**Comment by JiHong88** [comment]
Currently, new feature being applied to version 3 except for simple or critical fixes.

**Comment by a-tonchev** [comment]
@JiHong88 thanks, when is the version 3 release date planned?
