### ISSUE TITLE
window에서 복사/붙여넣기

### ISSUE THREAD

**Issue by KimseungMoo** [JiHong88/SunEditor#1033]
window Chrome에서 텍스트를 복사/붙여넣기 했을 때 br태그가 추가됩니다.

https://user-images.githubusercontent.com/77320847/173713426-3f162a91-1cc0-433d-a987-63bcb5cf7134.mp4

위 영상의 원본 html입니다.
```
<ol>
  <li>
    <br>
    <br>
    dsfdsdsfdf
    <br>
    &ZeroWidthSpace;
  </li>
  <li>
    <br>
    <br>
    dsfdsdsfdf
  </li>
  <li>sadsadsad</li>
  <li> 
   <br>
    <br>
    dsfdsdsfdf
    <br>
    <br>
    <br>
    <br>
    <br>
  </li>
</ol>
```

**Comment by JiHong88** [comment]
The [2.43.10](https://github.com/JiHong88/SunEditor/releases/tag/2.43.10) 버전이 업데이트 되었습니다.
이슈가 해결되지 않은 경우 이 이슈를 다시 열어주세요.
감사합니다.
