### ISSUE TITLE
A package to point users in doc

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/suneditor#1034]
@JiHong88 
Hi I need a feature in the editor, can you help me to build a package.

Package Description:
  If you look at the same github editor, you will see that whenever we type the word " @ ", it shows the list of users to select.

And you can choose one of the available users and mention him in the text.
Or search among users and find the user you want and point to him.
Also, when the editor wants to save the document, it sends a notification to the users mentioned in the doc.

I need a package with these features:
- First of all, we can: identify the users that can be mentioned.
- Secondly, when saving the document, we can get the list of users mentioned, so that we can send them a notification.

**Comment by JiHong88** [comment]
It will be add in the version  3.0.0

**Comment by Saeeed-B** [comment]
@JiHong88 What stage is version 3 at?
Apparently no progress!
On the other hand, if you postpone all the features to version 3, many bugs will be created.
Features should be added little by little.

**Comment by JiHong88** [comment]
I being refactoring the code.
Sorry, I cannot develop the next version while continuing to add features to the current version. :(
Currently, I only update critical bugs or simple feature additions.
