### ISSUE TITLE
Focusing the editor scrolls the page to top in Chromium browsers

### ISSUE THREAD

**Issue by Henk123456789** [JiHong88/SunEditor#1035]
**Describe the bug**
The page scrolls to the top when focusing the editor in Chromium browsers is the first thing you do after loading a page. This can be tedious when you have a lot of content in the editor and want to edit a specific part of the content, since you'll have the find the specific part you want to edit for a 2nd time (since you get scrolled to the top the first time you try to focus the editor).

In FireFox it works fine.

**----EDIT----**
Only seems to happen when the height of the editor is greater than the viewport height. Try to zoom in the page and try the steps below again if you can't reproduce it.

**Steps to reproduce the behavior**
1. Open a Chromium browser (the issue is confirmed in Edge and Chrome)
2. Go to http://suneditor.com/sample/index.html
3. Do **not** click anywhere on the page.
4. Zoom in in case the height of the editor is less than the viewport height of your browser.
5. Scroll to the bottom of the page.
6. Try to add some content in the editor at the bottom after the example text.
7. You will now get scrolled to the top of the page.

**Expected behavior**
The page shouldn't scroll to the top and should stay at the spot you already are.

**System**
 - OS: Windows 10 64 bit (Home and Pro)
 - Browser: At least in Chrome (version 102.0.5005.63) and Edge (102.0.1245.41). FireFox works fine.

Let me know if there are any questions!

**Comment by JiHong88** [comment]
The [2.43.10](https://github.com/JiHong88/SunEditor/releases/tag/2.43.10) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by Henk123456789** [comment]
Seems fixed now indeed, thanks!
