### ISSUE TITLE
Bold text not displaying as bolded on Windows machines

### ISSUE THREAD

**Issue by rekfoss** [JiHong88/SunEditor#1038]
**Describe the bug**
Text within the editor that is bolded does not display as bolded. The "B" on the toolbar lights up and the html code shows strong tags, but the text does not appear bolded. This is not an issue on Mac, but happens in multiple browsers on Windows.

**To Reproduce**
1. Add text to the editor and then bold it
2. Text does not appear bold

**Expected behavior**
Text should appear bolded

**Screenshots**
![boldtextissue](https://user-images.githubusercontent.com/100806453/173932469-5f672263-536b-4b52-a104-7d675dd33786.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version: 102
 
**Suneditor versions:**
"suneditor": "^2.43.9",
"suneditor-react": "^3.4.0"

**Comment by JiHong88** [comment]
It looks like the "span" tag has been styled.
Does "[suneditor.com](http://suneditor.com/sample/index.html)" reproduce the same in this link?

**Comment by roker15** [comment]
Try to clear format. There is button for clear format. Many times if a text have hidden formatting it does not respond to Suneditor formatting.

**Comment by JiHong88** [comment]
cannot be reproduced.
Please tell me more.

**Comment by rekfoss** [comment]
Thanks for the suggestions, it was a conflict with Bootstrap css, so we can close this.
