### ISSUE TITLE
Editor Initial value of P tag with text-align: right, converts to text-align: left in DOM

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#1041]
**Describe the bug**
In Editor, if you give the initial value of **p tag** with the inline style of **text-align: right**. it automatically converts to **text-align: left** in DOM

**To Reproduce**
1. Go to [suneditor sample](http://suneditor.com/sample/html/options.html)
2. Type ```<p style="text-align: right">Hello</p>``` in value input box
3. click create
4. now, created dom has text-align has left

**Expected behavior**
inline style of text-align should retain

**Screenshots**
[video link](https://www.loom.com/share/0a8104425c4d45c493e7e3c70634eac4)

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser : brave
 - Version : 1.39.122

**Comment by JiHong88** [comment]
The [2.43.12](https://github.com/JiHong88/SunEditor/releases/tag/2.43.12) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
