### ISSUE TITLE
The linkNoPrefix option strips out domains when opening the link edit modal

### ISSUE THREAD

**Issue by Henk123456789** [JiHong88/SunEditor#1044]
**Describe the bug**
When creating a link while the `linkNoPrefix` option is set to `true`, you can put in an absolute URL (internal or external) as you would expect. When applying the link, the `href` attribute is set to what you have filled in, e.g. `https://example.com/test`. Everything good so far. But when you want to edit this link, the whole domain gets stripped out in the link input field in the modal, leaving only `test` as the url. This shouldn't happen. You should be able to put any link, internal or external when the `linkNoPrefix` option is set to true.

**To Reproduce**
1. Set the `linkNoPrefix` to `true` for your editor
2. Add some text in the editor and create an absolute link from (some of) the text.
3. At this point the absolute link is present correctly in the `href` attribute of the `a` element.
4. Edit the link, and you will see the domain gets stripped out of the absolute link (which actually isn't absolute anymore at this point).

**Expected behavior**
Nothing should happen to the link that is filled in when editing the link while the `linkNoPrefix` option is set to `true` for the editor.

**Desktop (please complete the following information):**
 - OS: Tested on both Windows 10 Home and Pro
 - Browser: Happens in at least the most current versions of Chrome, Edge and FireFox

Would be super if this can be fixed! Thanks!

**Comment by JiHong88** [comment]
The [2.43.13](https://github.com/JiHong88/SunEditor/releases/tag/2.43.13) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by Henk123456789** [comment]
It's fixed now indeed, thanks!
