### ISSUE TITLE
Line above and below photo ready to type in it when adding photo

### ISSUE THREAD

**Issue by AntonioMB92** [JiHong88/SunEditor#1048]
## Version
suneditor - 2.42.0
suneditor-react - 3.4.0

## Additional context
When adding an image into the editor it has these buttons on top and bottom available once you click on the image to add a line above or below, and the button is hidden if there is a line already.
![sampleButtons](https://user-images.githubusercontent.com/17747391/176478212-d3107636-1b39-408b-ab1b-93af34657d4c.png)

Is it possible (recommended?) to trigger this behavior of adding a line above and below (if there's none yet) right away when the image is being added? If so, how can be implemented?

Note: I'm using handleImageUploadBefore in order to save image in DB and get corresponding url instead of having base64 in editor's content

**Comment by JiHong88** [comment]
```javascript
editorInstance.onImageUpload = function (targetElement, index, state, info, uploadedFileLength, core) {
    if (!targetElement) return;

    const component = core.getFileComponent(targetElement).component;
    const p = core.util.createElement('p');
    p.innerHTML = '<br>';

    if (!component.nextElementSibling) {
        core.context.element.wysiwyg.appendChild(p.cloneNode(true))
    }

    if (!component.previousElementSibling) {
        core.context.element.wysiwyg.insertBefore(p.cloneNode(true), component);
    }
}
```

**Comment by AntonioMB92** [comment]
It works! Thanks!

**Comment by hamid-hoseini** [comment]
Hi @JiHong88 
could you please let me know why the same code doesn't work for `onVideoUpload`?

```
  editorInstance.onVideoUpload = function (targetElement, index, state, info, remainingFilesCount, core) {
      if (!targetElement) return;
  
      const component = core.getFileComponent(targetElement).component;
      const p = core.util.createElement('p');
      p.innerHTML = '<br>';
  
      if (!component.nextElementSibling) {
          core.context.element.wysiwyg.appendChild(p.cloneNode(true))
      }
  
      if (!component.previousElementSibling) {
          core.context.element.wysiwyg.insertBefore(p.cloneNode(true), component);
      }
  }
```
