### ISSUE TITLE
Critical Katex parse  error, crashing production application.

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#1049]
I intentionally wrote **wrong katex** syntex (because any user can write wrong syntax)

`ax_2+\̲x̲r̲i̲g̲h̲t̲a̲w̲w̲o̲r̲`

And application crash with error 
**`ParseError: KaTeX parse error: Undefined control sequence: \xrightawwor at position 6: ax_2+\̲x̲r̲i̲g̲h̲t̲a̲w̲w̲o̲r̲`**

**And now I can not edit this syntax because application crashed before anything displayed on screen.**

### Expected behaviour - 

Editor should take wrong syntax and display as text which can be edited and corrected.

**Important Note -** 

At some point in earlier version (not sure which version) , behaviour was normal and when you put wrong syntax... it is displayed in red colour in preview and in text form in Editor. But now this behaviour is gone.

[Video link](https://imgur.com/a/tegyu2H) showing  Editor stuck when i put incomplete or wrong katex syntax. (this is from your website) 
If I load wrong syntax from database whole page crash. Not even chance to view.

**Comment by roker15** [comment]
When you are going to release 2.43.14, i need this fix immediately , my application is in production. And my clients not able to view their whole document because of a wrong tiny katex syntax.

**Comment by JiHong88** [comment]
The [2.43.14](https://github.com/JiHong88/SunEditor/releases/tag/2.43.14) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by roker15** [comment]
> The [2.43.14](https://github.com/JiHong88/SunEditor/releases/tag/2.43.14) version has been updated. If this issue has not been resolved, please reopen this issue. Thank you.

However issue is fixed but it is not as expected -----

1. It's showing full red colour error `ParseError: KaTeX parse error: Undefined control sequence: \xrightawwor at position 6: ax_2+\̲x̲r̲i̲g̲h̲t̲a̲w̲w̲o̲r̲` .it's good for developer but not for users. only `ax_2+\̲x̲r̲i̲g̲h̲t̲a̲w̲w̲o̲r̲` in red color is better for user experience.
2.  It would be even better (if possible) if user is allowed to submit wrong syntax in red colour **in editor** and user can edit it later.
