### ISSUE TITLE
Does this package use the native JS execCommand?

### ISSUE THREAD

**Issue by skru** [JiHong88/SunEditor#1059]
As the title.

Looking for a future-proof RTE and running into execCommand deprecation issues with our current setup.

All the best!

**Comment by JiHong88** [comment]
"execCommand" is used in three armies.
1. "print" method.
2. Exception handler of "insertHTML" method .
3. Exception handler for line consistency check.

What error do you get?
Please tell me the exact phenomenon.

**Comment by skru** [comment]
Hi @JiHong88  

Sorry, not a bug report. Just researching.
