### ISSUE TITLE
onChange does not fire on empty content

### ISSUE THREAD

**Issue by davidkonrad** [JiHong88/SunEditor#106]
Great work! Just discovered and started using it. By far the best vanilla JS-editor I have seen, 
I noticed that `onChange` not fire when you empty the editor. For example by deleting all content using backspace. So the only choice is to hook into another event like `onKeyUp`. Not optimal for performance,

**Comment by JiHong88** [comment]
Hi @davidkonrad 

Thanks for your feedback!

I fixed it.

It will be applied to the next version.

Thank you : )

**Comment by JiHong88** [comment]
Hi @davidkonrad 

Fixed in [v2.16.0](https://github.com/JiHong88/SunEditor/releases/tag/2.16.0)

Thank you.

**Comment by davidkonrad** [comment]
Tanks a lot! Have not tried it out yet, but guess it is fixed. Have made a PR with danish translations, da.js,. Hope I have done it all correctly.

**Comment by JiHong88** [comment]
Thank you :)

Updated to version [2.16.1](https://github.com/JiHong88/SunEditor/releases/tag/2.16.1)
