### ISSUE TITLE
error select lang

### ISSUE THREAD

**Issue by kit52** [JiHong88/SunEditor#1062]
Hi ! Thank you for such a wonderful library! I'm a beginner and I'm trying to use this library like this ↓ , but I get an error. What am I doing wrong?

**My error:**
react-dom.development.js:22839 Uncaught Error: Dynamic require of "suneditor/src/lang/ru.js" is not supported
    at chunk-ACCAMVX6.js?v=c83c95ed:12:9
    at getLanguage (getLanguage.js:8:20)
    at SunEditor.js:202:41
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)

**My code:**

`import React, { useRef, useEffect, useState } from 'react';
import SunEditor from 'suneditor-react';
import SunEditorCore from 'suneditor/src/lib/core';
import 'suneditor/dist/css/suneditor.min.css'; // Import Sun Editor's CSS File

const EditorComponents = (props: any) => {
  const editor = useRef<SunEditorCore>();

  // The sunEditor parameter will be set to the core suneditor instance when this function is called
  const getSunEditorInstance = (sunEditor: SunEditorCore) => {
    editor.current = sunEditor;
  };
  const [value, setValue] = useState(null);
  function setData(data: any) {
    console.log(data);

    setValue(data);
  }
  return (
    <div>
      <p> My Other Contents </p>
      <SunEditor
        onChange={setData}
        lang='ru'
        setOptions={{
          buttonList: [
            ['undo', 'redo'],
            ['font', 'fontSize'],
            // ['paragraphStyle', 'blockquote'],
            ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
            ['fontColor', 'hiliteColor'],
            ['align', 'list', 'lineHeight'],
            ['outdent', 'indent'],

            ['table', 'horizontalRule', 'link', 'image', 'video'],
            // ['math'] //You must add the 'katex' library at options to use the 'math' plugin.
            // ['imageGallery'], // You must add the "imageGalleryUrl".
            // ["fullScreen", "showBlocks", "codeView"],
            ['preview', 'print'],
            ['removeFormat'],

            // ['save', 'template'],
            // '/', Line break
          ], // Or Array of button list, eg. [['font', 'align'], ['image']]
          defaultTag: 'div',
          minHeight: '300px',
          showPathLabel: false,
        }}
        getSunEditorInstance={getSunEditorInstance}
      />
    </div>
  );
};
export default EditorComponents;
`

## Version
    "suneditor": "^2.43.14",
    "suneditor-react": "^3.4.1"
    "react": "^18.0.0",

**Comment by kit52** [comment]
Sorry. my bad.
If it helps anyone, you need to import the desired language right away , and then pass it to the editor properties
`import { ro } from 'suneditor/src/lang'
  <SunEditor
        lang={ru}
        onChange={setData}
        getSunEditorInstance={getSunEditorInstance}
      />`

**Comment by anselmoj** [comment]
I have recently been updating a project that used SunEditor with a translation to Portuguese (pt_br). 
I had the same issue with the page not loading. I imported it directly from the component, and it worked.


import { pt_br as nameVariable } from 'suneditor/src/lang';
