### ISSUE TITLE
글자크기 태그 관련해서 문의드리려고 합니다.

### ISSUE THREAD

**Issue by KAhhYoung** [JiHong88/SunEditor#1064]
에디터에서 글자크기를 조정하보면 생성되는 font태그의 크기관련 속성은 font-size: 10px; 로 단위가 px인데
종종 사용자들 입력값에 사용자가 크기를 변경한 게 아니라고 하는데, font-size: 0.85rem; 이렇게 span 태그가 삽입되어 게시글 글자크기가 들쭉날쭉 보여집니다.

이와 관련해서 혹시 알고계신 사항이 있으신지 여쭈어보려고 합니다.

에디터에서 생성되는 태그들을 스크립트 내에서 컨트롤 할 수 있는걸까요? 따로 관련해서 되어있는 설정은 보이지 않습니다.
혹시 제시해주실 방법이 있다면 안내해주시면 감사하겠습니다. 

감사합니다.

**Comment by JiHong88** [comment]
아마도 복사 붙여넣기 했을때 복사한 글자 스타일의 font-size 값이 rem으로 되어있던 것 같습니다.
붙여 넣기할때 fontSizeUnit 옵션대로 변환하도록 수정하겠습니다.
