### ISSUE TITLE
Disable Spell Check

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#1066]
I am trying to disable the auto spell check on the editor but am unable to do it. I see an attribute that can be specified with the `textarea` called `withspellcheck`. However, there is no way for me to define it via the editor.

I do see an attribute `spellcheck` on the editor wrapper div but can't find a way to disable it.

@JiHong88 Can you help?

## Version
2.43.14

**Comment by roker15** [comment]
> I am trying to disable the auto spell check on the editor but am unable to do it. I see an attribute that can be specified with the `textarea` called `withspellcheck`. However, there is no way for me to define it via the editor.
> 
> I do see an attribute `spellcheck` on the editor wrapper div but can't find a way to disable it.
> 
> @JiHong88 Can you help?
> 
> ## Version
> 2.43.14

I am using Chakra ui..

`<Box spellCheck="false">` solved my problem. `<Box>` in chakra ui is like `<div>`

**Comment by dgandhi1993** [comment]
@JiHong88 Can you please help here? Have been stuck with this for quite some time.

**Comment by dgandhi1993** [comment]
Hi @JiHong88, waiting for your input here.

**Comment by JiHong88** [comment]
Sorry for the late reply.
I've been busy with work. :(
Do you need to put a "spellCheck" attribute on the "wysiwyg" div?

**Comment by dgandhi1993** [comment]
The div that disables it has these classes: `se-wrapper-inner` `se-wrapper-wysiwyg` `sun-editor-editable`.
Adding an attribute spellcheck='false' disables it.

For example, this text
<img width="136" alt="image" src="https://user-images.githubusercontent.com/50414962/188410528-9ac348f1-5690-409e-8e0c-13696108231f.png">

turns into this 
<img width="136" alt="image" src="https://user-images.githubusercontent.com/50414962/188410438-2b9a7696-88bb-4e7c-8b1c-0fd191dc9c90.png">

**Comment by JiHong88** [comment]
I will add an option to add attributes to the "div".
Before updating the version, put the option directly.
```
editorInstance.onload = (core) => {
  core.context.element.wysiwyg.setAttribute("spellcheck", "false");
}
```

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
