### ISSUE TITLE
Strange behavior of copy paste after font change.

### ISSUE THREAD

**Issue by abvas** [JiHong88/SunEditor#1071]
**Describe the bug**
After changing the font, **copy-paste** **more than one line** behaves incorrectly.
First, **color: transparent** is added, and second, **one line is removed**.

**To Reproduce**
1. The editor is loaded
2. Change the font (for example, to Impact)
3. Write two lines of text
for example:
```
123
456
```
4. Copy these two lines
5. And paste them below

**Expected behavior**
We expect to receive:
```
123
456
123
456
```

but we get:
`123`

The content looks like this:
```
<p><span style="font-family: Impact;">123</span></p>
<p><span style="font-family: Impact;color: transparent">123</span></p>
<p><span style="font-family: Impact;color: transparent">456</span></p>
```

**Screenshots**
No problem with default font.
![def 0](https://user-images.githubusercontent.com/47285364/184650923-c1798538-151f-48b9-9b27-0b0e8fb37641.png)
We get without errors:
![def 1](https://user-images.githubusercontent.com/47285364/184650947-f57c098e-84e0-49d7-adb9-c6ac16942ed0.png)

There is a problem after changing the font.
![impacr 0](https://user-images.githubusercontent.com/47285364/184651039-6411666d-c59c-4006-ac53-57a8e45e6512.png)
e get with errors:
![impacr 1](https://user-images.githubusercontent.com/47285364/184651070-2e57ed78-b5c6-49ab-bbdf-7431263fa92a.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [104.0.5112.81 (64)]
 - suneditor@2.43.14

**Additional context**
This only happens after changing the font. Works great with the default font.

Thank you.

**Comment by abvas** [comment]
Not a big addition.
It turns out that exactly the same strange copy-paste behavior occurs after changing the font size, and not just after changing the font family.

**Comment by abvas** [comment]
Part of the problem has been resolved.

But still, after pasting the copied, one line is deleted (the last line)

To see do:
1. Change the font (for example, to Impact)
2. Write two lines of text
for example:
```
123
456
```

3. Copy these two lines
4. And paste them below

If we insert immediately below line `456`, then it will be deleted and we will get:
```
123
123
456
```

Thank you.

**Comment by JiHong88** [comment]
The version has not been updated yet.
I will notify you after the version update.

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
