### ISSUE TITLE
not open in iPad

### ISSUE THREAD

**Issue by luizcmarin** [JiHong88/suneditor#1078]
**Describe the bug**
It works on windows and android. But it doesn't open on ios iPad (see picture)

[](url)
![1661949342817](https://user-images.githubusercontent.com/67489841/187680680-d4a038f9-bae4-4277-a71d-59b49f7b337f.jpg)

**Comment by JiHong88** [comment]
Try it.
`<h2 style"=margin-left:0px;">`
