### ISSUE TITLE
이미지를 업로드했을때 오류?

### ISSUE THREAD

**Issue by trashtalker9** [JiHong88/SunEditor#1080]
최초로 이미지를 업로드 했을때 이미지에 리사이징 박스가 잡히는데
좌우 점을 제외한 다른 점을 끌어서 크기조절했다가 좌우를 조절하면 정상적으로 되긴하는데,
최초에 좌우에 있는 네모 점을 끌어서 늘리면 좌우만 길어지는게 아니고 비율? 맞춤으로 상하좌우 전체가 크기 조절이 됩니다.

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) 버전이 업데이트 되었습니다.
감사합니다.
