### ISSUE TITLE
sample examples에서 오류?

### ISSUE THREAD

**Issue by akeDread** [JiHong88/SunEditor#1081]
**Describe the bug**
suneditor홈페이지의 examples 페이지에 있는 Image management 데모에서
attach image를 눌러서 이미지 멀티 업로드를 한 후에,  오른쪽에 표시되는 이미지들을 복수개 클릭한후
remove버튼을 눌러서 삭제하게되면 이미지는 삭제되지만, 이미지 리사이징 편집박스가 그대로 남아있습니다.

**Screenshots**

**Comment by JiHong88** [comment]
앗.. 감사합니다.
예제 코드 수정하겠습니다.
