### ISSUE TITLE
Paste some text and images at once but cleanData.length of OnPaste is 0 

### ISSUE THREAD

**Issue by musang33** [JiHong88/SunEditor#1082]
To make it easier for us to help you, please include as much useful information as possible.

## Version
2.8.0 ~ 2.16.1, 3.4.1

## Additional context

If you copy and paste a text larger than a certain size containing an image, the length value of OnPaste's cleanData may be zero.

reproduction)

https://www.sisain.co.kr/news/articleView.html?idxno=48404

Copying the contents of to OneNote (MicroSoft) switches the image from Link to Blob data.
If you copy the same content about 3 times, increase the size, and paste it into the SunEditor after copying the entire content, the above symptoms occur.

**Comment by JiHong88** [comment]
This issue is not reproduced.
Currently the latest version is 2.43.14.

**Comment by musang33** [comment]
You are right. 
Not reproduced at Suneditor@2.43.14.
But reproduced at Suneditor-react.
Sorry. I'm asking to https://github.com/mkhstar/suneditor-react.
Thank you.
