### ISSUE TITLE
katex Error creates bad user experience

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#1084]
In last version `Katex error` was fixed but Error it shows when syntax is wrong is **cumbersome**  and creating bad user experience . Can You present it in some pleasant  way ? Earlier in some version, Just text becomes **red** when there is syntax error.
![image](https://user-images.githubusercontent.com/59526869/189530106-991b7319-304f-4b0b-af7c-c8020ef1f6ee.png)

----
----
**Message  should be Something like** --> _You have put wrong katex notaion, please correct it. Refer **Katex** webiste for Correct syntax_

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
