### ISSUE TITLE
All the default styles are ignored in full screen mode

### ISSUE THREAD

**Issue by AliBayatMokhtari** [JiHong88/SunEditor#1085]
All you need is just set some default styles for Suneditor instance when creating it. Steps are:
- Step 1: set `defaultStyle: "color: red; font-family: <custom font family from @font-face>"` in `create` method.
- Step 2: take a look at editor and everything seems okay 👍.
- Step 3: toggle editor to full screen mode.
- Step 4: all the default styles which have been set in Step 1 are gone and ignored.

**This is issue exists even in official website example**

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
