### ISSUE TITLE
멀티 이미지 업로드시 하이퍼링크 관련 오류

### ISSUE THREAD

**Issue by trashtalker9** [JiHong88/SunEditor#1086]
이미지를 2개를 선택한후에 링크 탭에서 인터넷 주소란에 링크를 걸고 확인을 누르면
이미지 2개가 같은 div에 포함이 되면서 2번째 이미지는 제어가 안됩니다.
그런데 멀티 이미지를 사용할 경우에는 대체 문자열이나 가로 세로, 링크가 다 한꺼번에 같은걸로 적용되니
다 비활성화를 시키는게 맞는건가? 싶네요.

**Comment by JiHong88** [comment]
이미지가 따로 적용돼야 하는데 버그네요.
수정후에 알려드리겠습니다.
