### ISSUE TITLE
Pasting the copied one deletes one line.

### ISSUE THREAD

**Issue by abvas** [JiHong88/SunEditor#1091]
**Describe the bug**
After pasting the copied, one line is deleted (the last line)
This happens after changing the font or changing the font family.

**To Reproduce**
1. Change the font (for example, to Impact)
2. Write two lines of text
for example:
```
123
456
```
3. Copy these two lines
4. And paste them below

If we insert immediately below line 456, then it will be deleted and we will get:

```
123
123
456
```

**Expected behavior**
Should be:
```
123
456
123
456
```

**Screenshots**
![Image 114](https://user-images.githubusercontent.com/47285364/191324927-6c67361e-aa2e-4d52-87fb-4a266f460e63.png)
![Image 113](https://user-images.githubusercontent.com/47285364/191324957-6f547993-0f6c-4111-a57a-31ab2317b378.png)

**Desktop (please complete the following information):**
OS: [Windows 10]
Browser [chrome]
Version [104.0.5112.81 (64)]
suneditor@2.43.14
**Smartphone (please complete the following information):**

**Additional context**
The error occurs after changing the font or changing the font family.

**Comment by JiHong88** [comment]
The [2.44.0](https://github.com/JiHong88/SunEditor/releases/tag/2.44.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
