### ISSUE TITLE
Pastes "color": "transparent" when copying.

### ISSUE THREAD

**Issue by abvas** [JiHong88/SunEditor#1093]
**Describe the bug**
I don't know which section to post this in. Perhaps this is a bug.

I have this style in my styles:
```
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video, input, textarea, button {

    -webkit-tap-highlight-color: transparent;
}
```

I can't remove this as I'm using the "Bubble" website building platform. And I have no way to change it.

After changing the font or font size, when copying text (more than one line) - the text is copied with "color": "transparent"
Of course and inserted with "color": "transparent" too.

This is happening precisely because of "-webkit-tap-highlight-color: transparent;"
If I first disable this setting via devTools and then copy and paste the text, everything works fine and the desired "color" is pasted, not "transparent".
It turns out that when changing the font or font size, `<span>` is added (for example, `<span style="font-family: Impact;">123</span>`) and if "color" is not clearly spelled out in it, then "color" why -something is taken from "-webkit-tap-highlight-color: transparent;"

**To Reproduce**
0. It is in the styles:
```
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video, input, textarea, button {

    -webkit-tap-highlight-color: transparent;
}
```
2. The editor is loaded
3. Change the font (for example, to Impact)
4. Write two lines of text
 for example:
```
123
456
```
5. Copy these two lines
6. And paste them below

**Expected behavior**
We expect to receive:

```
123
456
123
456
```
but we get:
```
123
456



```
**Screenshots**
![Image 121](https://user-images.githubusercontent.com/47285364/191848738-569d4084-2a83-4556-8b1f-3dcc1862dc1f.png)

![Image 122](https://user-images.githubusercontent.com/47285364/191848754-1c507125-9ce9-4715-951c-5ad87c51db5e.png)

![Image 123](https://user-images.githubusercontent.com/47285364/191848765-901ea627-d45c-4503-8757-8df45eef894a.png)

-webkit-tap-highlight-color: transparent; = on
![Image 126](https://user-images.githubusercontent.com/47285364/191848812-e66b0b32-bf1d-4f34-9661-b7bcb2637f3b.png)

-webkit-tap-highlight-color: transparent; = off
![Image 125](https://user-images.githubusercontent.com/47285364/191848794-d4fe2ca5-4282-480e-8b62-d3ee66efef66.png)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser [chrome]
- Version [104.0.5112.81 (64)]
- suneditor@2.44.0

**Additional context**
If this is not a bug, then please tell me if I can do something about it myself somehow fix it?
Thanks a lot.

**Comment by JiHong88** [comment]
This issue is not reproduced.
My windows is 8, Does this have anything to do with it?

**Comment by abvas** [comment]
Here is a small demo:
https://codepen.io/abvas/pen/ExLwOMp

Pay attention to CSS
![Image 131](https://user-images.githubusercontent.com/47285364/192069597-2f165432-16f1-427f-9c5c-198b2ff3445e.png)


1. Change the font
2. Print two lines
3. Copy these two lines
4. Paste what you copied below

**Comment by JiHong88** [comment]
The [2.44.1](https://github.com/JiHong88/SunEditor/releases/tag/2.44.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by abvas** [comment]
Excellent! That helped.
Thanks a lot!

You are the best!
