### ISSUE TITLE
Add custom button

### ISSUE THREAD

**Issue by triawarman** [JiHong88/SunEditor#11]
Hy JiHong, is there a way i could add custom button ?.

**Comment by JiHong88** [comment]
Hi, Modularization is in progress and you will be able to add custom buttons when this progress finished.
Please wait a little longer :)

**Comment by triawarman** [comment]
Yup, i will.

For now maybe i'll trying something to integrate your text editor with [RichFilemanager](https://github.com/servocoder/RichFilemanager)

Thanks :)

**Comment by JiHong88** [comment]
Hi, Modularization is complete.
I added customization and document menu to the sample and demo site.

**Comment by triawarman** [comment]
Thanks Jihong :)
