### ISSUE TITLE
editor.getText() doesn't see the line break.

### ISSUE THREAD

**Issue by abvas** [JiHong88/suneditor#1113]
**Describe the bug**
**getText()** returns the text without line breaks.

**To Reproduce**
1. Print text on multiple lines. For example:
```
Hey
How’s
it going.
```
2. Get text via **editor.getText()**
3. Returns:
`HeyHow’sit going.`

**Expected behavior**
There must be line breaks or at least spaces. Like this:
```
Hey
How’s
it going.
```

or
`Hey How’s it going.`

**Desktop (please complete the following information):**
 - OS: Windows 10 (64)
 - Browser chrome
 - Version 106.0.5249.119

SunEditor v2.44.3

Thank you.

**Comment by JiHong88** [comment]
Sorry, There is no way to include line breaks when importing only "text".
Use the "getContents()".
