### ISSUE TITLE
Tag visible on Sun editor 

### ISSUE THREAD

**Issue by vipin9457** [JiHong88/suneditor#1122]
Following steps to reproduce the issue

**1- Paste the following html content on code view** 

"&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t&lt;font color=&quot;#000000&quot;&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Do you agree with the following statements is not correct the data tested data?&lt;/font&gt;&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n&lt;ol&gt;\r\n\t&lt;li&gt;\r\n\t\t&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t\t\t&lt;font face=&quot;Arial, serif&quot;&gt;&lt;font size=&quot;5&quot;&gt;Mr. Kantha print is a design pattern of West Bengal.&lt;/font&gt;&lt;/font&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt; &lt;/font&gt;&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Agree/Disagree&lt;/font&gt;&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n\t&lt;/li&gt;\r\n\t&lt;li&gt;\r\n\t\t&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t\t\t&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Carrot Brocolli and Cauliflower are fruits.&lt;/font&gt;&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Agree/Disagree&lt;/font&gt;&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n\t&lt;/li&gt;\r\n\t&lt;li&gt;\r\n\t\t&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t\t\t&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Lotus Tree stems are pickled and also eaten as vegetable. Agree/Disagree&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n\t&lt;/li&gt;\r\n\t&lt;li&gt;\r\n\t\t&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t\t\t&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Jasmine flower&lt;/font&gt;&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt; is used for preparing tea leaves. Agree/Disagree&lt;/font&gt;&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n\t&lt;/li&gt;\r\n\t&lt;li&gt;\r\n\t\t&lt;p style=&quot;margin-bottom: 0in&quot;&gt;\r\n\t\t\t&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Goddess Lakshmi sits on a rose flower. &lt;/font&gt;&lt;/font&gt;&lt;font color=&quot;#000000&quot;&gt;&lt;font face=&quot;Verdana, serif&quot;&gt;&lt;font size=&quot;4&quot; style=&quot;font-size: 16pt&quot;&gt;Agree/Disagree&lt;/font&gt;&lt;/font&gt;&lt;/font&gt;&lt;/p&gt;\r\n\t&lt;/li&gt;\r\n&lt;/ol&gt;\r\n"

**2- Sun editor shows the html tag** 

<img width="1440" alt="Screenshot 2022-11-08 at 1 15 17 PM" src="https://user-images.githubusercontent.com/5819814/200504386-a5896c60-c39b-4064-9203-3a0c12631797.png">

@JiHong88 @rwaldron @madarche @rwhite226 @kubabogaczewicz 

Please help on the above issue

**Comment by JiHong88** [comment]
This issue is not reproduced.
Please tell me more accurate test environment.

**Comment by vipin9457** [comment]
@JiHong88  Please find the details for above bug

**Describe the bug**
When we add a html code on the code view and close the code view, then the blow tag is not rendered properly when using katex plugin.

**To Reproduce**
Steps to reproduce the behavior:
1- Click on the code view 
2- Add the below code on code view 
"<p style="margin-bottom: 0in">\r\n\t<font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Do you agree with the following statements is not correct the data tested data?</font></font></font></p>\r\n<ol>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Arial, serif"><font size="5">Mr. Kantha print is a design pattern of West Bengal.</font></font><font face="Verdana, serif"><font size="4" style="font-size: 16pt"> </font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Carrot Brocolli and Cauliflower are fruits.</font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Lotus Tree stems are pickled and also eaten as vegetable. Agree/Disagree</font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Jasmine flower</font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt"> is used for preparing tea leaves. Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Goddess Lakshmi sits on a rose flower. </font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n</ol>\r\n"
3- Close the code view 
4- Now you can see in editor HTML tag are shown instead of data .


Screenshots
[https://user-images.githubusercontent.com/5819814/200504386-a5896c60-c39b-4064-9203-3a0c12631797.png](url)

Desktop (please complete the following information):

OS: All
Browser All
Version All
Additional context

Please find the HTML below:
"<p style="margin-bottom: 0in">\r\n\t<font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Do you agree with the following statements is not correct the data tested data?</font></font></font></p>\r\n<ol>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Arial, serif"><font size="5">Mr. Kantha print is a design pattern of West Bengal.</font></font><font face="Verdana, serif"><font size="4" style="font-size: 16pt"> </font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Carrot Brocolli and Cauliflower are fruits.</font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Lotus Tree stems are pickled and also eaten as vegetable. Agree/Disagree</font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Jasmine flower</font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt"> is used for preparing tea leaves. Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n\t<li>\r\n\t\t<p style="margin-bottom: 0in">\r\n\t\t\t<font face="Verdana, serif"><font size="4" style="font-size: 16pt">Goddess Lakshmi sits on a rose flower. </font></font><font color="#000000"><font face="Verdana, serif"><font size="4" style="font-size: 16pt">Agree/Disagree</font></font></font></p>\r\n\t</li>\r\n</ol>\r\n
