### ISSUE TITLE
Cursor position error addRange() when playing with list

### ISSUE THREAD

**Issue by cub** [JiHong88/suneditor#1127]
**Describe the bug**
Cursor goto position 0 when :
- You stop a list
<video src="https://user-images.githubusercontent.com/1578812/205273119-606e97a3-cb47-435c-a812-16d7ab0fbf4a.mp4"></video>
- You re-attach a line to a list
<video src="https://user-images.githubusercontent.com/1578812/205273142-18d8acd2-02d4-4a31-a27a-604ba0b94f3b.mp4"></video>

**Expected behavior**
Cursor stay at his position to write content.

**Information**
 Chrome version 108.0.5359.71 (Official Build) (64-bit)

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
