### ISSUE TITLE
insert js code in SunEditor

### ISSUE THREAD

**Issue by IonCiobanu23** [JiHong88/suneditor#1130]
function editPageContent() {
  const editable = document.querySelectorAll(".sun-editor-editable");

  editable.forEach((element) => {
    let sg = document.createElement("script");
    let sd = document.getElementsByTagName("script")[0];
    sg.text = "alert(1111)";
    sd.parentNode.insertBefore(sg, sd);
    element.appendChild(sg);
  });
}

editPageContent();

i made it from browser console

an alert(1) is not something serious, 
but i think it is a kind of XSS

**Comment by davidkonrad** [comment]
I think you can do that on literally any webpage, also for example github. Just grab a random element and do the same as above. All SunEditor can do (and should do and does) is to prevent <script> inserted into the text.

**Comment by IonCiobanu23** [comment]
i have put the script tag in database using SunEditor and script i post above, not only display on page i make script execution from console.
So i have injected js code in SunEditor textarea and after this was sended request to server.

**Comment by JiHong88** [comment]
I'll modify the "getContents" method to check the HTML once again.
And I'll consider using MutationObserver later.

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
