### ISSUE TITLE
Matrix of vertical length more than 2 does not get rendered

### ISSUE THREAD

**Issue by sharmatapan** [JiHong88/suneditor#1131]
**Describe the bug**
When we add a matrix with vertical length more than 2 and then go to code view and close the code view, the matrix rendering is effected and the matrix box is not rendered properly when using katex plugin.

**To Reproduce**
1. Add a matrix latex using katex plugin.
2. Click on code view
3. Do not make any change and close code view
4. You will see the matrix box rendering is wrong now.

**Expected behavior**
Matrix box rendering should be effected.

**Screenshots**
Before issue appears
![image](https://user-images.githubusercontent.com/94465847/205570237-a91b1991-d64f-49a5-b04f-c32fe51f2995.png)
After we click on code view and close it, see how rendering is effected
![image](https://user-images.githubusercontent.com/94465847/205570394-d0795c31-8332-426d-afd6-0d4bbce5a4d1.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Additional context**

- Please find the HTML below:

Attached

-  Please find the latex below:

\left[\begin{matrix}
1&4&3\\
6&3&4\\
8&5&1
\end{matrix}\right]

**Comment by sharmatapan** [comment]
HTML:
<p>&nbsp;<span class="__se__katex katex" contenteditable="false" data-exp=" \left[\begin{matrix}1&amp;4&amp;3\\6&amp;3&amp;4\\8&amp;5&amp;1\end{matrix}\right]" data-font-size="1.0em" style="font-size: 1em;"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo fence="true">[</mo><mtable rowspacing="0.16em" columnalign="center center center" columnspacing="1em"><mtr><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>1</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>4</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>3</mn></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>6</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>3</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>4</mn></mstyle></mtd></mtr><mtr><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>8</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>5</mn></mstyle></mtd><mtd><mstyle scriptlevel="0" displaystyle="false"><mn>1</mn></mstyle></mtd></mtr></mtable><mo fence="true">]</mo></mrow><annotation encoding="application/x-tex"> \left[\begin{matrix}1&amp;4&amp;3\\6&amp;3&amp;4\\8&amp;5&amp;1\end{matrix}\right]</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:3.6em;vertical-align:-1.55em;"></span><span class="minner"><span class="mopen"><span class="delimsizing mult"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:2.05em;"><span style="top:-2.25em;"><span class="pstrut" style="height:3.155em;"></span><span class="delimsizinginner delim-size4">⎣</span></span><span style="top:-3.397em;"><span class="pstrut" style="height:3.155em;"></span><span style="height:0.016em;width:0.6667em;"><svg xmlns="http://www.w3.org/2000/svg" width="0.6667em" height="0.016em" style="width:0.6667em" viewBox="0 0 666.67 16" preserveAspectRatio="xMinYMin"><path d="M319 0 H403 V16 H319z M319 0 H403 V16 H319z"></path></svg></span></span><span style="top:-4.05em;"><span class="pstrut" style="height:3.155em;"></span><span class="delimsizinginner delim-size4">⎡</span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:1.55em;"></span></span></span></span></span><span class="mord"><span class="mtable"><span class="col-align-c"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:2.05em;"><span style="top:-4.21em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1</span></span></span><span style="top:-3.01em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">6</span></span></span><span style="top:-1.81em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">8</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:1.55em;"></span></span></span></span><span class="arraycolsep" style="width:0.5em;"></span><span class="arraycolsep" style="width:0.5em;"></span><span class="col-align-c"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:2.05em;"><span style="top:-4.21em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">4</span></span></span><span style="top:-3.01em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">3</span></span></span><span style="top:-1.81em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">5</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:1.55em;"></span></span></span></span><span class="arraycolsep" style="width:0.5em;"></span><span class="arraycolsep" style="width:0.5em;"></span><span class="col-align-c"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:2.05em;"><span style="top:-4.21em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">3</span></span></span><span style="top:-3.01em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">4</span></span></span><span style="top:-1.81em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:1.55em;"></span></span></span></span></span></span><span class="mclose"><span class="delimsizing mult"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:2.05em;"><span style="top:-2.25em;"><span class="pstrut" style="height:3.155em;"></span><span class="delimsizinginner delim-size4">⎦</span></span><span style="top:-3.397em;"><span class="pstrut" style="height:3.155em;"></span><span style="height:0.016em;width:0.6667em;"><svg xmlns="http://www.w3.org/2000/svg" width="0.6667em" height="0.016em" style="width:0.6667em" viewBox="0 0 666.67 16" preserveAspectRatio="xMinYMin"><path d="M263 0 H347 V16 H263z M263 0 H347 V16 H263z"></path></svg></span></span><span style="top:-4.05em;"><span class="pstrut" style="height:3.155em;"></span><span class="delimsizinginner delim-size4">⎤</span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:1.55em;"></span></span></span></span></span></span></span></span></span>​&nbsp;<br>
</p>

<p><br>
</p>

**Comment by sharmatapan** [comment]
@JiHong88 @LeeJiHong Please look into this.

**Comment by Himanshu95cloud** [comment]
Hi,@JiHong88  @LeeJiHong  I am also facing this issue.

**Comment by Gautam123kumar** [comment]
Hi, I'm also facing this issue. @JiHong88 @LeeJiHong

**Comment by JiHong88** [comment]
@sharmatapan  @Himanshu95cloud @Gautam123kumar This issue is not reproduced.
Am I doing the test wrong?

https://user-images.githubusercontent.com/13191953/214543909-d6c24246-a2e3-4ead-972a-70fbdd249361.mov

**Comment by vipin9457** [comment]
@JiHong88 in the attached video (timing 0:10 sec) after click on the code view  , you can see the matrix is not properly rendered  ,vertical line are broken .

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
