### ISSUE TITLE
Adding Buttons, Setting Properties

### ISSUE THREAD

**Issue by PleachiM** [JiHong88/SunEditor#114]
Hi,
is it possible to set the height after creation of the control. 
I can't set the textarea height or the editor height. 
Also it would be great thing to add and delete buttons after editor creation. 

1) Setting Editor Properties
2) Adding/Removing Buttons

**Comment by JiHong88** [comment]
Hi @PleachiM 

Thank you for your feedback.

I will update the version after developing the function :)

**Comment by JiHong88** [comment]
Fixed in [v2.18.0](https://github.com/JiHong88/SunEditor/releases/tag/2.18.0).

Thank you.
