### ISSUE TITLE
Uncaught TypeError: d._resourcesStateChange is not a function after getting latest .min file

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/suneditor#1142]
I just got the latest suneditor.min.js file.

Now I am noticing the following error in the console...

![image](https://user-images.githubusercontent.com/25779335/210009797-5da672a2-df08-4f41-858c-71ae3a38f530.png)

Any pointers as to what its about? Everything _seems_ ok but it concerns me that I could have broken something after the upgrade.

**Comment by JiHong88** [comment]
Resolved with issue #1138.
I will notify you after updating the version.
