### ISSUE TITLE
getText() always return empty string in onBlur callback

### ISSUE THREAD

**Issue by dev-mohanraj** [JiHong88/suneditor#1143]
**Describe the bug**

 I need to get text in the onBlur action but it always returns an empty string 

Issue code :

 const editorRef = useRef()
 function editorInitialize() {
    editorRef.current.onBlur = (e, core) => {
      let text = editorRef.current.getText();  **// Return empty string always**
      onBlur(core.getContents(), text);
    };

  }

**To Reproduce**

1. Just create a simple instance for the sun editor 
2. Consume the onBlur method in your instance 
3. Inside or outside consume getText() method 
4. Check the output of getText() , it always return empty string

**Expected behavior**
 Need to return plain text inside onBlur callback, currently, it returns plaintext in onChange callback 

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome
 - Version 108

**Comment by JiHong88** [comment]
This issue is not reproduced.
It could be a problem with "[suneditor-react](https://github.com/mkhstar/suneditor-react)".

**Comment by dev-mohanraj** [comment]
Yeah, i just checked it was working !
