### ISSUE TITLE
Focus and blur events not working as expected

### ISSUE THREAD

**Issue by s-ashwin** [JiHong88/suneditor#1144]
**Describe the bug**
The focus and blur events of the elements inside the custom submenu doesn't work as expected

**To Reproduce**
1. Create a custom plugin ( SubMenu ), with an Input tag and a button.
2. Click on the input. It gets focused
3. Click somewhere outside the input tag, like click the button
4. Input is still focussed

**Expected behavior**
On clicking outside the input element, It must not be in the focussed state

**Screenshots**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/47049152/211197826-cdb9707e-3bd6-438e-95ed-8c7d6415e387.png">

**Desktop (please complete the following information):**
 - OS: MacOs 13.1
 - Browser: Chrome
 - Version: 108.0.5359.124

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JiHong88** [comment]
This issue will resolve at the v3.0.0
