### ISSUE TITLE
Can modify markup outside of editor

### ISSUE THREAD

**Issue by JoelValet** [JiHong88/suneditor#1146]
**Describe the bug**
It seems that you can edit markup on the parent page that suneditor in embedded in

**To Reproduce**
1. Go to http://suneditor.com/sample/index.html
2. Highlight part of the "SunEditor distributed under the MIT license." string in the footer
3. In the editor go to "font color" and choose a color
4. It'll change the color outside the editor

**Expected behavior**
I would not expect the editor to be able to modify the markup outside of it

**Screenshots**
![image](https://user-images.githubusercontent.com/10109890/211470327-8993386e-e7ed-4084-82a8-23f7583490dd.png)

![image](https://user-images.githubusercontent.com/10109890/211470355-b9a2fe7a-4cd0-4e0c-9553-4c54e43a591a.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - Browsers: 
 -- Chrome Version 108.0.5359.124 (Official Build) (64-bit)
-- Firefox 108.0.1 (64-bit)
-- Opera 94.0.0.0

Also tested in Chrome on Windows 10 and happens there too

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.

**Comment by JoelValet** [comment]
Thank you very much!
