### ISSUE TITLE
Line breaks on copy/pasting bug

### ISSUE THREAD

**Issue by oaknorton** [JiHong88/suneditor#1147]
When I copy/paste from articles online to my app which uses Sun Editor, and on your own demo site, it often comes in from html with line breaks at the end of about 70-80 characters. Why does this happen? 
You can see it happen here: 
https://www.loom.com/share/14f0b8f1121446df81df405eff01c98e
Try copy/pasting the speech into the editor (https://www.americanrhetoric.com/speeches/benfranklin.htm)
If I paste into MS Word, it appears totally fine and I can then copy/paste it from Word into the Sun Editor and it works without a problem.

**Comment by s-kris** [comment]
Can confirm the same bug.

**Comment by oaknorton** [comment]
Wonderful! Thank you for fixing this.
