### ISSUE TITLE
Template Action

### ISSUE THREAD

**Issue by PleachiM** [JiHong88/SunEditor#115]
Another nice adjustment would be a Template button found in another project. 

So you can define templates by action. For this an eventlistener would be nice to insert templates from other sources. 

[https://alex-d.github.io/Trumbowyg/demos/#plugins-template](url)

**Comment by JiHong88** [comment]
Fixed in [v2.18.0](https://github.com/JiHong88/SunEditor/releases/tag/2.18.0).

Thank you.
