### ISSUE TITLE
Another way to check for "ResizeObserver" method support

### ISSUE THREAD

**Issue by SystemChanger** [JiHong88/suneditor#1154]
**Is your feature request related to a problem? Please describe.**
I am using a platform with old built-in version of WebKit
(userAgent looks this way : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/605.1 (KHTML, like Gecko) V8WebKit")

Some versions earlier, this repo started to rely on "ResizeObserver" function that is not supported by the engine I am stuck with.
Theoretically, this problem may reproduce in similar configurations.

The good point of this repo was it compatibility, and it'll be sad to lose it.

**Describe the solution you'd like**
Check function support some different way

**Describe alternatives you've considered**
Check for function existence:  `typeof ResizeObserver !== 'undefined'`
and then store it in variable `isResizeObserverSupported` instead of relying on `isIE`

**Additional context**
https://github.com/JiHong88/suneditor/blob/6f635926d5ca8cccebe9a1067553777d37b6184a/src/lib/core.js#L8009-L8013
https://github.com/JiHong88/suneditor/blob/6f635926d5ca8cccebe9a1067553777d37b6184a/src/lib/core.js#L8066
https://github.com/JiHong88/suneditor/blob/6f635926d5ca8cccebe9a1067553777d37b6184a/src/lib/core.js#L6022-L6032
https://github.com/JiHong88/suneditor/blob/6f635926d5ca8cccebe9a1067553777d37b6184a/src/lib/core.js#L7612
https://github.com/JiHong88/suneditor/blob/6f635926d5ca8cccebe9a1067553777d37b6184a/src/lib/core.js#L7616
... (May be some other places)

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
