### ISSUE TITLE
한줄 끝까지 선택 혹은 마우스 트리플 클릭 기능 문의 

### ISSUE THREAD

**Issue by rafael-develop** [JiHong88/SunEditor#116]
안녕하세요.

SUNEDITOR 라이브러리 사용 중 문의 사항이 있어서 이슈 등록합니다.

에디터 상에서 한 줄 전체 선택 혹은 마우스 왼쪽 트리플 클릭을 통한 선택 후,

스타일 적용할 경우 하위 라인의 텍스트도 함께 선택 적용되는 현상이 있는데

의도된 옵션 기능인 지, 의도 하지 않은 버그 동작인 지 확인 부탁 드립니다.

**Comment by JiHong88** [comment]
안녕하세요.

해당 현상은 버그 입니다 ㅠㅠ

픽스된 상태이고 다음 버전 업데이트때 적용될 예정입니다.

**Comment by rafael-develop** [comment]
네, 다음 버전에서 확인해보겠습니다.

감사합니다.

**Comment by rafael-develop** [comment]
안녕하세요.

혹시 다음 버전 업데이트 일정에 대해 알 수 있을까요?

감사합니다.

**Comment by JiHong88** [comment]
아마.. 이번 주 중이나 늦으면 주말에 업데이트할 것 같습니다.

**Comment by rafael-develop** [comment]
네 감사합니다. 이번 주 업데이트 완료 후 기능 적용하겠습니다.

**Comment by rafael-develop** [comment]
안녕하세요.
이번 주 업데이트 일정이 언제쯤 진행될 지 확인 부탁 드립니다.
감사합니다.

**Comment by JiHong88** [comment]
안녕하세요~

버그가 있어서 시간이 걸렸어요.

오늘 8시쯤 업데이트 예정입니다.

**Comment by JiHong88** [comment]
수정 버전 배포 되었습니다. [v2.18.0](https://github.com/JiHong88/SunEditor/releases/tag/2.18.0)

감사합니다.

**Comment by rafael-develop** [comment]
감사합니다.
