### ISSUE TITLE
Play Youtube videos in edit mode

### ISSUE THREAD

**Issue by oaknorton** [JiHong88/suneditor#1162]
**Is your feature request related to a problem? Please describe.**
In my project I never go into preview mode. I'm always in edit mode saving text so I can't add a video link and watch it in a document.

**Describe the solution you'd like**
I would like Youtube videos to play in edit mode when they are embedded.

**Describe alternatives you've considered**

**Additional context**
Here's a quick video showing what I'm talking about. 
https://www.loom.com/share/96dbf6bed7e84ca4b01073851b54d6b9

**Comment by JiHong88** [comment]
This issue has been resolved in v3.0.0.
It will take more time until version 3.0.0 is released.

**Comment by LuizFernandoAvant** [comment]
when we can start testing the v3 ?

**Comment by JiHong88** [comment]
Implemented in v3, but not ready for deployment yet.
Sorry, It will take more time.
When the date is predictable, we will mark it on the milestone.

**Comment by gxara** [comment]
Hi, @JiHong88 

First of all, congrats! You are doing a great job with suneditor. I'm already a fan.

I'm eager for this feature! I've noticed it's a little annoying for users to switch between edit mode and read-only mode. 

Please let us know if you need support with v3, I will be happy to contribute.

Do you consider releasing a beta version?

**Comment by gxara** [comment]
> Hi, @JiHong88
> 
> First of all, congrats! You are doing a great job with suneditor. I'm already a fan.
> 
> I'm eager for this feature! I've noticed it's a little annoying for users to switch between edit mode and read-only mode.
> 
> Please let us know if you need support with v3, I will be happy to contribute.
> 
> Do you consider releasing a beta version?

In case someone else wants to play videos in edit mode before v3, I've implemented a workaround:

```      <SunEditor
        onLoad={() => {
          let a = document.getElementById("editor")
          a.onmousedown = (e) => {
            try {
              const childrens = e.target.children;
              const searchFor = 'IFRAME'
              let newMode = 'edit'
              for (let i = 0; i < childrens.length; i++) {
                if (childrens[i].nodeName === searchFor) {
                  newMode = 'readonly';
                }
              }
              setMode(newMode);
              
            }
            catch (e) {
              console.log(e);
            }
          }
        }}
        autoFocus={false}
...
```
