### ISSUE TITLE
How can i remove resizing controller when I click the Image

### ISSUE THREAD

**Issue by poohc300** [JiHong88/suneditor#1164]
## Version
suneditor: 2.44.3
suneditor-react: 3.41

## Additional context
질문이 있습니다 다음 화면과 같이 이미지를 클릭하였을 때 
에디터 내에서 이미지 밑에 생성되는 도구박스 컨트롤러들을 어떻게 없앨 수 있을까요
onFocus 일때 해당 에디터를 setOptions를 통해 몇가지 옵션에 false값을 줘도 모두 없어지지는 않더라구요

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/25047319/219243806-b760d3c3-dfbc-4e51-a3cf-601b31beb470.png">

**Comment by JiHong88** [comment]
모든 컨트롤러를 없애고 싶으신건가요?

**Comment by poohc300** [comment]
예 그렇습니다. 이미지만 남고 제어는 불가능한 상황을 구현하고 싶어서 질문 남깁니다

**Comment by JiHong88** [comment]
컨트롤러는 없애는 옵션은 없습니다.
아래처럼 구현해야합니다.
```javascript
editorInstance.showController = function (name, controllers, core) {
    controllers.forEach((e)=>{
        e.style.display = 'none'
    })
}
```

**Comment by poohc300** [comment]
옙 감사합니다 적용했더니 원하던대로 나오네요
