### ISSUE TITLE
Default font units

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/suneditor#1166]
I want to use EM as my font unit. when I use them when I originally click into the editor the toolbar shows the units as px.

To reproduce...

1. Go to your options page http://suneditor.com/sample/html/options.html
2. Set font size options and create
![image](https://user-images.githubusercontent.com/25779335/219621192-d2326354-e9f4-43ee-b07b-00340c8638f8.png)
3. Click into the editor and look at the toolbar it shows units in px not em
![image](https://user-images.githubusercontent.com/25779335/219621372-05ae351a-1eae-43b2-8cca-dd0544ce41ca.png)

If you change the units, it then seems to work. But if you empty the contents it goes back to px

How can I set the default font size/unit? I would like it to be 1em

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
