### ISSUE TITLE
Feature Request: Add option to use `<iframe>` to edit full page

### ISSUE THREAD

**Issue by sirlancelot** [JiHong88/SunEditor#117]
Currently, the editor inherits all CSS on the page where it is added. If shown in an "admin" area, it's possible some CSS will reach in to the editor causing undesired side-effects.

If you use an `<iframe>` for the editing area, you can get not only 1) better sandboxing, but also 2) full-page editing.

It would be cool to see this editor support full page editing, where it can accept a `<!doctype html><html>...</html>` value and preserve the entire structure.

**Comment by JiHong88** [comment]
Hi @sirlancelot 

Does this mean that the "iframe" should cover the all area of the editor?

**Comment by sirlancelot** [comment]
In the implementation I've seen (CKEditor), the content under edit is in an iframe. All other UI/Editing elements surround the iframe.

**Comment by JiHong88** [comment]
Yup, I understand.
The old version was `<iframe>`.
I'll add an `<iframe>` mode to the option.
Thank you. 👍

**Comment by sirlancelot** [comment]
Here's an example: https://www.froala.com/wysiwyg-editor/examples/full-page

**Comment by JiHong88** [comment]
Hi @sirlancelot 

Updated in [v2.19.0](https://github.com/JiHong88/SunEditor/releases/tag/2.19.0)

Thank you : )
