### ISSUE TITLE
Add line number is codeview

### ISSUE THREAD

**Issue by prashanthvdckap** [JiHong88/suneditor#1185]
Try to add line numbers in codeview so its look like code editor.
Hope it will helpfull to all.

one more question is how to change scroll bar design in editor

Thanks in advance

**Comment by davidkonrad** [comment]
Easy, if you are using CodeMirror :

```
codeMirror: {
  src: CodeMirror,
  options: {
     mode: 'htmlmixed',
     htmlMode: true,
     lineNumbers: true,
     lineWrapping: true 
  }  
}
```

**Comment by prashanthvdckap** [comment]
Thanks it work
