### ISSUE TITLE
Enable style tag on codeview 

### ISSUE THREAD

**Issue by prashanthvdckap** [JiHong88/suneditor#1189]
Its better to have style tag on codeview so that we can avoid inline css

Editor like summernote as this option.

Thanks in advance

**Comment by JiHong88** [comment]
https://github.com/JiHong88/suneditor/issues/1185
Added this issue to the 3.0.0 milestone.

**Comment by guido-visser** [comment]
Is there any progress on 3.0.0 milestone? What do you expect in terms of release?
