### ISSUE TITLE
toolbar inline mode 일 때, toolbar 위치 조정 여부 문의

### ISSUE THREAD

**Issue by rafael-develop** [JiHong88/SunEditor#119]
안녕하세요.

suneditor를 포함한 화면을 모바일과 같은 화면에서 표현할 때, toolbar 위치를 조정하고자 합니다.

input 키보드 표현 시, toolbar를 표현하기 위해 mode를 inline으로 수정 후 특정 위치(키보드 상위)에 표현 하고자 하는데, 별도 제공하고 있는 CSS 옵션이 있는 지 문의 드립니다.

감사합니다.

**Comment by JiHong88** [comment]
안녕하세요~

inline 모드일때는 툴바의 넓이가 %값 이거나 넓이와 버튼 갯수에 따라서 높이가 달라지기 때문에

화면에 표시될때마다  [_showToolbarInline](https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L2777) 에서 직접 top 위치값을 넣어 주고 있습니다.

현재 관련된 옵션은 없고 바꾸려면 위의 함수를 직접 수정하거나,

[Functions](https://github.com/JiHong88/SunEditor#functions) 의 onClick 이벤트가 툴바 표시 후에 호출되니 여기에서 다시 위치를 조정하는 방법이 있습니다.

작업방식을 공유해 주시면 옵션을 어떻게 추가할지 고민해서 다음버전에 업데이트 하겠습니다.

감사합니다.

**Comment by rafael-develop** [comment]
안녕하세요. 

답변 감사드립니다.

궁극적으로 저희가 구현하고자 하는 기능은, 평소에는 classic 모드로 툴바를 표현 하다가,

특정 조건(특정 넓이 이하의 화면)에서는 첨부 화면처럼 키보드 상위에 툴바가 text 입력시에만 한줄의 가로스크롤로 표현되는 형식입니다.

일단 말씀해주신 두가지 방법 활용하여 테스트해보겠습니다. 감사합니다.
 
![image](https://user-images.githubusercontent.com/53458745/63834031-4d02ce00-c9af-11e9-8444-1a9dd71dbe02.png)

**Comment by JiHong88** [comment]
안녕하세요.

showInline 이벤트를 추가 하였습니다. [[v2.19.0](https://github.com/JiHong88/SunEditor/releases/tag/2.19.0)]

감사합니다.
