### ISSUE TITLE
core._resourcesStateChange is not a function (in core.js)

### ISSUE THREAD

**Issue by wmhartl** [JiHong88/suneditor#1191]
Hello, 

I'm getting the following error:

```
    TypeError: core._resourcesStateChange is not a function

      at _resourcesStateChange (node_modules/suneditor/src/lib/core.js:6190:22)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)
```

This appears related to https://github.com/JiHong88/suneditor/issues/1138 but is different and your fix for that doesn't seem to address this error.

This is with suneditor-react 3.4.1 and sunedtior 2.44.3.

Thank you for your help - we love suneditor!

**Comment by JiHong88** [comment]
The [2.44.4](https://github.com/JiHong88/suneditor/releases/tag/2.44.4) version has been updated.
Thank you.
