### ISSUE TITLE
search event "onModified"

### ISSUE THREAD

**Issue by pedefe** [JiHong88/suneditor#1193]
Hello,
- event onInput triggers for character. But when paste...
- event onKeyup catch paste. But nothing appends when attribute is changed (bold, italic...)
How to detect any change in the whole content (character, paste, insertion of table, link, video...) ?
Best regards.

**Comment by pedefe** [comment]
Perharps event "onChange" is slow, as delayed, and so strange in debug ?

**Comment by JiHong88** [comment]
Is "onChange" not working properly?

**Comment by pedefe** [comment]
It's ok, it work.
The strange thing is only it is slow.
You can close the ticket.
Best regards.

**Comment by JiHong88** [comment]
It is executed with a delay as much as the value of "historyStackDelayTime". - default: 400(ms)

**Comment by pedefe** [comment]
Thank you for your quick and documented answer.
Best regards.
