### ISSUE TITLE
이미지 업로드시 팝업 상단이 가려지는 이슈가 있습니다

### ISSUE THREAD

**Issue by poohc300** [JiHong88/suneditor#1198]
![image](https://user-images.githubusercontent.com/25047319/228166569-dcb8a262-2eb3-4fd7-a3ee-b1bd7ffb3a8d.png)

이런식으로 팝업의 상단부분이 헤더에 가려질 떄는 어떻게 이 팝업을 좀 더 내릴 수 있을까요?

**Comment by JiHong88** [comment]
CSS로 상단 마진값을 조정해야 합니다.
```
.sun-editor .se-dialog .se-dialog-inner .se-dialog-content {
     margin: 1.75rem auto;
}
```

**Comment by poohc300** [comment]
옙 알려주신거 수정하니 내려가네요 감사합니다

**Comment by poohc300** [comment]
아 이거 직접 css 수정말고 코드로 하려면 useRef로 가져와서 수정하면 되는건가요?

**Comment by JiHong88** [comment]
javascript로 스타일 수정하겠다는 얘기인가요?
네 DOM에서 직접 찾아서 해도 될것 같네요

**Comment by poohc300** [comment]
옙 감사합니다!

**Comment by poohc300** [comment]
개발자님 궁금한게 한가지 더 있습니다. 저번에 이미지 조절하는 컨트롤러의 경우는 showController 함수를 통해 제어가 가능했는데

저 위의 팝업의 css는 어떤함수를 통해 접근이 가능할 까요?

ref 값의 current를 찍어도 어떤건지 모르겠습니다

**Comment by JiHong88** [comment]
모달은 관련 이벤트가 없습니다.
생성된 엘리먼트에서 querySelector  등으로 직접 찾아야 합니다.

**Comment by poohc300** [comment]
const styles = {
    'se-dialog se-dialog-inner se-dialog-content': {
    
      margin: '10rem',
    },
  };
따로 스타일 양식 지정해서 SunEditor 컴포넌트에 넣어도 적용이 되는군요 감사합니다

**Comment by poohc300** [comment]
해결했습니다 감사합니다 직접  children 타고 타고 내려가니깐 해당하는 dialog 나오네요 감사합니다
