### ISSUE TITLE
setContents without html tag will cause crash when editing

### ISSUE THREAD

**Issue by cub** [JiHong88/suneditor#1201]
**Describe the bug**
Init a wysiwyg and then set some contents without html tag like this `editor.setContents('Try to edit me, set me bold, add new line, ... Crash x_x');`.
Then try setting a style to the existing text or add a new line. This causes an error:
`Cannot read properties of undefined (reading 'textContent')` (style like bold)
or
`Failed to execute 'createElement' on 'Document': The tag name provided ('#text') is not a valid name.` (new line)

In version 2.44.3 no problem. Since 2.44.4 it crashes.

**To Reproduce**
https://stackblitz.com/edit/js-w6byqc?file=index.js

**Comment by JiHong88** [comment]
The [2.44.6](https://github.com/JiHong88/suneditor/releases/tag/2.44.6) version has been updated.
Thank you.
