### ISSUE TITLE
removed image style in preview page

### ISSUE THREAD

**Issue by james-song** [JiHong88/suneditor#1205]
Insert some image file to the suneditor and then check to content in preview mode. it's wrong image style (remove specify image size)

이미지를 추가 하고 미리보기를 누르면 이미지의 스타일이 제거되어 있습니다

**Comment by JiHong88** [comment]
The [2.44.7](https://github.com/JiHong88/suneditor/releases/tag/2.44.7) version has been updated.
Thank you.
