### ISSUE TITLE
Inline font-size style using absolute sizes (small, medium, large etc) throws error. setContents() fails

### ISSUE THREAD

**Issue by andylwelch** [JiHong88/suneditor#1207]
**Describe the bug**
Rendering html with an inline style that has a font-size as a word (e.g. small) throws an error which crashes the editor completely in my page.

**To Reproduce**
1. Go to http://suneditor.com/sample/index.html
2. Click on `Code view` button
3. Paste html in editor:
`<p><span style='font-size: small;'>Test</span></p>`
4. Open browser console, see error:
```
Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object._cleanStyle (core.js:5277:96)
    at Object._cleanTags (core.js:5335:34)
    at String.replace (<anonymous>)
    at Object.cleanHTML (core.js:5460:111)
    at Object.getContents (core.js:5114:35)
    at h (history.js:56:30)
    at Object.push (history.js:114:21)
    at Object.toggleCodeView (core.js:4685:34)
    at Object.commandHandler (core.js:4515:26)
    at Object.actionCall (core.js:4464:22)

Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object._convertFontSize (core.js:5224:29)
    at Object.active (fontSize.js:66:89)
    at Object._applyTagEffects (core.js:6394:90)
    at HTMLDivElement.onClick_wysiwyg (core.js:6581:23)
```

**Expected behavior**
HTML with [valid font-size style attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size) should render without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/7505965/229387433-feffeb9b-6dbd-4834-961e-4b54950ace25.png)
Crash:
![image](https://user-images.githubusercontent.com/7505965/229387392-bc71f80f-b3b2-4178-afcc-38a259836ecd.png)
![image](https://user-images.githubusercontent.com/7505965/229387480-36adc9db-5443-42e6-aac1-21e6212df7e0.png)

On Suneditor.com
![image](https://user-images.githubusercontent.com/7505965/229388791-88c4548e-7600-4ba3-aed3-3d065b09e249.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111.0.5563.147

**Additional context**
Looking at the code, the bug is only if fontSize plugin is utilised.  Possibly a mistmatch in the regex used for testing and the regex used for matching/replacing:

```
...
if (!this._cleanStyleRegExp.fontSizeUnit.test(r[0])) {
        r[0] = r[0].replace(this._w.RegExp('\\d+' + r[0].match(/\d+(.+$)/)[1]), this._convertFontSize.bind(this, options.fontSizeUnit));
}
...
```

**Comment by JiHong88** [comment]
The [2.44.7](https://github.com/JiHong88/suneditor/releases/tag/2.44.7) version has been updated.
Thank you.
