### ISSUE TITLE
Adding wrong characters in html code

### ISSUE THREAD

**Issue by a-tonchev** [JiHong88/suneditor#1211]
I noticed that the editor generates sometimes weird characters inside the html tag tag

![image](https://user-images.githubusercontent.com/111856433/229538372-bb4e35e8-089f-4fd7-b957-07de82427320.png)

Here the generated HTML:

 ```HTML
 <div style="text-align: center" "=""><span style="font-size: 20px"><strong><span style="color: rgb(189, 189, 189)" "="">Unleash Your Sales Potential, Discover the Power of High-Performance</span>&nbsp;<span style="color: rgb(241, 241, 241)" "="">Online Shop</span></strong></span><br></div>
 ```

**Comment by JiHong88** [comment]
If it is not the latest version, please test with the latest version.
Can you give me test data where the issue occurs?

**Comment by a-tonchev** [comment]
Can not provide test data, because codesandbox has not the latest version yet, but this is my code:

https://codesandbox.io/s/objective-lichterman-dzbc9u?file=/src/App.js:669-677

**Comment by JiHong88** [comment]
The [2.44.8](https://github.com/JiHong88/suneditor/releases/tag/2.44.8) version has been updated.
Thank you.
