### ISSUE TITLE
v2.44.10 has messed up image-handling

### ISSUE THREAD

**Issue by davidkonrad** [JiHong88/SunEditor#1226]
v2.44.10 seems to have done some bad things with the image-handling. I really dont know what causes it, just gave up after three hours and rolled back. 

- `__se__float-none` seems to be injected randomly out of the blue, for no reason
- changes to images (like 50% float left) does not actually happen, or is soon forgotten (see above). If the image is resized the <figure> fill the rest of the space, just empty white space
- changes to image no longer triggers `onChange`-event
- SunEditor suddenly seem to want to insert `<p></p>` before and after images and nearby text, making it impossible to create a image with floating text, aligned correctly
- The code editor is now even more reluctant to ignore cut/copy/paste (before it worked "some times", I know it is a thirdparty-thing, but it seem to me SunEditor accidently hijack those commands)
- Overall: More complex Image size, position and alignment are now broken. 

Have done this hundreds of times with prior versions. Normally I use the code editor to fix images, because there is such limited options in the dialogs, so I know exactly how the markup should look like, and SunEditor have done a good job until now. 

Even if I take old markup of from previous posts, made solely by SunEditor, and paste that in, v2.44.10 seem to screw that up as well. 

After some hours with frustration i gave up and went back to 2.44.3, everything works as a charm. The odd behaviour seen in both Chrome and FF.

Sorry I cannot be more precise. Nothing in the recent updates seem to address images nor all the basic `<markup>` logic at all, so I guess it is some unexpected side effect of a really small change elsewhere. 

BTW:  🥰 SunEditor!

**Comment by JiHong88** [comment]
There were many updates in 2.44.4.
So something seems to be wrong...
I'll let you know after fix

**Comment by JiHong88** [comment]
Can you give me a source to test on?

**Comment by JiHong88** [comment]
The [2.44.12](https://github.com/JiHong88/suneditor/releases/tag/2.44.12) version has been updated.
Thank you.

**Comment by davidkonrad** [comment]
I can confirm that the above oddities now are gone with v2.44.12. Thank you. ❤️ SunEditor. It is really an impressive piece of work.
