### ISSUE TITLE
Resize Bar: Rendered outside of height constrained container

### ISSUE THREAD

**Issue by stolp** [JiHong88/suneditor#1227]
**Describe the bug**
When placing the editor in a height limited container, the placement of the resizing bar is done outside of the container space.

**To Reproduce**
1. Create a div with style="maxHeight: 320px", allowing vertical scroll overflow and containing the Sun Editor

**Expected behavior**
The resizing bar should be placed inside the scrolled area.

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: 2.44.10

**Additional context**
![Resizing-bar](https://user-images.githubusercontent.com/522940/232324463-7e8f73fd-5acc-42d0-9fd2-25219eff473c.png)

**Comment by JiHong88** [comment]
I don't quite understand.
All elements are rendered inside "<div.sun-editor>".
It is correct that the internal scrolling of the editor works separately from the resizing bar.

**Comment by stolp** [comment]
Ok, I think I found a solution by setting max-height directly on .sun-editor-editable. My bad, sorry for the false alert.

Closing this issue here.
