### ISSUE TITLE
글꼴 굵게랑 기울임이 적용이 안됩니다

### ISSUE THREAD

**Issue by poohc300** [JiHong88/suneditor#1228]
![image](https://user-images.githubusercontent.com/25047319/232668565-78d3362a-0582-4110-9756-82a1c53a2f7c.png)

위의 사진과 같이 밑줄이나 취소선 같은 기능은 되는데 굵게랑 기울임만 이상하게 안되네요

코드에서는 아래와 같이 옵션을 줬습니다

![image](https://user-images.githubusercontent.com/25047319/232668653-ca4a88c3-9bf0-4a5c-9654-714d51d132bb.png)

**Comment by JiHong88** [comment]
이슈 재현이 안됩니다..
굵기, 기울임 적용했을때 생성되는 태그 있는지 한번 확인해주세요.

**Comment by poohc300** [comment]
<p><strong> 내용 </strong> </p> 이거 말씀하시는거면 생성됩니다. 에디터에 상태값으로 넣어지는데도 저것만 적용이 안됩니다

**Comment by JiHong88** [comment]
strong 태그는 정상적으로 들어가는데 굵게 스타일이 적용 안된다는 건가요?

**Comment by poohc300** [comment]
예 마찬가지로 기울임도 em태그는 적용이 된 텍스트가 콘솔로그 찍어보니 나오는데 적용은 안되더라구요

**Comment by JiHong88** [comment]
태그 정상적으로 생성되고 있으면 이상은 없는것 같네요
css 확인해봐야할것 같습니다.
강제로 스타일 주고 있는게 있는지..

**Comment by poohc300** [comment]
예 한번 찾아보고 말씀드리겠습니다 감사합니다

**Comment by poohc300** [comment]
아 이거 늦게 말씀드립니다 제가 쓰는 css와 겹쳐서 생긴 단순 이슈였습니다 답해주셔서 감사합니다
