### ISSUE TITLE
A component is contentEditable and contains children managed by React in Suneditor while working in Next.js.

### ISSUE THREAD

**Issue by divrawat** [JiHong88/suneditor#1229]
Adding images or iframes through suneditor to a blogpost or article will give warning in console "A component is contentEditable and contains children managed by React" after viewing that article or blogposts.

![1](https://user-images.githubusercontent.com/83118748/232751915-9803043f-d577-49eb-a82e-c8e23f148c49.png)
...

..
..

Published Article -- 

![2](https://user-images.githubusercontent.com/83118748/232751970-f50d312b-225d-44b9-bb9b-39fd29519bee.png)

This is because when you add image or iframe then an attribute contenteditable=" false" is attached to image component or div of SunEditor. And because of this, warning can be seen in console.

![3](https://user-images.githubusercontent.com/83118748/232752055-4bcd2d70-6bba-4ec3-b3d9-74f040cf3dbf.png)

If I remove contenteditable=" false" from source of Suneditor while writing the article and then view that article after publishing then the warning is gone.

![4](https://user-images.githubusercontent.com/83118748/232752119-c8b9b91a-0a2f-444c-ba17-c078e3c1d35a.png)

@JiHong88  is there a reason why we add contenteditable=" false"?

Conclusion -  Adding images or iframes etc. through Suneditor to a blogpost or article will give warning in console "A component is contentEditable and contains children managed by React" after viewing that article or blogposts.

**Comment by JiHong88** [comment]
The [2.44.12](https://github.com/JiHong88/suneditor/releases/tag/2.44.12) version has been updated.
Thank you.
