### ISSUE TITLE
Paste from Word

### ISSUE THREAD

**Issue by Yves-K** [JiHong88/SunEditor#123]
Hello, this is a very nice work ;-)

Pasting from Word does only import first paragraph !

Is there a onPaste event and how to use it ?

Bes regards

**Comment by JiHong88** [comment]
Hi, @Yves-K 

Thank you : )

It will be added in the next update.

**Comment by JiHong88** [comment]
Hi @Yves-K  

Updated in [v2.19.0](https://github.com/JiHong88/SunEditor/releases/tag/2.19.0)(Added onPaste event)

Thank you : )
