### ISSUE TITLE
Font Color resets font size, and otherwise too

### ISSUE THREAD

**Issue by a-tonchev** [JiHong88/suneditor#1230]
When font color is set, the font size is reset, when I set again font size, the font color is removed. And so on.

The behavior can be tested also here:

http://suneditor.com/sample/index.html

1. I set font color:

![image](https://user-images.githubusercontent.com/54528540/232838243-c84fdde1-0427-48cf-8298-792b7292e14f.png)

2. I change font size:

![image](https://user-images.githubusercontent.com/54528540/232838404-8294df5f-cf1e-45fb-af0f-1b69d577e0b0.png)

3. Font color is removed:

![image](https://user-images.githubusercontent.com/54528540/232838572-1bdc55cd-88e9-467d-bd58-d49b4cc98b3f.png)

**Comment by JiHong88** [comment]
The [2.44.12](https://github.com/JiHong88/suneditor/releases/tag/2.44.12) version has been updated.
Thank you.

**Comment by a-tonchev** [comment]
@JiHong88 thank you. You are the best!
