### ISSUE TITLE
Read only mode - enter button press

### ISSUE THREAD

**Issue by CasperKZP** [JiHong88/suneditor#1234]
In read only mode, when we press enter button we can change the text.

1. Go to http://suneditor.com/sample/html/examples.html#functions
2. Click on ReadOnly button
3. Select the text and press Enter
4. Text changed

**Expected behavior**
Dont change the text in read only mode.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/98448356/234019753-d3abd306-7143-425f-9b97-c89b22ffd772.png)
2. ![image](https://user-images.githubusercontent.com/98448356/234019876-11c99a4a-8935-49c7-81ac-165f131a94a3.png)
3. ![image](https://user-images.githubusercontent.com/98448356/234020036-abdb2244-bc97-4354-93a8-f56ec262bca2.png)
4. ![image](https://user-images.githubusercontent.com/98448356/234020096-5c68a32e-f97a-44e9-883a-b860f534dac2.png)

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
