### ISSUE TITLE
Issues with inputting data in a pricing table plugin in multiple browsers

### ISSUE THREAD

**Issue by Tanay-J** [JiHong88/suneditor#1236]
I am creating a pricing table using a custom plugin inside a suneditor instance. The table has editable columns for Name, Price, and Quantity, and the subtotal column value is dyanamically calculated based on the values of the Price and Quantity columns. Also, the table has tax and discount columns, which are calculated accordingly. There are buttons to add and delete rows as well.

While the plugin works fine in Firefox, I am experiencing issues with inputting data in other browsers. I am only able to input one character at a time. After entering a character, the focus is lost, the cursor disappears and I need to click on the cell again to get the cursor.

I have created a CodeSandbox to replicate the issue. [Link](https://codesandbox.io/s/suneditor-pricing-table-so-vjzs9p).

The issue seems to be due to suneditor because same pricing table works correctly stand alone. Only inside suneditor and that too in Chrome the issue occurs.

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
