### ISSUE TITLE
formatBlock and styles

### ISSUE THREAD

**Issue by Yves-K** [JiHong88/SunEditor#124]
Hello again,

SunEditor is so good...
So i went in a deep deeeep testing.

**formatBlock :**
Is it possible to disable a default format (H1 for instance) ?
How to add new formats (tag + class) ?

**styles**
Is it possible to replace inline styles by classes ?

Best regards.
PS : how could we help ?

**Comment by JiHong88** [comment]
Hello,

Thank you very much :)

**formatBlock:**
1. You can override this in the formats [option](https://github.com/JiHong88/SunEditor#options).
2. It can be updated to add new formats.

**styles**
1. The [suneditor-contents.css](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css) file defines the style of all tags.
2. Inline styles mean things like font-color, font-size of span tag?

Best regards.

**Comment by JiHong88** [comment]
Hi @Yves-K 

Updated in [v2.19.0](https://github.com/JiHong88/SunEditor/releases/tag/2.19.0)

Thank you : )
