### ISSUE TITLE
Bug using shift-right arrow at the end of a line.

### ISSUE THREAD

**Issue by oaknorton** [JiHong88/suneditor#1242]
Please watch:
https://www.loom.com/share/98963b9bb4054aa9b80c8153f73e425f
I discovered this in my own app, then verified it happens in your demo page.

**Comment by oaknorton** [comment]
Recreated the lockup bug here and discovered more about the bug. Holding shift-right arrow acts different than tapping the right-arrow. https://www.loom.com/share/5e12976bfe33454ca74e8bbd5ea88f90

**Comment by JiHong88** [comment]
I can't figure out what the issue is just by watching the video.
There is a reason why I can't speak English.
Can you briefly write it down?

**Comment by oaknorton** [comment]
OK. If you are in any text editor like MS Word or the Sun Editor, if you hold down on the shift key and then use the arrow keys, you select or highlight text which you can then do an operation on. In the Sun Editor, if you are on a given line and hold the shift key down and there is a line break or paragraph end at the end of the line, if you press the right arrow key you and go beyond the end of the line you should go to the next line and continue highlighting. Sun Editor doesn't do this. You can use Shift with the up or down arrow and it works fine to select a range that includes multiple lines, or shift-left arrow to go to the left of a line and then to the end of the line before, but you can't use the shift-right arrow to get to the end of a line and go to the next row down. It just stops.
Another bug is in using shift-down arrow and getting to the bottom of a document, if I press it again, it jumps me back up to the higher position where I started from. 
Here is a new shorter video just demonstrating these 2 bugs. 
https://www.loom.com/share/9693399378d24f0dbc0e909e8da7c146

**Comment by JiHong88** [comment]
issue 1. shift + right
issue 2. shift + down

**Comment by oaknorton** [comment]
Thank you! Is the version 2.45 milestone a stable release? I see you added this to it. Can I implement it?

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
