### ISSUE TITLE
attributesWhitelist does not handle class attribute in img tags

### ISSUE THREAD

**Issue by spiff123** [JiHong88/suneditor#1244]
**Describe the bug**

This configuration:

 attributesWhitelist: {
            'img': 'class|style|data-.+'
        },

Does not keep the class attribute in the img tag.

**To Reproduce**
1) add a image
2) goto source editor
3) add class="myclass" to the img tag
4) save 

**Expected behavior**
It would be nice to have the class tag keept at the img tag even after save.
Use Case: PreviewImage in a template should be visible in editor and not visible in saved output.

Version: 2.44.12

 - Browser firefox

**Comment by JiHong88** [comment]
Classes must start with "se-, __se__".

**Comment by spiff123** [comment]
Thank you!

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
