### ISSUE TITLE
Adding links creates illegal href when protocol is given.

### ISSUE THREAD

**Issue by cardalda** [JiHong88/suneditor#1245]
Adding a link always prepends localhost://, despite a (custom) protocol was given.
For example: adding the link 

custom://my_handled_link/what_ever

should not change to 

https://localhost:8081/custom://my_handled_link/what_ever

Tested on version [v2.44.12] with latest chrome...

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
