### ISSUE TITLE
HTML elements removed / classes removed after editing WYSIWYG

### ISSUE THREAD

**Issue by cardalda** [JiHong88/suneditor#1246]
after pasting html code below; the editor renders the table in the right colors in WYSIWYG. After typing one character and switching to the Code editor, you can see one DIV has been removed and all class names are removed.
This is tested on v 2.44.12 and used to work in older versions...

```html
<h3>DIV Demo</h3>

<div style="display: flex;justify-content: space-evenly;">
    <div style="background-color:tan;display: flex;flex-direction: column;">
        <table class="db">
            <tbody>
                <tr class="title">
                    <td colspan="2">
                        <div>flow</div>
                    </td>
                </tr>
                <tr class="header">
                    <td>
                        <div>name</div>
                    </td>
                    <td>
                        <div>type</div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>id</div>
                    </td>
                    <td>
                        <div>number</div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
```

for example, change Demo to Demo2 in WYSIWYG mode and switch to code...

```html
<h3>DIV Demo2</h3>

<div>
    <table>
        <tbody>
            <tr>
                <td colspan="2">
                    <div>flow</div>
   ...
```

**Comment by JiHong88** [comment]
Classes must start with `se-`  or `__se__`.
In the next version, the 'allowClassName' option will be added.

**Comment by cardalda** [comment]
Hi mr JiHong,

did you close this for only the class names?
That's only part of the problem ;-)

The inline styles are also gone (I can solve this by adding more "se-" classes"
, and one DIV level has been removed, breaking my custom style; This cannot be solved with classes...

**Comment by JiHong88** [comment]
Add the "__se__tag" class to the topmost "div".
Then that element will not be checked for consistency.

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
