### ISSUE TITLE
characters added after switching code/WYSIWYG

### ISSUE THREAD

**Issue by cardalda** [JiHong88/suneditor#1248]
Tested in latest version, but behaviour already existed before.
Repro:
Start new editor, in WYSIWYG mode, type in:
```
Line1<SHIFT ENTER>
Line2
```
Switch to code for the first time:
```html
<p>Line1<br>
Line2</p>
```
Switch to WYSIWYG and immediately back to code; code changes to
```html
<p>Line1<br>

Line2</p>
<p></p>

```
So, an extra CR is added and at the end we have an extra paragraph.
Every time you switch between the modes, an extra CR is added and after 10 times you get
```html
<p>Line1<br>









Line2</p>
<p></p>

```

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
