### ISSUE TITLE
 suneditor can be attached to div?  

### ISSUE THREAD

**Issue by yashvi2026** [JiHong88/suneditor#1249]
i wanted to attach editor to a div not textarea ,but when i do it gives a textarea with undefined content to edit

**Comment by JiHong88** [comment]
"div" is also possible.
Just create it the same way as "textarea".

**Comment by yashvi2026** [comment]
but it creates a textarea with undefined contents
this hii div is not displayed
<div id="hy">hiiiiiiiiiii</div>
const editor = SUNEDITOR.create("hy", {
  mode: "balloon",
  buttonList: [["fontColor", "hiliteColor", "textStyle"]]
});

**Comment by JiHong88** [comment]
You can use the `value` option.
```
const editor = SUNEDITOR.create("hy", {
value: "hiiiiiiiii", // or HTML string
mode: "balloon",
buttonList: [["fontColor", "hiliteColor", "textStyle"]]
});
```

**Comment by yashvi2026** [comment]
do i have to get the contents and set to the value?

**Comment by JiHong88** [comment]
Yes, it is.
In the next version, I'll change it to get the contents of the div as well.

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
