### ISSUE TITLE
TD, TR closing tags are not indented properly 

### ISSUE THREAD

**Issue by cardalda** [JiHong88/suneditor#1252]
Repro:

Start a new editor; in WYSIWYG, add a new Table 1x2
When switching to Code editor, the HTML is properly aligned:
```html
<table>
  <tbody>
    <tr>
      <td>
        <div><br>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div><br>
        </div>
      </td>
    </tr>
  </tbody>
</table>
```
Now switch to WYSIWYG and back to code editor
```html
<table>
   <tbody>
     <tr>
       <td>
         <div><br>

        </div>
 </td>
 </tr>
     <tr>
       <td>
         <div><br>

        </div>
 </td>
 </tr>
 </tbody>
</table>
<p></p>
```
All closing TR,TD and TBODY tags are indented on the same level.
This makes is hard to use a DIFF editor to compare the original HTML code with the newly generated HTML code.

**Comment by JiHong88** [comment]
This issue fixed in the latest version.
