### ISSUE TITLE
image width/height compatibility for outlook

### ISSUE THREAD

**Issue by MatthSHo** [JiHong88/suneditor#1258]
Html code generated from suneditor containing img tag works great everywhere except in outlook mail where size value set in style attribute gets ignored.

For instance with an image real width 500px, this adds the image with a width 500px in outlook and 300px everywhere else.
`<img src="myImage-width-500.jpg" style="width:300px;">`
whereas this works and display an image 300px
`<img src="myImage-width-500.jpg" width="300" style="width:300px;">`

Would it be possible to set (when defined) width and/or height attribute in [image plugin setSize function](https://github.com/JiHong88/suneditor/blob/0337638ef6e3a41fbad32e928b0d44373f0afcd0/src/plugins/dialog/image.js#L948) (not only the value in style) ? 

I tried to parse and fix the generated html but this is much less efficient than manipulating the img tag when generated.
I was not able to find a clean way to register any js code to do it on the SUNEDITOR object.

**Comment by stryzhak** [comment]
I've experienced same thing and modify following function with little tweak 
https://github.com/JiHong88/suneditor/blob/0337638ef6e3a41fbad32e928b0d44373f0afcd0/src/plugins/modules/resizing.js#L377
```javascript
     _module_saveCurrentSize: function (contextPlugin) {
            const x = this.plugins.resizing._module_getSizeX.call(this, contextPlugin);
            const y = this.plugins.resizing._module_getSizeY.call(this, contextPlugin);
            contextPlugin._element.setAttribute('width',x.replace('px',''));
            contextPlugin._element.setAttribute('height',y.replace('px',''));
            contextPlugin._element.setAttribute('data-size', x + ',' + y);
            if (!!contextPlugin._videoRatio) contextPlugin._videoRatio = y;
        },
```
