### ISSUE TITLE
Font / Font size not being saved in lists

### ISSUE THREAD

**Issue by skyng22003** [JiHong88/suneditor#1268]
Encountered a possible bug where in lists the fonts / font size are not being saved, html showing the font being correctly applied in the suneditor for both lists and normal text
![Screenshot from 2023-06-30 12-33-25](https://github.com/JiHong88/suneditor/assets/10564466/c944a12c-eec3-4d84-b90b-f0e2f29ff499)

How ever after I save and reload from the backend the lists do not retain the font but the normal text is fine? html below

![Screenshot from 2023-06-30 12-34-40](https://github.com/JiHong88/suneditor/assets/10564466/0fcf0b63-c5d9-4d08-b637-4114d5167808)

**Comment by HoangLong08** [comment]
Have you solved your problem yet?

**Comment by JiHong88** [comment]
until the bug is resolved
For now, you can use the options below.
```
attributesWhitelist: {
        li: 'style',
}
```
