### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'previousElementSibling')

### ISSUE THREAD

**Issue by smorodin-it** [JiHong88/suneditor#1274]
**Describe the bug**
When I try to upload 2 images, i got error in console and editor stuck

```
core.js:2146 Uncaught TypeError: Cannot read properties of null (reading 'previousElementSibling')
    at Object.removeNode (core.js:2146:45)
    at Object.insertComponent (core.js:1565:28)
    at Object.create_image (image.js:677:18)
    at Object.onRender_imgBase64 (image.js:556:30)
    at Object.<anonymous> (image.js:533:63)
removeNode @ core.js:2146
insertComponent @ core.js:1565
create_image @ image.js:677
onRender_imgBase64 @ image.js:556
(anonymous) @ image.js:533
load (async)
setup_reader @ image.js:529
upload @ image.js:484
submitAction @ image.js:452
submit @ image.js:376
```

**To Reproduce**
1. Go to http://suneditor.com/sample/index.html
2. Remove all content from editor 
3. Click on image button
4. In modal, select image, then click submit
5. Click somewhere under editor.
6. Click on image button,
7. In modal, select image, then click submit

**Expected behavior**
Second image appear under first

**Screenshots**
![image](https://github.com/JiHong88/suneditor/assets/81906452/693e7cb9-182a-4eba-9379-95222049f55d)

**Desktop (please complete the following information):**
 - OS: fedora 37
 - Browser chrome
 - Version  114.0.5735.198 (Official Build) (64-bit)

**Comment by hamid-hoseini** [comment]
Could you please provide an update regarding this issue? 
I am currently using this editor and have encountered the mentioned problem. 
Even after adding the horizontal line twice, the issue persists. 
Any assistance or information would be greatly appreciated.

**Comment by JFox23** [comment]
This issue has been reported more than once, i made a pull request for #1312 which reports the same error on the same line.
