### ISSUE TITLE
Styles have wrong functionality on selected text in mobile devices

### ISSUE THREAD

**Issue by AliBayatMokhtari** [JiHong88/suneditor#1277]
**Describe the bug**
Changes not applying on selected text in mobile(touch) devices.

**To Reproduce**
1. Open Suneditor website examples.
2. Write some text contains spaces and new lines.
3. Select piece of text.
4. Make it bold(or any other style).
5. Bold styles not applied to the whole selected text.

**Expected behavior**
The whole selected text should get the styles.

**Screenshots**
The selected text:
![telegram-cloud-photo-size-4-5881832277808364195-y](https://github.com/JiHong88/suneditor/assets/40760750/0de72a99-fbe6-4981-afb9-d9b320b4ce33)

The result(bug):
![telegram-cloud-photo-size-4-5881832277808364196-y](https://github.com/JiHong88/suneditor/assets/40760750/d1a5c471-f434-41e7-81ac-f89417e503ea)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52s
 - OS: Android 13
 - Browser: Chrome
 - Version: 109

**Comment by AliBayatMokhtari** [comment]
@JiHong88 any update on this issue?

**Comment by payandeh** [comment]
I have the same problem 
when it would be fixed?

**Comment by iroon-ila** [comment]
I have the same problem

**Comment by JiHong88** [comment]
http://suneditor.com/v3/cdn_test.html
Can you check if the same phenomenon occurs here?

**Comment by AliBayatMokhtari** [comment]
It's working fine.

**Comment by JiHong88** [comment]
@AliBayatMokhtari That page is a test of version 3.
The code has changed a lot, so I will apply the estimated code to the current version.
