### ISSUE TITLE
Displace (always) & Paste (sometimes) result blank text with Firefox

### ISSUE THREAD

**Issue by sudwebdesign** [JiHong88/SunEditor#128]
When cut or copy **not** entire text with _return line(shift+enter) <br>_, Paste (ctrl+v) is empty.
i written an [article in with animated screen captures*](http://sudwebdesign.free.fr/index.php?article47/suneditor-error-on-firefox-when-cut-copy-and-paste) ;)

*Screen cast realized from [your sample page](http://suneditor.com/sample/index.html) at 2:55pm in France today (2019.09.29), Maybe its v2.19, sorry ;)

**Comment by JiHong88** [comment]
Hi, @sudwebdesign 

Thank you for the details. 👍 👍 👍 

Fixed in [v2.19.1](https://github.com/JiHong88/SunEditor/releases/tag/2.19.1)

**Comment by sudwebdesign** [comment]
Thank you to, its work fine now ;) :)
I published a [new version of plugin for Pluxml](https://forum.pluxml.org/discussion/comment/59339/#Comment_59339)
