### ISSUE TITLE
Styling issues with copy/paste from office apps

### ISSUE THREAD

**Issue by rocinante-sys** [JiHong88/suneditor#1280]
**Describe the bug**
There appears to be an issue with the parser from office apps. I tried to copy/paste some text from OneNote to Suneditor and there are styles missing as well as spaces.

**To Reproduce**
1. Go to OneNote and write text as seen here 
![image](https://github.com/JiHong88/suneditor/assets/52488395/a1d9bb08-1006-48bd-ad97-cef4d38b3654)

2. Highlight the text and copy it to clipboard
3. Go to suneditor and paste the text from clipboard
4. Pasted text to SunEditor 
![image](https://github.com/JiHong88/suneditor/assets/52488395/ac16da57-2dc8-4121-b58d-d1abc518e2fa)

p.s. If I copy same text from word then pasted text is ok with the exception of `paste` word not being bolded.
![image](https://github.com/JiHong88/suneditor/assets/52488395/7e9d65ca-eddc-445e-84c1-5d6b1b0594c6)

**Expected behavior**
I expect to see the same text formatting as in the office application.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome Version 115.0.5790.102 (Official Build) (64-bit)
 - suneditor version: 2.45.1
 - suneditor-react version: 3.6.1

**Comment by orijmm** [comment]
I was using the latest version 2.45.1 and when I copied tables with bold text it didn't paste it the same way. I had to roll back to version 2.44.1 which was the last version that did the pasting correctly.

![image](https://github.com/JiHong88/suneditor/assets/3276266/3d76ba17-896c-47cd-8175-9fea4e320845)
