### ISSUE TITLE
Remove Blue squarre qui resize l'image

### ISSUE THREAD

**Issue by Zoinloz** [JiHong88/suneditor#1281]
Hi,

My issue is the following :
If I want to put a large image in my component and the size exceeds a blue square appears to resize the image, how do I remove this feature?

This square appears when there is a scollbar (circled in red on the image)

In the second image we can see that the square continues to the full size of the image.

As requested above I only want to remove the blue square and leave the image size. Just be able to scroll in my component

Thanks

![image](https://github.com/JiHong88/suneditor/assets/56817478/990b7420-fd60-4b94-ab32-c804add21ed3)
![image](https://github.com/JiHong88/suneditor/assets/56817478/aedb4227-9e9c-44f7-8964-aca2bad7f0e9)

**Comment by JiHong88** [comment]
This issue is fixed in version 3.0.0.
It is expected that it will take several months to deploy.
