### ISSUE TITLE
Text Alignment after image and color for bullets 

### ISSUE THREAD

**Issue by phani697** [JiHong88/suneditor#1282]
Three bugs is here.

1. Unable type the text beside the selected image. 
2. Select the bullet listed text and change the color. Now check the preview. Color is not applied.
3. First upload the image. Next click the mouse pointer out side text editor. Next again try to upload image. Then you will get crash.

Please Check the video : 
https://drive.google.com/file/d/105-8KwGGi7bO0LMQb_Q7DP-O-QVpmxPG/view?usp=drive_link

**Comment by Tiago-Rocha09** [comment]
I'm getting the same font-color error.
Did you manage to resolve this?
