### ISSUE TITLE
Cannot read properties of undefined (reading 'charCounter') - NextJS - suneditor 2.45.1 - suneditor-react 3.6.1

### ISSUE THREAD

**Issue by dharyel** [JiHong88/suneditor#1286]
Greetings, @JiHong88 . First I need to say that I LOVE your rich text editor. I had a lot of headache with the popular ones, but neither of them work as I needed. Suneditor is a bless. Thank you very much.

**Describe the bug**
I am facing an error that prints on console only about charCounter funcionallity. But if you close the error, it is working normal(great). 
It looks that 'context.element' is undefined, but I didnt understand why because you already did a condicional check for its existance before:
![image](https://github.com/JiHong88/suneditor/assets/85208565/8cd911aa-fec8-436c-a848-f197da8b5b49)

I am using these versions(I believe its the latest ones):
- "suneditor": "^2.45.1",
- "suneditor-react": "^3.6.1",

**To Reproduce**
I am using nextjs with react-hook-form. 
The value its recieved is an useState variable from the component that is using RichTextEditor

my editor code:
`
//start
export const RichTextEditor = ({ value, onChange }: RichTextProps) => {
  const handleEditorChange = (content: string) => {
    onChange({ text: getContentText(content), html: content });
  };

  const getContentText = (content: string) => {
    const tempDiv = document.createElement("div");
    tempDiv.innerHTML = content;
    return tempDiv.innerText;
  };

return
<SunEditor
      onLoad={() => {
        const editorLabels = document.querySelectorAll(".sun-editor label");

        editorLabels.forEach((label) =>
          label.setAttribute("class", "sun-editor__label")
        );
      }}
      lang={"pt_br"}
      onImageUploadBefore={(data) => {
        console.log("imageUploadBefore", data);
        return false;
      }}
      onAudioUploadBefore={(data) => {
        console.log("onAudioUploadBefore", data);
        return false;
      }}
      onVideoUploadBefore={(data) => {
        console.log("onVideoUploadBefore", data);
        return false;
      }}
      setOptions={{
        maxCharCount: 5000,
        charCounterType: "char",
        charCounter: true,
        templates: [
          {
            name: "Template-1",
            html: "<p>HTML source1</p>",
          },
          {
            name: "Template-2",
            html: "<p>HTML source2</p>",
          },
        ],
        buttonList,
      }}
      onChange={handleEditorChange}
      setContents={value}
    />

//end
`

**Expected behavior**
there is no need to this console error be displayed, because its working normal.

**Screenshots**
![image](https://github.com/JiHong88/suneditor/assets/85208565/90dc9b16-554a-4a2a-8f83-64e95aaf5032)

Observation: the suneditor is inside a Drawer(ChakraUI drawer)
![image](https://github.com/JiHong88/suneditor/assets/85208565/3b91e2ce-edc2-4ce7-9401-131d9ab1ae02)

**Comment by JiHong88** [comment]
It's an incomprehensible bug. 
For now, I did my best to handle the exception..
