### ISSUE TITLE
이미지 연속 업로드 에러 관련 질문드립니다~

### ISSUE THREAD

**Issue by suCozy** [JiHong88/suneditor#1288]
To make it easier for us to help you, please include as much useful information as possible.

## Version
Write the version of the Editor you are currently using.
"next": "^13.1.6",
"react": "^18.2.0",
"suneditor": "^2.45.1",
"suneditor-react": "^3.6.1",

## Additional context

안녕하세요 이미지 업로드에 대해 여쭤보려고 합니다

현재 기능상 문제는 없지만 이미지 업로드를 연속으로 하면 에러가 발생합니다

예를 들어 첫번째 이미지를 업로드 한 후 화살표? 같은 버튼 클릭 안하고 다시 이미지 업로드를 하면 에러가 발생하고 있습니다

TypeError: Cannot read properties of null (reading 'previousElementSibling')

짐작으로는 커서를 못찾아서 그런건가 싶은데

혹시 이미지 업로드 중 에러 발생시 처리 할 수 있게 하고 싶은데 알고 계신거 알려주시면 감사합니다!!

```tsx
const onImageUploadBefore = (files, info, uploadHandler) => {
    try {
      const file = files && files[0];

      uploadFile({ file })
        .then((data) => {
          const response = {
            // The response must have a "result" array.
            result: [
              {
                url: data?.data?.Location,
                name: files[0].name,
                size: files[0].size,
              },
            ],
          };

          uploadHandler(response);
        })
        .catch((err) => {
          console.error(err);
        });
    } catch (err) {
      alert('에러가 발생했습니다.');
      // uploadHandler(err.toString());
    }

    return undefined;
  };

<SunEditor
        lang="ko"
        name="sun-editor"
        width="100%"
        height="100%"
        autoFocus
        setOptions={{
          ...
          ],
          defaultTag: 'div',
          minHeight: '300px',
          showPathLabel: false,
        }}
        getSunEditorInstance={getSunEditorInstance}
        onImageUpload={handleImageUpload}
        onChange={onChange}
        onImageUploadBefore={onImageUploadBefore}
        setContents={content}
      />
```

제 코드는 위와 같습니다.

**Comment by God-lives** [comment]
포커스가 없이 이미지 올려도 에러 납니다. 포커스 넣고 한글자 이상 있어야만 이미지업로드 에러가 안나더군요. 이부분만 빨리 고쳐주시길 바랍니다. 저는 그래서 이미지 업로드할때 강제로 글자 넣고 포커스하고 이미지 업로드하려고 계획중이긴합니다.
