### ISSUE TITLE
ios 환경에서 한글 줄바꿈 오류

### ISSUE THREAD

**Issue by insomenia-jungpyo** [JiHong88/suneditor#1289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

ios 환경에서 에디터에 '모음으로 끝나는 음절' 입력 후 줄바꿈(엔터) 시 줄바꿈이 제대로 되지않고 이전에 입력했던 글자가 한번 더 입력되는 현상이 있습니다.

**Comment by insomenia-jungpyo** [comment]
확인감사드립니다. 혹시 버그 영상 자료 첨부가 필요하실까요?

**Comment by JiHong88** [comment]
괜찮습니다. ios 에서 확인했습니다.
감사합니다.

**Comment by insomenia-jungpyo** [comment]
> 괜찮습니다. ios 에서 확인했습니다. 감사합니다.

혹시 해당 이슈에 대한 디버깅이 진행중이실까요? 경과가 궁금합니다.

**Comment by insomenia-jungpyo** [comment]
> 괜찮습니다. ios 에서 확인했습니다. 감사합니다.
혹시 디버깅이 진행중이실까요?

**Comment by JiHong88** [comment]
네 모바일에서의 IME 동작이 문제인것 같아.
관련 수정하려합니다.
