### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by pazicb** [JiHong88/SunEditor#130]
Hi,
Can you advise me how to set up an upload of image?
If I use:
imageUploadHeader: 'multipart/form-data',    
imageUploadUrl: "UploadProcess.ashx",
images will download correctly to the server, but SunEditor freezes.
I would need an example of what imageUploadHeader should look like and what imageUploadUrl should return.
Now it returns:
Response.StatusCode = 200
Response.ContentType = "text/plain"
Response.Write("Success")

Thank you

**Comment by JiHong88** [comment]
Hi, @pazicb 

Just return the array in "Response.result"

```  
Response.result = [
    {  
        "url": "/download/editorImg/test_image.jpg", // (Image url)
        "name": "test_image.jpg", // (Image origin name)
        "size": "561276" // (Byte)
    }  
]
```

If an error occurs, send an error message.

`Response.errorMessagex = ""`
