### ISSUE TITLE
Bullet formatting deletes text

### ISSUE THREAD

**Issue by Arushi2012** [JiHong88/suneditor#1308]
**Steps to reproduce:**
1. Use bullet formatting 
2. Now press tab for sub-bullets
3. Press enter twice and observe that the data is getting deleted

**Video:**
https://github.com/JiHong88/suneditor/assets/41018912/9d27d1c2-69dc-42e7-ad20-3640ee68d090

**Comment by Arushi2012** [comment]
@JiHong88 This looks like its related to this : https://github.com/JiHong88/suneditor/issues/1269 ?

**Comment by ashu-dev-ops** [comment]
@Arushi2012 did you find any solution .I am facing same problem
link =>https://github.com/mkhstar/suneditor-react/issues/350
