### ISSUE TITLE
Problem createElement

### ISSUE THREAD

**Issue by pazicb** [JiHong88/SunEditor#136]
Hello,
If I set
"imageFileInput": true 

and in the new plugin I do all at once
const oImg = this.util.createElement("IMG");
oImg.src = "abc.jpg";
this.insertNode(oImg);

const  oA = this.util.createElement("A");
oA.href = "http://www.suneditor.com";
oA.textContent = "test";
oA.target = '_blank';
this.insertNode(oA);

everything is inserted correctly in the editor, but I cannot select the image in the editor.

If I set
"imageFileInput": false 

element A is inserted and disappears immediately.

**Comment by JiHong88** [comment]
Hi @pazicb 

The image is made with a slightly more complicated structure.

Can you email me your custom plugin file?

**Comment by pazicb** [comment]
I'm doing experiments with your plugin "1. submenu plugin". If the editor is empty, the IMG tag is inserted, the A tag is deleted.

onClick: function () {
        const oImg = this.util.createElement("IMG");
	oImg.src = "abc.jpg";
	this.insertNode(oImg);

	const oA = this.util.createElement("A");
	oA.href = "http://www.suneditor.com";
	oA.textContent = "test";
	oA.target = '_blank';
	this.insertNode(oA);

        // submenu off
        this.submenuOff();

        // focus
        this.focus();
    }

**Comment by JiHong88** [comment]
Hi, @pazicb 
There are two ways to insert an image and text at the same time.

*1.*
Non-letter tags such as images and tables should be inserted using the "[insertComponent](http://suneditor.com/sample/html/out/document-editor.html#insertComponent)" method.
  Then move the "range" object to the newly added line and insert the link.
```
...
oImg.src = = "abc.jpg";
// this.insertNode(oImg);

const newFormat = this.insertComponent(oImg);
this.setRange(newFormat, 0, newFormat, 0);

const oA = this.util.createElement("A");
...
```

*2.*
The "[insertNode](http://suneditor.com/sample/html/out/document-editor.html#insertNode)" method deletes the selected area and inserts a tag at the current cursor position.
This removes the text added to the same line while checking the newly inserted image and changing its structure.
So after adding the image, and find the current line, and create a new line, and move the "range" object, and insert the link.
```
...
oImg.src = = "abc.jpg";
this.insertNode(oImg);

const format = this.util.getFormatElement(oImg);
const newFormat = this.appendFormatTag(format);
this.setRange(newFormat, 0, newFormat, 0);

const oA = this.util.createElement("A");
...
```

The methods used are described in [document](http://suneditor.com/sample/html/out/index.html).

**Comment by pazicb** [comment]
Thank you.
