### ISSUE TITLE
Hi. good bro   vite to build fail [commonjs--resolver] Expected ';', '}'

### ISSUE THREAD

**Issue by xiaomao996688** [JiHong88/suneditor#1367]
**i use vite to build the project**
but find 
`commonjs--resolver] Expected ';', '}' or <eof> in /Users/zhoulonglong/Desktop/workspace/Builder/node_modules/suneditor/src/lib/core.js
file: /Users/zhoulonglong/Desktop/workspace/Builder/node_modules/suneditor/src/lib/core.js:1165:82
1163:          */
1164:         getSelectionNode: function () {
1165:             if (!context.element.wysiwyg.contains(this._variable._selectionNode)) this._editorRange();
                                                                                        ^
1166:             if (!this._variable._selectionNode) {
1167:                 const selectionNode = util.getChildElement(context.element.wysiwyg.firstChild, function (`

**To Solution**
 if (!context.element.wysiwyg.contains(this._variable._selectionNode)) {this._editorRange();}
Hope it can be solved

**Comment by Anishadahal** [comment]
Could you please inform when this fix will be released?
