### ISSUE TITLE
uploading images from mobile

### ISSUE THREAD

**Issue by MuhammadHuss** [JiHong88/SunEditor#137]
when uploading image from mobile cut off image width

**Comment by JiHong88** [comment]
Hi, @MuhammadHuss 

How did you put the "imageWidth" property when creating the editor?
Try putting the "imageWidth" attribute value as "auto".
```
suneditor.create('id', {
    imageWidth: 'auto'
    // The default value of the "imageWidth" property is 'auto'.
})
```
