### ISSUE TITLE
Placeholder unhide if paste one line without EOL or BR

### ISSUE THREAD

**Issue by sudwebdesign** [JiHong88/SunEditor#138]
The new _placeholder work fine_, but if **paste one line**, sometime, placeholer stay here...
After add space, ENTER, (re)cut/(re)paste or other it's being hidden ;)

![placeholder_test](http://sudwebdesign.free.fr/data/medias/bugs/se/SE2.20.1.placeholder.gif)

With Firefox 68 (other?)

**Comment by JiHong88** [comment]
Hi, @sudwebdesign 

Thank you so much for reporting the bug.

The bug has been fixed and will be released in the next version.

Thank you :)

**Comment by JiHong88** [comment]
HI, @sudwebdesign 

Fixed in [v2.21.0](https://github.com/JiHong88/SunEditor/releases/tag/2.21.0)

Thank you.
