### ISSUE TITLE
lang attr stripped even when allowed with attributesWhitelist 

### ISSUE THREAD

**Issue by JanValkenburg** [JiHong88/suneditor#1380]
**Describe the bug**
I have whitelisted the 'lang' attribute using the attributesWhitelist, but the attribute is still being removed.

in:
< p lang="JA">x< /p>

out: 
< p>x< /p>

code:
attributesWhitelist: {
    'all': 'lang'
},

**Expected behavior**
Keep the lang attribute in the code

**Comment by JiHong88** [comment]
This issue is not reproduced.
Please try the latest version or provide a more detailed test environment.

**Comment by JanValkenburg** [comment]
It works at the moment, nothing changes. 
Was always using the latest version from the url below.
https://cdn.jsdelivr.net/npm/suneditor@latest/dist/suneditor.min.js
