### ISSUE TITLE
Bug using font-family with number

### ISSUE THREAD

**Issue by eliabecorrea** [JiHong88/suneditor#1382]
**Describe the bug**

I imported fonts from the Google Fonts API and some of them have numbers in their names, such as: Exo 2, Source Sans 3, Slabo 27px, etc. In this case, when selecting one of these fonts it is not applied.

**To Reproduce**
You can use the custom fonts option to add the above mentioned fonts
![image](https://github.com/JiHong88/suneditor/assets/53411970/e26c8f23-794f-43c1-bee4-a94bd3931214)

The fonts appears in the font menu, but when I click on one of them nothing happens.
![image](https://github.com/JiHong88/suneditor/assets/53411970/8cd1fbcb-2b38-4d5a-92ce-f5076560dccf)

![image](https://github.com/JiHong88/suneditor/assets/53411970/9b51ce70-977a-4720-8b96-2cb2fd9d7b9c)

![image](https://github.com/JiHong88/suneditor/assets/53411970/5aeacf29-8fa8-4bfd-b3b1-090dd1270b80)

But if I add a font without a number and click in it, it is applied normally
![image](https://github.com/JiHong88/suneditor/assets/53411970/378954a8-d1f3-47c2-b1b4-77178dd63296)

![image](https://github.com/JiHong88/suneditor/assets/53411970/4714ec7a-6a8e-480b-b0b3-73fc2dfc7bad)

**Comment by JiHong88** [comment]
Version [2.46.1](https://github.com/JiHong88/suneditor/releases/tag/2.46.1) has been deploied.
Thank you.

**Comment by eliabecorrea** [comment]
Wow, it was fast!
Thank you.
