### ISSUE TITLE
we need onPast event for  MathBox or Math Modal KaTeX or latex input

### ISSUE THREAD

**Issue by ashikjs** [JiHong88/suneditor#1396]
I need OnPast event here. So I can modified or check user past.

![image](https://github.com/JiHong88/suneditor/assets/13074235/68105bf2-43bb-4321-9052-e6a733abadad)

**Comment by JiHong88** [comment]
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you
