### ISSUE TITLE
After pressing the enter key, focus jumps to the top of the page.

### ISSUE THREAD

**Issue by malworthy** [JiHong88/suneditor#1407]
**Details**
After pressing the enter key, focus jumps to the top of the page. 

**To Reproduce**
Can be replicated in the options sample: http://suneditor.com/sample/html/options.html
Click into the editor. Press enter key.  Focus will go to the top of the screen.

Only happens in v2.46.3 of Suneditor,  Issue not present in v2.45.1

**Expected behaviour**
For focus to stay in the control after pressing the enter key

 - OS: Windows 10
 - Browser: Chrome
 - Version: 122.0.6261.129

**Comment by andylwelch** [comment]
I am also experiencing the issue with lost focus on enter key presses. It started occuring in `v2.46.0`. Looking through the change logs I suspect [this change set](https://github.com/JiHong88/suneditor/commit/e910c7af6337502ce16dca1c0ef4402001b7a2fc#diff-4756a56fc0765752d0f5af0f5228db0f4cb2609ab384f542ead6e9278ee5e93b)

Specifically `e.preventDefault()` is changed to call `event._enterPrevent(e)`

![image](https://github.com/JiHong88/suneditor/assets/7505965/ff5f18bf-bcfe-4cf3-9738-a6c24c81686c)

and there is an `_enterPrevent()` which triggers a focus event elsewhere: `this.__focusTemp.focus();`

![image](https://github.com/JiHong88/suneditor/assets/7505965/41d011e9-d582-406c-b4cf-3710bbdce3ce)

Thanks for your efforts!

**Comment by alexlaw-leo** [comment]
I think you're on to something there.

We've had a few people with laptops experience this, but most with laptops or desktops have no issue. Until I read this thread yesterday I couldn't reproduce it on my desktop.

This morning I learned how to set the user agent in Chrome, I chose iPad to make it appear mobile, and this trips the issue consistently.

![image](https://github.com/JiHong88/suneditor/assets/151845262/32c96ec5-e6c8-4968-88f9-6807b79b54ba)

**Comment by alexlaw-leo** [comment]
OK, I've messed about with this to trip or prevent the issue:

![image](https://github.com/JiHong88/suneditor/assets/151845262/f1358f7e-d697-43c0-b623-6132fe07fdc9)

I have no solution at this point other than locking the version of the library at 2.45.1.

**Comment by malworthy** [comment]
The laptop I'm experiencing this issue on has a touchscreen - so touch points theory hold up.

**Comment by BestLemoon** [comment]
same problem, but solved by locking to v2.45.1

**Comment by jreynolds12** [comment]
Is there any progress here? Unfortunately, we upgraded to > 2.46.0 to fix a different bug, so feels wrong to rollback to undo that.

**Comment by JiHong88** [comment]
This is code added due to a composition event issue with the IME input device on mobile. 
I will modify it so that scrolling does not occur.

**Comment by JiHong88** [comment]
@andylwelch @alexlaw-leo @malworthy @BestLemoon @jreynolds12
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you

**Comment by alexlaw-leo** [comment]
@JiHong88 Thank you!

**Comment by CorinnaZer** [comment]
I still have this issue even with 2.47.0 version, it seems to be related to touch devices. When I press enter focus still goes on the top of the page and I can't go on writing. Pressing enter should just add a line.

**Comment by johnnybaida** [comment]
Hi, I also have the same problem. 
I am using Firefox 130.0.1, in the desktop version.

I am attaching a video where I press ENTER and then see the focus disappear and via console, I see that the focus is on another element.

[screen-recorder-wed-oct-02-2024-15-09-12.webm](https://github.com/user-attachments/assets/06fcac81-6623-46b0-9f18-3fae0aed2e8d)
