### ISSUE TITLE
Appended videoTagAttrs are losing in editor

### ISSUE THREAD

**Issue by ChavitiSathish** [JiHong88/suneditor#1408]
Iam trying to add video with autoplay muted in editor, I configured the attributes as below 
**videoTagAttrs: {
    autoplay: true,
    muted: true,
 } .** 
 On adding the video url attributes are setting up but when switching to codeview and back to editor all the attributes are loosing only controls = true attribute is only remaining. 

**Expected behavior**
If video tagAttrs are configured the editorcontents should not loose attributes.

**Screenshots**
Attaching a video for Quick reference
In my Local : [screen-capture (63).webm](https://github.com/JiHong88/suneditor/assets/68001625/6aab9a29-fb2c-4bc9-a417-222f5bb24f52)
In Suneditor.com : [screen-capture (64).webm](https://github.com/JiHong88/suneditor/assets/68001625/583903be-2e5d-44a2-9524-7cbaeab65543)

**Comment by JiHong88** [comment]
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you
