### ISSUE TITLE
Style tag removed and can't apply css in codeview mode

### ISSUE THREAD

**Issue by mostafacs** [JiHong88/SunEditor#141]
Hi, 

Thanks for the beautiful editor. We currently using suneditor in production and we have users use codeview and copy/paste their html code including html style tag.
But i can see the editor is removing the style tag once switch to WYSIWYG.
I attached example of styles users copy paste. 

Thanks.
[html-with-css.txt](https://github.com/JiHong88/SunEditor/files/3805784/html-with-css.txt)

**Comment by JiHong88** [comment]
Hi @mostafacs 

Script tags are not allowed in all editors because of the risk of hacking.
Since the default mode is written inside the "div" tag, style tags cannot be inserted.

The "fullPage" option allows you to insert style tags in the header.
`SUNEDITOR.create('id', { fullPage: true })`
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/css/suneditor.min.css" rel="stylesheet">
    <!-- Style -->
    <style>
        ...
    </style>
</head>
<body class="sun-editor-editable" contenteditable="true">
    <!-- HTML code -->
    ...
</body>
</html>
```
If you need to include a script tag, delete the code that removes the script tag from the [toggleCodeView:L2059](https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L2059) method.

**Comment by mostafacs** [comment]
Hi @JiHong88 ,

Thanks for your reply. I'm using the editor with angular 8 application and it's downloaded via npm. so i think editing the code is not good from my side because i want to keep it managed via npm and upgrade also via npm. if i change the code and then rebuild project i will loss my changes.
Can y plz add options for disable script removing ? 
I will try also override codeview button click event from angular.

Thanks for your help.

**Comment by JiHong88** [comment]
Hi,
The disable script removal option is not very common, so it will be hard to add.
Instead, I'll update the editor this week so that I can override the "core" object method after creation.

Redefine it as follows:
```javascript
const editor = suneditor.create('id',{...});

editor.core._setCodeDataToEditor = function () {
    const code_html = this._getCodeView();

    if (this.context.option.fullPage) {
        const parseDocument = (new this._w.DOMParser()).parseFromString(code_html, 'text/html');

        this._wd.head.innerHTML = parseDocument.head.innerHTML;
        this._wd.body.innerHTML = this.util.convertContentsForEditor(parseDocument.body.innerHTML);

        const attrs = parseDocument.body.attributes;
        for (let i = 0, len = attrs.length; i < len; i++) {
            if (attrs[i].name === 'contenteditable') continue;
            this._wd.body.setAttribute(attrs[i].name, attrs[i].value);
        }
    } else {
        this.context.element.wysiwyg.innerHTML = code_html.length > 0 ? this.util.convertContentsForEditor(code_html) : '<p><br></p>';
    }
}
```
I will notify you after the update.
Thank you.

**Comment by mostafacs** [comment]
Thank

**Comment by mostafacs** [comment]
Thank you so much. waiting for your response

**Comment by JiHong88** [comment]
Hi, @mostafacs 

Updated in [v2.21.0](https://github.com/JiHong88/SunEditor/releases/tag/2.21.0)

Thank you.

**Comment by mostafacs** [comment]
Thanks, I will test and back to you.
