### ISSUE TITLE
Support VimeoQuery To achieve Autoplay for Attached Vimeo Videos

### ISSUE THREAD

**Issue by ChavitiSathish** [JiHong88/suneditor#1410]
To achieve autoplay for embedded youtube videos we shall use youtubeQuery: 'autoplay=1&mute=1&enablejsapi=1&controls=1&loop=1', whereas Embedded Vimeo Videos can't be autoplayed. Likely vimeo videos are also played in iFrame an option like youtubeQuery to overwrite vimeo query would be appreciated. 

1. Go to Editor and click on video and add vimeo video link.

**Expected behavior**
An option like youtubeQuery to overwrite the vimeo videos query would be appreciated.

**Comment by JiHong88** [comment]
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you
