### ISSUE TITLE
Indent button in toolbar activated when editor readonly

### ISSUE THREAD

**Issue by nonman1991** [JiHong88/suneditor#1418]
In the example (http://suneditor.com/sample/html/examples.html), when I set the editor to readonly, the indent button activated when I select some content. At the same time, other buttons are in a grayed-out state. 
Is this a bug?

1. Setting the Editor to Read-Only Mode
2. Selecting some content
3. Indent button lights up

**Comment by JiHong88** [comment]
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you
