### ISSUE TITLE
Uneditable templates

### ISSUE THREAD

**Issue by ilbrigz** [JiHong88/SunEditor#142]
Hi. Is there a way to make a template or parts of the template uneditable or unchangeable(to another element)? 

I have added this inline style 
`cursor: not-allowed;pointer-events: all !important;`.

**Comment by JiHong88** [comment]
Hi @ilbrigz 
Set the "contenteditable" attribute to false for areas you do not want to edit.
It's not perfect, but it seems to be the only one for now.
```html
<p contenteditable="false">TITLE</p>
<p>text</p>
```
