### ISSUE TITLE
Can we have free hand drawing feature in Version 3 (Draw and insert in editor). Lexical Editor by Facebook is having this feature.

### ISSUE THREAD

**Issue by roker16** [JiHong88/suneditor#1420]
Can we have free hand drawing feature in Version 3. Lexical Editor by Facebook is having this feature. Lexical is using Excalidraw for this feature. 
[Lexical ](https://playground.lexical.dev/)
[Excalidraw ](https://excalidraw.com/)

it would be even better if this feature could be done using only js/html only.

**Comment by JiHong88** [comment]
I postponed it to 3.1.0, but I will reschedule it to 3.0.0.
I think it can be added relatively easily with the current structure.

**Comment by roker16** [comment]
> I postponed it to 3.1.0, but I will reschedule it to 3.0.0. I think it can be added relatively easily with the current structure.

Any tentative date for 3.0.0 version
