### ISSUE TITLE
Enable (activate) a button / plugin by default?

### ISSUE THREAD

**Issue by kaju74** [JiHong88/suneditor#1425]
Hi,

is there a way to enable (activcate) a button by default? I want to "showBlocks" by default instead of clicking on the corresponding toolbar-button after the editor has been loaded.

Thank you for this great editor... ;-)

**Comment by JiHong88** [comment]
`editorInstance.core.commandHandler(editorInstance.core.allCommandButtons.showBlocks, 'showBlocks');`

```javascript
const editorInstance = suneditor.create(..)
editorInstance.onload = function (core, reload) {
  core.commandHandler(core.allCommandButtons.showBlocks, 'showBlocks');
}
```

**Comment by kaju74** [comment]
Ops - missed your reply ;-) Thank you very much....
