### ISSUE TITLE
What is Tentative date for version 3.0.0?

### ISSUE THREAD

**Issue by roker16** [JiHong88/suneditor#1426]
We are waiting for over a year now. Could u please tell us tentative date for the launch of version 3.

**Comment by JiHong88** [comment]
Alpha version is available. I will upload a simple method to set options etc. soon.

**Comment by gxara** [comment]
> Alpha version is available. I will upload a simple method to set options etc. soon.

Awesome!

I am eager to give it a try.

I am building https://nodeland.io with suneditor :)

**Comment by roker16** [comment]
> Alpha version is available. I will upload a simple method to set options etc. soon.

Kindly please consider react component for suneditor as an official part of your project...

**Comment by roker16** [comment]
> Alpha version is available.

Where is alpha version?

**Comment by melloware** [comment]
@roker16 i think its right here: https://github.com/JiHong88/suneditor/tree/version/3/dist

**Comment by roker16** [comment]
> @roker16 i think its right here: https://github.com/JiHong88/suneditor/tree/version/3/dist

How do i install this via npm

**Comment by JiHong88** [comment]
https://www.npmjs.com/package/suneditor?activeTab=versions

`npm i suneditor@3.0.0-alpha.14`

**Comment by JiHong88** [comment]
I haven't sorted out the options and types yet. 
There are still gallery, embed, icons, and typescript work left.
The structure may change due to the above work, so it is included in version 3.0.0.
I am thinking about how to create icons.
If you have any ideas, please let me know.

**Comment by melloware** [comment]
What do you mean by Create Icons?

**Comment by JiHong88** [comment]
@melloware I'm using icons in mdi, but there are some that are missing, so I'm looking for an AI that can generate them.

**Comment by JiHong88** [comment]
https://github.com/JiHong88/suneditor/blob/master/README_V3_TEMP.md

**Comment by robinbakshi007** [comment]
> [JiHong88](/JiHong88)

I have tested your Alpha version and is quite promising. However, it's still missing key pieces of solving the puzzle. To add motivation for you, I will pay you $250 to fix the below components.

Please see the below:

1.  When adding the Table, we are now able to move and resize Table. However, formating is the big issue with it. Please see the attached image for your kind reference. ![image](https://github.com/user-attachments/assets/4a40ebb7-f9bf-4059-8939-fd3d7572a3ad)
2. Below components are missing while using the keyboard shortcut

- Horizontal Line – - - - 
- - Numbered List – New line starting with “1.”
- - Bulleted List – 
- - New line starting with “*” + (Space bar)
- - With a bulleted list, hit “Tab” on a line to increase the indent (you can increase the indentation by one more indent than the previous line).
- - Quote – New line starting with “>” + (Space bar)
- - Header Level 1 – Ctrl+Shift+1 
- - Header Level 2 – Ctrl+Shift+2 
- - Header Level 3 – Ctrl+Shift+3

3. AI Integration is the small piece of puzzle which can be solved by integrating the API.

**Comment by JiHong88** [comment]
@robinbakshi007 I'll try.
 It's strange that the cell properties don't work. 
 Please try using the new version of css again.
 https://github.com/JiHong88/suneditor/blob/master/README_V3_TEMP.md#create

**Comment by robinbakshi007** [comment]
We are using the same version  of css.
https://github.com/JiHong88/suneditor/blob/master/README_V3_TEMP.md#create

**Comment by robinbakshi007** [comment]
@JiHong88 
Also, we have tried to work on the below and got some success. However, it's not functioning properly. Please see the below video:

https://github.com/user-attachments/assets/c6549d71-5e15-42e9-802a-be59ceebcb72

Below components are missing while using the keyboard shortcut
Horizontal Line – - - -
Numbered List – New line starting with “1.”
Bulleted List –
New line starting with “*” + (Space bar)
With a bulleted list, hit “Tab” on a line to increase the indent (you can increase the indentation by one more indent than the previous line).
Quote – New line starting with “>” + (Space bar)
Header Level 1 – Ctrl+Shift+1
Header Level 2 – Ctrl+Shift+2
Header Level 3 – Ctrl+Shift+3

**Comment by robinbakshi007** [comment]
Any Update?

**Comment by JiHong88** [comment]
@robinbakshi007 
`npm i suneditor@3.0.0-alpha.17`
The shortcut function has been updated.
This shortcut has been included in the basic functionality.
The shortcut setting method has been changed.
Search for "shortcuts" in the "[ReadMe](https://github.com/JiHong88/suneditor/blob/version/3/README_V3_TEMP.md)" file.

**Comment by rodrigosoareschaves** [comment]
Hi @JiHong88 
How can I add a HR using "hr: ['!+---+=+~shortcut', ''],"?
I tried adding "____" or "----" but nothing happened

**Comment by JiHong88** [comment]
@rodrigosoareschaves "hr: ['! + ---- + = + ~shortcut', '']"

**Comment by roker15** [comment]
> @rodrigosoareschaves "hr: ['! + ---- + = + ~shortcut', '']"

Can't see any example /Demo page of this version yet.... I mean i don't know how to start

**Comment by rodrigosoareschaves** [comment]
What this means?
How to make a line "----" transform in an HR tag?

For me, all shortcuts seems working, except:
hr: ['!+---+=+~shortcut', ''],
list_numbered: ['!+1.+_+~shortcut', ''],
list_bulleted: ['!+*.+_+~shortcut', ''],


@roker15 I used directly this file https://github.com/JiHong88/suneditor/blob/version/3/dist/suneditor.min.js then, tried the shortcuts listed on the Read Me file. I.e.: Ctrl+[ = indent, or Ctrl+Shift+1 turns the text into H1

**Comment by JiHong88** [comment]
@roker15 @rodrigosoareschaves 
After adding gallery and embed related features and defining types, we plan to create a demo page and release it as a full version.

https://github.com/JiHong88/suneditor/blob/version/3/README_V3_TEMP.md
import:
` npm i suneditor@3.0.0-alpha.17`



	Input a command in the first value.
	Input the character to be displayed in the tooltip in the second value. (ctrl, shift, etc. are automatically entered.)
	How to enter a command
	The key value of the object is the basic command or plugin name.
	The "+" delimiter is required.
	Starts with "c" or "!".
	
	- Command shortcut
	c = ctrl | command
	s = shift
	number = key code

	 - text shortcut
	"!" = Valid when starting from the first of a paragraph.
	The character following "!" is the key text value.
	"=" The shortcut key is executed when the key value character is completed without any other input.
	It is executed when the space key is entered after the "_" character.
	It is executed when the enter key is entered after the "/" character.

	---
	-- Plugin method 
	"~methodName" The method name of the plugin to be executed.

	-- Custom shortcut keys must start with "_".
	"p~pluginName.pluginMethod" It is valid when the key value is not a plugin or a basic command. The plugin name and the method name of the plugin.

	-- Registering a function directly
	"$" If you put "$" as the last value, the function in the third value of the array will be executed.
	- function arg ({ range, line, info, event, keyCode, editor: this.editor })
