### ISSUE TITLE
처음부터 준비된  tex언어를  에디터 로딩과 동시에 변환된채로 출력하고싶습니다.

### ISSUE THREAD

**Issue by woejr2988** [JiHong88/suneditor#1427]
To make it easier for us to help you, please include as much useful information as possible.

## Version
Write the version of the Editor you are currently using.
2.46.3

## Additional context
<textarea id="editor_classic">\int_{4}^{y} \underset{x \rightarrow 7}{lim} \sum_{k = 1}^{x} \frac{t}{x^{2}} d x </textarea>

위와같이 DB에 수식이 저장되어있고,

  const editorInstance = SUNEDITOR.create('editor_classic' .... )

에디터를 로딩시켰을때,   katex submit 한것처럼  바로 수식형태로 나오도록   할수있을까요?

suneditor.js  에서  
managedTags
_renderer
_renderMathExp
_submit   
위 코드를 조합해서 시도해보았으나 계속 실패하고있어서,

미리 준비된 수식을  자동렌더링 하는 방법이 있을까요?

**Comment by JiHong88** [comment]
```
<textarea><span class="katex" data-exp="\int_{4}^{y} \underset{x \rightarrow 7}{lim} \sum_{k = 1}^{x} \frac{t}{x^{2}} d x" data-font-size="1.5em" style="font-size: 24px" contenteditable="false"></span></textarea>
```

이렇게 span태그에 data-exp 속성으로 넣으면 됩니다.

**Comment by woejr2988** [comment]
빠른 답변에 감사드립니다.  

오늘도 좋은하루되세요
