### ISSUE TITLE
Copy paste from the same editor break the content

### ISSUE THREAD

**Issue by maximehuran** [JiHong88/suneditor#1428]
**Describe the bug**
When I copy paste the text from the editor, the first paste break the content, but not the second and the other times

**To Reproduce**

Source string
```
<p>Ôtez la <span style="color: rgb(235, 141, 117)">complexité</span>,<br>
M.Biz vous apporte des solutions utiles<br>
</p>
```

**Expected behavior**
The content is paste correctly on the first copy paste.

**Screenshots**

https://github.com/user-attachments/assets/712cd136-617c-4a01-b0f4-76d7d885939f

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser Firefox
 - Version 128

**Comment by JiHong88** [comment]
Version [2.47.0](https://github.com/JiHong88/suneditor/releases/tag/2.47.0) has been updated.
thank you
