### ISSUE TITLE
Resizing shape & contoller are above of the toolbar

### ISSUE THREAD

**Issue by sudwebdesign** [JiHong88/SunEditor#149]
I have solved in my [plugin](http://sudwebdesign.free.fr/depot.php#SunEditor) 
with _z-index setted to 1_ 
for this classes : 
_.sun-editor .se-resizing-container_ 
 _.sun-editor .se-controller_

in suneditor.min.css originaly is : z-index: 6

Proof in image (v2.21.2)
![shape](http://sudwebdesign.free.fr/data/medias/bugs/se/2.21.2_z-index6.se-resizing-container.png)
![control](http://sudwebdesign.free.fr/data/medias/bugs/se/2.21.2_z-index6.se-controller.png)
Best regards

**Comment by DrStrix** [comment]
@sudwebdesign almost
![Снимок экрана 2019-11-14 в 9 33 31](https://user-images.githubusercontent.com/17456749/68851200-83b2cf80-06e6-11ea-8a53-6c6ff66efced.png)

**Comment by JiHong88** [comment]
Hi,
Fixed in [v2.22.0](https://github.com/JiHong88/SunEditor/releases/tag/2.22.0).
Thank you.
