### ISSUE TITLE
sections that need plugin

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#150]
HI there, Please can you specify the sections that need plugins to be imported. For example the image buttonList needs the image plugin and so on.
I will need this to make dynamic imports for suneditor-react.
It will really help if you specify it at the documentation.

**Comment by JiHong88** [comment]
Hi @mkhstar 

Thanks for your work.
This week, I'll update the next version after adding the plugins and fixing bugs.
At this point, I'll also update the document and let you know.

Thank you :)

**Comment by mkhstar** [comment]
Alright. Can't wait. Thank you too :)

**Comment by JiHong88** [comment]
Hi,
[v2.22.0](https://github.com/JiHong88/SunEditor/releases/tag/2.22.0) has been updated.
Thank you.

**Comment by mkhstar** [comment]
Thanks, 
Firstly I have seen you listed the plugins at the bottom of your documentation page. You stated that the plugin and the buttons has got the same name but I couldn't find the button such as paragraphStyle or testStyle.
Can you please state their dependencies

**Comment by mkhstar** [comment]
No please this is different I want to know what buttons paragraphStyle and testStyle depend on

**Comment by JiHong88** [comment]
testStyle -> **textStyle**

Both "paragraphStyle" and "textStyle" use the same plug-in button with the same name.
[constructor.js#L439](https://github.com/JiHong88/SunEditor/blob/master/src/lib/constructor.js#L439)

**Comment by mkhstar** [comment]
Alright

**Comment by mkhstar** [comment]
Alright
