### ISSUE TITLE
getselectionnode problem

### ISSUE THREAD

**Issue by mcuneyda** [JiHong88/SunEditor#151]
Hello, i want use getSelectionNode() but i have error.

Code: 

```
setInterval(function(){
console.log("start" );
console.log(suneditor.getSelectionNode());
console.log("stop" );
}, 4000);
```

Error; suneditor.getSelectionNode is not a function

Can you help me?

**Comment by JiHong88** [comment]
Hi, @mcuneyda 

The getSelectionNode method belongs to the [core](http://suneditor.com/sample/html/out/document-editor.html#getSelectionNode) object.

```javascript
suneditor.core.getSelectionNode()
```

Thank you.

**Comment by mcuneyda** [comment]
thank you so much :)
