### ISSUE TITLE
HTML in figcaptions?

### ISSUE THREAD

**Issue by davidkonrad** [JiHong88/SunEditor#152]
Hey again.  Your work is priceless.  I was wondering if you could consider HTML to be rendered in figcaptions? To me figcaption content seem to be rendered as text, for example a link is rendered as <a href=" ... Have tried to figure out how to solve it in core.js, but honestly I do not dare to alter the code :) It is not a major problem at all, I just rerender the content in a timeout, but perhaps you have simply not thought about rendering HTML in figcaptions?

**Comment by JiHong88** [comment]
Hi, @davidkonrad 

Are you saying that the HTML inside the "figcaption" tag doesn't render?
Sorry, can you show me an example of what's going on?

**Comment by davidkonrad** [comment]
Thank you for the reply. Sorry, dont have an online example.  It seems to me that the figcaption content is rendered inside a div (why?), and that content is sanitized, e.g `<` is rendered as `&lt;` and so on. I solve it by using a stupid hack like this:

```
setTimeout(function() {
  $('figcaption').each(function(i,f) {
    let html = $(f, 'div').text()
    $(f).html(html)
  })
},10)
```
Sry for the jQuery :)

**Comment by JiHong88** [comment]
Hi,
[v2.22.0](https://github.com/JiHong88/SunEditor/releases/tag/2.22.0) has been updated.
Test please if the problem is resolved.
Thank you.

**Comment by davidkonrad** [comment]
Sorry for the long delay. Using your recent version and it is still the same. Everything you can call HTML is cleaned in view-mode. That is links, strong, italic and so on.  It is saved and still present in editor-mode, but when you view the article it is rendered as without HTML. Regards 💓

**Comment by JiHong88** [comment]
Sorry for the long delay.
I don't understand. 😢
Can you show me some images or something?

**Comment by davidkonrad** [comment]
Forget it. I am so sorry for the confusion :(  It was me who had the weird assumption, that HTML in the figcaption should be treated as HTML.  It is correctly treated as text; if you use the "SunEditor-way" of creating links, bold text etc, then it works.
