### ISSUE TITLE
Code view in 'Inline' mode hides toolbar

### ISSUE THREAD

**Issue by LexaGal** [JiHong88/SunEditor#154]
Hi! Issue: no toolbar in CodeView (**Inline mode**)
See,

![Screenshot_rte1](https://user-images.githubusercontent.com/9394689/69608411-6eb83380-1038-11ea-8734-db1173e67efc.png)

![Screenshot_rte2](https://user-images.githubusercontent.com/9394689/69608409-6eb83380-1038-11ea-9fc0-ebb3825974aa.png)

**Comment by LexaGal** [comment]
@JiHong88 I've found the fix:
![ScreenshFix](https://user-images.githubusercontent.com/9394689/69728782-2a12c200-1136-11ea-858a-cd4d929ca04d.png)

**Comment by LexaGal** [comment]
Added PR for this #156

**Comment by JiHong88** [comment]
Thank you @LexaGal 

I'll let you know after the version update : )

**Comment by JiHong88** [comment]
Hi,
[v2.22.0](https://github.com/JiHong88/SunEditor/releases/tag/2.22.0) has been updated.
Thank you.
