### ISSUE TITLE
Feature request: insert and scale image/figure using % of edit container

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#158]
I scale the editor area using @media depending on device width. I want images to keep size relative to editor area size independent of device. This works fine if I, after adding an image, resize it using the image modal (e.g. 75%, 50% etc.). 
It would be nice if image/figure width/height always can be set to % instead of px - perhaps controlled by an option?

**Comment by JiHong88** [comment]
Hi, @MRB60 

I'll add an option to always set it to "%".
Before that, you can use the following method:
```javascript
suneditor.create('id', {
    imageWidth: 'auto',
    imageResizing: false,
    ...
});
```

Thank you.

**Comment by MRB60** [comment]
Great.
Be aware, for me, it scales propely when the <div> element with the class se-component se-image-container is scaled (width as %), so not sure which element (this <div>, <figure> or <img>) actually should be the target here.

**Comment by JiHong88** [comment]
Hi @MRB60 
Updated in [v2.22.0](https://github.com/JiHong88/SunEditor/releases/tag/2.22.0).
Thank you.

**Comment by MRB60** [comment]
Did a quick test. I can set new % size in modal and it seem to do the job.
However, I cannot resize it with the mouse anymore, only through settings modal. I have configured as follows: 		
`imageSizeUnit:` "%",
imageResizing: true,`
Initial load of image (upload to server variant) still does not scale %-wise with edit area. I still need to resize it (or set % in modal) once to get image scaled properly.

**Comment by JiHong88** [comment]
Hi,
"%" size is can not be resized with the mouse.
Um.. Currently there are many restrictions on entering image size.
It may be better to enter a unit such as "px" or "%" directly like Tiny editor.

**Comment by MRB60** [comment]
I am not too familiar with TinyMCE since I decided not to use it - but perhaps better.
Using % in width (height) style for the html (div) element having the se-image-container class seem to do it for me - thus using % (of parent, which is editor area) as style in the html contents itself. See my earlier comment.

**Comment by JiHong88** [comment]
If it is still a percentage size, the se-image-container contains the style.
I'll modify the size input method so that you can enter up to the size unit.

**Comment by JiHong88** [comment]
Hi,
Updated in [v2.23.0](https://github.com/JiHong88/SunEditor/releases/tag/2.23.0)
Thank you.

**Comment by MRB60** [comment]
Thanks for your effort - did a quick try and it works fine for me.
Initial loading image of seem to ignore left/right selection but will not create an issue for that.
