### ISSUE TITLE
Feature request: make it possible to clear changed status after SetContents

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#161]
Again, thanks for making Suneditor!
It seems as if setContents() causes editor to assume a change to contents has been made (and save button is enabled). 
It would be nice to be able to clear this changed status (and disable save button) so that contents look unedited until user edit contents (or contents is appended/changed otherwise). I would suggest a function call which can clear the changed status (not sure about history though).
Any workaround would also work out for me!

**Comment by JiHong88** [comment]
Hi,
That's good idea.
I'll add an argument that does not update the history stack.
Thank you.

**Comment by JiHong88** [comment]
Hi,
Updated in [v2.23.0](https://github.com/JiHong88/SunEditor/releases/tag/2.23.0)
```javascript
const editor = suneditor.create(..);
editor.setContents('html');
editor.core.history.reset(); // history stack reset
```
Thank you.

**Comment by MRB60** [comment]
History clear works fine but setContents seem still to trigger an onChange event and the save button is still enabled (as if there is something unsaved). Anyway to avoid this? The event I can work around but would be nice if the save button could be disabled somehow.

**Comment by JiHong88** [comment]
Hi,
I fixed the issue.
Applies to the next version.
Before that, you can following method:
```js
const editor = suneditor.create(..);
editor.setContents('html');
editor.core.history.reset(); // history stack reset
// ** disalbed save button **
editor.core.context.tool.save.disabled = true;
```
[core.context](http://suneditor.com/sample/html/out/document-editor.html#context)

Thank you.

**Comment by MRB60** [comment]
Great - got it working with your workaround and by ignoring first onChange event.
Thank you.

**Comment by JiHong88** [comment]
You can declare the onChange event after setContents.
```js
const editor = suneditor.create(..);
editor.setContents('html');
editor.core.history.reset(); // history stack reset
// ** disalbed save button **
editor.core.context.tool.save.disabled = true;
// onChange
editor.onChange = function...
```

**Comment by MRB60** [comment]
Yes - works great.
You have shown how I can use setContents() and still handle content as unchanged - as requested in this feature request. I close the it now.
Thank You.

**Comment by JiHong88** [comment]
Hi, again

The [v2.23.1](https://github.com/JiHong88/SunEditor/releases/tag/2.23.1) version has been updated.

You can use it like this:
```javascript
const editor = suneditor.create(..);
editor.setContents('html');
editor.core.history.reset(true);
```
Thank you.
