### ISSUE TITLE
Outdent button is disabled

### ISSUE THREAD

**Issue by PyrozhenkoSerhii** [JiHong88/SunEditor#170]
Hi, for some reason outdent button is disabled. I still can use Shift+Tab and Ctrl + [ hotkeys to use outdent though. The problem seems to be present in examples as well.
![outdent](https://user-images.githubusercontent.com/34453331/71162813-8d36d680-2254-11ea-9fb1-8e14d0f7b124.png)

**Comment by JiHong88** [comment]
Hi, @PyrozhenkoSerhii 

Fixed in [v2.23.2](https://github.com/JiHong88/SunEditor/releases/tag/2.23.2)

Thank you : )
