### ISSUE TITLE
Image Positioning Improvement

### ISSUE THREAD

**Issue by ilbrigz** [JiHong88/SunEditor#175]
Hi! Is there a way to make inline images inlined perfectly? 

![image](https://user-images.githubusercontent.com/32309779/71315044-e1c59600-248e-11ea-92d2-65fef5cf50ef.png)

Also, I hope we can add text on the left side of a left aligned image as shown bellow.

![Capture](https://user-images.githubusercontent.com/32309779/71315063-7fb96080-248f-11ea-89dc-8eee1c737699.PNG)

**Comment by JiHong88** [comment]
Hi, @ilbrigz 

Delete the lines above the image using the delete key.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13191953/71321220-d22f6700-24f9-11ea-9579-dffc741bb61f.gif)

And.. adding text on the left side of the left aligned image is currently not possible. 😢
I'll think about how can implement it.

Thank you.
