### ISSUE TITLE
Uncaught DOMException:  Failed to execute 'setStart' 

### ISSUE THREAD

**Issue by olegbruev** [JiHong88/SunEditor#176]
Hi, 
If the cursor is in the starting position and the Bold(Ctrl+B) button is pressed and then the Backspace button on click, an error occurs:  Uncaught DOMException: Failed to execute 'setStart' for 'Range' ...

Maybe in core.setRange to do something like this:
`408 if (! StartCon ||! EndCon || startCon.length === 0) return;`

**Comment by JiHong88** [comment]
Hi, @olegbruev 

Will be fixed and reflected in the next version.

Thank you!!

**Comment by JiHong88** [comment]
Hi, @olegbruev

Fixed in [v2.24.0](https://github.com/JiHong88/SunEditor/releases/tag/2.24.0)

Thank you.
