### ISSUE TITLE
doesnt work in production build

### ISSUE THREAD

**Issue by duncanokeyo** [JiHong88/SunEditor#177]
when i run npm run development, i can see the editor and all the controls, but when i run npm run production the editor controls are listed and there is no editor
![Screenshot from 2019-12-30 16-44-35](https://user-images.githubusercontent.com/6240014/71584506-e2f86200-2b23-11ea-91f7-b1c4f58efbeb.png)

**Comment by JiHong88** [comment]
Hi, @duncanokeyo 

It looks like the css file is not loaded.

Um.. Is the css file also imported?

**Comment by setesolutions** [comment]
Hey man, nice work!!

I have a problem when I'm trying to use the pt_br (brazilian portuguese) language, in suneditor-react/misc/getLanguage.js was missing the case option.

`case 'pt_br':
          return require('suneditor/src/lang/pt_br');`

But it still doesn't work, do you have some idea?

And investigating other files, I saw that in suneditor-react/dist/main.js there's not indicating to pt_br language.



Thanks, you're helping me a lot.
