### ISSUE TITLE
개발모드에서 트랜스파일링을 거치지 않은 소스코드 바라보는 이슈

### ISSUE THREAD

**Issue by wacilpong** [JiHong88/SunEditor#178]
안녕하세요, 해당 에디터 라이브러리를 이용해 별 문제없이 잘 적용했는데요.

다름이 아니고 jest 테스트에서 아래와 같은 에러가 나더라구요.

```s
SyntaxError: Cannot use import statement outside a module
```

<br />

아마 suneditor를 임포트할 때 바벨 등으로 transpile되지 않은 소스코드를 참조해서 나는 에러인 것 같습니다. 
```javascript
import core from './lib/core';
^^^^^^
import _Constructor from './lib/constructor';
import _Context from './lib/context';

...
```

사실 이 이슈는 jest에서 해당 라이브러리만 babel로 변환 후 테스트하라고 옵션을 지정해주면 되고, 물론 프로덕션에서는 아무 문제 없는데요. 혹시 라이브러리 자체가 트랜스파일링된 소스코드를 참조하도록 할 수 없을까요?

그리고 아래는 제가 import하여 쓰고 있는 부분입니다. typescript를 사용중이어서 우선 급한대로 자체 definition을 만들어 사용 중입니다. 혹시 제가 놓친 부분이 있는 지도 모르겠어서 함께 첨부합니다!

<br />

```typescript
// editor
import suneditor, { IEditorConfig } from "suneditor";
import plugins from "suneditor/src/plugins";
import { ko } from "suneditor/src/lang";

...
```

```typescript
// .d.ts
declare module "suneditor" {
  export interface IEditorConfig {
    plugins?: IEditorPlugins;
    lang?: "ko" | "de" | "en";
    width?: number | string;
    height?: number | string;
    charCounter?: boolean;
    placeholder?: string;
  }

  export function init(config?: IEditorConfig);
}

declare module "suneditor/src/plugins" {
  export interface IEditorPlugins {}
}

declare module "suneditor/src/lang";
```

**Comment by JiHong88** [comment]
안녕하세요.
제가 보기엔 필요한 부분 다 import 되어있고 문제 없어 보입니다.
제대로 동작한다면 모두 제대로 작업하신거니 걱정 하지 않아도 될것 같습니다!
그리고..  jest 테스트 관련한 부분은.. 지금은 저도 잘 모르겠습니다. 죄송합니다. ㅜㅜ

**Comment by wacilpong** [comment]
앗 아닙니다. 좋은 오픈소스 감사합니다!! 그럼 우선은 이 이슈는 닫겠습니다. 추후 저도 해당 라이브러리에 기여해보도록 노력하겠습니다 👍
