### ISSUE TITLE
pt_br language is missing

### ISSUE THREAD

**Issue by setesolutions** [JiHong88/SunEditor#179]
Hey man, nice work!!

I have a problem when I'm trying to use the pt_br (brazilian portuguese) language, in suneditor-react/misc/getLanguage.js was missing the case option.

case 'pt_br': return require('suneditor/src/lang/pt_br');

But it still doesn't work, do you have some idea?

And investigating other files, I saw that in suneditor-react/dist/main.js there's not indicating to pt_br language.

Thanks, you're helping me a lot.

**Comment by JiHong88** [comment]
Hi, @setesolutions 

Thank you : )

It seems that the "suneditor-react" package is not yet updated to the new version.

I'll update and send pull request.

**Comment by setesolutions** [comment]
Thank you my good friend!

**Comment by setesolutions** [comment]
Hello my friend, any new about this subject? 
I would love to implement, your component is perfect
Hug!

**Comment by JiHong88** [comment]
Hi friend!
Thank you so much!
The update is almost over.
I'll let you know right away.

**Comment by JiHong88** [comment]
Hi,
I have requested PR to @mkhstar [suneditor-react](https://github.com/mkhstar/suneditor-react)
It will be updated soon.

**Comment by JiHong88** [comment]
[suneditor-react](https://github.com/mkhstar/suneditor-react) have been updated.

**Comment by setesolutions** [comment]
> [suneditor-react](https://github.com/mkhstar/suneditor-react) have been updated.

Thanks a lot my good friend, let me know if you need some contributions. Hug!
