### ISSUE TITLE
Deplay in onChange event

### ISSUE THREAD

**Issue by quanle1994** [JiHong88/SunEditor#180]
Hello

Thank you for this great component. I have just a small request on the delay time of the onChange callback.

Could you provide an option to get the onChange contents immediately after typing? I am doing empty message validation so getting this value without delay will make the error display promptly.

Regards

**Comment by JiHong88** [comment]
Hi, @quanle1994 

Yes, I can add options for delay time.
But, the change event will not call while the key is held down.
Is it enough to adjust the delay only?

Regards

**Comment by quanle1994** [comment]
Hi @JiHong88 

My ultimate goal is to capture all the changes immediately when the text value is changed so it's best if the callback is called on every character change even when a key is held down. For now, I just need to validate for empty messages so maybe just a callback when the text is empty will do. However, this is too specific to my use case so it may not benefit others.

Regarding the pressing and holding of a key, I think the onChange will not be called after the key is up in Chrome and Firefox. I have commented in https://github.com/JiHong88/SunEditor/issues/173 too. This seems to be a more critical request so if you could help me fix it, I can use it to validate the empty messages and hence I wouldn't need the reduction in onChange delay as much then.

**Comment by JiHong88** [comment]
OK, I see.
That issue has been fixed.
I'll let you know after the version update soon.
Thank you.

**Comment by JiHong88** [comment]
Hi, @quanle1994

Fixed in [v2.24.0](https://github.com/JiHong88/SunEditor/releases/tag/2.24.0)

Thank you.
