### ISSUE TITLE
paste from word

### ISSUE THREAD

**Issue by rbartholomay** [JiHong88/SunEditor#181]
Hi there,

currently i play with the nice Editor :-)   In my case i need a good paste from word and try the sample document from ckeditor:

[https://ckeditor.com/docs/ckeditor4/latest/examples/assets/pfw/CKEditor4.PFW.Sample.Recognition_of_Achievement.docx](https://ckeditor.com/docs/ckeditor4/latest/examples/assets/pfw/CKEditor4.PFW.Sample.Recognition_of_Achievement.docx)

But only the title will be paste... Any idea why?

Bye, René

**Comment by JiHong88** [comment]
Hi, @rbartholomay 

Fixed the code for processing data of the clipboard.
The next version will be updated soon.
Thank you.

**Comment by rbartholomay** [comment]
wow, fast answer. Nice!

**Comment by JiHong88** [comment]
Hi, @rbartholomay 

fixed in [v2.24.0](https://github.com/JiHong88/SunEditor/releases/tag/2.24.0)
Thank you.
