### ISSUE TITLE
language config bug?

### ISSUE THREAD

**Issue by rbartholomay** [JiHong88/SunEditor#183]
when set a language on this site:

[http://suneditor.com/sample/html/options.html](http://suneditor.com/sample/html/options.html)

the config will be created like this:

```
[...]
	"lang": "de"
}
```

But in this case i got an error in my application like "Uncaught TypeError: Cannot read property 'bold' of undefined".

When i change the config to:

```
[...]
	"lang": SUNEDITOR_LANG["de"]
}
```
all runs fine.  Bug,  Documentation Bug?

**Comment by JiHong88** [comment]
Hi, @rbartholomay 

That is a documentation bug.
This is the difference between using nodejs or cdn.
It has been fixed.
Thank you!
