### ISSUE TITLE
can i have an event instanceReady?

### ISSUE THREAD

**Issue by rbartholomay** [JiHong88/SunEditor#186]
Hi!

i try to use this editor inside ExtJS. It will be nice when SunEditor publish an event when all (instance, layout etc.) is ready.

Is this possible?

Kind regards, 
   René

**Comment by JiHong88** [comment]
Hi

Yes, It's possible.
I'll add an onload function.
Thank you.

**Comment by JiHong88** [comment]
Hi, @rbartholomay 

Updated in [v2.25.0](https://github.com/JiHong88/SunEditor/releases/tag/2.25.0)

Thank you.

**Comment by rbartholomay** [comment]
Thank you so much!
