### ISSUE TITLE
Unable to remove format of a paragraph

### ISSUE THREAD

**Issue by rsvitak** [JiHong88/SunEditor#188]
Selecting a block of code (paragraph) and changing the format works well. But removing the format (using the **removeFormat** button) back is not possible **later on**, e.g. when I leave the paragraph and return to it later. I am actually not able to replace the format in any other way then.

The "Undo" button is not option as it has to be possible to change the paragraph format after saving and reopening the document...
Also asking my users to do it through editing the HTML code is not acceptable, as they are not so exprienced with HTML to be able to do it.

Thank you for your help.

**Comment by JiHong88** [comment]
Hi, @rsvitak 

Can't use the "paragraphStyle" button?

You can delete the active style by clicking it again.

**Comment by rsvitak** [comment]
Hi @JiHong88,
thank you for your quick answer. The "paragraphStyle" works well and it looks like it covers all my needs. But I still think the current functionality of the "formats" is weird. I think the user should be able to change the format. 

Once more what I mean to avoid any misunderstandings (in the default configuration of suneditor):  Let's say user types "Hello World" to an empty editor. The <p>Hello World<p> element is created at the background. Then he selects the text, clicks Formats->Code in menu. SunEditor adds the wrapping "<pre>" element, so "<pre><p>Hello World</p></pre>" is the result. So far so good.

But later on, let's assume the user decides to change to format to heading. Again he selects the "Hello World" text, clicks Formats->Header1 and he gets "<pre><h1>Hello World</h1></pre>". As the result.

I understand that the "Formats" function works with the "most inner" element, but it should be possible to work with the root elements too. 

Btw, (maybe I should rather create another ticket) is it possible to configure the editor to avoid creating the default "<p>" element? 

Thank you for your time.

**Comment by rsvitak** [comment]
New observation: changing the format betwen some elements works as expected. For example user can switch the headings format from h1 to h2 and vice versa. That's fine. 

So maybe it would be good if the default "\<p\>" element is changed to just "\<pre\>" and not "\<pre\>\<p\>". Maybe there is a way through the custom formats?

Please help.

**Comment by JiHong88** [comment]
"PRE" and "BLOCKQUOTE" can be deleted as follows.
![deleteRangeFormat](https://user-images.githubusercontent.com/13191953/72680671-f33aa600-3aff-11ea-91ab-08b8e3d945ab.gif)

Yes, the current "PRE" tag is a mistake.😓
The "PRE" tag is being modified so that line breaks are "BR" tags. [feature/pre](https://github.com/JiHong88/SunEditor/tree/feature/pre)
And I'm thinking about splitting "BLOCKQUOTE" into another button.

**Comment by rsvitak** [comment]
Deleting was working fine, but I needed to changing the format. I cannot ask users to delete their work to change formatting.

I tried the "pre" branch you mentioned, but it works the same: \<pre\>\<p\>\</p\>\<p\>\</p\>...\<p\>\</p\>\</pre\>. No way to change the block "PRE" text to normal P paragraph later on...

I think that maybe your ideas about the PRE tag is different than mine, I understand that. Now I am trying to achieve what I need via the custom formatting (DIVs). I am getting some JS errors, I will create a separate issue, I hope you don't mind.

**Comment by JiHong88** [comment]
Since this is the same issue as the #190  issue, I close this issue.

**Comment by JiHong88** [comment]
This issue is treated together in issue #190
