### ISSUE TITLE
Incorrect space display when using formatting on text

### ISSUE THREAD

**Issue by stefanocorsi** [JiHong88/SunEditor#189]
I have the following text in the database, and I want to load in a suneditor field:

`<p>one <strong>two</strong> three four<br></p>`

I expect it to  be displayed like this:

one **two** three four

However, when I load it in an hidden field and display it with suneditor using the following code:

```
<input id="location_fiscal_header" name="location[fiscal_header]" type="hidden" value="<p>one <strong>two</strong> three four<br></p>" />
<script>
	const suneditor = SUNEDITOR.create((document.getElementById('location_fiscal_header')),{
		// All of the plugins are loaded in the "window.SUNEDITOR" object in dist/suneditor.min.js file
		// Insert options
		// Language global object (default: en)
		lang: SUNEDITOR_LANG['it']
	});
</script>
```
I get instead this:

one**two** three four

![image](https://user-images.githubusercontent.com/6546984/72704920-4b05fb00-3b5a-11ea-95bc-ec92d5c9cdfa.png)
So the space between "one" and "two" is removed.

If I inspect the suneditor snippet using the firebug I see this:

![image](https://user-images.githubusercontent.com/6546984/72704886-36c1fe00-3b5a-11ea-97b9-236c4919f89e.png)

It seems to me like if certain spaces (for example before formatting tags) are rendered with \n new lines.

**Comment by stefanocorsi** [comment]
The problem seems to be related to pure spaces. If I change them into &nbsp; they are displayed fine: 

`&lt;p&gt;one&nbsp;&lt;strong&gt;two&nbsp;&lt;/strong&gt;three&nbsp;four&lt;br&gt;&lt;/p&gt;`

![image](https://user-images.githubusercontent.com/6546984/72706065-60c8ef80-3b5d-11ea-8c7f-22c80bed253c.png)

The resulting html though is not pleasant to read and it's not easily maintainable.

**Comment by JiHong88** [comment]
Hi, @stefanocorsi 

Did you test with the latest version?

**Comment by stefanocorsi** [comment]
Sorry... I was sure to have downloaded last "master"... I was wrong. Having done it now it works correctly. Very sorry.
