### ISSUE TITLE
Problems with custom formats

### ISSUE THREAD

**Issue by rsvitak** [JiHong88/SunEditor#190]
I am using this custom configuration of formats: 
`formats: [
                  { 
                    tag: 'p', // Tag name
                    name: 'NORMAL', // default: tag name
                    command: 'replace', // default: "replace"
                    'class': '__se__format__NORMAL', // Class names must always begin with "__se__format__"
                  },
                  { 
                    tag: 'div', // Tag name
                    name: 'CODE', // default: tag name
                    command: 'replace', // default: "replace"
                    'class': '__se__format__CODE', // Class names must always begin with "__se__format__"
                  }
              ],`

When run suneditor with this configuration I have 2 issues (maybe rather requirements?): 
1. in main menu (balloon style) the name of the current format is not NORMAL or CODE, but just P or DIV. The NORMAL and CODE is only displayed in the submenu. This is quite confusing, can it be configured somehow?

2. Switching between formats works well, P element is switched to DIV and viceversa. But the value of class attribute is rather strange: First adjusting to CODE is ok. But after changing the format from CODE to NORMAL it becomes: "__se__format__NORMAL __se__format__CODE", after changing back to NORMAL it becomes: "__se__format__CODE __se__format__NORMAL".

But generally it works well. I wish the default P and PRE formats could work the same in SunEditor. The only reason is that I would like to have as simple HTML documents as possible consisting of just simple P, PRE, BR (etc.) elements if possible. The additional HTML attributes are not needed.

**Comment by JiHong88** [comment]
Hi, @rsvitak 

1. It will be modified to behave like the "CODE" format of the [froala editor](https://www.froala.com/wysiwyg-editor).
2. It will fix the bug where the "\_\_se__format__" class name remains.
3. It will modify it so that the set name is displayed.

I'll notify you when the edit is complete and the version is updated.
Thank you.

**Comment by rsvitak** [comment]
Thank you very much sir!

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
