### ISSUE TITLE
Focus on writing area

### ISSUE THREAD

**Issue by juan-pinzon** [JiHong88/SunEditor#191]
Hi, thanks for your project, I am currently using it. Only there is a small flaw that I may not know how to use or may not be available, it is about placing the focus of the pointer in the writing area when I create the editor  `suneditor.create ('content', this.initSuneditor ())`

I tried using this.suneditor.core.focus () as it says in [Document#Focus](http://suneditor.com/sample/html/out/document-editor.html#focus) and it didn't work, I also did it with `this.suneditor.getContext ( ) .element.wysiwyg.focus ()`

The process I follow is that when I click on a button I create a suneditor with its settings, so the idea is that when it is created it will focus there, but this does not happen

**Comment by JiHong88** [comment]
Hi, @juan-pinzon 

Try using the [onload event](http://suneditor.com/sample/html/out/document-user.html#onload).
```javascript
const editor suneditor.create(...)
editor.onload = function (core, reload) {
    core.focus();
}
```
Thank you.

**Comment by juan-pinzon** [comment]
unfortunately it does not work. I am using I use it in AngularJs 1.7. The editor is created within a .then () when a promise is fulfilled.

**Comment by JiHong88** [comment]
It is case sensitive.
Is it right that you defined it as "onload"?

**Comment by juan-pinzon** [comment]
Sure, I write "onload"

**Comment by JiHong88** [comment]
The issue is not reproduced.
Can you upload the code?
