### ISSUE TITLE
Drag and Drop Event

### ISSUE THREAD

**Issue by setesolutions** [JiHong88/SunEditor#192]
Hey man, what's up?

I've a doubt, I need to drag a card of a list and drop the content (text) inside editor, it's possible? Do you have some example for it?
Thanks a lot!

**Comment by JiHong88** [comment]
Hi, @setesolutions 

Text drag drops do not work in the editor.
Let's review that feature again.
Thank you :)

**Comment by kimhyeongyu** [comment]
안녕하세요.

저도 비슷한 문제가 발생해서 글을 남깁니다.

텍스트 작성하고 마우스 드래그로 지정한 후에 폰트 색상을 변경시키려는데,

드래그한 영역이 자꾸 풀리는 현상이 발생합니다.

혹시 이같은 현상에 대한 대안이 있을까요??

**Comment by JiHong88** [comment]
@kimhyeongyu 
다른 문제일것 같은데요..
드래그에 관련된 이벤트는 따로 정의 되어있지 않습니다.
데모사이트에서도 같은 문제가 발생하나요?

**Comment by kimhyeongyu** [comment]
네 그렇습니다.
동영상으로 캡쳐했는데, 동영상 업로드가 안되네요.

혹시 이메일로 보내드려도되나요??

**Comment by JiHong88** [comment]
넵 보내주세요

**Comment by kimhyeongyu** [comment]
넵 0125ses@hanmail.net 로 보내드렸어요

**Comment by JiHong88** [comment]
안녕하세요~
현재 selection 객체를 설정하는 함수가 onClick 이벤트때만 호출하도록 되어있습니다.
범위선택 하면서 마우스가 에디터 밖으로 나간상태로 클릭이 완료되면 에디터 에서 onClick 이벤트가 발생하지 않아 범위지정 한 정보가 저장되지 않는 문제가 있네요.
수정 하였으니 다음 버전부터 적용 됩니다.
감사합니다.

**Comment by kimhyeongyu** [comment]
네 늦은시간에 이렇게 답변해주셔서 감사드립니다.

**Comment by kimhyeongyu** [comment]
안녕하세요~ 
Suneditor를 사용하는 프로젝트를 진행중인데,
혹시 다음버전은 언제쯤 적용되는지 알 수 있을까요??

**Comment by JiHong88** [comment]
@kimhyeongyu 
업데이트는 모두 완료 했습니다.
테스트가 잘 끝나면, 내일 다음 버전 배포 됩니다.

**Comment by JiHong88** [comment]
@kimhyeongyu 
[2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) 버전이 업데이트 되었습니다.
관련된 이슈가 있다면 새로운 이슈를 등록해주세요.
감사합니다.

**Comment by JiHong88** [comment]
@setesolutions 
It seems like it will take some time to implement a drag drop within the editor.
I'll close this issue.
