### ISSUE TITLE
Toolbar with text options doesn't hide

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#194]
Hello,

once again I want to say thank you for this package. I noticed one thing which is a bug for me. When I have some text in table cell and I mark it, then appears the toolbar with text formatting options. But when I click somewhere else but still in table range, this toolbar doesn't hide. It hides only when I type in another cell more than one sign. The following gif is showing this behaviour.

[https://i.imgur.com/WsOccvG.gifv](https://i.imgur.com/WsOccvG.gifv)

Kind regards,
Adrian

**Comment by JiHong88** [comment]
Hi, @kranczeer 

Thank you for reporting a bug.
I'll notify you after the version update.
Thank you : )
