### ISSUE TITLE
Editor state doesn't change on text align change

### ISSUE THREAD

**Issue by witflash** [JiHong88/SunEditor#195]
Hello!
On text align change Editor state doesn't change. Only if I do some DOM changes.

**Comment by subrahmanyaadiga** [comment]
Yes, same problem. I have raised the same issue a week before. But issue is deleted i guess.

**Comment by JiHong88** [comment]
Hi, @witflash @subrahmanyaadiga 

Thank you for reporting a bug.
I'll notify you after the version update.
Thank you : )

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
