### ISSUE TITLE
Need to add Google font Roboto in the font list

### ISSUE THREAD

**Issue by subrahmanyaadiga** [JiHong88/SunEditor#196]
Hello,

I want to add google font roboto in the font list. How can i add? I have added the 'robot' in the font array. But font is not loading. For that i have to include the style sheet link. 

`<link href=https://fonts.googleapis.com/css?family=Roboto rel=stylesheet>`

Where i can add this? Is this possible? Please help me

**Comment by MRB60** [comment]
In the configuration:
E.g.
`font: ['Arial', 'tahoma', 'Courier New,Courier', 'Roboto','PlayfairDisplay','Dancing Script','Great Vibes'],
`

**Comment by JiHong88** [comment]
Hi, @subrahmanyaadiga 

Just include the style in the same HTML as the editor.

**Comment by subrahmanyaadiga** [comment]
Thanks @JiHong88 @MRB60
