### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#197]
Hi,
Thanks for the library, it's a good piece of work.
Do you have plans for providing TypeScript support for the library (at least typings)? I'm using the library in a TypeScript project and when of course it's not a problem to use plain JS libs, it would make many things easier.

Cheers!

**Comment by Datyriam** [comment]
This is still incomplete (only has the main suneditor module and the plugins modules defined) but should help you on your way:
https://hastebin.com/odafulemet.cs

**Comment by tswistak** [comment]
Thanks! However, I prefer to wait for types to be on a package manager to not worry about updating them manually (it can be easily forgotten to download new or to change to NPM ones when they are ready).

**Comment by JiHong88** [comment]
Thank you @tswistak 
I'll notify you know when version is update.
And there is a question.
[index.d.ts#L76](https://github.com/JiHong88/SunEditor/blob/89207f883b798d28963021a6765c227f7c9ace19/index.d.ts#L76)
`codeMirrorEditor` is the object returned after executing [options.codeMirror.src.fromTextArea()](https://github.com/JiHong88/SunEditor/blob/89207f883b798d28963021a6765c227f7c9ace19/src/lib/constructor.js#L135).
Is this code needed?

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
