### ISSUE TITLE
onBlur event

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#198]
Hi! 
Thanks again for great library. Would you consider adding "onBlur" event or is there any possibility to use it somehow in current version?

Cheers!

**Comment by JiHong88** [comment]
Hi!

I'll add an "onblur" event to next version.
It's a easy task : )

Thank you.

**Comment by tswistak** [comment]
Great news! It will really help for my use case :) . When are you planning to release new version to npm?

**Comment by JiHong88** [comment]
Maybe.. It will be released this month.

**Comment by tswistak** [comment]
Hi! Sorry for interrupting, but is a release still possible in this month?

**Comment by JiHong88** [comment]
Hi~
Maybe it will.
Now only issues #208, #218, and #215 remain.
All of these issues can be addressed right away, but replacing web font data with "inline svg" seems a bit tricky. (#215 )

**Comment by tswistak** [comment]
Hi,
I've checked your develop branch and tested onBlur functionality. I've found a bug, that when you are using color picker and changing color, it invokes onBlur before performing a change. I find it a problem in my case, because I want to use "onBlur" event to close an editor and it closes editor without saving all the changes. Please check codesandbox for sample: https://codesandbox.io/s/suneditor-onblur-p3ugq (I've built it based on the f7b0bc2263c65257dd07c18d4c1138b0e350d27b commit).
In my opinion, the best would be to not invoke onBlur when using toolbar or at least first invoke onChange, then onBlur.

Cheers!
