### ISSUE TITLE
How about port SunEditor to Vue.js?

### ISSUE THREAD

**Issue by ruslankonev** [JiHong88/SunEditor#2]
Hi, you write a nice editor, but how about to portable your code to Vue.js?

**Comment by JiHong88** [comment]
Hi, Sorry to check in late
I do not know Vue.js so I'll check it again :(

**Comment by JiHong88** [comment]
I checked.
I do not have a sense of how to port it.
Are you talking about rendering with vue.js?

**Comment by ruslankonev** [comment]
Yeah, and events binding.. ok, anyway thanks, maybe I will have enough time to port it/
