### ISSUE TITLE
"Code View" mode rejects the "canvas" tag

### ISSUE THREAD

**Issue by steve-langley** [JiHong88/SunEditor#200]
Thanks for your excellent work - very nice package!

I found that if I switched to "code view" mode I could enter a "canvas" tag but it got removed when switching back to WYSIWYG mode. I was able to patch around this by adding "canvas" to the _deleteExclusionTags and convertHTMLForCodeView methods but it would be nice if the "canvas" tag was accepted by default. (I don't need a fancy plugin to create one in WYSIWYG mode, just a way to add tags that SunEditor doesn't directly support.

Another solution would be to add a new option which told SunEditor to simply **tolerate** any tags it did not recognize (where "tolerate" means "don't remove them"!)

**Comment by JiHong88** [comment]
Hi, @steve-langley 

I'll add the "canvas" and another tags in the next version.
And I think about "Another solution" along with other methods.
Thank you for the idea.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
