### ISSUE TITLE
Question: how to support custom element?

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#201]
For example, we want to create a custom inline tag or label, which is a indeed a span with any other styles, but it can only be updated as a whole, meaning it's content text is not editable.

Is there a proper way to implement this? thanks.

**Comment by JiHong88** [comment]
Hi, @zhaoyao91 

Can you explain in more detail?

**Comment by zhaoyao91** [comment]
Like the patterns of @mention or #hashtag, we want to insert some predefined labels by click some toolbar buttons.

The label should have some background color, the content text of the label cannot be edit, but you can apply styles (bold, underline...) to the whole label, or just delete the whole label.

In rendering, the label is just a span with background style.

**Comment by zhaoyao91** [comment]
I've seen the template plugin may help insert certern predefined dom, but how to keep it atomic is a problem.

**Comment by zhaoyao91** [comment]
I found a workaround: insert a span with contenteditable set to false.
