### ISSUE TITLE
Adding custom plugin to config renders all other plugins implicitly included as not found 

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#202]
Thanks for your efforts on this!
Note: I think this is not a bug but since I am not using js modules (no import/export) and accessing suneditor via 
`"https://cdn.jsdelivr.net/npm/suneditor@2.25.0/dist/suneditor.min.js"`, I am simply not sure what the best way is to solve my issue.
When adding a new custom plugin:
`			plugins: [custom_plugin_submenu],
`
all other plugins included with "buttonList" shown an error: not found (although buttons are there). 
Is there instead a possibility to add a custom plugin to the list of already defined ones (defined via buttonList)?

And perhaps a documentation issue on submenu plugin example: one need to add class="se-submenu" to the submenu html code. The Eventlistener does not trigger otherwise.

**Comment by JiHong88** [comment]
Hi @MRB60 

Thank you.
I'll modify the example :)

Is it correct to code like the [example](https://github.com/JiHong88/SunEditor/blob/master/sample/html/customPlugins.html#L180)?
Can you show me your code?

**Comment by MRB60** [comment]
It is a very simple custom submenu where one can paste in an <iframe> map from Google maps or OSM (with some regex checks).
This part now works fine for me;
`    setSubmenu: function () {
        const listDiv = this.util.createElement('DIV');

        listDiv.className = 'se-submenu se-list-layer';
        /* se-submenu must be included otherwise onClick does not work */
        listDiv.innerHTML = '' +
                    '<div class="se-list-inner se-list-align">&nbsp;Karten<br>&nbsp;HTML einfügen:' +
                    '   <ul class="se-list-basic">' +
                    '       <li><input class="se-input-form" type="text" style="width: 100%; border: 1px solid #CCC;" /></li>' +
                    '       <li><button id="se-maps-button" type="button" class="se-btn se-tooltip">' +
                    '           <span>OK</span>' +
                    '           <span class="se-tooltip-inner">' +
                    '               <span class="se-tooltip-text">Einfügen</span>' +
                    '           </span>' +
                    '       </button></li>' +
                    '   </ul>' +
                    '</div>';
        return listDiv;
    },
`

**Comment by JiHong88** [comment]
Yup, "se-submenu" is a required class name.
Then does it work well now?

**Comment by MRB60** [comment]
Yes the submenu works fine.
Please also reflect on my first issue; adding my custom plugin makes all other plugins unavailable (defined in buttonList). So this does not work (from the example):
`plugins: [pluginObject],
     buttonList: [
         ['undo', 'redo', 'image'],
...
`   
The pluginObject is callable but the ones in buttonList no more.
Note that I do not use a js module so not import/export directly possible.

**Comment by JiHong88** [comment]
How exactly did you put the button list?
Did you put it in this format?
The error is not reproduced :(
```javascript
buttonList: [
    ['undo', 'redo', 'image'],
    [
        {
            name: 'custom_plugin_submenu', 
            dataCommand: 'custom_plugin_submenu',
            buttonClass:'', 
            title:'Custom plugin of the submenu', 
            dataDisplay:'submenu',
            innerHTML:'<i class="se-icon-add"></i>'
        }
    ]
]
```

**Comment by MRB60** [comment]
OK.
maps is the name of the plugin, plugin defined as const maps = { ...
Thus no import in this case.

Config looks as follows:
>
			lang: SUNEDITOR_LANG['de'],
			plugins: [maps], // makes all other plugins to fail - q in github
			buttonList: [
			    ['undo', 'redo', 'image'],
			    [
			        {
			            name: 'maps', 
			            dataCommand: 'maps',
			            buttonClass:'', 
			            title:'Custom plugin of the submenu', 
			            dataDisplay:'submenu',
			            innerHTML:'<i class="se-icon-add"></i>'
			        }
			    ]
			],
			showPathLabel : false,
			charCounter : true,
:
etc.
Error when clicking on image button:

> suneditor.min.js:1 jsdelivr.comUncaught Error: [SUNEDITOR.core.callPlugin.fail] The called plugin does not exist or is in an invalid format. (pluginName:"image")
    at Object.callPlugin (suneditor.min.js:1)
    at HTMLDivElement.onClick_toolbar (suneditor.min.js:1)
callPlugin @ suneditor.min.js:1
onClick_toolbar @ suneditor.min.js:1:

**Comment by MRB60** [comment]
I found the problem.
I am setting config after create:
    let suneditor = SUNEDITOR.create(...
    suneditor.setOptions(editorconfig);

This does not work with custom plugins. 
Works:
let suneditor = SUNEDITOR.create((document.getElementById('suneditor') || 'suneditor'), editorconfig);

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
