### ISSUE TITLE
Customizing allowed tags in cleanHTML

### ISSUE THREAD

**Issue by Mistralys** [JiHong88/SunEditor#203]
Hello,

I am trying to filter pasted text to keep only a specific set of tags, and to offer the option to paste as plain text.

I saw that there is a whitelist of tags here, which is used when cleaning the pastedHTML:

https://github.com/JiHong88/SunEditor/blob/master/src/lib/util.js#L1080

It would be great if it was possible to influence this list somehow.

Alternatively, it would be great if we could modify the cleaned HTML before it is pasted. The onPaste event only allows cancelling the event, not modifying the HTML.

What do you think, would something like that be possible, or is there an existing way that I overlooked?

**Comment by JiHong88** [comment]
Hi @Mistralys 

The whitelist is a list of tags that the editor allows.
Do you need the ability to keep certain tags only when pasting?

This means that the tags allowed by the editor and the tags allowed when pasting are different.

**Comment by Mistralys** [comment]
Hi @JiHong88,

yes, I want to keep only specific tags when pasting. You are right, that's different from the tags the editor allows, which do not necessarily have to be the same set of tags.

What I am trying to do with a whitelist when pasting is this:

- Keep only specific tags when pasting (for example only <p> tags)
- Be able to paste as plain text (possibly with an empty whitelist)

Ideally, it should be possible to change the whitelist on the fly, which I could easily implement if the onPaste event allowed modifying the HTML.

What do you think?

And thanks for the reply :)

**Comment by JiHong88** [comment]
Yes I can make related options.
Does making an immediate change mean making end user to change?

**Comment by Mistralys** [comment]
Hi JiHong88,

thanks, that would be great!

What do you mean with the immediate change for end users?

**Comment by JiHong88** [comment]
No sorry, forget it.
I don't have enough English.
I'll update it by adding related options.

**Comment by Mistralys** [comment]
Awesome, thanks a lot! Looks good :)

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
