### ISSUE TITLE
Feature: support handle image uploading manually

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#205]
Currently we can only specify an uploading url, but in many situations the uploading processes are quite different from there to there.
It would be great if we can specify an custom function to fully handle the image uploading.

**Comment by JiHong88** [comment]
Hi @zhaoyao91 
Can you give me an example of how it should be?
I don't know much about it :(

**Comment by zhaoyao91** [comment]
for example, there may be another image option `imageUploadHandler`, which is an async function like  `async (imageFile) => imageUrl`

**Comment by MRB60** [comment]
I agree that a function call wound be nice. I use FetchAPI style myself. 
I also miss that I cannot add additional info (like user reference) prior to upload and in the reply callback. At the moment I misuse filename for that.

**Comment by JiHong88** [comment]
Um.. Do you need a function that will be called just before an image create to modify the information in the image?

**Comment by MRB60** [comment]
I need the be able to add custom parameters to the POST request - and receive custom parameters in reply. @zhaoyao91 might need to do more of course.

**Comment by JiHong88** [comment]
Okay.
First, I'll add a custom parameter.

**Comment by zhaoyao91** [comment]
The current uploadUrl way may be convenient for some cases, but it is not flexible and extensible.

By supporting the uploadFunc, which is lower level in abstraction, you can span more situations without any effort.

The two ways are not conflicting. But I think capability if prior to the ease-of-use.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
