### ISSUE TITLE
Suggestion: inline assets as js

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#206]
SunEditor has no external dependencies, which is good for easy importing.

But it requires assets such as css and fonts, which indeed requires the dependant app to support importing such files, what's more, it make it more difficult to create lib based on it.

Nowadays css-in-js is hot, libraries such as [emotion](https://emotion.sh) make it pretty easy. So, just an thought, SunEditor may be refactored as a pure js library.

**Comment by zhaoyao91** [comment]
BTW, I think the svg file is useless and it's of too big size to be linlined. Could it be removed?

**Comment by JiHong88** [comment]
Isn't it necessary in web font?
I will compress it with svgz extension.
Then the size is reduced to 1KB.

**Comment by zhaoyao91** [comment]
@JiHong88 I don't known much about web fonts, but by previewing it, I see it is just an empty image. Is it just generated by some tools?

**Comment by JiHong88** [comment]
The file created by the [site](https://glyphter.com/) that merges SVG.
Show the editor's icon.

**Comment by zhaoyao91** [comment]
ok, let's come back. the issue is, is it possible to inline all assets without making the user having to import non-js files?

**Comment by JiHong88** [comment]
Currently I can't represent the icon with the JS file alone.

**Comment by zhaoyao91** [comment]
some ideas:

- use webpack file loader
- use any css-in-js tech, but convert the asset into base64 manually and insert them in the js file

**Comment by JiHong88** [comment]
Yup, I'll try it

**Comment by zhaoyao91** [comment]
[bundled-suneditor.zip](https://github.com/JiHong88/SunEditor/files/4180472/bundled-suneditor.zip)
I have made a project to use webpack to bundle this library. the final size of the ouput file is 300k, but the svg file takes a significant part. of about 100k.

**Comment by JiHong88** [comment]
This issue is handled together in the #215 issue.
