### ISSUE TITLE
About Custom buttons

### ISSUE THREAD

**Issue by shaan1974** [JiHong88/SunEditor#207]
Hello,
in the documentation we have :

// 'submenu' or 'dialog' or '' (command button)
dataDisplay:'submenu'

But in the examples we have only "submenu" and "dialog", is it possible to create just a button that execute a custom command like a clear content ?

By the way great job.
Best regards
Shaan

**Comment by JiHong88** [comment]
Hi @shaan1974 

I am developing a command plugin.
It will be added in the next version, and I'll notify you after the update.
Thank you.

Best regards
JiHong

**Comment by shaan1974** [comment]
Hello, I succeed to do it but it's a little tricky. I explain.

A- I create a custom plugin with "type" - "Submenu". 

B - Inside the "Add" i put the code to clear the content of the editor. For the first time when action click is done on the button.

C - Inside the "setSubmenu" i add an event listener "click" on the button to run a dedicate script ( in my case to clear content ) related to "onClick" of plugin.

D - inside the "onClick" i put the code to clear the content of the editor.

So in this way it's working :) I admit it's a little bit tricky :)

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
[How to create custom plugin](http://suneditor.com/sample/html/customPlugins.html)
If there is an issue, please register as a new issue.
Thank you.
