### ISSUE TITLE
Opening balloon just by clicking in editor

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#208]
Hi!
Is there a possibility to trigger the opening toolbar in balloon mode just by clicking on the editor? Some kind of fusion between balloon and inline mode. My use case is that I want to give a possibility for a user to insert a table without the need to write anything, but still keeping the balloon mode (toolbar near the caret).

Cheers!

**Comment by JiHong88** [comment]
Hi
It does mean that the toolbar can be opened by just clicking on the text in "balloon" mode?

**Comment by tswistak** [comment]
Hi,
Yes, something like that. So, exactly the same behavior as in inline mode, but positioning of toolbar like it is in balloon mode.

**Comment by natanielcz** [comment]
Maybe it could show up after clicking the right mouse button?

**Comment by JiHong88** [comment]
@natanielcz It's possible but it doesn't seem intuitive.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
