### ISSUE TITLE
No ability to format text in multiple cells in a table

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#209]
After selecting multiple cells there is a possibility to adjust a table but text formatting toolbar is not showing.

![ErHmO7c84r](https://user-images.githubusercontent.com/1231703/74314187-4efdf500-4d75-11ea-948d-eb6c61333659.gif)

**Comment by JiHong88** [comment]
If you select multiple cells, the text in the cells is not selected.
And if select the text in the cell, I'll modify it to only display the text formatting toolbar.
