### ISSUE TITLE
Table can be edited when editor is disabled

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#210]
Hi!

I've found out an issue with disabled mode. When there's usual text it can be edited when editor is disabled, which is good. However, when there is a table, I'm able to edit a table and it's content despite that editor is disabled. Take a look into the sample here: https://codesandbox.io/s/suneditor-disabled-not-work-m40dd . Am I doing something wrong or is it a bug in library?

Cheers!

**Comment by JiHong88** [comment]
Thank you :)
I'll fix the bug and apply it to the next version.
