### ISSUE TITLE
Toolbar is not disappearing after exiting selection

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#212]
![pf2HdTcJbc](https://user-images.githubusercontent.com/1231703/74317667-1ca3c600-4d7c-11ea-8ac0-2be7b4480c2c.gif)

Browser:
works in Firefox and Edge
doesn't work in Chrome (tested on version 80.0.3987.100 (Official Build) (64-bit))

Issue: toolbar is not disappearing 

Expected behavior: toolbar disappears

Steps to reproduce: 
1. Type a single line of text
2. Select a word with double click
3. Click somewhere inside RTE

**Comment by JiHong88** [comment]
Thank you so much.
I'll fix the bug and apply it to the next version.
