### ISSUE TITLE
Toolbar item is disabled but cursor is displayed as a pointer

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#213]
The item on the screenshot below is disabled but cursor is still displayed as a pointer when we hover on the edge of the item.

![image](https://user-images.githubusercontent.com/1231703/74319186-cedc8d00-4d7e-11ea-909a-14da2c728893.png)

**Comment by JiHong88** [comment]
Thank you :)
I'll fix the bug and apply it to the next version.

**Comment by natanielcz** [comment]
Hi, 

You did a great job fixing many of the reported issues recently :) This one is still present (commit `546c3992f4c3c56164e3868740f6301b8978d275`). The pointer is displayed for the element `button._se_table_split_button.se-tooltip`

![yip8bdLqW0](https://user-images.githubusercontent.com/1231703/75651934-1b1e3d00-5c5a-11ea-9c1c-68db9e195131.gif)

We're looking forward to the next version of the SunEditor 😃  When do You plan to publish the next official version? Maybe You could publish a new version with already fixed bugs and later release smaller versions more often?

Best wishes 😄

**Comment by JiHong88** [comment]
Hi, @natanielcz 
Other code has encountered problems while implementing nested lists and is currently working on it.😥
I'm sorry I can't distribute it right away.
We'll fix and deploy in a few days.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
