### ISSUE TITLE
Balloon toolbar is overlapping table toolbar

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#214]
Hi!

In balloon mode sometimes it happens that toolbar overlaps table-toolbar. See attached screenshot:
![obraz](https://user-images.githubusercontent.com/9076255/74319460-49a5a800-4d7f-11ea-899b-5694788dd4d9.png)
Do you have any idea how to prevent it?

Cheers!

**Comment by JiHong88** [comment]
I'll modify it to only display the text formatting toolbar when select the text in the cell. #209

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
