### ISSUE TITLE
Balloon toolbar appears in a wrong place when editor is inside div with overflow:auto

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#216]
Hi!

Sorry for raising so many issues, but I'm currently implementing the editor in the app and finding out many new things. I've found out, that when I use editor inside a div that has scrollbars (constant height with set overflow to auto), position of toolbar is calculated wrong and appears way too high. I've created a reproduction environment on codesandbox: https://codesandbox.io/s/suneditor-scrolled-down-toolbar-yumjh
Also, screeenshot:
![obraz](https://user-images.githubusercontent.com/9076255/74321591-d140e600-4d82-11ea-97ac-df5b7113fbb7.png)

Cheers!

**Comment by JiHong88** [comment]
Hi, @tswistak 
Thank you so much.
I'll fix the bug and apply it to the next version.
