### ISSUE TITLE
Feature request: Nested lists

### ISSUE THREAD

**Issue by kristofferlund** [JiHong88/SunEditor#217]
I have been looking at several rich text editors for the past days, and I wanted to submit a feature request that I thought could be of use for your component; nested lists.

How to use:
When editing inside a list, press tab to add a list within the list. The list button in the toolbar will now change this child list, not the parent. If you're using an ordered list (1, 2, 3), the child list elements should by default be ordered (a, b, c). If you're using an unordered lists, the child elements should by default be unordered.

The html could look something like this:
```
<ul>
  <li>First regular li</li>
  <li>Second regular li</li>
  <ul>
    <li>First child li</li>
  </ul>
</ul>
```
And should render like this:

<ul>
  <li>First regular li</li>
  <li>Second regular li</li>
  <ul>
    <li>First child li</li>
  </ul>
</ul>

Let me know what you think!

**Comment by JiHong88** [comment]
Hi @kristofferlund 
It's good idea.
It seems to be not hard to implement.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.

**Comment by johnnybaida** [comment]
@JiHong88 Would it be possible to parameterize this functionality?
Thank you.
