### ISSUE TITLE
Turn off focus on setContents

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#218]
Hi!

Is there a way to not focus richtext editor while performing setContents? I'd like to change textarea contents but don't want to change focused input to textarea. Take a look into sample code on codesandbox: https://codesandbox.io/s/suneditor-autofocus-75pui , and maybe it will better look on a full environment: https://75pui.csb.app/ .

Cheers!

**Comment by JiHong88** [comment]
Hi

I am sorry for late to answer it.
This is unexpected behavior :(
I'll notify you know after fixed.

Thank you!
