### ISSUE TITLE
이미지 업로드 시 beforeUpload

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#220]
안녕하세요~ 너무 잘 사용하고 있습니다!
혹시 이미지 업로드 요청 시작전에 사용할 이벤트가 있을까요?
BeforeSend에서 검증할게 있어서요. 
가능한 방법이 있을까요?

**Comment by JiHong88** [comment]
안녕하세요~
현재 버전에서는 코드를 직접 바꾸는것 말고는 불가능 합니다ㅠ
현재 개발중인 버전에 추가해서 업데이트때 알려드리겠습니다.

**Comment by kimhyeongyu** [comment]
감사합니다^^
