### ISSUE TITLE
First Text Block is removed all content when using only one backspace

### ISSUE THREAD

**Issue by vuvansang07** [JiHong88/SunEditor#221]
- Bug: First Text Block [P] is removed when using Shift + Enter, then use only one time Backspace.
- Please only remove text block when text content is empty
![suneditor](https://user-images.githubusercontent.com/49393076/74907414-ea324280-53e5-11ea-9323-2e2022a1afcd.png)

**Comment by vuvansang07** [comment]
please fix this bug, this problem make me annoy when using SunEditor

**Comment by JiHong88** [comment]
Hi, @vuvansang07 
This issue has been fixed at develop version.
I'll notify you after the version update.

**Comment by vuvansang07** [comment]
good job ^^

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
