### ISSUE TITLE
에디터 null 체크

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#222]
안녕하세요. 에디터 널체크 할때

placeholder : true 

if(editor.core._placeholder.style.display != 'none'){

}
이렇게 하면 editor.core._placeholder 가 null로 되서 style.display를 못찾습니다.

저만의 해결책으로 

placeholder : ' '
으로 하면 editor.core._placeholder.style.display가 block으로 설정되어서 이상없이 됩니다.

혹시 저만 placeholder : true 했을때 editor.core._placeholder.style.display가 셋팅이 안되는건가요??

**Comment by JiHong88** [comment]
안녕하세요.

placeholder 옵션은 문자열만 유효합니다.
옵션값이 문자열로 왔을때에만 core._placehoder 노드가 생성됩니다.
[#199-comment](https://github.com/JiHong88/SunEditor/issues/199#issuecomment-582274494) 를 참고하시면 될것 같습니다.

그리고, 다음 버전에 빈값 체크 함수를 추가하겠습니다.

**Comment by kimhyeongyu** [comment]
네 감사합니다.
