### ISSUE TITLE
Base64 이미지 업로드

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#223]
안녕하세요. 

너무 자주 문의드려 죄송합니다. 개발시작한지 얼마되지.않아서 자꾸 여쭤보게 되네요... 이해부탁드립니다!

글과 이미지 첨부해서 등록할때, 
$.Ajax({
 Url : url,
 data : { contents : editor.getContents() }
DataType : "json", success : function(data){}
})

대략 이런식으로 해서 base64방식으로 DB에 contents값을 넣으려고 합니다.

하지만 Controller에서 넘어온 값을 vo.getContents() 찍어보면 <img alt = ""> 으로 이미지 경로가 null로 받습니다.

Jsp파일에선 alert(editor.getContents()) 으로 보면 base64방식으로 잘 보입니다.

Controller로 넘어갈때 변환되는거같은데, 혹시 이런 현상에 대해 아시는거 있나요??

**Comment by JiHong88** [comment]
안녕하세요~

vo.getContents() 값이 null 이란 얘기인가요?

**Comment by kimhyeongyu** [comment]
널값은아닙니다.
이미지만 첨부해서 controller에서 vo.getContents() 값이

<p><br></p><div class = "se-compornent se-image-container _se_float_-none"><fugure stlye="margin : 0px;"><img alt="" stlye=""></figure></div><p><br></p>

이렇게찍힙니다.

**Comment by kimhyeongyu** [comment]
![Screenshot_20200221-165523_Chrome](https://user-images.githubusercontent.com/39076893/75015035-022fc200-54cb-11ea-9a3b-8469b422120b.jpg)

**Comment by JiHong88** [comment]
src="data:image/...." 부분이 다 없어지네요..
혹시 서버에서 스크립트 태그 삭제하는 부분이 있으면 거기서 삭제되는거 아닐까요
소스를 볼수있는게 아니라 잘 모르겠네요

**Comment by kimhyeongyu** [comment]
감사합니다. 
정확한 이유는 못찾았지만, 기존에 프로젝트에 설정잡힌거랑 충돌이 된걸로 생각됩니다 감사합니다.
