### ISSUE TITLE
Appen fullpage HTML into Suneditor

### ISSUE THREAD

**Issue by tranchem** [JiHong88/SunEditor#224]
I want to upload HTML file content. I using option CodeMirror.
Firstly, i get all content of file then using appendContents. But editor lost tag <style> in HEAD

Please help me how to append full page HTML into SunEditor !!!

**Comment by JiHong88** [comment]
By default, style tag is not allowed.
Use the "fullPage" option.
```javascript
const editor = suneditor.create('xxx', {fullPage: true});
const frameDocument = editor.util.getIframeDocument(editor.getContext().element.wysiwygFrame);
frameDocument.head // style tags
frameDocument.body // Put the content inside the body
// or
frameDocument .documentElement.innerHTML = 'full page HTML string';
```

**Comment by tranchem** [comment]
Thanks for your reply. It's actived.
But when toggle codeview, tag <body> only <p><br></p>.
How to fix this ?

**Comment by JiHong88** [comment]
Did you use the "fullPage" option?

**Comment by tranchem** [comment]
> Did you use the "fullPage" option?

Yes, i used option "fullPage, iframe, iframeCSSFileName, codeMirror"

**Comment by JiHong88** [comment]
If you use the "fullPage" option, the "iframe" option is automatically true.
What data in the body tag is lost?
Doesn't it just make certain tags disappear?

**Comment by tranchem** [comment]
> If you use the "fullPage" option, the "iframe" option is automatically true.
> What data in the body tag is lost?
> Doesn't it just make certain tags disappear?




[submenu.txt](https://github.com/JiHong88/SunEditor/files/4248643/submenu.txt)

This is file i want to add to editor. I do as your instructed. It's good util toggle codeview. Tag body only p, br.

**Comment by JiHong88** [comment]
Tags other than those declared below do not apply.
```javascript
br|p|div|pre|blockquote|h[1-6]|ol|ul|dl|li|hr|figure|figcaption|img|iframe|audio|video|table|thead|tbody|tr|th|td|a|b|strong|var|i|em|u|ins|s|span|strike|del|sub|sup
```
It will be available in the next version when the "addTagsWhitelist" option is added.

And for security reasons, all script tags are removed.
Even if the script tag does not disappear, the event will not be registered because the function is not executed automatically.
Is there a reason to write script tags in the editor?

**Comment by tranchem** [comment]
> Tags other than those declared below do not apply.
> 
> ```js
> br|p|div|pre|blockquote|h[1-6]|ol|ul|dl|li|hr|figure|figcaption|img|iframe|audio|video|table|thead|tbody|tr|th|td|a|b|strong|var|i|em|u|ins|s|span|strike|del|sub|sup
> ```
> 
> It will be available in the next version when the "addTagsWhitelist" option is added.
> 
> And for security reasons, all script tags are removed.
> Even if the script tag does not disappear, the event will not be registered because the function is not executed automatically.
> Is there a reason to write script tags in the editor?

Thank you very much! I will wait option "addTagsWhiteList". Now, your editor is so pretty but i think it will more wonderfull in next version.
And the reasion i give you file txt because github not allow upload file html.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
