### ISSUE TITLE
How to when click a plugin , it will show another plugin.

### ISSUE THREAD

**Issue by BuiChiBach** [JiHong88/SunEditor#225]
Hi, your editor is very nice, I really love it, but I have a problem, example:
- I have a plugin 'format_text', then I click, it will show another plugin like bold, fontSize, fontColor, etc..

Is it possible ? if yes, how can I do it ?. 
Thank you first.

Best regards,
ChiBach

**Comment by JiHong88** [comment]
Hi @BuiChiBach 
Yes it is possible.
But it will be a bit complicated.
What is your HTML desired structure?

**Comment by BuiChiBach** [comment]
![image](https://user-images.githubusercontent.com/44353566/75325647-c2425380-58ab-11ea-8e71-b6826a091db5.png)
Hi @JiHong88 , It's like this.

**Comment by JiHong88** [comment]
Can you give me that link?

**Comment by BuiChiBach** [comment]
This is the 'New Message' form of Gmail. :D

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
[How to create custom plugin](http://suneditor.com/sample/html/customPlugins.html)

**Comment by BuiChiBach** [comment]
Thank you @JiHong88  <3
