### ISSUE TITLE
core.getContents is not a function

### ISSUE THREAD

**Issue by omarzion** [JiHong88/SunEditor#226]
pushStack in history can cause a crash after calling `editor.destroy` maybe destroy should also clear the timeouts?

**Comment by JiHong88** [comment]
Hi, @omarzion 
Thank you for raising an issue.
I'll add code to delete the history object from the destroy function.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
