### ISSUE TITLE
Insert Image Popup Won't Open After Closed

### ISSUE THREAD

**Issue by jatimyw** [JiHong88/SunEditor#230]
Hello, first of all i need to say big thanks to the Author for this awesome SunEditor.
Currently i have working with Ajax to load SunEditor, all button functionality seem normal, but all popup window won't open after i __close window__ for __"insert image"__. 
This error is not occur when i close video or link popup, only after closing "insert image" popup that affecting all of those 3 windows.

I have load main SunEditor Main JS, Lang JS, & CSS inside HTML header.
Am i doing wrong with Ajax load? or something else happen?

**Comment by jatimyw** [comment]
I have found the error, it seem caused by SunEditor Option.
When i added __imageFileInput: false,__ this error occurs.

**Comment by JiHong88** [comment]
Hi, @jatimyw 
Thank you for raising an issue.
The fix will apply to the next version.
Thank you :)
