### ISSUE TITLE
Feature: Disable image edit

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#231]
![image](https://user-images.githubusercontent.com/3808838/75831740-4ab27e00-5def-11ea-94c1-21db18cba961.png)

The image edit modal is too complex. How can I disable this button to prevent user being here?

**Comment by JiHong88** [comment]
Hi @zhaoyao91 

Added `showController` event.
You can use as below after version update.
```javascript
const editor = subeditor.create(..);
editor.showController = function (name, controllers, core) {
    // target element
    console.log('target', core.currentControllerTarget);

    let c = null;
    for (let i in controllers) {
        c = controllers[i];
        if (core.util.hasClass(c, 'se-controller-resizing')) {
            const updateButton = c.querySelector('[data-command="update"]');
            if (name === 'image') updateButton.setAttribute('disabled', true);
            else updateButton.removeAttribute('disabled');
        }
    }
}
```
I'll notify you know when the version is updated.

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
