### ISSUE TITLE
Failed to add custom plugin

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#232]
I just copy the demo in this page

http://suneditor.com/sample/html/customPlugins.html

fix a typo of lack of comma

when click the button, the menu show up, but after typing some text and click ok, the submenu just dispear and nothing else happened(no text inserted).

**Comment by zhaoyao91** [comment]
![Kapture 2020-03-04 at 9 10 12](https://user-images.githubusercontent.com/3808838/75834778-fcee4380-5df7-11ea-91ab-f69322b322cc.gif)

**Comment by zhaoyao91** [comment]
It seems the button didn't get clicked at all. While type `tab` and `space`, it got triggered.

**Comment by zhaoyao91** [comment]
strangely, after reinstall, it cannot be replayed :(

**Comment by zhaoyao91** [comment]
is it ok to change the mousedown event to mouseup? or add some background layer below the menu and listen to the click of that layer?

**Comment by JiHong88** [comment]
Could you explain a more detail?

**Comment by zhaoyao91** [comment]
as the gif shows
- first, click the button on the toolbar
- the submenu pop up
- try to click the button on the submenu, but the submenu closed immediately before the button got clicked

**Comment by JiHong88** [comment]
If you do not call the submenuOff method, it will not close.
```javascript
onClick: function () {
	const value = this.util.createTextNode(this.context.custom.textElement.value);

	this.insertNode(value);
	this.setRange(value, value.length, value, value.length);
 
        // -------------------- submenu off ----------------------
	// this.submenuOff();
	this.focus();
}
```

**Comment by zhaoyao91** [comment]
no, it will close.
see here: https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L274
I've tried to comment the submenuOff, however, the onClick is event not get triggered. I put a console.log at the top line of the onClick. when click the button, the menu closed directly, and there is no any log.

**Comment by zhaoyao91** [comment]
https://github.com/JiHong88/SunEditor/pull/234

**Comment by JiHong88** [comment]
Yup, There was a mistake in the examples.
Thank you for your contribution!
