### ISSUE TITLE
bug: indent for list should make it nested

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#233]
Currently indent on list only add some margin, but the correct behavior is to make a new nested list

![image](https://user-images.githubusercontent.com/3808838/75835970-5ad05a80-5dfb-11ea-9104-cf36b15fafa8.png)

**Comment by JiHong88** [comment]
Thank you :)
I'll fix it.

**Comment by johnnybaida** [comment]
@JiHong88 Would it be possible to parameterize this functionality?
Thank you.
