### ISSUE TITLE
Question: how to move the cursor to be the end of newly inserted tag?

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#235]
I've made some function to insert a special tag, but the cursor after inserting is before the tag. How to move it to the end of the new tag?

![Kapture 2020-03-04 at 16 52 18](https://user-images.githubusercontent.com/3808838/75861579-8cb3e200-5e38-11ea-85e0-3030b151eaf8.gif)

```
  pickup: function(e: any) {
    e.preventDefault();
    e.stopPropagation();

    const [variableKey, target] = extractAttrValue(
      e.target,
      "data-variable-key",
      (target: any) => /UL/i.test(target.tagName)
    );

    if (variableKey) {
      const variablePlaceholder = target.textContent;

      // @ts-ignore
      const node = this.util.createElement("var");
      node.setAttribute("data-node-type", "variable");
      node.setAttribute("data-variable-key", variableKey);
      node.setAttribute("contenteditable", false);
      node.textContent = variablePlaceholder;

      // @ts-ignore
      this.insertNode(node);
      // todo move cursor to the end ?

      // @ts-ignore
      this.history.push(false);
    }

    // @ts-ignore
    this.submenuOff();

    // @ts-ignore
    this.focus();
  }
};
```

**Comment by JiHong88** [comment]
Hi, @zhaoyao91 

In the next version, the cursor moves after the tag inserted by `core.insertNode`.

In the current version, you can `core.setRange` method.
```javascript
// @ts-ignore
this.insertNode(node);
// set range---------
this.setRange(node, 1, node, 1);
```

**Comment by zhaoyao91** [comment]
I tried this snippet, it didn't work. the cursor just dispeared after inserted.

Not hurry for now. There are bunch of features I am expecting for the next version. Do you have a schedule? Just curious, not push~

**Comment by JiHong88** [comment]
Maybe it didn't work becouse I did test it in the develop brunch.
I registered a [milestone](https://github.com/JiHong88/SunEditor/milestone/1) :)

**Comment by zhaoyao91** [comment]
:) BTW, I found the user functions are useful, such as uploadImage and insertHTML. but we can't use them in core when writing plugin :(

**Comment by JiHong88** [comment]
I'll be fix to access user functions from the `core` as `functions` object.

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
