### ISSUE TITLE
bug: title tooltip of custom plugin is in `i` tag

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#236]
the tooltip texts of built-in plugins are outside the `i` tag:

![image](https://user-images.githubusercontent.com/3808838/75867562-c0473a00-5e41-11ea-95a5-11080a495586.png)

but that of custom plugins are inside the `i` tag, which made they show up italic font-style:

![image](https://user-images.githubusercontent.com/3808838/75867639-df45cc00-5e41-11ea-8023-cc1d3028f68e.png)

![image](https://user-images.githubusercontent.com/3808838/75867666-e8cf3400-5e41-11ea-864b-5ea4ec833679.png)

![image](https://user-images.githubusercontent.com/3808838/75867678-ecfb5180-5e41-11ea-818a-ca51a0ff87fc.png)

**Comment by JiHong88** [comment]
The issue is not reproduced.
Did you put the button type as below?
```javascript
{
    // plugin's name attribute
    name: 'custom_plugin_submenu', 
    // name of the plugin to be recognized by the toolbar.
    // It must be the same as the name attribute of the plugin 
    dataCommand: 'custom_plugin_submenu',
    // The class name of the button to add
    // ** If you want to enable it even in code view mode, add a "code-view-enabled" class **
    buttonClass:'', 
    // HTML title attribute
    title:'Custom plugin of the submenu', 
    // 'submenu' or 'dialog' or '' (command button)
    dataDisplay:'submenu',
    // HTML to be append to button
    innerHTML:'<i class="se-icon-add"></i>'
}
```
