### ISSUE TITLE
Bug: cannot delete selected content when the first element is `contenteditable=false`

### ISSUE THREAD

**Issue by zhaoyao91** [JiHong88/SunEditor#237]
I've create a customized element which is a `var` tag with `contenteditable=false`. Everything works well until I found if it is at the first place, select all and delete will not work:

![Kapture 2020-03-05 at 11 44 17](https://user-images.githubusercontent.com/3808838/75946093-0e5a4d00-5ed7-11ea-9a6b-9317b9065428.gif)
<img width="1324" alt="Snipaste_2020-03-05_11-39-03" src="https://user-images.githubusercontent.com/3808838/75946099-12866a80-5ed7-11ea-94e7-f50f3a0ad302.png">
<img width="1286" alt="Snipaste_2020-03-05_11-40-09" src="https://user-images.githubusercontent.com/3808838/75946103-14502e00-5ed7-11ea-92b2-7a7daa07aefa.png">

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
