### ISSUE TITLE
Check SunEditor is focus

### ISSUE THREAD

**Issue by tranchem** [JiHong88/SunEditor#238]
Hi !
Firstly, i'm very grateful for your editor.
I have a question: "How to check SunEditor is focus ?"
Can you help me? I'm using options CodeMirrors

**Comment by JiHong88** [comment]
Do you want the focus event in code view mode?

**Comment by tranchem** [comment]
> Do you want the focus event in code view mode?

I just want to know focus is true or false

**Comment by JiHong88** [comment]
Focus and blur event, It will be added in the next version.
In the current version >>
```javascript
const editor = suneditor.create(...);
const w = core.options.iframe ? core._ww : context.element.wysiwyg;

let onFocus = false;
w.addEventListener('focus', function(e){onFocus = true});
w.addEventListener('blur', function(e){onFocus = false});
```

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
