### ISSUE TITLE
Inline CSS styles

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#239]
Hello,

thank you for your editor. Really good job. 

I have one question about inline CSS styles for pasted contents. In my case users can paste tables from Word or other sources and I want to keep the inline styles in editor after pasting some elements. I saw that in newest versions on your development branch you added whitelist for tags which could be pasted. Is there any option to add similar whitelist but with elements for which we want to keep inline styling? It will be really great enhacement for me.

Kind regards,
Adrian

**Comment by JiHong88** [comment]
Hi, @kranczeer 
Yes, it looks like a useful option.
It's an option to simple add.
I'll add it in the next version.

**Comment by kranczeer** [comment]
Hello,

I saw your commit and thanks for your fast reaction. But I rather mean, that more useful will be array of elements to which we want keep attributes. Because right now, if I add a "style" or "id" or "name" attribute to the whitelist, this will apply to every element (ie. table, tbody, tr, td, h1, h2, p, div) but I think maybe better will be to do some array of dependencies (ie.` ['table', 'style|id|name|class']`, `['tbody', 'style|id|name|class']`) to keep only selected attributes for selected elements.

Kind regards,
Adrian
