### ISSUE TITLE
Is it possible to change the function so that "Full Screen" can be used as "User Function"?

### ISSUE THREAD

**Issue by MARO-JANG** [JiHong88/SunEditor#24]
Hi! 

It is an simple and good editor.

Is it possible to change the function so that "Full Screen" can be used as "User Function"?

Thanks in advance.

**Comment by JiHong88** [comment]
Hi~Thank you for your interest.
Once you have created a custom button, you can find it [here](http://suneditor.com/sample/html/customize.html).
If you want to run "User Function" after full-screen operation
You can put your code inside the suneditor.js : 1384 (toggleFullScreen) function.
In the current version, the only way to add functions to the original button is to insert the code yourself.
