### ISSUE TITLE
Balloon-always issue

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#241]
Hello,

thank you again for your great work. Unfortunately I need to use your development branch because I don't have time to wait for official releases. Today when I wanted to implement your new functionality "balloon-always" I noticed very strange behaviour - onChange event is not firing when I type something into editor. On classic "balloon" mode everything is okay. Here is codesandbox with reproduced issue. I took the newest commit of develop branch: [https://github.com/JiHong88/SunEditor/commit/78410c5106aeaac4778c0eab9c103932aae89c71](https://github.com/JiHong88/SunEditor/commit/78410c5106aeaac4778c0eab9c103932aae89c71).

Codesandbox: [https://codesandbox.io/s/suneditor-onblur-9mwt9](https://codesandbox.io/s/suneditor-onblur-9mwt9)

PS. I have also suggestion for you about creating feature and bugfix branches and working on them. Then for example after finishing a few of these, merge it to develop branch and then to master. In this way you can release new versions (even minor but as official releases) more frequently and for us as a users of suneditor this will be very valuable. Because as I wrote earlier, I need to use your develop branch in my application due to lack of time to wait for new version.

Kind regards,
Adrian

**Comment by JiHong88** [comment]
Hi, @kranczeer 

Yes I agree with you.
This release modified a lot of things by implementing nested lists.
I'am sorry for the delay in deployment.
I'll postpone the work of "inline svg" to the next version, and we will be deploying it soon.

Kind regards,
JiHong

**Comment by JiHong88** [comment]
The [2.26.0](https://github.com/JiHong88/SunEditor/releases/tag/2.26.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
