### ISSUE TITLE
Link target

### ISSUE THREAD

**Issue by Yves-K** [JiHong88/SunEditor#245]
Hello,
Still testing SunEditor ;-) and really appreciate your work
It might realy improve it's power if it was possible to define a **list of targets** for link plugin

**linkTargets** : [
    { target : '_blank', name : 'New window'},
    { target : '_parent', name : 'Parent frame'}
    { target : '_top', name : 'First frame'}
    { target : 'AnyFrame', name : 'Frame name'}
    { target : '_dialog', name : 'Self defined dialog'}
],
**linkTargetDefault** : '_top',

Best regards

**Comment by JiHong88** [comment]
Hi @Yves-K 
Thank you for your interest in this project. :)
I consider these are options that are not too common for users.
Need those options?

**Comment by Yves-K** [comment]
Hello @JiHong88 
I need to know how to do it.
Would like to create a new linkTarget plugin and/or suggest a pull request on the existing one.
But dialog sample in documentation is empty  and i don't catch how actual link plugin works... 
Need explainations.
Best regards

**Comment by JiHong88** [comment]
Yeah,
I'll upload the sample of "newLink" plugin.
And I'll notify you know when work done.
Best regards

**Comment by Yves-K** [comment]
Fine, thank you

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
[Sample: custom plugin](http://suneditor.com/sample/html/customPlugins.html#)
Thank you.
