### ISSUE TITLE
에디터 글자 배경색 오류

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#249]
안녕하세요.
에디터 잘 사용하고 있습니다.

폰트색변경, 폰트배경색 변경, 사이즈변경을 하면 발생하는 오류가 있습니다.

글로 설명드리기가 한계가 있어서 메일로 보내드렸습니다. 확인한번 부탁드립니다.

**Comment by JiHong88** [comment]
안녕하세요~
텍스트노드를 변경할때 같은 속성의 태그를 합치는 과정이 있는데
속성체크하는 부분에 버그가 있었습니다.
수정된 버전 업데이트때 알려드리겠습니다.
감사합니다!

**Comment by kimhyeongyu** [comment]
네 감사드립니다~ 이번 패치가 얼마전에 되서 다음패치는 시간이 좀 흘러야겠죠? ^^;

**Comment by JiHong88** [comment]
다음주 중에 배포할 수 있을것 같습니다. ^^
[마일스톤](https://github.com/JiHong88/SunEditor/milestones) 에서 진행률을 확인할 수 있습니다.

**Comment by kimhyeongyu** [comment]
헉 진심으로 감사드립니다^^

**Comment by JiHong88** [comment]
[2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) 버전이 업데이트 되었습니다.
관련된 이슈가 있다면 새로운 이슈를 등록해주세요.
감사합니다.
