### ISSUE TITLE
Editor inserts new lines when navigating trough cells with tab key

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#250]
Hi,

thanks for the awesome work and great progress You've made last month! :)

Affected browsers: Mozilla Firefox

Steps to reproduce:
1. Create a table
2. Fill cells with values
3. Put the cursor in the first cell
4. Press tab

![LscyRVYHla](https://user-images.githubusercontent.com/1231703/76842542-b8709800-683a-11ea-86bd-da1720c24250.gif)

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
