### ISSUE TITLE
Weird behavior after pressing delete

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#251]
Hi,

We're going to release an application using SunEditor (which is great BTW :) ) but we've encountered an issue on Mozilla Firefox. 

After pressing some key sequences editor keeps adding new lines on every keypress.

Affected browsers: Mozilla Firefox
Steps to reproduce:
1. Press enter
2. Press delete 
3. Press any key

![cuiq0v4wmP](https://user-images.githubusercontent.com/1231703/76842975-60866100-683b-11ea-9cde-01cda1763a22.gif)

**Comment by JiHong88** [comment]
Hi @natanielcz 
Thanks to the image you gave, it was easy to fix.
It will be distributed as soon as the milestone is complete.
I'll notify you know after the update.
Thank you.

**Comment by natanielcz** [comment]
Thanks for quick reaction. It's really impressive! :)

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
