### ISSUE TITLE
onChange method not called when char count == maxCharCount

### ISSUE THREAD

**Issue by cwhitwell** [JiHong88/SunEditor#255]
Hi there,
I've been running some tests on the SunEditor as I will be using it in my web application. First of all big props as it works really well :). I have however found some bugs and will raise a separate issue for each.

So this bug is when you are typing values into the editor I can see the 'onChange' event being called each time there is a change, as expected. However when you type the final character (to reach the maxCharCount limit) the event is not called. This could cause problems as I am saving the data via the 'onChange' event, which means with a limit of 100 chars for example, I could only ever save 99 chars and not the final 100.

Environment:
MacOS Mojave V10.14
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
suneditor V2.26.0

Please see video demo attached (I've added a console.log in the onChange method). 
[onChange Bug SunEditor.mov.zip](https://github.com/JiHong88/SunEditor/files/4343629/onChange.Bug.SunEditor.mov.zip)

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
