### ISSUE TITLE
onBlur triggered while using toolbar

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#257]
Hi,
I've found out that onBlur is raised while using some toolbar options, e.g. changing color. I've raised that issue with more details in a previous closed ticket, so you can check it. Here is a codesandbox to reproduce the issue with latest NPM version: https://codesandbox.io/s/suneditor-onblur-x4kmi

Cheers!

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
