### ISSUE TITLE
Holding backspace then clicking insert table causes the editor to crash/become unusable

### ISSUE THREAD

**Issue by cwhitwell** [JiHong88/SunEditor#258]
Hi there,
I've been running some tests on the SunEditor as I will be using it in my web application. First of all big props as it works really well :). I have however found some bugs and will raise a separate issue for each.

This bug is caused when you hold down the backspace key (on an empty editor) while simultaneously trying to insert a table item. While this isn't exactly standard user behaviour, it shouldn't cause the editor to crash. Once the editor has crashed, attempting to change certain properties (e.g line height) causes an uncaught TypeError.

I was able to work around this issue by blocking the backspace (keyCode=8) and delete (keyCode=46) keyDown event when the editor is empty.

Possibly related to: #256 

Errors message in console:
Clicking **line height** after crash: `core.js:737 Uncaught TypeError: Cannot read property 'parentNode' of null`
Clicking **ordered list** then **indent** after crash: `core.js:704 Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.`

Environment:
MacOS Mojave V10.14
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
suneditor V2.26.0

Please see video demo attached (I've added an application to display my keystrokes on the screen).

[Hold backspace insert table.mov.zip](https://github.com/JiHong88/SunEditor/files/4343971/Hold.backspace.insert.table.mov.zip)

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
