### ISSUE TITLE
Can't change font-family of text in the 'font' tags

### ISSUE THREAD

**Issue by cwhitwell** [JiHong88/SunEditor#259]
Hi there,
I've been running some tests on the SunEditor as I will be using it in my web application. First of all big props as it works really well :). I have however found some bugs and will raise a separate issue for each.

When you change the font-family of text in the editor, occasionally the text will end up wrapped in a 'font' tag, rather than a 'span'. The problem is that when the text is in a 'font' tag and you select it to change the font, you are unable to change the font-family to anything else. Once you delete the entire text and ensure the 'font' tag is gone it works again. It also seems that switching back and forth between 'codeView' and normal view can result in the 'font' tags being removed which also solves the problem.

My suggested solution would be to remove the use of the 'font' tags all together, as the use of 'font-family' in the 'span' tag seems to be sufficient in setting and changing the font, so i'm not sure why its even needed.

Environment:
MacOS Mojave V10.14
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
suneditor V2.26.0

Please see video demo attached (I've added an application to display my keystrokes on the screen).

[Font Tag Bug.mov.zip](https://github.com/JiHong88/SunEditor/files/4344166/Font.Tag.Bug.mov.zip)

**Comment by JiHong88** [comment]
Hi
If tags with color or font-family style attributes are deleted to fit the number of characters, they are revived as "font" tags.
I don't know why not yet.😭
I'll try find a way to solve it.
