### ISSUE TITLE
Feature Request - Remove Word Formatting

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#26]
Any chance of adding a feature to remove Word formatting like the following when pasting from Word?

`<p class="MsoNormal"></p>`

`<o:p></o:p>`

**Comment by JiHong88** [comment]
yes, that is possble.
I will upload it this week!

**Comment by JiHong88** [comment]
Hi, 

I tried it, but I can not get the tag of Word from the clipboard and edit it. : (

**Comment by CMTietgen** [comment]
That's ok. Thanks for trying.

**Comment by JiHong88** [comment]
Updated from version 2.8.0

Thanks : )
