### ISSUE TITLE
Feature Request: Method to get current charCount

### ISSUE THREAD

**Issue by cwhitwell** [JiHong88/SunEditor#260]
Hi there,
Any chance we could add a method to get the current charCount from the editor? I have an application which I wish to use in conjunction with the SunEditor and it would be good if I could get the current character count of the editor to display in another section of my application.

Example: `suneditor.getCharCount() //5`

Apologies if there is already a way to achieve this but I can't find it.

Thanks.

**Comment by JiHong88** [comment]
Hi, @cwhitwell 
You can get char count by below method:
`suneditor.core.context.element.wysiwyg.textContent.length`

Even if I implement the "getCharCount" method.
It will be the same way as above code.

Thank you.

**Comment by cwhitwell** [comment]
Hi @JiHong88,
That's worked perfectly!

Thank you
