### ISSUE TITLE
Selected 'Align' option does not update when changed

### ISSUE THREAD

**Issue by cwhitwell** [JiHong88/SunEditor#262]
Hi there,
I've noticed that when changing the 'align' option in the SunEditor, the selected/highlighted option does not update until you create a new line (return key). Can't see any errors in the console.

Environment:
MacOS Mojave V10.14
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
suneditor V2.26.0

Please see video demo attached.
[Align selected item bug.mov.zip](https://github.com/JiHong88/SunEditor/files/4348691/Align.selected.item.bug.mov.zip)

**Comment by JiHong88** [comment]
Hi
This is a bug fixed in the `develop` brunch.
A new version will be released today or tomorrow.
I'll notify you know when the version is released.

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
