### ISSUE TITLE
Table manipulation without button

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#263]
Hello,

I've found another issue in tables module. I want only allow user paste and manipulate tables but without possibility to creating new tables. But there is a problem - when I delete table button from buttons list and leave 'table' plugin, there is no possibility to manipulate a pasted table. I think there should be possibility to do it even without the button.

Please try to manipulate this pasted table on sandbox: [https://codesandbox.io/s/suneditor-pasted-table-manipulation-quxwp](https://codesandbox.io/s/suneditor-pasted-table-manipulation-quxwp)

Regards,
Adrian

**Comment by JiHong88** [comment]
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
