### ISSUE TITLE
Need to consider blank list items in character count in order to restrict on the character limit

### ISSUE THREAD

**Issue by FineStrokes** [JiHong88/SunEditor#264]
Hi I need to consider blank list items in character count while user is typing in in order to restrict on the character limit

**Steps to reproduce**

1. Type a text say "sample text"
2. Style the sentence as a list item (any bulleted or numbered)
3. Now move the cursor before the word same and start pressing Enter repeatedly
4. You will observe that the list keeps on increasing by addition of blank list items but the character limit remain unchanged 

Before 
<img width="912" alt="Screenshot 2020-03-19 at 4 01 51 PM" src="https://user-images.githubusercontent.com/53820426/77058116-00d6b400-69fb-11ea-9537-3973418e9174.png">

After
<img width="912" alt="Screenshot 2020-03-19 at 3 56 50 PM" src="https://user-images.githubusercontent.com/53820426/77057995-d2f16f80-69fa-11ea-8b85-472af9ffc5fd.png">

But the issue does not happen when you make editor blank and copy paste the above type content then the character limit becomes enforceable.

**Comment by JiHong88** [comment]
Hi @FineStrokes 
Even if it is not a list, the number of characters does not increase by line breaks.
This is true for other editors.

**Comment by FineStrokes** [comment]
The issue is that we store the content typed by the user in html in localstorage so we need to restrict data over the character limit.

**Comment by JiHong88** [comment]
I consider that need add a data limit option independent of the number of characters.

**Comment by FineStrokes** [comment]
Thanks @JiHong88 for your prompt reply

Our Prime is to **allow users to add meaningful data** and **avoid adding blank list items**.
The data limiting I think will not let user know that they should add meaningful data
I see the character limit restriction working when we copy paste the list items with blank data in the editor. I am just hoping that we could achieve similar behavior when user types in with blank list items

**Comment by JiHong88** [comment]
I am sorry for the late reply.
Did you it means that an empty list should also be counted?

**Comment by FineStrokes** [comment]
Yes as we want to tell users to always enter useful data and avoid putting empty items in list.

**Comment by JiHong88** [comment]
If increase the count by 1 to an empty list, the count will not increase when you first enter the letter in the list.
I think this is an unusual behavior.
And currently I am using ".textContent" to get the number of characters.
Checking the empty list is resource intensive, and it's hard to add because it's not a common option.

Please override the "_charCount" method.
I have implemented the code here.
```javascript
const editor = suneditor.create(...);
// Redefinition
editor.core._charCount = function (nextCharCount, blink) {
    const charCounter = this.context.element.charCounter;
    if (!charCounter) return true;
    if (!nextCharCount || nextCharCount < 0) nextCharCount = 0;

    const maxCharCount = this.context.options.maxCharCount;
    const wysiwyg = this.context.element.wysiwyg;

    ///// -- get empty list ////
    const emptyListCount = this.util.getListChildren(wysiwyg, function (current) {
        return this.isListCell(current) && current.childNodes.length === 1 && this.isBreak(current.firstChild)
    }.bind(this.util)).length;
    //// ------------------ ////

    this._w.setTimeout(function () {
        charCounter.textContent = wysiwyg.textContent.length + emptyListCount; // add empty list
    });

    if (maxCharCount > 0) {
        let over = false;
        const count = wysiwyg.textContent.length + emptyListCount; // add empty list
        
        if (count > maxCharCount) {
            this._editorRange();
            const range = this.getRange();
            const endOff = range.endOffset - 1;
            const text = this.getSelectionNode().textContent;

            this.getSelectionNode().textContent = text.slice(0, range.endOffset - 1) + text.slice(range.endOffset, text.length);
            this.setRange(range.endContainer, endOff, range.endContainer, endOff);
            over = true;
        } else if ((count + nextCharCount) > maxCharCount) {
            over = true;
        }

        if (over) {
            if (blink && !this.util.hasClass(charCounter, 'se-blink')) {
                this.util.addClass(charCounter, 'se-blink');
                this._w.setTimeout(function () {
                    this.removeClass(charCounter, 'se-blink');
                }.bind(this.util), 600);
            }

            return false;
        }
    }

    return true;
}.bind(editor.core);
```

**Comment by FineStrokes** [comment]
I am having code in typescript
