### ISSUE TITLE
Unable to SetContents

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#267]
I get an empty editor area after SetContents. Suneditor v2.27.0. Also tried with a simple string. No success. 
It could be that I have old incompatible config settings and if so, it would be great if someone can point out what has changed between 2.26.0 and 2.27.0.
Code:
> this.suneditor = SUNEDITOR.create((document.getElementById('suneditor') || 'suneditor'), this.editorconfig);
this.suneditor.setContents(HTMLeditorcontent);
// register event handler so we can track if data is changed
this.datachanged = false;
this.suneditor.core.history.reset(true); // history stack reset

**Comment by JiHong88** [comment]
The [2.27.1](https://github.com/JiHong88/SunEditor/releases/tag/2.27.1) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
