### ISSUE TITLE
한글 사용중 타이핑관련 이슈가 하나 있습니다.

### ISSUE THREAD

**Issue by pieaces** [JiHong88/SunEditor#268]
우선, 이렇게 훌륭한 오픈소스를 공유해주셔서 진심으로 진심으로 감사드립니다. 당신의 능력과 넓은 아량에 경의를 표합니다!

 색상을 바꾸거나 Bold를 입히는 등 style을 줄때, 한글입력이 처음부분에서 깨지는 현상이 발생합니다. 예를 들어, 빨간색을 입히고 '안'을 입력하면 'ㅇㅏㄴ'이 됩니다. 후에는 정상적으로 입력됩니다. style을 입힌 첫 부분에서만 발견되는 듯합니다.
 제 짧은 견해로는 새로운 태그가 생성되고 그 태그에 set을 해버리는 그 초기시점에서 무엇인가 문제가 생긴게 아닌가 싶습니다. 일반 알파벳이라면 조합형이 아니기에 문제가 없지만, 한글은 그 구조가 다르기에 다른 방식이 필요한 것 같습니다.

 당신의 무궁한 발전과 행복을 기원하며 이만 마무리하겠습니다.

**Comment by JiHong88** [comment]
안녕하세요~
텍스트 선택없이 새로운 태그를 생성하면 커서를 위치시키기 위해서 공백문자(\u200B) 를 넣어줍니다.
그리고 키업 이벤트에서 해당 텍스트노드에 공백문자가 있으면 삭제하고 다시 커서를 위치시키는데
이 코드때문에 한글입력시에 문제가 생기네요.
이동이나 삭제시 에는 일반 문자처럼 하나씩 이동하고 지워지기 때문에 처리를 안 할수도 없습니다.
방법을 찾아 보겠지만 이슈 해결이 오래걸릴수도 있습니다.

**Comment by pieaces** [comment]
빠른 피드백 감사합니다.

**Comment by JiHong88** [comment]
[2.28.0](https://github.com/JiHong88/SunEditor/releases/tag/2.28.0) 버전이 업데이트 되었습니다.
관련된 이슈가 있다면 새로운 이슈를 등록해주세요.
감사합니다.

**Comment by pieaces** [comment]
아이쿠야, 제가 최근 바빠서 깃헙 신경을 못썼네요.
만인을 위해 힘써주셔서 정말 감사합니다.
덕분에 즐겁고 행복한 하루가 될것 같습니다.
감사합니다!
