### ISSUE TITLE
How to whitelist html comments ? 

### ISSUE THREAD

**Issue by anuradhaindika83** [JiHong88/SunEditor#269]
Hi
Thanks for this wonderful editor. I have one question. How can I whitelist the HTML comments? right now these comments are being added to the body as a plain text. Is there a way to override this ?

Many thanks
Anuradha

**Comment by JiHong88** [comment]
Hi @anuradhaindika83 
If there are no HTML comments on the whitelist, I'll delete them.

**Comment by JiHong88** [comment]
The [2.27.1](https://github.com/JiHong88/SunEditor/releases/tag/2.27.1) version has been updated.
If there is an issue, please register as a new issue.
Thank you.

**Comment by anuradhaindika83** [comment]
Thanks for the quick response
