### ISSUE TITLE
Feature Request - Mentions Plugin

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#27]
Any chance on adding support for mentions?

For example, if I type "@john" a popup list would display letting me choose a specific person from a list?

Once I choose a person, then maybe insert their name with a styled background color?

The popup list should be closable by pressing ESC and navigable by keyboard arrow keys.

**Comment by JiHong88** [comment]
Sounds like a good idea!
Where do I get the user list?
Did you mention the "github" user list?

**Comment by CMTietgen** [comment]
I was thinking about pulling the user list from an API using ajax or something.

My main goal with this feature request is to a have a simple that functions like the Github comments box, which has mention support.

**Comment by JiHong88** [comment]
I understood what you were saying.
I'll update it when I'm done.
Thanks : )
