### ISSUE TITLE
For counting.

### ISSUE THREAD

**Issue by shaan1974** [JiHong88/SunEditor#271]
Hello,

Is is possible to set an option to define the counting method.

Like "normal" length and "binary" length. I explain, in one of my application i have a field of 4000 chars, but to avoid problem inserting data in database i count in binary like "Euro" sign is 3 bytes, and "é" is 2 bytes.

Thanks for your work.

Could be done easily with a prototype:

/*
    BLENGTH
  	String.prototype.BLENGTH 	= function()	 		{	return unescape(encodeURIComponent( this.toString() )).length;	};		
*/
String.prototype.BLENGTH = function()
{
    //	VARS
    //
    var cr, cl;

    //  CHECK DEPENDING OF BROWSER
    //
    if ((navigator.userAgent.match(/(MSIE |Trident.*rv[ :])([0-9]+)/) !== null) || (navigator.appVersion.indexOf('Edge') > -1))
    {
        cl = window.unescape(encodeURIComponent(this.toString())).length;
        cr = 0;

        if (encodeURIComponent(this.toString()).match(/(%0A|%0D)/gi) !== null)
        {
            cr = encodeURIComponent(this.toString()).match(/(%0A|%0D)/gi).length;
        }

        return cl + cr;
    }
    else
    {
        cl = (new TextEncoder('utf-8').encode(this.toString())).length;
        cr = 0;

        if (encodeURIComponent(this.toString()).match(/(%0A|%0D)/gi) !== null)
        {
            cr = encodeURIComponent(this.toString()).match(/(%0A|%0D)/gi).length;
        }

        return cl + cr;
    }
};

**Comment by JiHong88** [comment]
Hi @shaan1974 
Thank you so much!
Good code and ideas.
I'll try apply this feature.

**Comment by JiHong88** [comment]
The [2.28.0](https://github.com/JiHong88/SunEditor/releases/tag/2.28.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.

**Comment by shaan1974** [comment]
Thanks a lot
