### ISSUE TITLE
Icons feature

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#272]
Hello,

thanks for new version. I have idea for new feature - can you add possibility to edit the font that you are using for toolbar icons? Because I need to change some of them according to users needs and I will want to do it in straightforward way, not to make workaround solutions.

Thanks,
Adrian

**Comment by JiHong88** [comment]
Hi

If you are developing in nodejs environment, you can change it as below.
As we modify the icon object, it will be applied to all editors.
```javascript
import icons from '../../src/assets/defaultIcons';
icons.bold = '...'
```
I'll add the option to change the default icon in the next version.
Thank you.

**Comment by JiHong88** [comment]
The [2.28.0](https://github.com/JiHong88/SunEditor/releases/tag/2.28.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
