### ISSUE TITLE
setContents doesn't work immedietaly after creating editor

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#273]
Hi!

I've found out that in the newest version of library setContents doesn't work as it worked before. I used it in my workflow directly after creating editor (I'm using it as a React component, so I'm using setContents inside useEffect hook). Please see codesandbox: https://codesandbox.io/s/suneditor-setcontents-m4fow . First call, that is executed right after creating suneditor doesn't work, but the postponed one in setTimeout works. For me, unfortunately, that is a critical issue that makes current version unusable :( .

Cheers!

**Comment by tswistak** [comment]
I've found that it's already raised so I'm closing
https://github.com/JiHong88/SunEditor/issues/267

**Comment by JiHong88** [comment]
The [2.27.1](https://github.com/JiHong88/SunEditor/releases/tag/2.27.1) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
