### ISSUE TITLE
Pasting tables issue

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#274]
Hello,

thanks for releasing new suneditor version. I've noticed following bug - when I try to paste tables every style dissapear also with table formatting. I added every element which I want to keep to the whitelist attributes so it's strange behaviour.

Example: [https://i.imgur.com/hwa2ItC.gifv](https://i.imgur.com/hwa2ItC.gifv) 
Codesandbox: [https://codesandbox.io/s/suneditor-paste-npm-9mwt9](https://codesandbox.io/s/suneditor-paste-npm-9mwt9)

Regards,
Adrian

**Comment by JiHong88** [comment]
The [2.27.1](https://github.com/JiHong88/SunEditor/releases/tag/2.27.1) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
