### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by pazicb** [JiHong88/SunEditor#275]
Hello,
How do i have to proceed? I need to view only SunEditor content, including "katex".
I need the user to see the content, not edit it and not see the editor control.

Thank you.

**Comment by MRB60** [comment]
Place the html output from editor within a div and add class:

`<div class="sun-editor-editable"><p>my suneditor contents</p></div>`

**Comment by JiHong88** [comment]
Hi
Do you means to use only the "math" plugin without editing the editor directly?

**Comment by pazicb** [comment]
Yes, in SunEditor I want to prepare texts including math formulas and then display it without an editor.

**Comment by JiHong88** [comment]
Yup,
Just remove the "contenteditable" attribute.
```javascript
import katex from 'katex'

const editor = suneditor.create('id', {
  buttonList: [['math']],
  katex: katex
})

editor.core.context.element.wysiwyg.removeAttribute('contenteditable')
```

**Comment by pazicb** [comment]
Thank you, but I need to hide everything from the editor. Buttons, header and footer.

**Comment by JiHong88** [comment]
Ok, Use it like this.
```javascript
const editor = suneditor.create("id", {
  resizingBar: false,
  katex: katex
})
editor.toolbar.hide();
```

**Comment by pazicb** [comment]
Thank you for your quick help. I have one more problem, when I start the editor I see "undefined" and I don't see "placeholder"

**Comment by JiHong88** [comment]
Can I see your code?
How did you defined the editor?

**Comment by pazicb** [comment]
When the editor is started, the text "undefined" is displayed in the editor.

**Comment by JiHong88** [comment]
Remove this code `"lang(In nodejs)": "en"`
This is shows additionally how to define language files in nodejs environment.
And Modify code `"katex": "window.katex",` -> `"katex": window.katex,`
This is shown to text as a limitation of expression in the sample code.

**Comment by pazicb** [comment]
It is still the same. The editor starts correctly, works correctly, but it contains the word "undefined", which I can delete.

**Comment by JiHong88** [comment]
Where is the "undefined" character included?
Can you show me a screenshot?

**Comment by pazicb** [comment]
![img](https://user-images.githubusercontent.com/34579080/77252300-383f9d80-6c53-11ea-9da6-571441b3cc48.png)

**Comment by JiHong88** [comment]
Are you using "placeholder" option?
Can I see the HTML code and script code?

**Comment by pazicb** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="css/suneditor.min.css" rel="stylesheet" />
    <script src="suneditor.min.js"></script>   
    <script src="en.js"></script>
    <script  src = "https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js"> </script>
    <link  rel = "stylesheet" href ="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" />
</head>
<body>  
   <div id="editor">
   </div>
    <script>
        var editor = SUNEDITOR.create('editor', {
                "mode": "classic",
            "katex": window.katex,
                "buttonList": [
                    [
                        "undo",
                        "redo",
                        "font",
                        "fontSize",
                        "formatBlock",
                        "paragraphStyle",
                        "blockquote",
                        "bold",
                        "underline",
                        "italic",
                        "strike",
                        "subscript",
                        "superscript",
                        "fontColor",
                        "hiliteColor",
                        "textStyle",
                        "removeFormat",
                        "outdent",
                        "indent",
                        "align",
                        "horizontalRule",
                        "list",
                        "lineHeight",
                        "table",
                        "link",
                        "image",
                        "video",
                        "math",
                        "fullScreen",
                        "showBlocks",
                        "codeView",
                        "preview",
                        "print",
                        "save",
                        "template"
                    ]
                ],
                "lang": SUNEDITOR_LANG.en
        });       
    </script>
</body>
</html>`

**Comment by JiHong88** [comment]
The constructor element of suneditor is "textarea".

`<textarea id="editor"></textarea>`

Please see here: [getting-started](https://github.com/JiHong88/SunEditor#getting-started)

**Comment by pazicb** [comment]
Thank you.
