### ISSUE TITLE
Html comments within the body tag are not being whitelisted

### ISSUE THREAD

**Issue by anuradhaindika83** [JiHong88/SunEditor#277]
Hi,
Thanks for the quick fix on that previous issue. But however HTML comments within the BODY tag are not getting whitelisted. They are still being added as plain text.  

Thanks
Anuradha

**Comment by JiHong88** [comment]
The [2.28.0](https://github.com/JiHong88/SunEditor/releases/tag/2.28.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
