### ISSUE TITLE
SetContent not whitelisting html comments

### ISSUE THREAD

**Issue by anuradhaindika83** [JiHong88/SunEditor#278]
Hi,

At the page load, I get the HTML data from the DB to a javascript variable and that variable is being passed to the SetContent() method. In this case, the HTML comments are not getting whitelisted. 

Eg. 

`suneditor.setContents('<!-- html comment -->');`

here the "html comment" is added as a plain text to the body. 

Thanks
Anuradha

**Comment by JiHong88** [comment]
The [2.28.0](https://github.com/JiHong88/SunEditor/releases/tag/2.28.0) version has been updated.
If there is an issue, please register as a new issue.
Thank you.
