### ISSUE TITLE
Binary counter.

### ISSUE THREAD

**Issue by shaan1974** [JiHong88/SunEditor#281]
Hello,

I'v test the binary counter feature.
It's seems that the binary counter don't take in count the html tags only the text content.

Have a nice day
Shaan1974

**Comment by JiHong88** [comment]
Yeah, That is the intended behavior.
I will add an option.
"charCounterType" : "char", "byte", "byte-html"

**Comment by shaan1974** [comment]
Ok thanks.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
