### ISSUE TITLE
에디터 초기화면 <br>

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#282]
![Screenshot_20200323-153044_NAVER](https://user-images.githubusercontent.com/39076893/77289422-4e199500-6d1d-11ea-99db-4b5aab2b87ad.jpg)

초기 로드화면에 <p><br></p> 태그로 되어있는데, 글 입력시 br태그가 없어지는게 되있는거 같습니다.

하지만 explorer 11에서는 글 입력해도 br태그가 안없어져 이슈가 생기는거 같습니다.

확인한번만 부탁드립니다!

**Comment by JiHong88** [comment]
안녕하세요~
글입력시 br 태그가 사라지는건 에디터 기능이 아닌,  브라우저 엔진에서 동작합니다.
IE 에서 br 태그가 사라지지 않았을때, 어떤 이슈가 있는건가요?

**Comment by kimhyeongyu** [comment]
답장이 늦어서 죄송합니다.
메일로 동영상 캡쳐해서 보내드렸습니다.

**Comment by JiHong88** [comment]
감사합니다!
메일의 버그 내용과 관련이 없어 이 이슈는 닫겠습니다.
수정 후 알려드리겠습니다

**Comment by JiHong88** [comment]
안녕하세요~
[v2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) 버전에서 모두 수정되었습니다.
감사합니다.
