### ISSUE TITLE
<ins> shouldn't be used for underline

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#283]
Hi!

I've found out that when applying underline, text gets wrapped in tag `<ins>`. That is wrong semantically. `<ins>` tag should be used to annotate new, added parts to document, not to be used as underline. To do it properly, you should use `<span style="text-decoration: underline;">` (using `<u>` is not an alternative, since it also have different semantics, despite being used as underline).
I think it would be good to fix that, so documents are not only looking good, but are also semantically correct.

References:
- Usage of `<ins>` tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins
- Usage of `<u>` tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u

Cheers!

**Comment by tswistak** [comment]
To give you another argument for not using <ins>, I've created this HTML:
`<html>
<body>
<p>normal text</p>
<p><ins>underlined text by ins</ins></p>
<p><u>underlined text by u</u></p>
<p><span style="text-decoration: underline">underlined text by span</span></p>
</body>
</html>`
and I've opened it in Word and got this:
![image](https://user-images.githubusercontent.com/9076255/77892114-5704ec00-7272-11ea-987a-edaa50264efb.png)
The vertical line on the left is a Word annotation, that this paragraph has been added to the original document.

That's somehow similar to my use case of Suneditor. Results of what has been entered by user I'm sending as HTML to the backend and on backend I'm creating Word files out of these HTMLs. Unfortunately, whatever way I'm doing the parsing (external libraries or inserting HTML as AltChunk to docx), <ins> is always treated as something inserted to the file, not underline. For now, I'm using a workaround, by replacing all usages of <ins> with <span style="...">, but it would be better if editor wouldn't create wrong semantically output.

**Comment by JiHong88** [comment]
Hi @tswistak 

sorry for late reply.😔
When editing the underline, I was mistaken for the `<ins>` as a substitute for the `<u>`.

I think it's correct to switch to the `<u>`.
I have seen so many different editors.
All editors using the `<u>` without exception.

Buttons such as "bold", "underline", "italic".. are buttons to insert different tags.
If to accurately reflect the meaning of the HTML tag, it will need to replace all buttons with a `<span>`.
I think most of the users will use the underline button expecting the `<u>` to be inserted.

**Comment by tswistak** [comment]
I think that `<u>` can be used. Maybe it won't be exactly "just underline" but every viewer and editor will treat it just as underline. 
Version with `<span>` could be a future improvement, if you'd like to switch from tags like `<b>` to inline styles in `<span>` like e.g. DraftJS does.

**Comment by JiHong88** [comment]
OK, I'll change  "ins" to "u" in next version.
For now, I will follow the way other editors.
The tag issue seems to have to look for more information and consider it.
After modification, it is replaced as follows.
`<ins>` -> `<u>`

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
