### ISSUE TITLE
No ability to insert new line before after the table when It doesn't exist 

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#284]
Hi,

thanks for the next release! I see that many bugs are fixed but this one still occurs. Description and steps to reproduce in #253.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
