### ISSUE TITLE
Three-click edit text styling

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#285]
Hello,

I've noticed another bug - when I try to mark a text in cell by three-times click on it and style it, then style is applied to two cells instead of one.

Demo: [https://i.imgur.com/DAsV8tA.gifv](https://i.imgur.com/DAsV8tA.gifv)
Sandbox: [https://codesandbox.io/s/suneditor-three-click-npm-9mwt9](https://codesandbox.io/s/suneditor-three-click-npm-9mwt9)

Regards,
Adrian

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
