### ISSUE TITLE
TypeScript support is very partial

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#287]
Hi!

Thanks for adding TypeScript support. However, I think that current support is not sufficient. Actually, after doing suneditor.init, we're getting type "any", so we don't have any type annotations for editor functionalities. I think that's the most crucial part because most of the logic is after instantiating the object, not before.
Another thing with the support is the fact, that currently, support is only for the main suneditor module. There's no support for plugins and locale, so in strictly typed environment we still need to add empty declaration like `declare module 'suneditor/*';` to avoid TypeScript errors.

It's not critical, it's just a nice to have feature, that would be very useful for development purposes. It's much easier to browse through code suggestions from TypeScript in IDEs like WebStorm or VS Code than browsing through documentation.

Cheers!

**Comment by JiHong88** [comment]
Hi
I am not yet familiar with TypeScript.😭
Can you send me a PR?

**Comment by tswistak** [comment]
Hi,

When I'll have some free time I can start with adding some new typings :)

Cheers!

**Comment by JiHong88** [comment]
Yeah.

Thank you so much :)

Cheers!

**Comment by tswistak** [comment]
I've created the first PR where I've added typings that will allow using Suneditor in TypeScript without any problems. Now, the only thing left is to provide typings for the whole core which should match docs. Probably it can be done automatically from JSDOC comments, but I'm not sure of results. I will check it or just do it manually over time and send you another PR.

**Comment by JiHong88** [comment]
Hi
Thank for your contribution!
You did a lot of things I couldn't.
Thank you.

**Comment by JiHong88** [comment]
Hi, @tswistak 
Is it necessary to create .d.ts files only for files in the lib folder?
If you show me an example please, I will add it.

**Comment by tswistak** [comment]
Hi @JiHong88 
It should be enough, similarly as I did for plugins and languages. I can do more specific example some time later. For now, you can do something like this to have something from the start:
1. install Typescript globally (npm install -g typescript)
2. create tsconfig.json in main directory with following config:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "allowJs": true,
    "emitDeclarationOnly": true,
    "checkJs": true,
    "declaration": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
3. run `tsc` command
It should generate some d.ts files basing on JSDoc comments and implicit type guessing. It's not perfect, probably they won't work very well, but for the beginning of creating types they should be enough.

**Comment by JiHong88** [comment]
Thank you @tswistak 
[commit](https://github.com/JiHong88/SunEditor/commit/dd056d244469b0724c1ceb2729c21b71c3b1acaa)
I added the tsconfig.json
Is this enough?

**Comment by JiHong88** [comment]
@tswistak 
The files in "lib" are not directly imported and used by the user.
Are these files needing to generate d.ts?

**Comment by tswistak** [comment]
Hi @JiHong88,
They are not imported by user, but they can be used in main typing file, since most of logic is in there. Unfortunately TS can't properly do types with old style of creating JS objects and a lot needs to be rewritten here manually. I'm in progress of creating proper types for whole Core, probably today or tommorow I will create a PR with that. In few cases I couldn't guess a proper type, but I will leave "TODO" comment in each case. I hope it will be a good base for further work :)

**Comment by tswistak** [comment]
@JiHong88 please check: https://github.com/JiHong88/SunEditor/pull/311

**Comment by JiHong88** [comment]
@tswistak 
Thank you so much!
I will release a new version after further work :)

**Comment by JiHong88** [comment]
Hi, @tswistak 
I updated all "TODO" comments and other d.ts files at the `develop` branch.
Can you please check that I corrected it correctly? [#518075b](https://github.com/JiHong88/SunEditor/commit/518075b5d9bd40828b8c2f53bfe240f06088240a)
Thank you.

**Comment by tswistak** [comment]
Hi @JiHong88,
Looking at the code, it looks OK to me :) . My only concern is about init function in suneditor.d.ts. I think, that it could use better return type for { create }, so user will know what he'll get after executing that create. Some time later I can download it and check how it works and maybe I will think of some way how to approach init better.

**Comment by tswistak** [comment]
@JiHong88 everything looks good. I've just added an additional pull request https://github.com/JiHong88/SunEditor/pull/315 with small fix. 

And IMO we can close that ticket :) . TypeScript works great now.

**Comment by JiHong88** [comment]
Thank you! I couldn't find a way.
It helped me a lot in studying TypeScript.
I'll release new version and let you know.
Thank you again : )

**Comment by JiHong88** [comment]
Hi @tswistak 
The [2.28.3](https://github.com/JiHong88/SunEditor/releases/tag/2.28.3) version has been updated.
Thank you!

**Comment by kristofferlund** [comment]
Hi, great job on adding TS support! 
When i import as referred to in the documentation: `import SunEditor from "suneditor-react";`, I get this error:
`TS7016: Could not find a declaration file for module 'suneditor-react'.`

It works if I surpress it, but with warnings. Did I go about this wrong?
