### ISSUE TITLE
Style for whole table applied only on focused element

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#288]
Hello,

I've noticed another bug. When I paste table to the suneditor, then I click on cell (no matter which cell) then I click "Ctrl + A" to mark whole content and add a style for it (for example bold text) then style is applied only for before focused element.

Demo on your environment: [https://i.imgur.com/aDSBHr9.gifv](https://i.imgur.com/aDSBHr9.gifv)
Table which I'm pasting is from: [https://www.w3schools.com/html/html_tables.asp](https://www.w3schools.com/html/html_tables.asp)

Regards,
Adrian

**Comment by kranczeer** [comment]
It happens also when I click few elements in a row, then Ctrl + A to give style: [https://i.imgur.com/uNpcSqW.gifv](https://i.imgur.com/uNpcSqW.gifv)

**Comment by JiHong88** [comment]
Hi
This issue will be fixed in #291 
Thank you.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
