### ISSUE TITLE
Text color of last cell in a table is not changing

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#289]
Steps to reproduce:
1. Copy & paste table from https://www.w3schools.com/html/html_tables.asp
2. Focus every table cell with Tab (workaround for #288)
3. Mark all text (Ctrl + A)
4. Change color three times

Expected result: all cells have the same color
Actual result: the last cell didn't change the color

![mFq1715XtM](https://user-images.githubusercontent.com/1231703/77316050-f2451100-6d08-11ea-9fc9-3c93e0359e34.gif)

**Comment by JiHong88** [comment]
Hi
This issue will be fixed in #291 
Thank you.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
