### ISSUE TITLE
Sometimes styles are not applied to text in cells

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#290]
Hello,

steps to reproduce:

- paste a table
- mark randomly some text and try to style
- in random cases, styling doesn't work

Table pasted from: [https://www.w3schools.com/html/html_tables.asp](https://www.w3schools.com/html/html_tables.asp)
Demo on your's env: [https://i.imgur.com/i326v6s.gifv](https://i.imgur.com/i326v6s.gifv)

Regards,
Adrian

**Comment by JiHong88** [comment]
This issue will be fixed in #291 
Thank you.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
