### ISSUE TITLE
Strong element added to clean table

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#292]
Hello,

I've noticed another issue. I have document in Google Docs - pure table with some text, totally unstyled. When I'm pasting it into suneditor, then text inside table is bold (element `<strong>` is added before pasted content) and you cannot unbold this text.

Link to document with table: [https://docs.google.com/document/d/1IIfBaAKizrakeaLOdrGpaMgUT-aToEaBUZLdVJd3yCs/edit](https://docs.google.com/document/d/1IIfBaAKizrakeaLOdrGpaMgUT-aToEaBUZLdVJd3yCs/edit)
Demo on your's environment: [https://i.imgur.com/CqHDAKE.gifv](https://i.imgur.com/CqHDAKE.gifv)

Regards,
Adrian

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
