### ISSUE TITLE
Color picker displaying off page and resizing page

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#294]
Hi,
I've met another issue ;) The color picker is extending the page so the white background appears. We should detect if there is enough space to display balloon below or maybe we should display it above ;)

Sandbox: https://codesandbox.io/s/suneditor-baloon-position-4sn8m

![50PbsB0AQM](https://user-images.githubusercontent.com/1231703/77416269-fc781580-6dc3-11ea-98f1-8797d26327ff.gif)

Best wishes,
Maciej

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
Only the left position of the menu has been modified.
The issue displaying the menu at the above button will be modify in the next version.
Thank you.

**Comment by JiHong88** [comment]
Hi
The [2.28.2](https://github.com/JiHong88/SunEditor/releases/tag/2.28.2) version has been updated.
Thank you.
