### ISSUE TITLE
How to write a plugin to Ctrl + Click link to open them

### ISSUE THREAD

**Issue by soulcurrymedia** [JiHong88/SunEditor#295]
We need a way to open the links by Ctrl click without linking them. 

Our workflow simply paste a content (including links) in a text editor, and we want that the links should open when Ctrl + clicked.

We need to know how to build this kind of custom plugin.

Thanks

**Comment by JiHong88** [comment]
Hi @soulcurrymedia 

It's simple to implement.
```javascript
const editor = suneditor.create(...);

editor.onKeyDown = function (e, core) {
    const keyCode = e.keyCode
    const ctrl = e.ctrlKey || e.metaKey || keyCode === 91 || keyCode === 92;
    if (ctrl && keyCode === 187) {
        e.preventDefault();
        core.actionCall('link', 'dialog', null);
    }
}
```
Documents:
[onKeyDown](http://suneditor.com/sample/html/out/document-user.html#onKeyDown), [actionCAll](http://suneditor.com/sample/html/out/document-editor.html#actionCall)

Thank you.

**Comment by JiHong88** [comment]
Sorry I misunderstood the question.
```javascript
const editor = suneditor.create(...);

editor.onKeyDown = function (e, core) {
    const keyCode = e.keyCode
    const ctrl = e.ctrlKey || e.metaKey || keyCode === 91 || keyCode === 92;
    if (ctrl && keyCode === 187) {
       e.preventDefault();
       const anchor = core.util.getParentElement(core.getSelectionNode(), core.util.isAnchor)
        if (anchor) {
            window.open(anchor.href)
        }
    }
}
```

**Comment by soulcurrymedia** [comment]
Hi @JiHong88,

I feel bad as saying thanks doesn't pay the bills.
I hope you are safe and happy.

To begin with a big thank you for this code snippet, I will surely use suneditor. 

How we could help you in this project?

Thanks.

**Comment by JiHong88** [comment]
It is enough to say thank you. 😊 
Let me know if you find a bug!
And you can also participate in this project with new features.
Thank you.
