### ISSUE TITLE
Pasting text doesn't trigger onChange and placeholder doesn't hide

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#296]
Hi!

I've found an issue with paste functionality. When you have an empty textarea and paste any text into it:
- placeholder doesn't hide
- onChange action is not triggered.

Please take a look into codesandbox with it: https://codesandbox.io/s/suneditor-copypaste-0cyo0 .

Cheers!

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
