### ISSUE TITLE
`undefined` error when try to apply/remove style to/from already styled selection

### ISSUE THREAD

**Issue by LexaGal** [JiHong88/SunEditor#297]
![ScreenshtErr](https://user-images.githubusercontent.com/9394689/77623788-c8caf600-6f51-11ea-8b4b-7bbaca079eea.png)

![ScreenshtErr1](https://user-images.githubusercontent.com/9394689/77624785-6246d780-6f53-11ea-9cf9-b0b459cb941e.png)

The issue happens at times but with any style tag (strong, ins, span, ...). Seem to be a text parsing bug.

**Comment by JiHong88** [comment]
The editor must have a format tag (P, DIV..).
I'll improve the consistency check before rendering the HTML in the editor.
Thank you.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
