### ISSUE TITLE
그누보드 커스텀

### ISSUE THREAD

**Issue by seintroad** [JiHong88/SunEditor#298]
안녕하세요. 
에디터가 너무 가볍고 좋아 보여서... 지금 쓰는 그누보드에 옴겨쓰려고 작업시도 하고 있습니다.
제가 실력이 아주 미약하여 더이상 진행이 안되 결국 도움 요청 드립니다.
문제가, suneditor.create() 에서 가져오는 값이 textarea로 넘어가지 않아 textarea에 내용이 없는 걸로 계속 처리가 되고 있습니다.  값을 가져오는 방식이 틀린건가요 아니면 textarea에서 id값이 충돌이 나는건가요?..  시간이 되신다면 한번 살펴봐 주셨으면 감사하겠습니다.

![suneditor문의](https://user-images.githubusercontent.com/62705721/77655414-b682a380-6fb5-11ea-9993-e4a422ae2f06.jpg)

**Comment by JiHong88** [comment]
에디터를 생성하는 것만으로 textarea에 값이 넘어가지 않습니다.
에디터는 렌더링 되었나요?

**Comment by seintroad** [comment]
리플 감사합니다.
개발 수준이 전문적으로 배운것이 아니라 렌더링이 됬는지는 알수 가 없습니다. 죄송합니다.
다만 에디터가 화면에 출력은 되었고 작동은 잘되는데 썬에디터에서 작성된 코드를 Editor.getContents(); 로 뽑아서 그누보드 필드값을 가지고 있는 textarea로 값을 옮겨질때 아무 내용이 없는것으로 나오고 있네요. Editor.getContents();을 사용 하여 값을 가져올경우 문제가 되는지요.?
전문 개발자가 아니라 좀 이해가 떨어지는점 이해해주세요

**Comment by JiHong88** [comment]
저도 그누보드는 사용해본적이 없어서..
올려주신 코드만 봐서는 정확히 어떻게 하고 계신지 모르겠네요.
```javascript
var textarea = document.getElement('texteare_id')
var Editor = SUNEDITOR.create(textarea,{})
textarea.value = Editor.getContents()
```
이런식으로 해야합니다.
getContents는 에디터의 값을 가져오고 이값을 textarea에 넣어주면 됩니다.

**Comment by seintroad** [comment]
정말 감사합니다.  부족한 질문에도 일일이 답변해주시고..
".value" 로 해결됬습니다.  감사합니다.
