### ISSUE TITLE
Pasting text from Word creates empty paragraph at the top

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#299]
Hi!

I've found another issue connected with pasting functionality. When you paste from Word, the text gets an additional empty paragraph that can't be removed with backspace, nor selected (however, it can be removed when selecting everything via CTRL+A). What's good, it triggers onChange and hides placeholder, but it shouldn't paste a fragment that can't be removed.
Please take a look at GIF showing this:
![suneditor-paste](https://user-images.githubusercontent.com/9076255/77728673-44ce4800-6ffd-11ea-92f0-d20595f4af89.gif)
Under editor, I'm showing the HTML returned by editor on onChange event to see what's going on.

Cheers!

**Comment by JiHong88** [comment]
Hi!
This issue will be fix with #297
Thank you always.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
