### ISSUE TITLE
Feature Request - Custom Image Resizing

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#30]
When clicking on an image in the editor you get options to resize it by 100%, 75%, 50%, and 25%.

Is there a possibility to allow a custom size in pixels?

Maybe make it part of the same dialog that displays when you click the **Picture** button on the image?

In the screenshot below I added a **Size** drop down that contains options for 100%, 75%, 50%, 25%, and Custom.

![insert image 1](https://user-images.githubusercontent.com/13341574/38647357-d9b8731e-3db9-11e8-9dc8-33ef88e78b01.png)

Choosing the **Custom** option would display **Height** and **Width** fields, as shown below.

![insert image 2](https://user-images.githubusercontent.com/13341574/38647396-0f7a7eb6-3dba-11e8-885d-4ef4895d979d.png)

The check box between the Height and Width would allow the user to maintain the aspect ratio, so that if they changed the Height OR Width, the other value would be adjusted automatically and keep the image from being distorted. 

The **refresh** icon simply swaps the Height and Width values with each other.

I'm not sure of my availability, but I might be able to implement this, if you're accepting pull requests?

**Comment by JiHong88** [comment]
Yes, it is a required feature : )
Of course, I will accept your pull request !
However, it would be better to remove the dropbox and have only the "Height" and "Width" input boxes.
 1. When the Modify button is pressed on the image, the "Height" and "Width" items will be filled with the current size.
 2. If you change one of "Height" or "Width", the other side of the image should be changed to match the proportion of the image.

**Comment by CMTietgen** [comment]
Sadly, it doesn't look like I will have time to work on this PR.

**Comment by JiHong88** [comment]
Yup, that's ok

Thank you for giving me your idea.

I will start working on this PR : )

**Comment by JiHong88** [comment]
Hi,

I have fixed this Feature Request : )

**Comment by CMTietgen** [comment]
Thanks, I will try it out.
