### ISSUE TITLE
Facing css import issue in create react app in typescript

### ISSUE THREAD

**Issue by FineStrokes** [JiHong88/SunEditor#300]
I am facing css import issue in create react app in typescript

Can u please let me know how I can resolve this issue as I have imported the css into my typescript file as below

import 'suneditor/dist/css/suneditor.min.css';

![image](https://user-images.githubusercontent.com/53820426/77743166-a910fc00-703d-11ea-85bc-5fa3ef20d1eb.png)

**Comment by JiHong88** [comment]
Which version are you using?

**Comment by FineStrokes** [comment]
suneditor@2.25.0

**Comment by FineStrokes** [comment]
I have added the path of the suneditor.min.css in CopyWebpackPlugin in Webpack
as node_modules/suneditor/dist/css/suneditor.min.css
And in  
new HtmlWebpackIncludeAssetsPlugin({
        assets: [
'css/suneditor.min.css'] })

And  use in  my typescript file as

import 'suneditor/dist/css/suneditor.min.css';

It works in my dev env but fails in Prod after build as shown in figure above

**Comment by JiHong88** [comment]
It seems that the web font is not loaded.
You must have a file loader.
```javascript
{
	test: /\.(eot|svg|ttf|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
	use: [{
		loader: "file-loader",
		options: {
			publicPath: '../',
			name: 'fonts/[hash].[ext]',
			limit: 5000,
			mimetype: 'application/font-woff'
		}
	}]
}
```
Or 
The latest version uses "inline svg" rather than a web font.
Please update the editor to the latest version.

**Comment by FineStrokes** [comment]
ok how do I use font import in CopyWebpackPlugin

**Comment by JiHong88** [comment]
Sorry, I don't know..😭
I recommend updating the version.

**Comment by JiHong88** [comment]
I set it like this in my webpack environment.

```javascript
{
	test: /\.(eot|svg|ttf|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
	use: [{
		loader: "file-loader",
		options: {
			publicPath: '../',
			name: 'fonts/[hash].[ext]',
			limit: 5000,
			mimetype: 'application/font-woff'
		}
	}]
}
```
Even if the web font is loaded with this setting, it is recommended to use the latest version.

**Comment by FineStrokes** [comment]
Can u  let me know what is the improvement in switching to newer version

**Comment by JiHong88** [comment]
Please refer to the release history.
[https://github.com/JiHong88/SunEditor/releases](https://github.com/JiHong88/SunEditor/releases)

**Comment by rwaldron** [comment]
I was experiencing similar issues, as I have 

```
import 'suneditor/dist/css/suneditor.min.css';
```

...in my code as well. 

Here's what I've learned: in development mode, webpack is just copying the contents of that file and putting it into a `<style>` element, without interacting with the source. In production mode, webpack will open the source, copy the contents into memory and attempt to minify it with Terser, however there must be a syntax error in 'suneditor/dist/css/suneditor.min.css', because it fails to parse and therefore fails to include it in the final production bundle. There is also evidence that 'suneditor/dist/css/suneditor.min.css' has a syntax error, because my text editor cannot apply css syntax highlighting to it. I will report back if I can find more information.

**Comment by rwaldron** [comment]
According to csslint.com: `Expected RBRACE at line 1, col 30372.`

**Comment by rwaldron** [comment]
I think both my CSS syntax highlighter, Terser and CSS Lint don't understand the `1turn` value here: 

```css
@keyframes spinner{
  to {
    transform: rotate(1turn);
  }
}
```

When I change it to: 

```css
@keyframes spinner{
  to {
    transform: rotate(360deg);
  }
}
```

CSS Lint is happy.

**Comment by JiHong88** [comment]
@rwaldron Thank for your feedback!
I have checked this issue, and it seems that "cssnano" converts "360deg" to "1turn".

https://github.com/cssnano/cssnano/issues/823
This issue does not seem to be resolved. :(
I will fix this issue by changing "360deg" to "361deg".

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
