### ISSUE TITLE
onChange event is not fired when removing styled text

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#301]
Hello

thanks for your library, great job! I've noticed one bug.

Repro steps:

- write some text
- make it bold, underlined (just style it)
- mark everything using Ctrl + A / Shift + arrow
- delete it using backspace

Example gif: [https://i.imgur.com/uRdMUhU.gifv](https://i.imgur.com/uRdMUhU.gifv)
Sandbox url: [https://codesandbox.io/s/suneditor-deleting-styled-text-70bjo](https://codesandbox.io/s/suneditor-deleting-styled-text-70bjo)

Thanks,
Adrian

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
