### ISSUE TITLE
Select tags disabled in custom plugin

### ISSUE THREAD

**Issue by aderaHenry** [JiHong88/SunEditor#302]
Hello @JiHong88 . Select tags were working fine in custom plugins, but now they seem to be disabled.

**Steps to reproduce**

1. Create a custom plugin with a select tag

The select functionality is disabled.

**Comment by JiHong88** [comment]
Hi @aderaHenry 
It does mean the select tag is disabled in your custom plugin?

**Comment by aderaHenry** [comment]
Yes JiHong. Select tags are disabled by default, in my custom plugin. I
can't seem to find a way to enable them. This came after the recent update.

Warmest regards,
Adera Henry

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by aderaHenry** [comment]
@JiHong88 this issue has not solved in v2.28.1
