### ISSUE TITLE
Bug. Doesn't work javascript

### ISSUE THREAD

**Issue by AkioSarkiz** [JiHong88/SunEditor#303]
Hi! I'd like use this editor. But he doesn't work in my web-app. Watch the video:
https://www.youtube.com/watch?v=8so4651nx4Y

**Comment by JiHong88** [comment]
Hi!
Please show me the error message printed on the debug console.

**Comment by AkioSarkiz** [comment]
Big message:
https://pastebin.com/bXKZCkaw

**Comment by JiHong88** [comment]
It does not collide with vue.

Only errors that occurred in vue are visible.
> templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

Did you put the script in the template tag?
Try creating an editor from the "mounted" method.

**Comment by AkioSarkiz** [comment]
Ok. I moved style after app vue and put there editor. Reload page browser and it working. Thank you!
