### ISSUE TITLE
Feature request: make it possible to append/insert piece of html into existing contents via button menu

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#304]
Thanks for a great piece of SW!
Perhaps it is already a way to do it somehow (hint someone?), but if not; I would like to have the possibility to insert some lines of html into existing contents via a Suneditor button dropdown. Thus very similar to the Template button but not overwrite contents - instead insert it at cursor point.

**Comment by JiHong88** [comment]
Hi
This function has been tried a few times and has not been implemented yet.😔
Cannot receive cursor position at event object.
I will try again.

**Comment by MRB60** [comment]
I was not aware that it is hard to get cursor position. 
If any help, it would suffice if it would be possible to insert a html element (template code) before or after a (selected) paragraph/block.
If any help, here is a cursor pos [codepen](https://codepen.io/neoux/pen/OVzMor).

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by MRB60** [comment]
Thanks for implementing this!
Could you hint how this can be used to insert a few lines of html content via a my custom button menu (or existing template menu)?
