### ISSUE TITLE
Set default video height

### ISSUE THREAD

**Issue by tranchem** [JiHong88/SunEditor#305]
Hi
I want to set default video height in form insert video.
I can see option videoWidth but can't see videoHeight.
How to make it ?
![issue-video](https://user-images.githubusercontent.com/43035967/77999409-d53dbd00-735c-11ea-86d3-30f197f0d1eb.PNG)

**Comment by JiHong88** [comment]
Hi
There are currently no options to set.
I will add videoHeight and imageHeight options.

**Comment by JiHong88** [comment]
The [2.28.1](https://github.com/JiHong88/SunEditor/releases/tag/2.28.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
