### ISSUE TITLE
missing plugins when using plain javascript

### ISSUE THREAD

**Issue by rbartholomay** [JiHong88/SunEditor#306]
when using plain javascript and include the editor from the dist folder  suneditor.min.js i get an error:

Uncaught TypeError: Cannot read property 'modal' of undefined

It seems that the plugins are not available (in this case dialog). Must i include the additionally?

**Comment by JiHong88** [comment]
Hi
Did you create a custom plugin?

**Comment by rbartholomay** [comment]
after some debugging: It´s a timing problem in my ExtJS-Wrapper. Interesting behaviour...

Sorry for that...
