### ISSUE TITLE
Select tags disabled in custom plugin

### ISSUE THREAD

**Issue by aderaHenry** [JiHong88/SunEditor#308]
Hello @LeeJiHong . The issue #302 has not been solved in the latest release.

**Comment by JiHong88** [comment]
Hi
Can you show me your code?
HTML structure, code in "add" method.

**Comment by aderaHenry** [comment]
Here's the add method. I added jQuery UI for it's datepicker:

`import $ from 'jquery';
import 'jquery-ui/themes/base/all.css';
import 'jquery-ui/ui/widgets/datepicker';`

`add: function (core, targetElement) {

        // Registering a namespace for caching as a plugin name in the context object
        const context = core.context;
        context.custom = {
            textElement: null
        };

        // Generate submenu HTML
        // Always bind "core" when calling a plugin function
        let listDiv = this.setSubmenu.call(core);

        // Input tag caching
        context.custom.textElement = [...listDiv.getElementsByTagName('INPUT'), listDiv.getElementsByTagName('SELECT')[0]];

        // You must bind "core" object when registering an event.
        /** add event listeners */
        listDiv.getElementsByTagName('BUTTON')[0].addEventListener('click', this.onClick.bind(core));

        /** append html */
        targetElement.parentNode.appendChild(listDiv);

        $(function() {
            $("#datepicker").datepicker({
                onSelect: date => listDiv.querySelector('#duedate').value = date,
                dateFormat: 'DD, d MM, yy',
                changeMonth: true,
                changeYear: true
            });
        });
    },`

**Comment by JiHong88** [comment]
Please show me code in `this.setSubmenu`

**Comment by aderaHenry** [comment]
I have updated the comment to contain it

**Comment by JiHong88** [comment]
Is it working?

<img width="310" alt="스크린샷 2020-04-02 오후 9 15 57" src="https://user-images.githubusercontent.com/13191953/78248226-33b69700-7527-11ea-97b6-c3cc884ceeda.png">

**Comment by aderaHenry** [comment]
It's disabled @JiHong88 . is it working on your end?

**Comment by JiHong88** [comment]
Yead, It's working well.
<img width="512" alt="스크린샷 2020-04-02 오후 9 22 04" src="https://user-images.githubusercontent.com/13191953/78248678-10d8b280-7528-11ea-9c5c-2c84baf95576.png">

Um.. try remove the cache

**Comment by aderaHenry** [comment]
Okay. Trying now

**Comment by aderaHenry** [comment]
I've cleared cache. It's still disabled on my side

**Comment by JiHong88** [comment]
Did you update to v2.28.1?

**Comment by aderaHenry** [comment]
Use this for setSubmenu then show me the screenshot when you try changing the assignee:

```
setSubmenu: function () {
        const listDiv = this.util.createElement('DIV');

        let userOptions = '';
        const assigneables = [{name: 'JiHong'}, name: 'Henry']

        assigneables.map(user => userOptions += `<option value="${user.name}">${user.name}</option>`);

        listDiv.className = 'se-list-layer';
        listDiv.innerHTML = '' + 
            `<div class="se-list-inner se-list-align" style="width: auto;">
               <form class="se-submenu-form-group">
               <ul class="se-list-basic">
                   <li><div class="form-group form-material floating" data-plugin="formMaterial"><label class="form-control-label">Action</label><input class="form-control" type="text" style="width: 250px; border-bottom: none; text-transform: none;" /></div></li>
                   <li><div class="form-group form-material" data-plugin="formMaterial"><label class="form-control-label">Assignee</label><select class="form-control" style="width: 250px; border-bottom: none;">${userOptions}</select></div></li>
                   <li><div class="form-group form-material" data-plugin="formMaterial"><label class="form-control-label">Due date</label><input class="form-control" type="text" id="duedate" style="width: 250px; border-bottom: none; text-transform: none;" disabled /><div id="datepicker" style="margin: 5px;"></div></div></li>
                   <li><button type="button" class="se-btn se-tooltip" style="margin-top: 10px;">
                       <span>Done</span>
                       <span class="se-tooltip-inner">
                           <span class="se-tooltip-text">Append item</span>
                       </span>
                   </button></li>
               </ul> 
               </form>
            </div>`;

        return listDiv;
    }
```

**Comment by JiHong88** [comment]
<img width="283" alt="스크린샷 2020-04-02 오후 9 30 27" src="https://user-images.githubusercontent.com/13191953/78249382-36b28700-7529-11ea-83ea-91855449d1a4.png">
What browsers have you tested?

**Comment by aderaHenry** [comment]
@JiHong88 Let me clear all data then test. I'll close the issue if it works. Just now

**Comment by JiHong88** [comment]
OK, if that doesn't work, tell me more about the test environment.

**Comment by aderaHenry** [comment]
Sure thing @JiHong88

**Comment by aderaHenry** [comment]
@JiHong88 , I've tried everything I can. Cleared cache, cookies and browsing history, but they're still disabled. I've even used the new way outlined at [](http://suneditor.com/sample/html/customPlugins.html). See what I get:

![Screenshot 2020-04-02 at 18 25 06](https://user-images.githubusercontent.com/45875048/78267144-4e7d1180-750f-11ea-8fe1-fa5c83013b00.png)

I'm on macOS Catalina v10.15.3. I've tried with Firefox Developer edition v75.0b10 (64-bit), Google Chrome v80.0.3987.149 (Official Build) (64-bit) and Safari v13.0.5 (15608.5.11). The select tag is disabled.

**Comment by aderaHenry** [comment]
It works when I roll back to v2.24.0

**Comment by JiHong88** [comment]
@aderaHenry 
Try adding the 'se-submenu' class to the submenu.
```javascript
setSubmenu: function () {
        const listDiv = this.util.createElement('DIV');

        listDiv.className = 'se-submenu ...';
```

**Comment by JiHong88** [comment]
Can you show the whole plugin code and the editor creation part?

**Comment by aderaHenry** [comment]
Hello @JiHong88 . The problem was actually in my build process. Version 2.28.1 is very okay. My bad.

**Comment by JiHong88** [comment]
@aderaHenry 

Update to version 2.28.2.
You can improve your code like this:
```javascript
onClick: function () {
...
// rendering
// const template = this.util.createElement('DIV');
// template.innerHTML = data;

// // insert
// const children = template.children;
// let after, child;
// while (children[0]) {
//     child = children[0];
//     this.insertNode(child, after);
//     after = child;
// }
// this.setRange(after, 1, after, 1);
->
this.functions.insertHTML(data)
...
}
```

**Comment by aderaHenry** [comment]
> @aderaHenry
> 
> Update to version 2.28.2.
> You can improve your code like this:
> 
> ```js
> onClick: function () {
> ...
> // rendering
> // const template = this.util.createElement('DIV');
> // template.innerHTML = data;
> 
> // // insert
> // const children = template.children;
> // let after, child;
> // while (children[0]) {
> //     child = children[0];
> //     this.insertNode(child, after);
> //     after = child;
> // }
> // this.setRange(after, 1, after, 1);
> ->
> this.functions.insertHTML(data)
> ...
> }
> ```

A very clean solution @JiHong88 !
