### ISSUE TITLE
Feature Request - Add Image Caption

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#31]
It would be nice to be able to provide a caption for images that are inserted. The caption would need to be part of the image area, as shown below.

You'll need to click the image to see a larger version, sorry.

![image caption](https://user-images.githubusercontent.com/13341574/38647878-7e0ed76c-3dbc-11e8-8299-9afcbdfae990.png)

I'm not sure of my availability, but I might be able to implement this, if you're accepting pull requests?

**Comment by JiHong88** [comment]
Yup, that's a good feature.

I will accept your pull request!

Thanks : )

**Comment by CMTietgen** [comment]
Sadly, it doesn't look like I will have time to work on this PR.

**Comment by JiHong88** [comment]
Yup, that's ok

Thank you for giving me your idea.

I will start working on this PR : )

**Comment by JiHong88** [comment]
Hi,

I have fixed this Feature Request : )
