### ISSUE TITLE
Bug: When you add an image to the editor, it displaces the image and under a different set of elements.

### ISSUE THREAD

**Issue by ZoltanAtFlyte** [JiHong88/SunEditor#312]
The steps to reproduce.
1. I created the editor
2. With no text present in the editor AND without focusing on the editor, I inserted an image.
3. The image was misplaced into my sidebar on the left hand side of the page.

More information (sorry)
My settings included all the plugins (provided with the import plugins from '{path}' code that the documentation provided.

```      
plugins: plugins,
        buttonList: [
            ['undo', 'redo'],
            ['font', 'fontSize', 'formatBlock'],
            ['paragraphStyle', 'blockquote'],
            ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
            ['fontColor', 'hiliteColor', 'textStyle'],
            ['removeFormat'],
            // '/', // Line break
            ['outdent', 'indent'],
            ['align', 'horizontalRule', 'list', 'lineHeight'],
            ['table', 'link', 'image', 'video', /** 'math' */], // You must add the 'katex' library at options to use the 'math' plugin.
            ['fullScreen', 'showBlocks', 'codeView'],
            ['preview', 'print'],
        ],
        width:"100%",
        height:"200px",
        showPathLabel: false,
        imageFileInput : false,
        imageWidth: "300px",
        imageHeight: "300px",
```

![image](https://user-images.githubusercontent.com/53495572/78460352-17813a00-768e-11ea-81ca-4313998dc900.png)

Edit 2: The bug does not seem to reproduce if I select any direction other than 'basic' 

Edit 3: Upon further experimentation, it seems to happen when there is no focus on the editor itself. It seems to replace an existing image / icon I have on the left side nav

**Comment by JiHong88** [comment]
@ZoltanAtFlyte 
The issue is not reproduced.
What browser have you tested and editor version?

**Comment by JiHong88** [comment]
The [2.28.3](https://github.com/JiHong88/SunEditor/releases/tag/2.28.3) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
