### ISSUE TITLE
Bug: Resizing an image in a height constrained editor causes the image resizing selection to overflow.

### ISSUE THREAD

**Issue by ZoltanAtFlyte** [JiHong88/SunEditor#313]
In order to replicate this issue, I simply added an image that was larger than the height constrained in the settings (200px) 

That image in question is 300x300

The overflow covers other content on the screen.

![image](https://user-images.githubusercontent.com/53495572/78460417-c6257a80-768e-11ea-904e-f2cecb1353c3.png)

**Comment by JiHong88** [comment]
Hi @ZoltanAtFlyte 
I'll modify z-index of the resizing div, so it's positioned above the toolbar.
I'll leave the issues related to overflow untouched.
Thank you!

**Comment by JiHong88** [comment]
The [2.28.3](https://github.com/JiHong88/SunEditor/releases/tag/2.28.3) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
