### ISSUE TITLE
onBlur invoked while adding line before/after table

### ISSUE THREAD

**Issue by tswistak** [JiHong88/SunEditor#318]
Hi!

Great work with fixing all those bugs :) . I've found out a small issue connected with onBlur and new functionality of adding lines before and after table. When user clicks on the button, it invokes onBlur. I think it shouldn't since we're still in editor context.
Take a look into GIF with this:
![suneditor_blur](https://user-images.githubusercontent.com/9076255/78530817-a1dbb200-77e4-11ea-8f6d-e8bdb1e56da1.gif)
Codesandbox with reproduction: https://codesandbox.io/s/suneditor-onblur-table-p51p7

Cheers!

**Comment by JiHong88** [comment]
The [2.28.4](https://github.com/JiHong88/SunEditor/releases/tag/2.28.4) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
