### ISSUE TITLE
Feature Request - Copy/Paste Images

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#32]
I've seen this in other editors, but it doesn't appear to be an option for SunEditor.

Having the ability to copy an image from some image editor app and paste it into SunEditor at the cursor position would be awesome.

This could be done as some sort of plugin, if SunEditor supports plugins?

**Comment by JiHong88** [comment]
You can still paste the image at the current cursor position.

Does that mean you have to provide this as an option?

**Comment by CMTietgen** [comment]
I can copy an image off the internet and paste at the cursor location, but it I save that image to my drive, open it in a program like Paint.NET and make changes, then select the image and copy it to the clipboard I can't paste it into the editor.

Ideally, the editor should almost work like an image upload drop zone. When I paste an image at the cursor using the above method, it should upload the image to the server, or base64 encode it, then insert it at the cursor location.

This is how editors like CKEditor and TinyMCE work.

**Comment by JiHong88** [comment]
Hi~

Thanks for pointing out.

I uploaded it : )
