### ISSUE TITLE
want to add whiteboard into this editor 

### ISSUE THREAD

**Issue by ngcgolf11** [JiHong88/SunEditor#322]
want to intigrate few things into this editor please guide me 
1. first one is sketch functionality for this http://literallycanvas.com/
2. second mention features for users

Please help me in that 
I am also working on upgrading katex with full mathjax support 

thanks in advance.

**Comment by JiHong88** [comment]
Hi @ngcgolf11 
 1. How do you want to use the sketch function?
 2. You can refer to [commandPlugin](http://suneditor.com/sample/html/customPlugins.html#command)
     Buttons are not required.
     And Yoou can use [events](http://suneditor.com/sample/html/out/document-user.html)

**Comment by ngcgolf11** [comment]
when i user click on sketch button it will open a popup and user can draw there and then editor can save all the data in editor area

**Comment by JiHong88** [comment]
@ngcgolf11 I am sorry for the late reply.
I wanted to reply after the test, but it seems to be too much work. :(
Content created in "literallycanvas" can be put into the editor using [insertHTML](http://suneditor.com/sample/html/out/document-user.html#insertHTML), etc.
Please refer to [commandPlugin](http://suneditor.com/sample/html/customPlugins.html#command) for how to create a plugin.
Sorry for not helping a lot.

**Comment by ghilasjku** [comment]
@ngcgolf11 i also want to integrate MathJax to suneditor, did you make some progress ?
