### ISSUE TITLE
Table header bold text

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#324]
Hello,

thanks for fast fixing bugs. I've noticed another bug. Steps to reproduce:

- create/paste table
- add header
- try to **bold**/unbold text in header - it's not working but button is visible and can be selected/unselected

Example: [https://i.imgur.com/4PyeNmK.gifv](https://i.imgur.com/4PyeNmK.gifv)

Regards,
Adrian

**Comment by JiHong88** [comment]
Hi
Did you checked a element?
<img width="284" alt="스크린샷 2020-04-09 오후 6 15 14" src="https://user-images.githubusercontent.com/13191953/78878925-24d36580-7a8e-11ea-8a0b-e600cebfb057.png">
The default style value of th tag is "font-weight: bold ".
So even if the "strong" tag is applied, it may not change at looks.
