### ISSUE TITLE
Underline color different than text color

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#326]
Hi! 

I hope You are safe and healthy. I've found another minor issue but It would be great to have it fixed :)

![image](https://user-images.githubusercontent.com/1231703/78972288-b2a26580-7b0d-11ea-9215-6cf49c5ff833.png)

**Comment by JiHong88** [comment]
Hi
New nodes are added over the existing nodes.
`<span>test</span>` -> `<u><span>test</span></u>`
So, the existing span tag styles is not applied to the underline tag.

If you want to color to the `<u>`, you should try changing the color once more.
A new `<span>` is added and nodes with the same conditions are deleted.
`<u><span>test</span></u>` -> `<span><u>test</u></span>`

I'll not change this behavior.
The same problem occurs in the opposite case even if put a **new node inside**.
`<u>test</u>` -> `<u><span>test</span></u>`

And only part of the text may have a `<span>`.
`te<span>s</span>t` -> `<u>te<span>s</span>t</u>`

Thank you.

**Comment by natanielcz** [comment]
Thanks. Seems reasonable
