### ISSUE TITLE
Table content disappearing after changing formatting

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#327]
Hi, 

We've found another issue. 

Steps to reproduce:
1. copy&paste table from Word (don't select it via Ctrl+A just select it with your mouse)
2. click ctrl+A in SunEditor
3. change color twice

Effect: data in table disappers
Expected result: table data are formatted

![APDDiVEZ0u](https://user-images.githubusercontent.com/1231703/78984892-b04d0500-7b27-11ea-9c07-629f05e2f558.gif)

**Comment by natanielcz** [comment]
Hi @JiHong88,

Did you make any progress with this bug? Unfortunately It'saffecting me and I wonder that you could release version 2.28.5.

**Comment by JiHong88** [comment]
I'll release the 2.29.0 version this week or later next week.
Please wait a little longer.

**Comment by natanielcz** [comment]
Great! Thanks :)

**Comment by natanielcz** [comment]
Hi, when can we expect next version?

**Comment by JiHong88** [comment]
Today, It will be update.

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
