### ISSUE TITLE
Toolbar disappears for tables from e-mail

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#330]
Hi,

Just to remember about this bug (visible also on gif in #327 )

Steps to reproduce:
1. Copy a table from e-mail & paste it to SunEditor
2. Select all with Ctrl+A
3. Change table formatting (toolbar is disappearing)

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
