### ISSUE TITLE
Editor is trimming empty lines before a table

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#331]
Hi,

please take a look at the gif below.

Affected browsers: Google Chrome, Microsoft Edge (version with Blink engine)

![UcAJj4XLHQ](https://user-images.githubusercontent.com/1231703/79217596-67f75500-7e4f-11ea-9e2c-3604d140c0a2.gif)

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
