### ISSUE TITLE
Customize imageUploadUrl request format

### ISSUE THREAD

**Issue by wacilpong** [JiHong88/SunEditor#332]
안녕하세요.

suneditor를 굉장히 잘 사용하고 있는데요. 질문이 하나 있어 이슈 납깁니다.
혹시 imageUploadUrl을 지정하여 API 요청을 보낼 때, request format에 대해서는 수정할 수 없을까요? 예를 들면 현재는 파일을 담은 form data의 키 이름이 기본적으로 `file-0`의 형식으로 들어가는데, 이를 `images`라는 이름으로 바꾸고 싶거든요.

혹은 우회해서라도 가능한 방법이 있다면 알려주시면 감사하겠습니다!

**Comment by JiHong88** [comment]
안녕하세요

현재는 이미지 플러그인의 `submitAction` 메소드를 재정의해서 사용하는 방법밖에 없습니다.
[image.js#L264](https://github.com/JiHong88/SunEditor/blob/master/src/plugins/dialog/image.js#L264)
[image.js#L319](https://github.com/JiHong88/SunEditor/blob/master/src/plugins/dialog/image.js#L319)
```javascript
core.plugins.image.submitAction = function ()...
```

하지만 이렇게 했을땐 버전이 업데이트 되면서 수정되는 코드를 반영해줘야 하는 번거로움도 있고,
추천드리지는 않습니다.
`images` 라는 이름으로 바꾸는 이유는 무엇인가요?

**Comment by wacilpong** [comment]
아아 이미지를 업로드할 때 base64대신 서버로 한번 요청을 보내서 가져온 url로 이미지태그의 src를 교체하려고 했고, 서버를 수정할 수 없는 상황이어서, images라는 이름으로 formData를 보내야 했거든요.

그런데 혼자 좀 해보니까 `onImageUploadBefore`에서 파일을 core 객체에 커스텀 프로퍼티로 임시 저장해두고, `onImageUpload`에서 core에 저장해둔 파일을 꺼내서 API로 보낸 후 가져온 url을 `update_src`하는 방식으로 구현했습니다!

답변 감사드립니다 :)

**Comment by JiHong88** [comment]
음.. base64 로 이미지를 넣고 다시 서버에 업로드한 url 로 이미지의 src 를 교체한다는 말인가요?

**Comment by wacilpong** [comment]
사실 이미지를 업로드할 때부터, 그 이미지를 서버로 업로드한 url로 바꾼 후 이 url을 src로 넣고 싶은데, 방법을 모르겠어서 `onImageUpload`에서 교체하는 방식으로 구현했습니다!

혹시 다른 좋은 방법이 있을까요!?

**Comment by JiHong88** [comment]
`imageUploadUrl' 이란 옵션이 있습니다.
여기 업로드 url 을 넣고 정의된 형식되로 response 를 보내면 업로드된 이미지를 만들 수 있습니다.
[options](https://github.com/JiHong88/SunEditor#options) 를 참고 해주세요.

**Comment by wacilpong** [comment]
아 네네 그 옵션을 이용해보려고 했는데 요청할 때 formData 키 이름을 `images`로 지정해야 하는 상황이어서 이슈 남긴 것입니다 ㅠㅠ 서버를 건드릴 수 없는 상황이거든요.

`imageUploadUrl` 옵션을 이용하면서 formData 키이름을 바꾸려면 위에 알려주신 방법밖에 없는 것이 맞죠?

```javascript
core.plugins.image.submitAction = function ()...
```

**Comment by JiHong88** [comment]
그렇군요..
네 지금은 그 방법밖에 없습니다.

**Comment by wacilpong** [comment]
ㅠㅠ 알겠습니다
답변 감사드리고 이슈는 닫겠습니다.

수고많으십니다. 👍
