### ISSUE TITLE
Unable to cut/delete table in Firefox

### ISSUE THREAD

**Issue by natanielcz** [JiHong88/SunEditor#333]
Description: After cutting/deleting a table in Firefox, a table with empty cells remains.

Affected browsers: Firefox

sandbox: https://codesandbox.io/s/suneditor-remove-table-in-firefox-z62op

**Comment by JiHong88** [comment]
Hi
Thanks for reporting the bug.
This is a known bug, but it is too difficult to fix.
It may take time. :(

**Comment by natanielcz** [comment]
Sure. Do You have any ideas what may be the reason of this issue?

**Comment by JiHong88** [comment]
It seems to be the behavior of the Firefox engine.
When the selection is in the table, it seems to be necessary to delete the table directly in the editor.

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
