### ISSUE TITLE
Adding autolink URLs in the editor on paste and while typing

### ISSUE THREAD

**Issue by soulcurrymedia** [JiHong88/SunEditor#334]
Hi @JiHong88 

I'm trying to add AutoLink feature in the Editor using events, so URL are autolink as the type or paste -- the content from Word or Text editor which has URLs. I've shortlisted this npm package http://alexcorvi.github.io/anchorme.js/ 

However replacing the contents of the editor will reset the cursor position. I think this could work if the cursor position can be retained. How the other RTE does the auto-linking?

and lastly two more things 
1. Can we enable autosave to update the TextArea as the content is updated?
2. I've multiple RTE boxes on the page, how I could have one global event listener for all of them. Currently I need to setup the event for each Editor instance?

Thanks
Lalit

**Comment by JiHong88** [comment]
Hi @soulcurrymedia 

How are you changing the content of the editor from outside?
Are you changing the contents of the editor using "setContents"?

> and lastly two more things

You must set the "onChange" event for each editor.
```javascript
const editor = suneditor.create(...)
editr.onChange = function (contents, core) {
    core.functions.save();
    // or
    editor.save();
}
```
