### ISSUE TITLE
Line break in code view

### ISSUE THREAD

**Issue by larand01** [JiHong88/SunEditor#338]
Line breaks in code view are deleted instead of replacing it with a blank space.

Example:
<p>Two
words</p>

Result:
Twowords

**Comment by JiHong88** [comment]
Hi @larand01 
The issue is not reproduced.
Please show me a more accurate test method.

**Comment by larand01** [comment]
I'm sorry I just saw that my example shows nothing. 

Between "Two" and "words" it's a line break and there's no space.

`<p>Two`
`words</p>`

Actually the problem occurs when I paste some text from MS Word. Some spaces (between words) get lost. They had the same problem in textAngular and it's well described :
https://github.com/textAngular/textAngular/issues/598

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
