### ISSUE TITLE
Words don't break correctly in blockquote, in almost every tags when using preview and print functions

### ISSUE THREAD

**Issue by ducatrinh** [JiHong88/SunEditor#340]
Word break should be set to 'normal' instead of 'break-all'

.sun-editor-editable {
  word-break: normal;
}

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
