### ISSUE TITLE
[Feature request] stickyToolbar optionally relative to an optional container

### ISSUE THREAD

**Issue by madarche** [JiHong88/SunEditor#342]
At the moment the `stickyToolbar` option sets the sticky toolbar relative to the top and this works great 😀

It would be a nice option to SunEditor if it could be possible to optionally set the sticky toolbar relative to another container.

Some other editors have this option:
* https://froala.com/wysiwyg-editor/docs/options/#toolbarContainer
* https://froala.com/wysiwyg-editor/docs/options/#toolbarSticky

Would it be possible?

**Comment by JiHong88** [comment]
Is it a option that causes the toolbar to be created in a separate element from the editor?

**Comment by madarche** [comment]
Thanks @JiHong88 we'll be testing the new version and I'll report here! Thanks again!

**Comment by madarche** [comment]
@JiHong88 I confirm, if a bit late, that the `toolbarContainer` option is great! Thanks a lot!
