### ISSUE TITLE
[Feature request] Option to disable TAB

### ISSUE THREAD

**Issue by madarche** [JiHong88/SunEditor#343]
It would be a nice option to SunEditor if it could be possible to optionally disable TAB.

Some other editors have this option:

* https://summernote.org/deep-dive/#disable-tab

Would it be possible?

**Comment by JiHong88** [comment]
Hi @madarche 
Thank you for a good idea. :)
I'll add it to the next version.

**Comment by madarche** [comment]
Nice @JiHong88 😀

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by madarche** [comment]
A very big thank you @JiHong88! Thanks a lot for this feature. We'll test this release very fast!

**Comment by madarche** [comment]
@JiHong88 please see #370 for both feedback on the new `tabDisable` option and a potential improvement. Thanks!
