### ISSUE TITLE
IE 11 이미지 복사

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#345]
안녕하세요~ 
전에 IE에서 이미지 복사해서 붙여넣기하면 없어지는 이슈 수정해주셔서 잘되는거 확인했습니다.
다만, 뉴스에 글처럼 이미지+본문글을 같이 복사 붙여넣기하면 글이사라지는 현상이 생기는거 같습니다.

**Comment by JiHong88** [comment]
안녕하세요
이슈가 재현되지 않는데 복사 붙여넣기 했을때 글이사라지는 사이트 샘플이 있을까요?

**Comment by kimhyeongyu** [comment]
https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=055&aid=0000809747&viewType=pc

본문내용 글 + 이미지 복사 후 에디터에 붙여넣기

여러 브라우저에서 테스트 중인데 IE에서만 발생하는거같습니다.

전  IE11에서 테스트 했습니다.

**Comment by rafael-develop** [comment]
안녕하세요.

**Comment by JiHong88** [comment]
[2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) 버전이 업데이트 되었습니다.
문제가 해결되지 않은경우 이 이슈를 다시 열어주세요.
감사합니다.
