### ISSUE TITLE
nodeChange method have a bug

### ISSUE THREAD

**Issue by basecss** [JiHong88/SunEditor#346]
https://github.com/JiHong88/SunEditor/blob/fffc96f7dc69abae2311b15e8bcd37b0d36b3410/src/lib/core.js#L2149

`className.trim()` don't compatible with SVG element.

The `className` for SVG element will has `baseVal` / `animVal`.

**Comment by JiHong88** [comment]
Hi
The "svg" element is not called in the "[validation](https://github.com/JiHong88/SunEditor/blob/fffc96f7dc69abae2311b15e8bcd37b0d36b3410/src/lib/core.js#L2100)" function.
It is filtered first in the "[util._isIgnoreNodeChange](https://github.com/JiHong88/SunEditor/blob/fffc96f7dc69abae2311b15e8bcd37b0d36b3410/src/lib/util.js#L1461)" method.
Is an error occurring during use?
