### ISSUE TITLE
setOptions imageFileInput as false, editor create get error.

### ISSUE THREAD

**Issue by wxjzeke** [JiHong88/SunEditor#347]
```js
SUNEDITOR.create('example', {
  buttonList: [
    [
      'image'
    ]
  ],
  imageFileInput: false
})
```
=> `Uncaught TypeError: Cannot read property 'addEventListener' of null`

and the image upload dialog can not open.

**Comment by JiHong88** [comment]
Hi @wxjzeke 
This bug is fixed.
I'll notify you when version is update.

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
