### ISSUE TITLE
Image alignment  of exported content is not working.

### ISSUE THREAD

**Issue by wxjzeke** [JiHong88/SunEditor#348]
#### In editor:
![image](https://user-images.githubusercontent.com/8022227/80175259-ac40dd00-8627-11ea-9297-3b9aecd91c83.png)

#### Exported content rendering in somewhere else:
![image](https://user-images.githubusercontent.com/8022227/80175437-2b361580-8628-11ea-8c6d-8e15e9530015.png)

**Comment by JiHong88** [comment]
Hi,
The issue is not reproduced.
Isn't the registered image aligned in the center?

**Comment by wxjzeke** [comment]
Hi, sorry for the lately reply.
I check the code that align right,  and everything looks fine in editor.
![image](https://user-images.githubusercontent.com/8022227/81136091-20b33e80-8f8d-11ea-9a79-199f94629e72.png)



But the exported string would like below
```js
"<div class="se-component se-image-container __se__float-right"contenteditable="false"><figure style="margin: auto;"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."alt=""data-rotate=""data-proportion="true"data-rotatex=""data-rotatey=""data-size=","data-align="right"data-percentage="auto,auto"data-file-name="SqlJoins.png"data-file-size="162672"origin-size="0,0"data-origin=","style=""data-index="0"></figure></div>"
```


when I render this string in somewhere else, the alignment would not work.

**Comment by JiHong88** [comment]
[suneditor-contents.css](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css) or [suneditor.min.css](https://github.com/JiHong88/SunEditor/blob/master/dist/css/suneditor.min.css) is required for content created in the editor.
And the content should be in the `sun-editor-editable` class.

**Comment by f2016862** [comment]
Here is the reproduced issue.
https://www.loom.com/share/b971c3b60f7045e495fb11dab5418728

**Comment by mikaelkadga** [comment]
hi, i am also facing this problem, can anyone help me? should i include the suneditor-contents.css or suneditor.min.css in the platform that rendered it? (like in my react native app)
