### ISSUE TITLE
Question: upload image to server at drag/drop

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#349]
Again, thanks for your great work here!
When an image is dragged and dropped into editor window, it always get inline base64 encoded. I need to have it sent to server instead (contents gets too large with base64). 
It works fine with the image plugin, but not at drag/drop. Do you have any guideline on how I can achieve this also for images inserted with drag/drop? 
onImageUpload() gets called but e.g. not onImageUploadBefore(). I set imageUploadUrl but see nothing sent to server at drag/drop.

**Comment by JiHong88** [comment]
Hi,
The issue is not reproduced.
Image drop and dialog popup action are call same methods.
Are the plugin and drag/drop behavior different in the same editor?

**Comment by MRB60** [comment]
I did a mistake and did a drag/drop on images in Google Search images result - these thumbs are themselves base64 encoded - so no surprise they get base64 encoded in Suneditor - now I just need to prohibit this somehow (hint?).
Suneditor either uploads images (e.g. drag/drop via file manager) or link the url if drag/drop, copy/paste on most web pages. All fine.

**Comment by JiHong88** [comment]
I'll adjust the timing the "onDrop" user event to called before excuting the editor action.
You can use it like the current "onPaste" event.

**Comment by MRB60** [comment]
Thanks!
Here is an example how a drop event (here only string: text/html) can be checked to prohibit base64 encoded drop in onDrop():
```
for (let i = 0; i < ev.dataTransfer.items.length; i++) {
   if (ev.dataTransfer.items[i].kind === 'string' && ev.dataTransfer.items[i].type === 'text/html') {
      ev.dataTransfer.items[i].getAsString(function (s) {
         if (s.includes('<img') && s.includes('base64')) {
            alert ("Error: image type not supported");
            return false;
         } else if (s.length > 2047) {
            alert ("Error: Drop element too large");
            return false;
         }
      });
   }
}
```

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
