### ISSUE TITLE
Beautiful line break

### ISSUE THREAD

**Issue by AkioSarkiz** [JiHong88/SunEditor#352]
How to make a beautiful line break? Now the words are spelled, I'm trying to do it according to the words. Example
Before:
![Image of Yaktocat](https://i.ibb.co/kX33GxB/38.png)
After:
![Image of Yaktocat](https://i.ibb.co/xsN1tY6/39.png)

**Comment by ethanyu94** [comment]
Try setDefaultStyle("word-beak: unset;")

**Comment by AkioSarkiz** [comment]
Tried to
![image](https://i.ibb.co/JnzXqKh/40.png)

**Comment by JiHong88** [comment]
Hi @AkioSarkiz 

Try it
```javascript
suneditor.create('..', {
    defaultStyle: 'word-wrap: normal;'
})
```

**Comment by AkioSarkiz** [comment]
@JiHong88
Tried to
![image](https://i.ibb.co/TwCPKMr/20.png)

**Comment by JiHong88** [comment]
@AkioSarkiz 

<img width="532" alt="스크린샷 2020-05-01 오후 3 47 13" src="https://user-images.githubusercontent.com/13191953/80788034-10811500-8bc3-11ea-95d6-6babd980081f.png">

Did you copy and paste words with spaces?
If so, the space is copied by "\&nbsp;" 

ex) `wording\&nbsp;wording\&nbsp;wording\&nbsp;...`
The above text are recognized as one word.
It is separated by a space and does not wrap.
Test it by typing it yourself.

**Comment by AkioSarkiz** [comment]
No, I didn't copy the text. Here's a video of me typing and the words aren't transferred to the new line. 
https://youtu.be/nIDS8PnA-_o
I also turned off app.css to check, but that didn't help either.

**Comment by JiHong88** [comment]
Hi @AkioSarkiz 

Sorry for the late reply.
Modify css like below:
```css
word-break: normal;
word-wrap: break-word;
```

**Comment by AkioSarkiz** [comment]
Thanks!
