### ISSUE TITLE
Inserting image with height/width thru insertHTML() method resize automatically

### ISSUE THREAD

**Issue by chagonzles** [JiHong88/SunEditor#353]
Hi, 

Is there a way to insert images thru `.insertHTML()` method with size indicated like `<img height="100" width="100" src="..." />` ? 

Right now when I tried to insert image with height/width indicated it still auto resize. 

Thank you.

**Comment by JiHong88** [comment]
Hi,
The inserted tag has the attributes removed according to the "whitelist" of option.
If you give the second argument value of  `.insertHTML` true, html clean will not work.
And please specify the size in style.
```javascript
.insertHTML('<img style="height:100px; width:100px;" src="..." />', true)
```

**Comment by chagonzles** [comment]
> ```js
> style="height:100px; width:100px;"
> ```

I did try to add `.insertHTML('<img style="height:100px; width:100px;" src="..." />', true)` 
it's inserting the image with the indicated size but then it resets to its original/auto size. 
perhaps i need to add the attributes in the whitelist option? can you provide an example?

**Comment by JiHong88** [comment]
Sorry, the "auto" size is being set while re-creating the image format.
It will be fixed once a new version is released this week.
We will let you know when the version is updated.

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
