### ISSUE TITLE
Feature request: table cell editing options in the toolbar instead of inline

### ISSUE THREAD

**Issue by pjpauwels** [JiHong88/SunEditor#355]
In my use-case the user does not work with complex tables and the editing options, when clicking in a cell, are covering other cells making it hard to select them quickly.

Adding a feature flag or display mode to move those buttons into the toolbar (when inside a table) instead of inline would keep the editing field clean and easy to navigate while keeping the features those buttons provide.

![table-toolbar](https://user-images.githubusercontent.com/1911277/80481779-6a7ba380-8953-11ea-9e84-bb5865a0206f.png)

**Comment by JiHong88** [comment]
Hi @pjpauwels 
It is difficult and not intuitive to move the table controller to the toolbar.
I'll add an option to choose whether to use a controller to edit table cells.

**Comment by pjpauwels** [comment]
Thank you for the quick response and solution. Though I am not sure this option will cover our needs. If I understand it correctly the user will have no option to add rows any longer with this option enabled?

**Comment by JiHong88** [comment]
Hi,
I made a mistake.
I'll not add the option to not edit the cell.
Instead, we will add an option to specify the location of the cell editing controller. ('top', 'cell')

**Comment by JiHong88** [comment]
The [2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
