### ISSUE TITLE
zeroWidthSpace cause strange string on click in formatter (like bolt)

### ISSUE THREAD

**Issue by cristianandreon** [JiHong88/SunEditor#356]
zeroWidthSpace: "​" : Doesn't work

zeroWidthSpace:'\u200b', : is OK

**Comment by JiHong88** [comment]
Hi @cristianandreon 
I don't understand the question.
Currently zeroWidthSpace is "\u200b" [util.js#L48](https://github.com/JiHong88/SunEditor/blob/master/src/lib/util.js#L48)

**Comment by cristianandreon** [comment]
Hi JiHong88
Look in **SunEditor/dist/suneditor.min.js** : for unknown reason it's set to ""
If you beautify the code (https://beautifier.io/) you see cleary it .. (or just search the set code)

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
