### ISSUE TITLE
Context Menu Implementation

### ISSUE THREAD

**Issue by Megamind2301** [JiHong88/SunEditor#359]
Hi,
I have integrated **SunEditor** in my react project. I need to implement custom context menu on right click. But there is no event handler for the same (Neither **onMouseDown** nor **onContextMenu**).
Can it be implemented manually, if need be?

**Comment by JiHong88** [comment]
Hi @Megamind2301 

You can use the [onMouseDown](http://suneditor.com/sample/html/out/document-user.html#onMouseDown) or [onClick](http://suneditor.com/sample/html/out/document-user.html#onClick).
And it may be helpful to refer to the code in [submenuOn](https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L464) and [controllersOn](https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L582).

```javascript
const editor = suneditor.create(..);
editor.onMouseDown = function (e, core) {
  core.controllersOff();
  // Edit contextMenuDiv
  const menu;
  core.controllersOn(menu);
}
```
```
