### ISSUE TITLE
Paste image not working in IE 11 and remove image when browser resize

### ISSUE THREAD

**Issue by rafael-develop** [JiHong88/SunEditor#362]
안녕하세요.
IE11에서 이미지 붙여 넣기 시 , 마우스 우클릭-붙여넣기 할 경우, 정상 표현되나
Ctrl+v를 통해 붙여넣기 할 경우, 이미지가 사라지는 현상이 발생합니다.
또한 브라우저(크롬, IE11) resize 시, 붙여넣기 한 이미지가 사라집니다.
해당 현상 관련 이미 해결된 이슈 인가요? 확인 부탁 드립니다.
감사합니다.

**Comment by JiHong88** [comment]
안녕하세요.
해당 이슈는 수정되었습니다.
오늘 버전 업데이트 후에 알려드리겠습니다.

**Comment by JiHong88** [comment]
[2.29.0](https://github.com/JiHong88/SunEditor/releases/tag/2.29.0) 버전이 업데이트 되었습니다.
문제가 해결되지 않은경우 이 이슈를 다시 열어주세요.
감사합니다.
