### ISSUE TITLE
How to pass content to php page?

### ISSUE THREAD

**Issue by eliyahu-shmuel** [JiHong88/SunEditor#366]
Hi!
I have a form with the editor and I want add button that will send content on clicking to php page, when I try send via post method, if I insert an image my php return error because the uri of image very large....
IF someone can help me I will be happy:)

**Comment by MRB60** [comment]
Web servers has a default upload size limit - aorund 1-2MB. php also has a default max limit - 2MB. Why is URI large - is image base64 encoded inline?

**Comment by eliyahu-shmuel** [comment]
@MRB60 beacuse when uploaded imgae he send to my php uri with 243,000 charecters(!),
ny php close connection.

**Comment by Datyriam** [comment]
Looking through the code of dialog/image.js, you'll have to set the imageUploadUrl, or upload the images elsewhere and reference them in suneditor with the "Image Url" under Insert Image 
- if imageUploadUrl is unset (aka, its default value null, or it is not a string, or is an empty string), it defaults to returning a base64 rendition of the image, which will indeed easily pass that character count.

**Comment by eliyahu-shmuel** [comment]
@Datyriam Thank you, but can you please help me how can I make uploader?
I'm using PHP.
I'v code for get image uri and save image but that can't help me (too large string of uri...)
Here mu simple code that cant help me:(
```
`$data = $_POST['data'];
$email = $_POST['email'];
//echo $data;

$imgData = str_replace(' ','+',$data);
$imgData =  substr($imgData,strpos($imgData,",")+1);
$imgData = base64_decode($imgData);
// Path where the image is going to be saved
$filePath = '/home/barakdoc/fileUploads/'.$email;
if (!file_exists($filePath)) {
    mkdir($filePath, 0777, true);
}
$filePath.='/singture.png';
// Write $imgData into the image file
$file = fopen($filePath, 'w');
fwrite($file, $imgData);
fclose($file);`
```
