### ISSUE TITLE
Serious mobile view problems - near 0 editing space

### ISSUE THREAD

**Issue by vanillamasonry** [JiHong88/SunEditor#368]
The buttons and the toolbars are too big, The editor is useless for mobile apps and sites. You must find another solution. The current solution is OK for desktop and tablets

And another problem... the android selection prompt do not disappear after selection... see the red circle form screenshot.

![Screenshot_20200510-030135](https://user-images.githubusercontent.com/2625401/81494891-0e712300-9261-11ea-8414-e5e0cfc15f13.png)

Visiting your website 5.2 inch phone  - No real space to edit 

![Screenshot_20200510-123315](https://user-images.githubusercontent.com/2625401/81496035-788dc600-9269-11ea-846b-7f92a1e0ff47.jpg)

And another screenshot from a larger phone 6.7 inch

![Screenshot_2020-05-10-12-15-57-661_com android chrome](https://user-images.githubusercontent.com/2625401/81495487-6f9af580-9265-11ea-91dc-beee00891edf.jpg)

You must add an icon version for font type, font size, paragraph and use only ONE toolbar with a popup button  - toolbox  for the rest of buttons may be something like this:

![Figure-1_The-Toolbox-menu-always-available-in-the-Mac-menu-bar](https://user-images.githubusercontent.com/2625401/81488339-5cb00300-921c-11ea-8d86-487ca77f87a8.png)

another solution from CKEditor 

![Screenshot_2020-05-10-13-41-45-957_com android chrome](https://user-images.githubusercontent.com/2625401/81497076-f43f4100-9270-11ea-91a9-5f60e5296df9.jpg)

or even better look at Microsoft word for mobile/desktop that combine tabs and toolbars. I think that is the best solution (elegant, professional, space saving) for mobile, desktop, and the inline editor when you want more buttons/options.

![word-mobile-dead](https://user-images.githubusercontent.com/2625401/81494241-298d6400-925c-11ea-8fb7-bc5aae72596b.jpg)

I hope that the next version will be usable for mobile apps / websites. On the other hand excepting this bug (prompt bug) and design problems ... you have done a very good job.

Thank you in advance,
Paul

**Comment by JiHong88** [comment]
Hi, @vanillamasonry 
Thank you for your interest in this project!

1. Focus:
The editor's cursor disappears only when the editor loses focus.
It is a bad practice to lose focus whenever the editor clicks a button on the toolbar.
And whenever the editor loses focus, the input area at the bottom will disappear.
As a result, each time the button on the toolbar is clicked, the input area at the bottom disappears and reappears.
This is a bad experience for the user.

2. Toolbar buttons:
I agree with your opinion.
Currently you can define a container plugin, but it is very lacking.
In the next version, I'll improve the responsive and button layout.

Thank you.

**Comment by vanillamasonry** [comment]
Dear Lee,

First of all I want to thank you for your fast reply and taking in consideration my suggestion and clarifying the Focus issue. 

On the hand I have setup the editor in one application and after 
creating -> editing -> deleting (destroy +null)  -> creating again with the saved content I get the following problem (error):

![suned](https://user-images.githubusercontent.com/2625401/81514133-2c329c80-92e2-11ea-89a3-8a8da5d99c12.jpg)

Beautifying the suneditor.min.js and tracking down the error I have found that
 ( no d.history.push(!1) in the else statement )  is causing the error

setContents: function(t) {
  const n = this.convertContentsForEditor(t);
  if (this._resetComponents(), d._variable.isCodeView) {
        const e = this.convertHTMLForCodeView(n);
         d._setCodeView(e)
    } else e.element.wysiwyg.innerHTML = n, d.history.push(!1) <- HERE
},

removing  ", d.history.push(!1)" from the else statement, the loading, creation editing etc... was working without any errors. I have no idea  what "d.history.push(!1)" is doing and I am wondering if is OK to delete it

I hope that you will have time to review also this problem for the next release.

Thank you,
Paul

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
