### ISSUE TITLE
How to upload images to server?

### ISSUE THREAD

**Issue by eliyahu-shmuel** [JiHong88/SunEditor#369]
Hi!
I want upload the images to my server not using only url, how to make it?
Thank you very much!

**Comment by paindever** [comment]
I have same problems :'(

**Comment by MRB60** [comment]
Not sure what you mean and I cannot help you on the php server side but add this to your Suneditor config:
```
imageUploadHeader: {'X-CSRF-TOKEN': CSRFtoken},
imageUploadUrl: 'imageupload',
```
CSRFtoken is the string. In the reply back to the browser json encoded:
`{"result":{"url": <ur to filel>, "name": <yourfilename>,"size": <in bytes>}}
`

**Comment by eliyahu-shmuel** [comment]
Thank you very help:)

‫בתאריך יום ב׳, 11 במאי 2020 ב-16:30 מאת ‪MRB60‬‏ <‪notifications@github.com
‬‏>:‬
