### ISSUE TITLE
tabDisable option not included in typings

### ISSUE THREAD

**Issue by coroki** [JiHong88/SunEditor#371]
Hello,

It looks like you recently added a new "tabDisable" option but may have forgotten to include the addition in your typings. I am using TS so it complains when I try to assign this.

Your recent commit:
https://github.com/JiHong88/SunEditor/pull/367/commits/4b21596d5d21ef86398442247edf4f29b575183a

I am just trying out your library recently. It looks really great!

**Comment by JiHong88** [comment]
Hi,
Thank you for your advice!

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
