### ISSUE TITLE
Integrate SunEditor to grapesjs pagebuilder

### ISSUE THREAD

**Issue by triawarman** [JiHong88/SunEditor#373]
Hello JiHong, i trying change grapesjs default text editor (Rich Text Editor), based on this [guide](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html) .

![ok](https://user-images.githubusercontent.com/10298895/81773630-54f1a680-951b-11ea-88d6-aadaadef7eab.png)

I can say this works, but theres problem, the SunEditor inline toolbar is rendered inside iframe, is there a way to move to another DOM ?

**Comment by JiHong88** [comment]
Hi, @triawarman 
Can't load css file inside "Iframe"?

**Comment by triawarman** [comment]
Yes, but im sure that's not the problem.
After checking the HTML element i found that every time i dragged new grapesjs **text** component  to the grapesjs editor, SunEditor will create new HTML element.

![ok](https://user-images.githubusercontent.com/10298895/81806312-ddd60580-954e-11ea-9c09-0330c14186aa.png)

and just realize that the actual grapesjs model doesnt updates its model element (i will fix this later).

So i need your feedback or some idea, is there a way to move SunEditor toolbar outside grapesjs iframe (editor), or should i just disable the SunEditor toolbar and make new tollbar outside iframe?

Owh forgot to tell you that i use _mode: 'inline'_ for SunEditor toolbar.

**Comment by triawarman** [comment]
Get an idea, maybe its better to destroy SunEditor when Grapesjs text component isnt focus, then reinit SunEditor (add css file to iframe) when focusing on text component, im sure this solving the problem(s) 

i'll close this issue, going ask you for any other.
Thanks JiHong.

**Comment by swapnilkhedkar-vb** [comment]
Hi @triawarman,
can u share a sandbox link for the code ?
