### ISSUE TITLE
TypeError Cannot read property 'style' of null

### ISSUE THREAD

**Issue by doug-luce-kubra** [JiHong88/SunEditor#374]
Hello, thanks for your work with this it's appreciated.

Currently, I'm using sun editor to persist images in base64 to a database, but they are getting wrapped in a div with a class name of se-component which is causing an error TypeError Cannot read property 'style' of null. I've replicated it in this code sandbox [https://codesandbox.io/s/setoptions-failed-with-cannot-read-property-style-of-null-4j8w6?file=/src/App.js](https://codesandbox.io/s/setoptions-failed-with-cannot-read-property-style-of-null-4j8w6?file=/src/App.js) By removing the se-compoent class it works just fine.

I'm not sure what I'm missing, is it intended that the <img tag is wrapped in a div with this class?

This is in version 2.11.0 of the React component and it looks like that version uses version 2.29.0 of Sun Editor.

Thanks,

Doug

**Comment by doug-luce-kubra** [comment]
@JiHong88 Do you have an estimate of when this will be released as part of the 2.30.0 release?

Thanks!

**Comment by JiHong88** [comment]
@doug-luce-kubra It will be released this week.

**Comment by doug-luce-kubra** [comment]
Awesome, thanks.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by doug-luce-kubra** [comment]
Thanks! @JiHong88
