### ISSUE TITLE
How to create a grid?

### ISSUE THREAD

**Issue by andreyciocan** [JiHong88/SunEditor#375]
Hello! 

I've been struggling with this for days. I want to create a grid so the user can write on two or more columns but I cannot figure out how.

What I've tried: 
1. Go to source mode and write some bootstrap style div (as I have bootstrap in my project). The problem is that if I write `<div class="row">
<div class="col-lg-6">content</div>
<div class="col-lg-6">content 2</div>
</div>` when I close the source mode, the editor deletes `<div class="row">` as it has no text childs
2. Try to create my own classes for a grid, but this leads to some overflow issues if grid is not complete (say the user makes only one col-6 then writes something else, this goes inline).

Is there a way to achieve this? Maybe a plugin or something? 

Thanks

**Comment by digifyro** [comment]
He's right!

If you add this code in source view:
`<div class="row">
  <div class="col">111</div>
</div>`

And switch to normal view, then only
`<div class="col">111</div>` remains. The rest is erased.

I would need that too!

**Comment by JiHong88** [comment]
Hi,
Is it possible to upload the HTML of the table used in the source view mode?

**Comment by digifyro** [comment]
Try `<div class="row"><div class="col">111</div></div>`
After switching to normal view `<div class="row"></div>` will dissapear. This happends in the demo on your website too.

**Comment by andreyciocan** [comment]
As @digifyro said, there is no table. Looks like the editor does not let to have nested divs. No mather of what classes are used. Even if I type: 
`<div>
<div>
content
</div>
</div>`
it removes the first div that contains the second

**Comment by JiHong88** [comment]
@digifyro @andreyciocan 
When returning from the code view mode to the WiziWig mode or pasting, a check the HTML to convert tags that do not fit the editor's format.
So, nested div tags are removed because divs are format tags..

It seems that there is a way to exclude the nested format with a class or put an option not to check HTML in code view mode.

**Comment by andreyciocan** [comment]
@JiHong88 how to put that option? In config? Can you post an example please?
Also, I would like to contribute to your project. First I can help you with locales for romanian if you like. 

Thanks in advance

**Comment by JiHong88** [comment]
@andreyciocan There are no options at this time.😭
I'll update it at next versions.
Maybe it will be available until next week.
And I would be very grateful if you could provide a Romanian translation.
Thank you.

**Comment by andreyciocan** [comment]
I was wondering, if I would create a custom plugin that will insert the necessary divs, will the editor remove them on save?

**Comment by JiHong88** [comment]
@andreyciocan @digifyro 
If you give 'se-component' class name to the top div,
HTML is preserved.

**Comment by andreyciocan** [comment]
Not yet. Maybe you must make a new release? 

Reproducing code:

`<div class="se-component">
<div class="col">content</div>
</div>`

when I switch back to editor mode (from code), only `<div class="col">content</div>` is persisted

**Comment by JiHong88** [comment]
It will be applied when a new version is released.
Tags with the class name `se-component` or `se-tag` of the top-level tag will not be deleted.

`se-component` is the component type of the editor.
Class name for wrapper tags such as images and videos.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
