### ISSUE TITLE
Unknown edit feature in disabled editor

### ISSUE THREAD

**Issue by Mikco11** [JiHong88/SunEditor#376]
Hello,

I am using editor in react just for displaying content without ability to edit it.
Property `disable `is set to `true `.
When i go with my mouse just slightly over the top of image this feature appears.
See attached screenshot.
![unknown_feature_suneditor](https://user-images.githubusercontent.com/43450691/82436702-8972de80-9a96-11ea-8f48-46a1c8ea3528.png)
I found out it add empty line. Why is it shown in "disabled mode" ?

I should mention that i add that red image/logo to HTML string in backend based on business logic.
**Note:** i also created this issue in suneditor-react but i also posted it here since this is probably core problem/bug.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
