### ISSUE TITLE
Loosing focus on initial typing in Internet Explorer 11

### ISSUE THREAD

**Issue by Mikco11** [JiHong88/SunEditor#377]
Hello,
i am using suneditor-react package version 2.11.1 with 2.29.0 suneditor
When i want to type something into empty editor in Internet Explorer version 11.3247 I click into editor area but then it immediately loses focus.
I have to be typing something and at the same time i have to click on editor to get some text in it or just click on editor and the be very quickly type something. It is very inconvinient.
Once it has some value in it i can type more text, edit, etc. normally without a problem.

I am providing empty string from Redux to setContents property as a initial value.

**Note:** I also created this issue in suneditor-react but i also posted it here since this is probably core problem/bug.

**Comment by JiHong88** [comment]
Hi, @Mikco11 
The issue is not reproduced.
Please tell me more about the execution environment.
And the editor is create `<p><br></p>` to default
Can you check it?

**Comment by Mikco11** [comment]
As I said i am running a react package in react app. React version 16.12.0.
This is component
`<SunEditor
              ref={r => {
                this.sunEditor = r;
              }}
              lang='en'
              showToolbar={!this.props.toolbarDisabled}
              disable={this.props.readOnly}
              setOptions={{
                placeholder: this.props.placeholder,
                minHeight: '50vh',
                resizingBar: false,
                showPathLabel: false,
                defaultStyle: "font-family: 'WienerMelange'",
                formats: ['p', 'blockquote', 'h1', 'h2', 'h3'],
                buttonList: [
                  [
                    'formatBlock',
                    'paragraphStyle',
                    'blockquote',
                    'bold',
                    'underline',
                    'italic',
                    'textStyle',
                    'removeFormat',
                    'outdent',
                    'indent',
                    'align',
                    'list',
                    'table',
                    'link',
                    'image'
                  ]
                ]
              }}
              setContents={this.props.editorHtmlValue}
              onChange={this.handleChange}
   />`
Nothing extra i would say.
`this.props.editorHtmlValue` is HTML string from Redux (State management for react)
onChange function just sets new and changed html string to Redux `editorHtmlValue` property

**Comment by JiHong88** [comment]
@mkhstar Can you answer this issue?
It does not occur in SunEditor package.

**Comment by trembacz** [comment]
@Mikco11 I've had the same issue and fixed this by creating default range again in onLoad handler
```// fix issue with losing focus on IE 11
if (editorRef.current.editor.core.util.isIE) {
  editorRef.current.editor.core._createDefaultRange();
}

**Comment by mkhstar** [comment]
[https://github.com/mkhstar/suneditor-react/issues/58#issuecomment-637048103](url)

**Comment by JiHong88** [comment]
This issue will fix at the [suneditor-react](https://github.com/mkhstar/suneditor-react/issues/58)
