### ISSUE TITLE
video problem

### ISSUE THREAD

**Issue by daybat** [JiHong88/SunEditor#381]
if insert in code view mode the video like this: `<video controls="" style="width:auto;height:auto;max-width:100%;max-height:100%;"><source src="/uploads/0/iTYiGksjH/1.mp4" type="video/mp4"></video>`

it does not appear in the preview mode and even can not be saved

**Comment by JiHong88** [comment]
Hi
I don't see code :(

**Comment by daybat** [comment]
I'm sorry. Here it is
`<video class="kv-preview-data file-preview-video" controls="" style="width:auto;height:auto;max-width:100%;max-height:100%;"><source src="/uploads/0/iTYiGksjH/1.mp4" type="video/mp4"></video>`

**Comment by JiHong88** [comment]
If the source tag is not used, it will be displayed normally.
`<video controls="" style="width:auto;height:auto;max-width:100%;max-height:100%;" src="/uploads/0/iTYiGksjH/1.mp4"></video>`
I'll fix the source tag to be available in the next version.

**Comment by daybat** [comment]
ok. thank you!

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
