### ISSUE TITLE
Font menu opens above font button with many fonts in list

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#382]
Just a minor issue;
With many items (12-20) in font list, menu shows above font button where I have no possibility to scroll and would prefer all menus to open up below their buttons.
It seem to be dependent on viewport size.
I open Suneditor in a full page modal and cannot scroll up.

**Comment by MRB60** [comment]
A comment to my own issue:
Adding !important to: .sun-editor .se-list-layer, top attribute solves my issue.
```
.sun-editor .se-list-layer {
    ...
    top: 37px!important;
}
```

**Comment by JiHong88** [comment]
Thank you for your feedback.
I'll modify it to adjust the length and position of the menu according to the size of the screen and menu.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
