### ISSUE TITLE
setOptions method suggestions

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#383]
Hi @JiHong88,
Currently when the setOptions method is called, it replaces the old options passed to it. Can we make it in such a way that, after the initial setting, when a specific option is set afterwards, it only updates that specific option.
For example.
Initially setOptions was called like 
```
setOptions({buttonList: [['image', 'fontSize']]})
```
Afterwards when it is called like below
```
setOptions({width: '80%'})
```
It shouldn't replace the whole options but it should just set the width option like below

```
setOptions({width: '80%', buttonList: [['image', 'fontSize']] })
```

**Comment by JiHong88** [comment]
Hi @mkhstar 
This is a bug different from the development intent.
It has been modified in the development version, and will be updated from the next version.
It was scheduled to be updated today, but it will take another day or two.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
