### ISSUE TITLE
Text is inserted without paragraph

### ISSUE THREAD

**Issue by kranczeer** [JiHong88/SunEditor#385]
Hello,

thank you for your's product. It's really great. I have found two bugs in new version but I think it can be descripted as one because it's similar behaviour.

**Steps for reproduce (1):**

1. Paste a table
2. Click on left side of the table and type a text.
3. Text is not a paragraph but only clear text or span.

![FKRXWC3U2X](https://user-images.githubusercontent.com/16227335/83622722-aa582b00-a590-11ea-9047-3c5645a57274.gif)

**Steps for reproduce (2):**

1. Paste a table
2. Click three times on left side of table to select whole table.
3. During holding mouse button start typing text.
4. Text is not a paragraph but only clear text or span.

![1aLe3Hf24h](https://user-images.githubusercontent.com/16227335/83623178-45e99b80-a591-11ea-9284-62c29efa521a.gif)

Thanks and have a nice day,
Adrian

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
