### ISSUE TITLE
Trigger an event when toggling between code view and wysiwyg view?

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#386]
Is there a way to save the contents when the user toggles into code view, and when they toggle back to wysiwyg?

**Comment by JiHong88** [comment]
Hmm.. currently, It is impossible.
I'll add a code view toggle event.

**Comment by rwaldron** [comment]
Very cool! Thank you.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
