### ISSUE TITLE
Show the correct shortcuts (OS) and disable on the tooltip

### ISSUE THREAD

**Issue by giovanigenerali** [JiHong88/SunEditor#387]
Show the correct command according to the user's operating system on the tooltip.

- windows
 ```Ctrl + B``` 

- osx
```⌘ Cmd + B```

Also, how can I remove this shortcut text from the tooltip?

![Screen Shot 2020-06-03 at 23 18 05](https://user-images.githubusercontent.com/41435/83707492-7dd3fb80-a5f0-11ea-8d26-26a783ed6ef9.png)

**Suggestion**
Create an option ```shortcutsHint``` and when enabled the shortcut is displayed in the button tooltip.

```js
shortcutsHint: When enabled the shortcut is displayed in the button tooltip. default: false {Boolean}
```

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
