### ISSUE TITLE
Format issues if only a single word is typed (Edge browser)

### ISSUE THREAD

**Issue by G-S2h** [JiHong88/SunEditor#388]
hi, and thank you for your great WYSIWYG, 

There is a bug with Edge browser where format actions (such as bold) result in an `Unable to get property 'textContent' of undefined or null reference` if one tries to format the word he has just typed.
![SunEditor_bug_bold-just-typed-word](https://user-images.githubusercontent.com/1252585/83772208-714cb300-a683-11ea-8fa0-a434ce96c21d.gif)
Steps to reproduce:
1. Make sure all SunEditor textarea is empty;
2. Type a word; select this word and apply some basic format (bold e.g.) to it.

If you do not type anything and first click a format option, it will break a new formated line in textarea, but (plus) it may lead to a new bug.
![SunEditor_bug_bold-before-anything](https://user-images.githubusercontent.com/1252585/83774035-86c2dc80-a685-11ea-9e11-1cb45529f623.gif)
Steps to reproduce:
1. Make sure all SunEditor textarea is empty;
2. Click on Bold (cursor should move below) then type a first word;
3. Click back to Bold, hit and space a type another word;
4. Select that second word and click on Italic.

### But it _works_ with keyboard shortcuts
However I have noticed that everything works well if you use keyboard shortcuts, even if the error logs in console `(Unable to get property 'textContent' of undefined or null reference).`

**Comment by JiHong88** [comment]
The old version of the edge browser is really hard.
Even "selection" has different results than IE. :(
I modified it, but it may not be perfect.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
