### ISSUE TITLE
Bug when delete text on a table

### ISSUE THREAD

**Issue by giovanigenerali** [JiHong88/SunEditor#389]
![PCnZZOny23](https://user-images.githubusercontent.com/41435/83802956-123a6e80-a682-11ea-8881-fee9ef87ca5f.gif)

### Steps to reproduce the bug

1. create a table with only one row and column
2. type some text
3. delete the text
4. Bug: the entire table is removed.

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
