### ISSUE TITLE
util.isIE doesn't really work?

### ISSUE THREAD

**Issue by G-S2h** [JiHong88/SunEditor#391]
Hi, 

It seems like `isIE` utility function doesn't always work.

Example: `'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)'.match(/(MSIE|Trident.*rv[ :])([0-9]+)/)`  will return `null`.

I had to change quantifier to  `?` to have it work.

**Comment by JiHong88** [comment]
Hi,
This editor supports only version IE11.
It seems your userAgent string is IE10.

IE check will be modified to `navigator.userAgent.indexOf('Trident') > -1`.
Thank you!

**Comment by G-S2h** [comment]
Huh my bad, sorry and thank you.
