### ISSUE TITLE
2.30.0 Release timeline?

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#392]
Congrats on completing all of the [tasks in 2.30.0!!](https://github.com/JiHong88/SunEditor/milestone/7) 

Do you have a timeline for when we can expect this release to ship? Looking forward to upgrading—Thanks again!

**Comment by JiHong88** [comment]
Thank you @rwaldron  : )
It is distributed after updating the examples and release notes.
It will probably be today.
I will notify know after the version update.

**Comment by rwaldron** [comment]
Excited to see that 2.30.0 is in master now, but it's not on npm yet!

**Comment by rwaldron** [comment]
(Thanks again!!)

**Comment by JiHong88** [comment]
Hi, @rwaldron 
I was in the last tests and bug fixes.
I'll release in an hour. :)

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
Thank you.
