### ISSUE TITLE
Remove all tag in table when press "backspace"

### ISSUE THREAD

**Issue by tranchem** [JiHong88/SunEditor#393]
[Hi.](url

[issue_table.txt](https://github.com/JiHong88/SunEditor/files/4750975/issue_table.txt)

)
I have a template email with many tag table in table. I copy it, paste to "codeview" and come back editor . I choose text "Hello" and "backspace" it,  every tag in table disappear.
I think it's a bug. Can you help me? 
I'm using option "codeMirror"

**Comment by JiHong88** [comment]
Hi, @tranchem 
This issue has been resolved.
I'll nofify you know after the version update at today.

**Comment by tranchem** [comment]
> Hi, @tranchem
> This issue has been resolved.
> I'll nofify you know after the version update at today.

Oh. Thank you so much !

**Comment by tranchem** [comment]
I have a question that may related to this:
I'm using `this.editor.core._setCodeView(html); this.editor.core._setCodeDataToEditor();` to append fullpage. Can you show me a better way?

**Comment by JiHong88** [comment]
You can use the [functions.insertHTML](http://suneditor.com/sample/html/out/document-user.html#insertHTML)
`this.editor.innerHTML(html, false)`

**Comment by tranchem** [comment]
This way remove all tag in my <style></style>

**Comment by JiHong88** [comment]
`this.editor.innerHTML(html, true)`
This code is don't run [cleanHTML](http://suneditor.com/sample/html/out/document-editor.html#cleanHTML)

**Comment by tranchem** [comment]
Is this any way to remove dom editor before insertHTML ?

**Comment by JiHong88** [comment]
>Is this any way to remove dom editor before insertHTML ?
Sorry, I don't understand what means.
Please tell me in detail.

**Comment by tranchem** [comment]
Sorry. My english is not good
My mean is: insertHTML('') then insertHTML(html, true).
Is this better way?

**Comment by JiHong88** [comment]
What is your want?
HTML string insertion or initial value assignment

**Comment by tranchem** [comment]
I want to initial value

**Comment by JiHong88** [comment]
You can use "insertHTML" and also use "setContents" to change the entire contents of the editor.
`editor.setContents(html)`

You can also put content inside the textarea element.
```html
<textarea>html</textarea>
```

**Comment by JiHong88** [comment]
The [2.30.0](https://github.com/JiHong88/SunEditor/releases/tag/2.30.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by tranchem** [comment]
It has been resolved. Thank you very much!
