### ISSUE TITLE
Re-pasting formula with Katex code does not render SVG tags

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#395]
When I paste some content that has Katex formula with SVG tags (try sqrt to reproduce) taken from one editor instance (using getContents) to another (using setContents), the SVG tags in the formula (katex) do not render in the new editor preview. Rest of the formula appears fine.
A sample of square root of 2 appears as follows:
![image](https://user-images.githubusercontent.com/50414962/84228047-97e76f80-ab03-11ea-9cc1-8ba2080ac171.png)

Moreover, if I click the edit button on the formula snippet, the SVG appears in the modal preview perfectly fine since the katex code is preserved perfectly. On submitting the modal, the formula starts rendering the SVG tags. 

The ideal behaviour is that the formula should have that SVG tags appear in the first place.

P.S.: This is the first time I am creating an issue, so please forgive if I am not able to convey here.
P.P.S.: @JiHong88 Amazing work. I actually moved from using a paid editor to Sun :)

**Comment by JiHong88** [comment]
Hi, @dgandhi1993 
Thank you using this project. :)
I'll notify you know after fixing the bug.

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
