### ISSUE TITLE
Wrong html generated on "Enter" key

### ISSUE THREAD

**Issue by andreyciocan** [JiHong88/SunEditor#397]
Hi. First of all, thank you for the "se-component" and "__se__tag" classes that fixes https://github.com/JiHong88/SunEditor/issues/375 .

I have a new bug now. If I have a code like this one:
`<div class="se-component row"><div class="se-component col">Some text in here</div></div>`

and from the editor i change the text in the `<div class="se-component col">Some text in here</div>` then hit Enter key, the editor is generating a new div instead of adding a <br /> or <p> in the current div. 

Code generated after enter is:
`<div class="se-component row"><div class="se-component col">Some text in here</div><div class="se-component col">Some text in here</div></div>`

Should be:
`<div class="se-component row"><div class="se-component col">Some text in here <br /></div></div>`

Thanks in advance

**Comment by JiHong88** [comment]
"se-component" and "__se__tag" should only be used for the top element.

"se-component":
Currently, "se-component" is used for wrapper elements of image, video, and audio. [suneditor-contents](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css#L323)
It is a special class name. [util.js#L301](https://github.com/JiHong88/SunEditor/blob/master/src/lib/util.js#L301)
It should be used for containers that contain element not text, like image.

"__se__tag":
It is free to use.

**Comment by andreyciocan** [comment]
Tried the following: 
`<div class="se-component row"><div class="__se__tag col-md-3">column 1 content</div><div class="__se__tag col-md-9">column 2 content</div></div>`

When I hit enter in the first div (for example) the code becomes: 

`<div class="se-component row"><div class="__se__tag col-md-3">column 1 content</div><div class="__se__tag col-md-3"><br></div><div class="__se__tag col-md-9">column 2 content</div></div>`

Should be:
`<div class="se-component row"><div class="__se__tag col-md-3">column 1 content <br/></div><div class="__se__tag col-md-9">column 2 content</div></div>`

**Comment by JiHong88** [comment]
>"se-component" and "__se__tag" should only be used for the top element.

```html
<div class="(se-component or __se__tag) row">
  <div class="col-md-3">column 1 content</div>
  <div class="col-md-9">column 2 content</div>
</div>
```

In the editor, Enter creates a new line.
(shift + enter) is create `<br>` in the line.
The line must be [isFreeFormatElement](http://suneditor.com/sample/html/out/document-util.html#isFreeFormatElement) to create the `<br>` tag with only the Enter key.
```html
<div class="(se-component or __se__tag) row">
  <div class="col-md-3 __se__format__free_xxx">column 1 content</div>
  <div class="col-md-9 __se__format__free_xxx">column 2 content</div>
</div>
```

**Comment by JiHong88** [comment]
Currently, if you use the Enter key continuously in an empty space, it will exit the line and create a new line.
This is the required behavior in the `<pre>` tag, I'll let's find a way around this.

**Comment by andreyciocan** [comment]
Thank you!

`__se__format__free_xxx` works like a charm for me. It does the job right. 

I think we can close this issue.

**Comment by JiHong88** [comment]
Hi @andreyciocan 
Added "closureFreeFormat".( __se__format__free__closure_)
It is a format that does not create a new line even if you enter in the last line.
```html
<div class="(se-component or __se__tag) row">
  <div class="col-md-3 __se__format__free__closure_xxx">column 1 content</div>
  <div class="col-md-9 __se__format__free__closure_xxx">column 2 content</div>
</div>
```
I will notify you know when the version is updated.

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
