### ISSUE TITLE
Copy pasting text from one editor instance to another does not copy the KaTeX in it

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#399]
When I try to copy the text written in an editor instance with some KaTeX code, to another editor instance, the KaTeX code fails to copy, instead, it converts into text along with the KaTeX syntax.
For example, I tried copying:
![image](https://user-images.githubusercontent.com/50414962/84595464-a8864580-ae75-11ea-91bc-017d1a1f8b64.png)
The pasted value looks like this:
![image](https://user-images.githubusercontent.com/50414962/84595487-c94e9b00-ae75-11ea-9ff6-b234119e6b34.png)
This is a bad experience for users who have multiple editors on the same page and want to copy-paste between such editors.

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by dgandhi1993** [comment]
@JiHong88 Facing similar issue where I loose SVGs inside the formula.

Steps to reproduce.
1. Add a formula to an editor, let's say "\sqrt2i". This will add the formula perfectly.
2. Cut this formula and try repasting it.
3. You will see that you would have lost the square root symbol. 

However, if you click on the edit button of the formula, it will open the Formula modal with the correct notation (i.e. including the symbol). If you submit this modal, the symbol starts appearing again in the editor as well.

**Comment by JiHong88** [comment]
@dgandhi1993 This issue is resolved.
I'll notify you after updated the version.

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by dgandhi1993** [comment]
@JiHong88 This issue has started popping up when using vector symbols. 
Try adding `\vecA` using the Formula modal. 
Now switch to the code view and back to editor view.
You will see the arrow on top of A would be gone.

This happens with me when I try to add a vector KaTeX html to the editor using `setContents()`.

Also, while doing so I noticed while adding `\overrightarrow{AB}` as LaTeX to the editor, the editor representation is a little off.

**Comment by JiHong88** [comment]
@dgandhi1993 When inserting HTML string, "\" in "data-exp" disappears.
Please use the new "Katex" tag when after update the version.
