### ISSUE TITLE
Text color and highlight color are not copied 

### ISSUE THREAD

**Issue by KubaWysocki** [JiHong88/SunEditor#400]
When copying from SunEditor  and pasting into SunEditor those 2 styles (text color and highlight) are not copied. All other standard formats seem to copy right

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
