### ISSUE TITLE
Image deleting error

### ISSUE THREAD

**Issue by GitNomster** [JiHong88/SunEditor#402]
**Reproduce**
Open [http://suneditor.com/sample/index.html](http://suneditor.com/sample/index.html), open console (F12) and delete image from edit field. The console will catch an error:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at String.deleteInfo (suneditor.min.js:1)
    at Object.destroy (suneditor.min.js:1)
    at HTMLDivElement.onKeyDown_wysiwyg (suneditor.min.js:1)
```

**Comment by JiHong88** [comment]
The [2.30.1](https://github.com/JiHong88/SunEditor/releases/tag/2.30.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
