### ISSUE TITLE
Unable to create editor instance with the latest release

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#404]
I am getting below error when I call the create function on the editor.

editor.min.js:formatted:8487 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.convertContentsForEditor (editor.min.js:formatted:8487)
    at Object._initWysiwygArea (editor.min.js:formatted:8825)
    at Object._init (editor.min.js:formatted:8793)
    at A (editor.min.js:formatted:10225)
    at Object.create (editor.min.js:formatted:10279)
    at Object.<anonymous> (editor.min.js:formatted:10238)

If I move to the previous release, things were perfectly fine. Is there any change that I am supposed to do with this new release?

**Comment by JiHong88** [comment]
Hi, Can you show me the editor's define code?
And also show me value of the target textarea.

**Comment by dgandhi1993** [comment]
Below is the code I am trying to execute.
```
let imageEditor = SUNEDITOR.create("imageContainer",{
    mode: "balloon-always",
    resizingBar: false,
    showPathLabel: false,
    display: "inline",  
    tabDisable: false,
    placeholder: "Enter the image here",
    buttonList: [
        [
            "image",
            "removeFormat"
        ]
    ],
});
imageEditor.setContents("");
```
The error appears on the create function. 

There is no value in the target textarea. In fact, there is no textarea inside the #imageContainer at the time of create function call.

Not sure what changed in this release, since the same code was working fine so far.

**Comment by JiHong88** [comment]
Um.. what tested browser?

**Comment by dgandhi1993** [comment]
Using Google Chrome.

**Comment by JiHong88** [comment]
Can you check this code?
`imageEditor.core.context.element.originElement`

**Comment by dgandhi1993** [comment]
Give below error:
Uncaught TypeError: Cannot read property 'core' of null

**Comment by JiHong88** [comment]
Current code is below:
```javascript
this.convertContentsForEditor(context.element.originElement.value);
convertContentsForEditor: function (contents) {
 contents = contents.replace(....)
}
```
I think `contents` is undefined.
And `context.element.originElement` is the target `<textarea>`

**Comment by dgandhi1993** [comment]
Before the editor is initialized it is bound to be undefined. I believe the _convertContentsForEditor_ should only be executed if _contents_ is not undefined.

**Comment by JiHong88** [comment]
The "value" attribute of "textarea" cannot be "undefined".
There will be something wrong.

The error is not reproduced.
Show me the HTML code as well.
OS is Windows or Mac?

**Comment by dgandhi1993** [comment]
```
<div id="imageContainer"></div>
```
I was using a div to create the editors so far. Seemed to work perfectly fine. But now it seems that I'll need to change it to textarea.

I am using Mac.

**Comment by JiHong88** [comment]
The target element should use only the `textarea`
Hmm.. Is there a difference in using the target element `div` and `textarea`?

**Comment by dgandhi1993** [comment]
Up until 2.30.0 ```div``` was working fine. In the new release (2.30.1), things broke.

I have not used a single ```textarea``` so far.

**Comment by JiHong88** [comment]
Defined as using only `textarea` and developed the editor.
If you used the save() function, an error would have occurred.
It's not difficult to allow div possible, so I will consider.

**Comment by dgandhi1993** [comment]
Converting all the ```div``` to ```textarea``` seems to do the trick for now.
Thanks @JiHong88 :)
