### ISSUE TITLE
How to remove the whole node ?

### ISSUE THREAD

**Issue by ltbysky** [JiHong88/SunEditor#408]
Hi,

I created a custom plugin for adding a pre-defined text node, such as "select" "username", and  I want to delete the entire "select" when user tapping the delete key, is there a sample for this ?

**Comment by JiHong88** [comment]
Hi,
Please tell me the structure of the predefined text node.

**Comment by ltbysky** [comment]
> Hi,
> Please tell me the structure of the predefined text node.

Thanks for reply, the structure of predefined text node just like the math plugin, user can setup some variables by our popup panel, the json structure is like :  {'name': 'sales', 'express':'gte', 'value':100},  then the variable display as plain text in editor such as "sales > 100", and the entire node 'sales > 100' should be deleted when user tapping the delete key in editor.

**Comment by ltbysky** [comment]
![image](https://user-images.githubusercontent.com/1297439/85225174-d3d2dc80-b401-11ea-897e-4902650e7805.png)
Please refer to the sceenshot, user can delete chars to the defined plugin [select], but cannot delete the [select] when keep tapping the delete key

**Comment by ltbysky** [comment]
@JiHong88 I guess it's a BUG, in the sample (http://suneditor.com/sample/index.html), I can delete the entire math content by keep tapping the delete key in Chrome,  but it's not working on firefox.

**Comment by JiHong88** [comment]
Thank you.
I'll release new version when resolved this issue.

**Comment by JiHong88** [comment]
The [2.30.5](https://github.com/JiHong88/SunEditor/releases/tag/2.30.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
