### ISSUE TITLE
Question: use of attributesWhitelist

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#409]
Thanks for the great work and your responsiveness to issues and questions!

I started to try to insert a html grid with icons and text and failed. 
What I want:
![image](https://user-images.githubusercontent.com/58078302/85218934-6bebaa00-b39f-11ea-869a-2a7cec557b73.png)
html:
```
<div class="__se__tag uk-grid">
  <span uk-icon="icon: plus; ratio: 1.0"></span>
  <span>Text</span>
  <span uk-icon="icon: plus; ratio: 1.0"></span>
</div>
```
As recommended, I added "__se__tag" class to top DIV. I also added "uk-icon" to attributesWhitelist:
`	attributesWhitelist: {'all': 'uk-icon'},
`
Thr problem is that the span tags containing the "uk-icon" attribute gets removed (in editor mode).
I might do something wrong - I would appreciate a hint how to use `attributesWhitelist` correctly.

**Comment by JiHong88** [comment]
Hi,
This is a bug.
I will notify you after fix.

**Comment by JiHong88** [comment]
The [2.30.5](https://github.com/JiHong88/SunEditor/releases/tag/2.30.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by Nirav2021** [comment]
@JiHong88 Thanks for the great work on SunEditor. One issue i m facing with attributesWhitelist is - <em> tag is not retained and deleted by the SunEditor's Code view.
This is the html that i am using in Code view
<h4><em class="fas fa-eye mr-2"> </em> At a glance</h4>
I am using attributesWhitelist: { em: "class" } to retain em tag.
Can you please help to not remove em tag from my html content. 
Note:  I am using version 3.6.1 for SunEditor-React.
