### ISSUE TITLE
Angular 8 integration error

### ISSUE THREAD

**Issue by OSorokin** [JiHong88/SunEditor#411]
Hi, tried to add suneditor in my angular 8 project.
got some errors:

> ERROR in node_modules/suneditor/src/lib/core.d.ts:770:35 - error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
> 
> 770     setToolbarButtons(buttonList: Array): void;
>                                      
> node_modules/suneditor/src/lib/util.d.ts:30:43 - error TS2304: Cannot find name 'ActiveXObject'.
> 
> 30     getXMLHttpRequest(): XMLHttpRequest | ActiveXObject;
>    

 component code:

```
import {Component, OnInit} from '@angular/core';

import 'suneditor/dist/css/suneditor.min.css';
import suneditor from 'suneditor';

import image from 'suneditor/src/plugins/dialog/link';
import list from 'suneditor/src/plugins/submenu/list';
import {font} from 'suneditor/src/plugins';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  ngOnInit() {
    suneditor.create('sample', {
      plugins: [font, image, list],
      buttonList: [
        ['font', 'image', 'list']
      ],
    });
  }
}

```

**Comment by JiHong88** [comment]
Hi, 
The Typescript file has been modified as below:
`setToolbarButtons(buttonList: Array)` -> `buttonList: any[]`
I'll notify you know when the version is update.

>node_modules/suneditor/src/lib/util.d.ts:30:43 - error TS2304: Cannot find name 'ActiveXObject'.

Please refer to the URL below:
https://github.com/photonstorm/phaser3-docs/issues/87

Thank you!

**Comment by JiHong88** [comment]
The [2.30.5](https://github.com/JiHong88/SunEditor/releases/tag/2.30.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by mayilsaran** [comment]
Can you give an example for Angular8?

**Comment by BrianJVarley** [comment]
Like @JiHong88 said you need to add the `scripthost` lib defintions to your `tsconfig.json`.

Because the standard type definitions configured in an Angular project don't include a definiton for the `ActiveX` type. For example you may have this setup already but missing scripthost:

```
"lib": [
      "es2018",
      "dom"
    ]



```
See: https://stackoverflow.com/a/57478236/1829251
