### ISSUE TITLE
영역 초과할 경우 엘리먼트 삭제

### ISSUE THREAD

**Issue by hajeonghun** [JiHong88/SunEditor#413]
https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L4298
@JiHong88 

위 함수를 참고하여 에디터의 offsetHeight가 특정값을 초과할 경우 해당 엘리먼트를 삭제할려고 하는데,
( core.context.element.wysiwyg.innerHTML = 리턴받은 값;)

원본 contents와 replace한 contents가 동일하게 나와 return util._tagConvertor(cleanHTML); 값이
에디터에 작성된 내용과 동일하여 삭제가 안되네요.

텍스트, 이미지, 비디오, 테이블 등 모두 삭제하고싶은데
혹시 더 좋은 방법이 있거나, 제가 잘못된 방법으로 시도하고 있는건가요?

contents = contents
                .replace(/\n/g, '')
                .replace(/<(script|style).*>(\n|.)*<\/(script|style)>/g, '')
                .replace(this.editorTagsWhitelistRegExp, '');

**Comment by JiHong88** [comment]
제가 주소를 드릴때와 코드가 달라져서 다른 메소드를 참고하신것 같네요ㅠ
core.js 의 _charCount: function 메소드를 참고하시면 되는데, 글자를 지우는거라 별로 도움이 될것 같지는 않네요.

어차피 에디터에 라인은 무조건 들어가게 되고, 테이블이나 이미지등도 라인과 별개로 추가 됩니다.
높이가 초과되면 추가된 라인 전체를 삭제해야 높이가 줄어드니,
높이를 초과한 경우 제일 끝의 한줄을 지워주면 될 것 같은데요.
`core.context.element.wysiwyg.lastElementChild.remove()`

**Comment by hajeonghun** [comment]
> core.context.element.wysiwyg.lastElementChild

이렇게 간단한게 있었군요.. 감사합니다.
