### ISSUE TITLE
Bug: The image in a table disappears from the editor when switching to code view

### ISSUE THREAD

**Issue by giovanigenerali** [JiHong88/SunEditor#415]
### Description
- The image in a table disappears from the editor when switching to code view

### Simulation
![bug](https://user-images.githubusercontent.com/41435/85570856-136c1500-b60a-11ea-8a55-7d953b60f892.gif)

**Comment by JiHong88** [comment]
The [2.30.5](https://github.com/JiHong88/SunEditor/releases/tag/2.30.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
