### ISSUE TITLE
autoFocus 말고 직접 focus를 줄 수 있는 엘리먼트

### ISSUE THREAD

**Issue by hajeonghun** [JiHong88/SunEditor#417]
@JiHong88  

autoFocus로 초기 포커스를 주는 방법 말고, 다른 어떠한 액션(Button Click...etc)을 할때
에디터 작성영역에 포커스를 주고싶은데 어떤 element에 .focus를 줘야 할까요?

core.context.element.wysiwyg.focus(); 를 시도해봤는데 동작하지 않습니다.

**Comment by JiHong88** [comment]
core.focus() 를 호출하면 됩니다
