### ISSUE TITLE
Question: prohibit remove of contenteditable="false" element 

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#418]
I have text within a "p" element which shall not be editable nor removable. However, if all following elements are removed (with delete button), the non-editable element finally gets deleted too and I end up with an empty page. I do not wish that. 
Any chance this can prohibited?

**Comment by JiHong88** [comment]
There is only a way to prevent the whole selection.
However, it can be deleted by selecting it by dragging the mouse if "non-editable" element is in the middle.
