### ISSUE TITLE
스타일 적용 버그 제보 

### ISSUE THREAD

**Issue by chbin05** [JiHong88/SunEditor#422]
안녕하세요. 
suneditor react 버전을 사용중인데요, 쉽게 사용할 수 있도록 만들어주셔서 유용하게 쓰고 있습니다. 감사합니다.

에디터에서 두 문단 이상을 선택하여 스타일 (B/색상 등..)을 적용하려고 하면 적용이 안되거나 전체 스타일이 변하거나 하는 버그를 발견했습니다.
p 스타일, div 스타일의 문단에서 동일하게 발생합니다.
혹시 적용을 잘못한건가 싶어서 데모 페이지에서 시도해 보았는데 동일한 이슈가 있어 제보드립니다.

**Comment by JiHong88** [comment]
안녕하세요~
버그 제보해 주셔서 감사합니다!
수정 후에 알려드릴게요.

**Comment by JiHong88** [comment]
해당 이슈는 [2.30.7](https://github.com/JiHong88/SunEditor/releases/tag/2.30.7) 버전에서 수정 되었습니다.
감사합니다.

**Comment by chbin05** [comment]
빠른 수정 감사합니다~!
