### ISSUE TITLE
UX feedback re: "line breaker component"

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#423]
During a recent UX test with client stakeholders, it was reported by several users that the "line breaker" (described as "that button with the slash in it") is confusing and frustrating. The issue came from users uploading images, then trying to add text content and having that not work as expected, but also not realizing that when they clicked away from the image they lost the button that would fix that for them. 

Is there anyway to intercept the image markup injection to put line breaks around an image automatically?

**Comment by JiHong88** [comment]
Hi,
1. Do you mean the design of the line break button is strange?
2. Do you mean you want to intercept the action when the line break button is pressed?

**Comment by rwaldron** [comment]
Here's a mock up of what they've asked for, because "/" is meaningless: 
<img width="597" alt="Screenshot 2020-06-30 15 15 54" src="https://user-images.githubusercontent.com/27985/86168236-eaee8a00-bae5-11ea-80b4-8e4e8cd9e283.png">

Strike my original suggestion about intercepting the image markup as it gets inserted, I think the easiest solution would be to all embedders a way to customize the displayed text of that button.

**Comment by JiHong88** [comment]
You can use "icons" option.
```javascript
icons: {
  line_break: '...'
}
```

And I'll modify icon.
<img width="419" alt="스크린샷 2020-07-01 오후 2 26 42" src="https://user-images.githubusercontent.com/13191953/86206663-e7bbd280-bba7-11ea-898e-31d115f87881.png">

**Comment by JiHong88** [comment]
The [2.30.7](https://github.com/JiHong88/SunEditor/releases/tag/2.30.7) version has been updated.
Thank you.

**Comment by rwaldron** [comment]
Excellent!!
