### ISSUE TITLE
No contents in v2.30.7

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#426]
In newest version, v2.30.7, all contents in editor window is cleared. Left is: `<p><br></p>`.
Contents is set with `setContents()`.

**Comment by JiHong88** [comment]
The "setContents()" is change all contents of the editor.
Whats problem?

**Comment by MRB60** [comment]
I use `setContents()` function to load the contents into Suneditor. Nothing seem to load.
If I open Suneditor, edit contents, save the data and exit the edit mode, contents is visible. If I then try to edit this contents (fetched and set with `setContents`), I end up with an empty edit area. Worked fine up till version 2.30.7.

**Comment by JiHong88** [comment]
I will notify you after modifying the code regarding the editor's loading.
Please use this code:
```javascript
editor.onload = (core, reload) => {
 editor.setContents("contents");
}
```

**Comment by JiHong88** [comment]
Hi,
"value" option has been added.
It is a initial value of the editor.
It can be used from the next version.

**Comment by JiHong88** [comment]
The [2.31.0](https://github.com/JiHong88/SunEditor/releases/tag/2.31.0) version has been updated.
Thank you.
