### ISSUE TITLE
On deleting an entire table the editor cannot be focused

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#427]
If my editor only has a table which I try to delete entirely, then the editor cannot be focused again. It gives below error in the console:
```
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at Object._createDefaultRange (editor.min.js:1)
    at Object._editorRange (editor.min.js:1)
    at Object.nativeFocus (editor.min.js:1)
    at Object.focus (editor.min.js:1)
    at Object.onClick_tableController (editor.min.js:1)
```
If I try to click inside the editor to manually set focus, I get a similar error:
```
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at Object._createDefaultRange (editor.min.js:1)
    at Object._editorRange (editor.min.js:1)
```

**Comment by JiHong88** [comment]
Hi,
The issue is not reproduced.
Please tell me the tested browser and more details.

**Comment by dgandhi1993** [comment]
Hi,
Browser is Chrome (Version 83.0.4103.106)
Steps to reproduce:

1. Create an editor with below options:
```
imageEditor = SUNEDITOR.create("imageContainer",{
    mode: "balloon-always",
    resizingBar: false,
    showPathLabel: false,
    display: "inline",  
    tabDisable: false,
    placeholder: "Enter the question image here",
    buttonList: [["image","removeFormat"]],
});
imageEditor.onImageUploadBefore = function (files, info, core, uploadHandler) {
    try {
        resizeImage(files, uploadHandler, info, core)
    } catch (err) {
        uploadHandler(err.toString())
    }
};
imageEditor.setContents("");
```
2. Now try adding a table of any size to the editor.
3. Delete this table entirely.

You will see that the table will be deleted and the editor loses focus and could not be focussed again. In the console, you will see the errors stated above.

**Comment by JiHong88** [comment]
The [2.31.0](https://github.com/JiHong88/SunEditor/releases/tag/2.31.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
