### ISSUE TITLE
imageMultipleFile 이슈

### ISSUE THREAD

**Issue by hongku** [JiHong88/SunEditor#428]
imageMultipleFile: true
로 사용하면 file muliti select가 가능하지만
실제 에디터에 삽입되는 이미지는 한개만 삽입됩니다.
데모 에디터에서도 같은 이슈가 확인되는데
확인부탁드립니다

**Comment by JiHong88** [comment]
[2.31.0](https://github.com/JiHong88/SunEditor/releases/tag/2.31.0) 버전이 업데이트 되었습니다.
해결되지 않으면 이 이슈를 다시 열어주세요.
감사합니다.
