### ISSUE TITLE
Bug: Katex Formula changing after entering and exiting codeView

### ISSUE THREAD

**Issue by cford256** [JiHong88/SunEditor#431]
I have noticed a bug with the Katex integration.
When you enter in this formula (one of the ones listed on the Katex function page.)

`\sum_{\substack{0<i<m\\0<j<n}}`

It will display the formula correctly, however if you enter codeView and then exit again it will change to this text (not as a formula). 

∑0<i<m0<j<n\sum_{\substack{0<i<m\\0<j<n}}∑0<i<m0<j<n​​​

I am guessing that it is probably due to the fact that the formula has the double \\ in it, but I have not yet looked into the code of SunEditor or Katex to know for sure.  

I found this while just messing around with this editor, and figured I should point it out. 

Great editor by the way. Much better than the other ones I have messed with before (Summernote, and Quill).

**Comment by JiHong88** [comment]
The [2.31.1](https://github.com/JiHong88/SunEditor/releases/tag/2.31.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
