### ISSUE TITLE
CR - Add Template

### ISSUE THREAD

**Issue by PleachiM** [JiHong88/SunEditor#434]
I'm using setOptions to create templates at runtime. the previous existing ones are deleted by using setOptions. 
I don't know what's the best way to change the functionality. 

I'm not sure what's the best way to handle this. 
-     editor.addOptions({     
        templates: [
            {
                name: 'second template',
                html: '<b>second template</b>'
            }
        ]        
    });  

- editor.getOptions('templates')
?

**Comment by JiHong88** [comment]
What version are you currently using?
In the latest version, "setOptions" does not initialize existing options.

**Comment by PleachiM** [comment]
Latest Version. The old setOptions bug where the complete toolbar was gone is already fixed in this one. Setting the template works fine. Just when there is already one I can't add another on at runtime. so I will have to pass all templates. 
But great job it's really usefull.

**Comment by JiHong88** [comment]
Adding it to the template option?
```javascript
templates.push({}) ?
```

**Comment by PleachiM** [comment]
This could do the job.

**Comment by JiHong88** [comment]
Currently, the menu is not updated once created.
Call "setOptions" by accumulating the templates added to the "templates" option.
I'll consider how to change options without reloading the editor.

**Comment by JiHong88** [comment]
Sorry, Implementing "addOptions" was judged to be inefficient.
This feature will not implement.
