### ISSUE TITLE
Help getContents

### ISSUE THREAD

**Issue by anhdoantm** [JiHong88/SunEditor#435]
Hi, @JiHong88 Editor very good
 
I used `editor.getContents();` to validators to get text values to receive notifications, but in this case it gets the whole code of textarea instead of key text.
Only get **text**, is there any method to do that, I'm using [formvalidation](https://formvalidation.io/guide/examples/integrating-with-tinymce/).
Take a look at the code and look through the link below for info.
_Thanks in advance_.

                "post[content2]": {
                    validators: {
                        callback: {
                            message: 'The contents must be between 5 and 2000 characters long',
                            callback: function(value) {
                                // Get the plain text without HTML
                                const text = editor.getContents({
                                    //format: 'text'
                                });
                                return text.length <= 2000 && text.length >= 5;
                            }
                        }		
                    }
                }

**Comment by JiHong88** [comment]
Hi,
I'll add get Text method.
Until then, you can get it in the following way:
`editor.core.context.element.wysiwyg.textContent`

**Comment by anhdoantm** [comment]
Thanks for the quick help,
I have tried your code but it has no response, the message of that callback does not appear,
See if there's a way for that callback.

There is another question, I found another Editor while searching on [cssscript.com](https://www.cssscript.com/rich-text-editor-kothing/) seems to have changed the name but I know it's the product of your previous version.
Because I don't see any link to your branch or from you there. I thought it was illegal
Here is the link:

https://github.com/kothing/Kothing-Editor

**Comment by JiHong88** [comment]
` editor.core.context.element.wysiwyg.textContent` is undefined?

> https://github.com/kothing/Kothing-Editor

Thanks for the link.
Do you know how to deal with this?

**Comment by anhdoantm** [comment]
they only work on github or [gitee](https://gitee.com), you need to report to the website vendors that they operate, [cssscript](https://www.cssscript.com) also needs to report, they are long-standing websites or large storage places for code and they will stop working action.
What worries me is that they bring viruses into these software, if that is very dangerous, we do not know what their purpose is. I have downloaded it and have deleted it now.

**Comment by JiHong88** [comment]
@anhdoantm 
Are you resolved this issue?

**Comment by anhdoantm** [comment]
Thanks for this feedback.
  I tried the code but it didn't work, I haven't solved it yet.

**Comment by JiHong88** [comment]
`editor.core.context.element.wysiwyg.textContent` What part of this doesn't work?

**Comment by anhdoantm** [comment]
I tried all the elements in the code and the combination reversed, but it all failed. It didn't work.
For this code **`editor.getContents`** it works but it counts everything including **`Div P`** or even Image data it counts, , It should be taken according to **`CharCount`.

![Ảnh chụp màn hình (22)](https://user-images.githubusercontent.com/30150983/86957216-93ef5180-c184-11ea-80d0-8a90751f3a63.png)
**

**Comment by JiHong88** [comment]
You can use the [getCharCount](http://suneditor.com/sample/html/out/document-user.html#getCharCount)
And it is same `editor.getCharCount("char")` === `editor.core.context.element.wysiwyg.textContent.length`

**Comment by anhdoantm** [comment]
Somehow, he doesn't accept it.
Too difficult to ignore. 😂😊

So wait Add **`GetContent`** **NO Code** So.

**Comment by JiHong88** [comment]
Hmm.. is right?
`editor.getContents` is working
`editor.getCharCount` is not working
`editor.core.context.element.wysiwyg.textContent.length` is not working

**Comment by anhdoantm** [comment]
That's right, only `editor.getContents` works.
So If adding or changing **`1Get`** please make `editor.getContents("text")`.

**Comment by JiHong88** [comment]
Are you using suneditor-react?
I added a `getText` method.
You can use it at the next version.

**Comment by anhdoantm** [comment]
No, I'm targeting only using pure javscript, I don't want to rely on the 3rd library.
Thank you for the effort.

**Comment by JiHong88** [comment]
The [2.31.1](https://github.com/JiHong88/SunEditor/releases/tag/2.31.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

PS: The lack of other attributes in editor is that something is wrong.
