### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by gponimansky** [JiHong88/SunEditor#438]
Under setOptions.icons, all icons are working such as print and preview etc, however there is a strange behaviour with full-screen icons:

- expansion
- reduction

As you can see the fullscreen icon has been changed and is showing the correct behaviour. However when I click it to go to the reduction icon.
![Screenshot_2020-07-06](https://user-images.githubusercontent.com/7742170/87462159-7e8f8280-c5dd-11ea-8727-18075a398f6d.png)

The reduction icon that I overwrote is not there. This behaviour gets stranger when I click on the reduction icon.
![Screenshot_2020-07-06](https://user-images.githubusercontent.com/7742170/87462187-86e7bd80-c5dd-11ea-94ca-13c450df2fd7.png)

Now the fullscreen icon has changed to its default.

![Screenshot_2020-07-06](https://user-images.githubusercontent.com/7742170/87462199-8c450800-c5dd-11ea-8944-f9ab8c204e88.png)

**Comment by JiHong88** [comment]
Hi @gponimansky 
Are you using the "icons" option?
```javascript
suneditor.create("..", {
    icons: {
        expansion: "icon",
        reduction: "icon"
    },
})
```

**Comment by gponimansky** [comment]
Correct

**Comment by JiHong88** [comment]
I checked it.
This is a bug when using the responsive toolbar.
I'll notify you after version update at this week.
Thank you.

**Comment by gponimansky** [comment]
Thank you!

**Comment by JiHong88** [comment]
The [2.31.2](https://github.com/JiHong88/SunEditor/releases/tag/2.31.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
