### ISSUE TITLE
HTML Post request

### ISSUE THREAD

**Issue by ATOPBIO** [JiHong88/SunEditor#440]
Hello, is there anything special that must be included to process the SunEditor input via an HTML POST request?

My editor renders on the front-end, but the input is not sent via POST request.

Is there anything I am missing?

**Comment by JiHong88** [comment]
Hi @ATOPBIO 

POST send of editor's contents?
```javascript
const editor = SUNEDITOR.create(...);
const contents = editor.getContents();
post(contents)
```
Question is this correct?

**Comment by ATOPBIO** [comment]
Hello, thanks for your response.

I am using SunEditor for 1 out 4 fields in my form but the submit button does not send input of SunEditor.

I only copy pasted the installation guide, using <textarea> referenced by ID,  without adding anything to integrate with HTML Form action,  Submit in POST request.

I have tried adding the script you wrote above but received an error of "post is not a function".

**Comment by JiHong88** [comment]
Hi,
"post()" was an example.
With `getContents` you can get the content of the current editor and send it to the server.
If you use the `save` button, you can define a function in the `callBackSave` option.

**Comment by ATOPBIO** [comment]
Hello, thanks for your response.

I understand that I must getContents and insert it into the callBackSave at the end of my script.
![image](https://user-images.githubusercontent.com/61521619/87832423-abb68c00-c88e-11ea-9fe9-f88128fca3a6.png)

However, I failed to get it to work yet.

Can you please advice me how should I include getContents to include in the script.

Many thanks in advance

**Comment by JiHong88** [comment]
Hi,
The first argument value of "callBackSave" is "contents".
```javascript
callBackSave: function (contents) {
  alert(contents);
}
```

**Comment by ATOPBIO** [comment]
Hello, thanks for your response. 

I have tried the following using "content" in "callBackSave" but it still doesn't seem to work?
Am I right for using an eventlistner or is there an alternative way to automatically have the input saved without using an onclick listener?

Many thanks in advance

buttonList : [
            ['font', 'fontSize',
            'fontColor', 'hiliteColor', 'video',
            'paragraphStyle', 'textStyle',
            'fullScreen', 'codeView']
        ],
        
function myFunc(action) {
  document.getElementById('submit').addEventListener('click', action);
}
        
 callBackSave: function (contents) {
        alert(contents);
    }
     
    });
</script>

**Comment by JiHong88** [comment]
Hi
You can use the `onChange` event.
```javascript
const editor = suneditor.create(..)
editor.onChange = (contents, core) => {
alert(contents)
}
```

**Comment by ATOPBIO** [comment]
Thank you for your response, after carefully looking into your guidance. I have finally fixed the issue.

For those coming for the same issue, SunEditor (or any other JS input), needs a trigger to SAVE the input, otherwise the browser/form will not recognize new input as "value" unless you SAVE hence the solution required saving, you can do that using an onclick event for the submit button, or (in my case), an on change event. Here is a screenshot of how it should flow.
![image](https://user-images.githubusercontent.com/61521619/88328569-50bee200-cd31-11ea-9016-464080a6bde2.png)

**Comment by yakubu234** [comment]
> Thank you for your response, after carefully looking into your guidance. I have finally fixed the issue.
> 
> For those coming for the same issue, SunEditor (or any other JS input), needs a trigger to SAVE the input, otherwise the browser/form will not recognize new input as "value" unless you SAVE hence the solution required saving, you can do that using an onclick event for the submit button, or (in my case), an on change event. Here is a screenshot of how it should flow.
> 
> ![image](https://user-images.githubusercontent.com/61521619/88328569-50bee200-cd31-11ea-9016-464080a6bde2.png)

in case upcoming did not get the solution here is what he meant 

const editor = suneditor.create(........)
editor.onChange = (contents, core) => {
editor.save();
}
