### ISSUE TITLE
Image Copy and paste

### ISSUE THREAD

**Issue by hongku** [JiHong88/SunEditor#441]
안녕하세요~
에디터에서 이미지 수정 관련해서 질문이 있어서요.
에디터에서 이미지를 복사 & 붙여넣기(ctrl + c & ctrl + v)는 안되는거 같아서
혹시 숏컷 설정이 있나요?
이미 에디터 안에 넣은 이미지의 순서를 변경한다던지 동일한 이미지를 재활용한다던지 할때 유용할 거 같아서
질문드립니다!

**Comment by JiHong88** [comment]
안녕하세요~
지금 이미지만 클릭해서 복사나 잘라내기는 안됩니다.
하지만 있으면 좋은 기능이네요.
추가하겠습니다.

**Comment by JiHong88** [comment]
[2.32.0](https://github.com/JiHong88/SunEditor/releases/tag/2.32.0) 버전이 추가 되었습니다.
이미지의 복사 및 잘라내기는 IE 에서는 동작하지 않습니다.
감사합니다.
