### ISSUE TITLE
Is it possible to disable the download option on the audio player that is created on adding an audio file?

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#442]
I am trying to upload audio files in the editor, but once I do the player shows a download button on the end. It is possible to disable it with a `controlsList="nodownload"` HTML property. Is it possible to do with an option on the editor?

**Comment by JiHong88** [comment]
Currently, there is no option to set the properties of the audio tag.
I'll add it at next version.

**Comment by JiHong88** [comment]
The [2.32.0](https://github.com/JiHong88/SunEditor/releases/tag/2.32.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
