### ISSUE TITLE
How to: onDrop, onPaste, if image, then upload to imageUploadUrl?

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#447]
This is isn't an "issue", I'm just hoping to get some help. How would I connect onDrop and onPaste to the imageUpload mechanism? It seems like this should be possible, but I'm struggling to put the pieces together.

**Comment by JiHong88** [comment]
Hi, @rwaldron 

When drag and drop or paste an image file, image upload is performed automatically.
The same method as when registering an image in the image modal is called.

Images copied with text are pasted as they are.
