### ISSUE TITLE
onChange is not retaining css property in html output 

### ISSUE THREAD

**Issue by sawanmakwana** [JiHong88/SunEditor#452]
Hello,
I am using this editor in my application to get formatted HTML output which can be displayed with the help of iframe.
But the property/styles applied to my text are not reflecting in onChange output and hence I end up getting default basic HTML.
Is this the correct approach? @JiHong88 
I am using the react version of this library and have posted the same issue their also.
I have attached ss of use case

![editor1](https://user-images.githubusercontent.com/45915871/88404040-fa15de80-cdea-11ea-9097-af837f7a77e2.png)
![editor2](https://user-images.githubusercontent.com/45915871/88404054-fd10cf00-cdea-11ea-8a1e-8baddf02e17c.png)
![editor3](https://user-images.githubusercontent.com/45915871/88404059-feda9280-cdea-11ea-88a6-ec527ef1623e.png)

**Comment by JiHong88** [comment]
Hi @sawanmakwana 
I am sorry for the late reply.
The CSS defined above is separate.
It is also impossible to bring css defined above.

**Comment by sawanmakwana** [comment]
@JiHong88 Np...
But then how are style properties of the editor are relevant if we don't get in output...Because the style is visible only in the editor and not in the output.
Is there any way?

**Comment by JiHong88** [comment]
@sawanmakwana 
The style of the editor is specified as "style" or "class".
Common styles require loading a style file on the output screen. ex) "suneditor-contents.css"

**Comment by sawanmakwana** [comment]
Yes, we have to load style or class name to iframe. But I am not able to get how to save/store the currently applied styles of the editor and reflect the same style in an iframe after getting HTML content from the store as I am able to store the only HTML structure and not the styles applied to it. @JiHong88

**Comment by JiHong88** [comment]
@sawanmakwana 
Do you mean you can't bring the "haed" part of "iframe"?

Please tell me the operation more detail.
I don't understand what you want. :(

**Comment by sawanmakwana** [comment]
@JiHong88 
Sorry it was my understanding issue..everything is working fine.
Thanks!
