### ISSUE TITLE
Adding image via link does not seem to work

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#455]
Again, thanks for a great editor and awesome response time here!
I perhaps found a glitch: 
I open up the dialog to add an image via link, add the url in the input field and apply but nothing is inserted. Drag and drop works although (now same image seem to work via link too). Also image upload works. 
Is there something in config I need to consider?

**Comment by JiHong88** [comment]
Hi, @MRB60 
Can you tell me please to the more detail?

**Comment by MRB60** [comment]
Perhaps I have misunderstood the function.
I open "Insert image" dialog and select "Link" (Instead of "Image"). In "URL to link" I insert an URL to an external image and submit.
What is expected to happen? I see nothing changing in textarea.

**Comment by JiHong88** [comment]
"link" tab is image's link url.
`[a:src="url" [img]]`

The image address must be entered in the "Image URL" input.

**Comment by MRB60** [comment]
I add the following string in the input field:
`https://placekitten.com/200/300`
and expected that a link is created in my textarea. I do not see this.
Is this the wrong format? I get no error message.
