### ISSUE TITLE
Question : When I add html, sun editor converts tags to <p>

### ISSUE THREAD

**Issue by cbynirav** [JiHong88/SunEditor#456]
Try to add custom design in sun editor using iframe. When I add my html to sun editor converts all tags to <p> as well as class name also change.

**Comment by JiHong88** [comment]
Hi @cbynirav 
The editor deletes or changes tags that do not meet the criteria.
Please refer this issue. https://github.com/JiHong88/SunEditor/issues/397, reference: https://github.com/JiHong88/SunEditor/issues/412#issuecomment-648065274

**Comment by gabriel-seven** [comment]
Hi Guys. 

Always when the editor is blank and i start inserting text, the editor put my text inside a <p> tag by default.

There is a way to config to put my text inside a <div> tag instead? I tried changing the position of format options putting the <div> as the first item but without success.

Thank you and congrats for the awesome component.

**Comment by JiHong88** [comment]
Hi, @gabriel-seven 

Try like this:

```html
<textarea id="editor"><div><br></div></textarea>
```
or
```javascript
suneditor.create("editor", {
  value: "<div><br></div>"
})
```
