### ISSUE TITLE
Text styles not applied to list item element

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#457]
This issue was reported to me today, so I reproduced it and also did a mock up of what I would expect the correct behavior to look like. 

Here's the reported issue: 

![image](https://user-images.githubusercontent.com/27985/88849873-85f78400-d1b8-11ea-81c2-efa4e51be2a0.png)

And this is the expected formatting: 
![image](https://user-images.githubusercontent.com/27985/88850336-3796b500-d1b9-11ea-80e5-f1fdd6cbb45b.png)

It looks like the style just needs to be put on the `<li>` instead of a `<span>`?

**Comment by JiHong88** [comment]
Hi, @rwaldron 

The list is a single line, and various tags can come.
![a](https://user-images.githubusercontent.com/13191953/89020239-9004b880-d359-11ea-9044-9bf180958f05.PNG)

This is also true for other WYSIWYG editors.
The suggested method is not possible.

Thank you.

**Comment by rwaldron** [comment]
My understanding of our user's feedback is that they expect it to act like google docs:  https://youtu.be/bTUX4qwojUc (Which I agree with)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
