### ISSUE TITLE
Auto remove html tag

### ISSUE THREAD

**Issue by ajayartificialchat** [JiHong88/SunEditor#458]
Sun-editor auto-remove HTML tag like

,
If any tag empty then editor remove this tag
I want to put HTML like this
```
<div class="container">
       <div class="row">
             <div class="col-md-4">Hello</div>
             <div class="col-md-4">Hello</div>
              <div class="col-md-4">Hello</div>
        </div>
</div>
```
but when I put in editor the after it's remove all the

tag only remains only
```
<div class="col-md-4">Hello</div>
<div class="col-md-4">Hello</div>
<div class="col-md-4">Hello</div>
```
Please have any solution for this then guide me
Thanks

**Comment by JiHong88** [comment]
Hi @ajayartificialchat
The editor deletes or changes tags that do not meet the criteria.
Please refer this issue. https://github.com/JiHong88/SunEditor/issues/397, reference: https://github.com/JiHong88/SunEditor/issues/412#issuecomment-648065274

**Comment by ajayartificialchat** [comment]
What about i tag
`<i class='fas fa-layer-group' style='font-size:40px;color:#6d64f7'></i>`
This is replaced with 
`<em></em>`
Please have any solution for this then guide me
Thanks

**Comment by JiHong88** [comment]
There is currently no way.
I'll fix this issue the next version.

**Comment by JiHong88** [comment]
`<i>` is must be have `__se__tag_xxx` class.
`<i class='__se__tag_icon fas fa-layer-group' style='font-size:40px;color:#6d64f7'></i>`

And add the `i` to the `addTagsWhitelist` option.
```javascript
suneditor.create("...", {
  addTagsWhitelist: 'i',
})
```
Available from the next version.

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by vaishnavi-capsitech** [comment]
_**dfd**_
