### ISSUE TITLE
이미지 정렬

### ISSUE THREAD

**Issue by kimhyeongyu** [JiHong88/SunEditor#459]
안녕하세요 정말 잘 사용하고있는 개발자입니다.
이미지를 기준으로 왼쪽에 커서를 둬서 띄어쓰기나 글자를 입력하고싶은데, 가능한 방법이 있을까요?

**Comment by JiHong88** [comment]
안녕하세요~
이미지를 오른쪽 정렬 하시면 됩니다.

**Comment by kimhyeongyu** [comment]
답변감사합니다%^^
오른쪽정렬을 했을때 이미지가 오른쪽에 고정되어있는데, 동적으로 사용하고싶습니다.

예를들면 
가. (실제이미지파일) 

위에처럼 가. 뒤에 이미지를 바로 붙이고 싶은데, 방법이 있을까요?^^;

**Comment by JiHong88** [comment]
음.. 단락안에 이미지가 들어가는게 아니기 때문에,
현재 구조에서는 불가능 합니다.ㅠ
