### ISSUE TITLE
Question: Is there a way to add multiple tags to an image in the image gallery?

### ISSUE THREAD

**Issue by cford256** [JiHong88/SunEditor#460]
I would like to add multiple tags to an image using image gallery.
I tried to add more than one tag by separating the tags with commas like this. 

```
 var obj = {"statusCode":200,"result":[
          {
                 "src": "1.jpg",
                 "name": "title",
                 "alt": "some text",
                 tag": "tag1, tag2"
           },
]};
var url =  URL.createObjectURL( new Blob([JSON.stringify(obj)], {type: "application/json"});)
```

I also tried to do it using an array.

```
 var obj = {"statusCode":200,"result":[
          {
                 "src": "1.jpg",
                 "name": "title",
                 "alt": "some text",
                 tag": [tag1, tag2]
           },
]};
var url =  URL.createObjectURL( new Blob([JSON.stringify(obj)], {type: "application/json"});)
```
but neither of these worked.

Is there a way to accomplish this?

**Comment by JiHong88** [comment]
Currently, not possible.
I'll update at the next version.

**Comment by cford256** [comment]
Sweet! Thank you!

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
