### ISSUE TITLE
`_setDefaultFormat` incorrectly wrap `<ul><div><li>...</li></div></ul>`

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#461]
Try to paste an copied HTML like
```html
<ul>
  <li>111</li>
  <li>222</li>
</ul>
```
the `_setDefaultFormat` will wrap the `<li>`s into `<div>`
```html
<ul>
  <div>
    <li>111</li>
    <li>222</li>
  </div>
</ul>
```

![2020-08-02_16-28-50](https://user-images.githubusercontent.com/313189/89120077-77251000-d4dd-11ea-8d6f-00812986908b.gif)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
