### ISSUE TITLE
Unnecessary text appears when pasting text from Microsoft Word

### ISSUE THREAD

**Issue by hibado** [JiHong88/SunEditor#462]
### Issue description
Copy text from Microsoft Word and paste into SunEditor, the pasted text is not same as the copied text. The pasted text has Microsoft Word's doc message in the previous and css message(definition of font) in the back. The excess text is expected.

### Steps to reproduce the issue

1. Edit text in Microsoft Word without custom format. e.g. A warm welcome to my city! 
2. Paste text into the editor.

### What's the expected result?

The pasted text is:
> A warm welcome to my city! 

### What's the actual result?
The pasted text is:
> Normal
> 0
> 7.8 磅
> 0
> 2
> false
> false
> false
> EN-AU
> ZH-CN
> X-NONE
> A warm welcome to my city!
> /* Style Definitions */ table.MsoNormalTable {mso-style-name:普通表格; mso-tstyle-rowband-size:0; mso-tstyle-colband-size:0; mso-style-noshow:yes; mso-style-priority:99; mso-style-parent:""; mso-padding-alt:0cm 5.4pt 0cm 5.4pt; mso-para-margin-top:0cm; mso-para-margin-right:0cm; mso-para-margin-bottom:8.0pt; mso-para-margin-left:0cm; line-height:107%; mso-pagination:widow-orphan; font-size:12.0pt; mso-bidi-font-size:11.0pt; font-family:"Times New Roman",serif; mso-bidi-font-family:"Times New Roman"; mso-bidi-theme-font:minor-bidi; mso-ansi-language:EN-AU;}

###  Environment
Windows 10/Mac 
Microsoft Word

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/48470563/89160527-cd5c8680-d5a3-11ea-82bb-ee26e897c984.png)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by wxjzeke** [comment]
@JiHong88 
Still have the problem.
Copy from Word, has css message in the previous.
![image](https://user-images.githubusercontent.com/8022227/102955051-fc9e7080-450f-11eb-8f91-8cf0ad8f9e86.png)

**Comment by JiHong88** [comment]
@wxjzeke 
Can you send me the tested Word file to my email?

**Comment by wxjzeke** [comment]
@JiHong88 

File sent ~

And I did some test with below changes then paste looks fine
```js
        _deleteDisallowedTags: function (html) {
           // ...
           // .replace(/<(script|style).*>(\n|.)*<\/(script|style)>/gi, '')  change to
           .replace(/<(script|style)[\s\S]*>[\s\S]*<\/(script|style)>/gi, '')
           // ...
        },
```

**Comment by JiHong88** [comment]
@wxjzeke Thank you. :)
I will update this after code verification.

**Comment by JiHong88** [comment]
@wxjzeke What browser at the tested?

**Comment by wxjzeke** [comment]
@JiHong88 
![image](https://user-images.githubusercontent.com/8022227/103254692-50520380-49c1-11eb-9014-15626a967f12.png)

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
