### ISSUE TITLE
null is shown in width / height input field when constraint proportion checked with 0 in one of the input

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#463]
[Null in Width  or height.zip](https://github.com/JiHong88/SunEditor/files/5016489/Null.in.Width.or.height.zip)
![Null in Width input](https://user-images.githubusercontent.com/26658261/89192638-669a9580-d5c2-11ea-8bf3-e00c2cd1e841.PNG)

**Issue Description**
In Image Selection, null is set when other input is 0px.

**Detailed Steps:**
1. Open Image Dialog,
2. Upload an image.
3. Ensure checkbox [**Constrain Proportions**] is checked.
4. try giving 0 in width or height

**Actual Behavior:**
Null is set in other input

**Expected Behavior:**
0 should be set in other input field also

**Comment by JiHong88** [comment]
`Codedfsaf`

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
