### ISSUE TITLE
ctr+b, ctrl+i and ctrl+u doesn't apply necessary formatting for selected text when it is selected by mouse from the last

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#464]
**Description**
When selected with mouse from the last, keyboard shortcuts for bold italic or underline are not applied to the selected text

**Steps:**
1. Clear editor.
2. Type three or four words
3. With the mouse select form the last letter of the last word till the first letter
4. Press CTRL+B, CTRL+i or CTRL+U

**Actual Behavior:**
Selected text gets deselected and performed shortcut reflects only for upcoming inputs.

**Expected Behavior:**
1. Selection should be maintained
2. Bold, italic or underline should get reflected for appropriate buttons

PFA
[Shortcut Mouse Formatting issue.zip](https://github.com/JiHong88/SunEditor/files/5016603/Shortcut.Mouse.Formatting.issue.zip)

**Comment by JiHong88** [comment]
Hi @vijayaragavan95 
This issue is not reproduce.
Can you upload more detail video file?

**Comment by vijayaragavan95** [comment]
Hi @JiHong88 ,
Its a special scenario issue. 
**Steps:**
1. Open editor newly.
2. Clear all the text if you have any
3. Type two or three words
4. Select the word with **mouse (From the last letter to the beginning)**
(Do exactly as this step)
5. Now perform keyboard shortcuts. Since it is first time it will get reflected.
6. Now select.
7. Repeat step 4 and 5
Now you can see formatting doesn't apply.

**Note:**
- Don't select with ctrl+A because its working.
- Don't select from the beginning of the word that also works.

Just select from the last letter of the word and select till the beginning don't stop in the middle also.

**Actual Behavior:**
Selected text gets deselected and performed shortcut reflects only for upcoming inputs.
(Check the video attached)

**Expected Behavior:**
Selection should be maintained
Bold, italic or underline should get reflected for appropriate buttons

Kindly PFA
[CTRL+v.zip](https://github.com/JiHong88/SunEditor/files/5020021/CTRL%2Bv.zip)

If you still cannot reproduce kindly ping me. 

Moreover could you please let me know when the **milestone 2.33** will become live to us.
I mean if not possible to say accurate date at least let me know approximate month.
Because i have few bugs that you marked them as 2.33.0 milestone.

Thanks in advance.

**Comment by vijayaragavan95** [comment]
@JiHong88 
Thank you. I have seen the deadline of your milestone 2.33.0 in the project.
Could you please confirm the above issue and if anything let me know.

**Comment by vijayaragavan95** [comment]
@JiHong88 
Is there any update regarding this issue?

**Comment by JiHong88** [comment]
@vijayaragavan95 
It is expected to be released this month.
https://github.com/JiHong88/SunEditor/milestone/13

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
