### ISSUE TITLE
Background Color is not applied to whole font size

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#465]
**Description**
Background color is not applied to whole font size.

**Steps:**
1. Clear editor
2. Type two or three words in small font size
3. change font size to 48px.
4. Type three or four words
5. Now apply background color.
6. Try typing any word

**Actual Behavior:**
Background color is not applied to full font size

**Expected Behavior**
Background Color need to be shown for current font size.

**Suggestion**
<span style:"background-color #xxx; **display:'inline-block'**" >

**PFA**
![Background Color Issue](https://user-images.githubusercontent.com/26658261/89195352-4a98f300-d5c6-11ea-969b-4fb408852ea0.PNG)

[Background Color Issue.zip](https://github.com/JiHong88/SunEditor/files/5016664/Background.Color.Issue.zip)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
