### ISSUE TITLE
Feature Request: Allow developer to select custom image extensions in image icon button

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#466]
**Description:**
Image button by default accepts all image file extension.

**Request:**
A prop can be provided in set options to allow developer to decide needed file extensions

**Current Implementation:**
accept:"image/*"

**PFA**
![image extension](https://user-images.githubusercontent.com/26658261/89196070-53d68f80-d5c7-11ea-814f-96965486a80e.PNG)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
