### ISSUE TITLE
Cannot paste code into a code block

### ISSUE THREAD

**Issue by hudsonfoo** [JiHong88/SunEditor#467]
To reproduce:

Select "Code" from format. A new code block will be created. Without moving text cursor, paste into the code block. The pasted text will appear above the code block rather than inside of it.

I can overcome this by hitting "Enter" first which creates a new line in the code block, then pasting, but then I have to delete the extra line.

**Comment by JiHong88** [comment]
Hi @hudsonfoo 
This issue is not reproduce.
Can you tell me more detail?

**Comment by hudsonfoo** [comment]
@JiHong88 Here's a video: https://www.loom.com/share/87ed6d5904cc4b7fb91803f7ff5c2d78

I select "code" then paste code from VS Code. Does this help? I can screenshare as well.

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
