### ISSUE TITLE
[Safari] img src="undefined" / [Chorme] img src="http://~~~"

### ISSUE THREAD

**Issue by hajeonghun** [JiHong88/SunEditor#468]
@JiHong88 안녕하세요.

썬에디터 사용시 서버에서 Contents 값을 받아와 그대로 setContent 해주고 있는데요.

아래와 같이 데이터를 받은 후 띄우면 크롬에선 문제없이 src에 정상적으로 값이들어가 이미지가 노출되는데
ex) `'<p>~!#EWQ<div><img src="http://www.naver.com"/></div>~~</p>'`

사파리에선 src에 자동으로 img src="undefined" 가 들어가 이미지가 노출이 안되는 문제가 있더라고요.

에디터의 브라우저 문제 인가요 ? 혹시, 해결방법이 있을까요?

**Comment by JiHong88** [comment]
@hajeonghun 안녕하세요~
맥 사파리 얘기하시는거죠?

**Comment by hajeonghun** [comment]
제가 잘못 착각한 것 같습니다..ㅎㅎ 죄송합니다.
