### ISSUE TITLE
Add ability to set language on a code block

### ISSUE THREAD

**Issue by hudsonfoo** [JiHong88/SunEditor#470]
Would be great to be able to select a language when hovering over a code block. Once selected, the syntax would highlight appropriately.

![image](https://user-images.githubusercontent.com/1385980/89688609-2a1fb000-d8c8-11ea-81f8-371384f75740.png)

**Comment by JiHong88** [comment]
Hi @hudsonfoo 
Are there any good library you know?

**Comment by hudsonfoo** [comment]
@JiHong88 I had been looking at https://highlightjs.org/ for the wide language support. I was nearly able to integrate it with SunEditor but the SunEditor styles would override Highlight.js. Is there a way to disable SunEditor styles for a specific node?

**Comment by youens** [comment]
We also use https://prismjs.com for syntax highlighting. This would be awesome if we could define a language for a code block so that it would apply a class/attribute!

**Comment by JiHong88** [comment]
I'll modify to disable the style of a specific area.

**Comment by JiHong88** [comment]
@hudsonfoo I added the `se-code-language` class.
If you give the class `se-code-language` to the `<pre>` tag,
the default css will not be applied to the lower `<span>` tags.

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by JiHong88** [comment]
If you have an issue with a code block, please register a new issue.
