### ISSUE TITLE
Inserting image after a line break delete paragraph text

### ISSUE THREAD

**Issue by hudsonfoo** [JiHong88/SunEditor#473]
Type some text, hit shift enter then try to paste an image there. It will release the text in your paragraph.

This also may delete the text below if pasted above. (Even though it looks to the user as if there is a paragraph between.)

You must hit a full enter key (creating a new paragraph) before pasting.

https://t1261137.p.clickup-attachments.com/t1261137/83562ba3-83e8-4825-b234-531e8e5cc1f6/CleanShot%202020-07-23%20at%2016.54.13.mp4?view=open

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
