### ISSUE TITLE
Toolbar에서 특정 버튼만 활성화 되는 기능

### ISSUE THREAD

**Issue by hajeonghun** [JiHong88/SunEditor#475]
@JiHong88 님 안녕하세요.

에디터가 disable=true 상태일때 툴바의 특정 버튼만 활성화 시키고싶은데

아래사진처럼 특정 버튼(ex. 전체화면, 미리보기)만 활성화 할 수 있는 방법이 있을까요?

![image](https://user-images.githubusercontent.com/52861562/89856054-2d21e580-dbd3-11ea-8094-e074863c3484.png)

**Comment by JiHong88** [comment]
@hajeonghun 
아래 코드가 이미지 선택시 버튼 비활성화 하는 코드 입니다.
이걸 사용하시면 될 것 같아요.
`core.util.setDisabledButtons(true, core.resizingDisabledButtons);`

**Comment by JiHong88** [comment]
다음 버전 부터 `toggleDisabledButtons` => `setDisabledButtons` 로 이름이 변경 됩니다.

**Comment by hajeonghun** [comment]
@JiHong88 네 참고하겠습니다.
혹시 추가로, 이미지 업로드시 작은 로딩바가 노출되는걸 적용 안되게 할 수 있을까요?
