### ISSUE TITLE
The default image size is set to zero when it's a SVG, and  toggle the image description is not working for SVG

### ISSUE THREAD

**Issue by michelmar** [JiHong88/SunEditor#476]

**Comment by michelmar** [comment]
Sorry for the delay. I think you can see this issue in the video bellow. Your work is really well done, that's art.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/60835138/90990205-decafa00-e575-11ea-9e48-3720de7e04a0.gif)

**Comment by JiHong88** [comment]
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
