### ISSUE TITLE
Please consider registering SunEditor to bower as package manager

### ISSUE THREAD

**Issue by triawarman** [JiHong88/SunEditor#48]
Hello jihong,
I hope you will register this repo to bower, it will make easier to search and install.

And thanks for your efforts to make SunEditor, i'm sure your's is one of top best Web based text editor.

**Comment by JiHong88** [comment]
thank you so much!

I have registered the source in bower and npm  : )

**Comment by triawarman** [comment]
Thanks JiHong :)
