### ISSUE TITLE
math plugin issues

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#482]
Hi @JiHong88 
I am using the katex plugin for math but it seems to be repeating the keystrokes. Is there anything i am doing wrong.
![Screen Shot 2020-08-21 at 11 47 28 (2)](https://user-images.githubusercontent.com/26695391/90871876-70830d80-e3a4-11ea-8351-28738350116c.png)

**Comment by mkhstar** [comment]
You can use this demo link
[https://codepen.io/mkhstar/pen/wvMpXMZ](https://codepen.io/mkhstar/pen/wvMpXMZ)

**Comment by JiHong88** [comment]
@mkhstar To use "katex" you need to attach "katex" css.
```html
<html>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css">
  <textarea id="sample"></textarea>
</html>
```
