### ISSUE TITLE
Feature Request - Add Table Caption

### ISSUE THREAD

**Issue by kurtmoan** [JiHong88/suneditor#484]
HTML is supporting Caption, but even if I'm trying to add it to the html code of the editor, it is moved to a P-tag above the table when I go back to normal editor mode.

Image below shows demo of caption from [w3schools.com](https://www.w3schools.com/tags/tag_caption.asp)

![image](https://user-images.githubusercontent.com/64800975/91271114-f96dc080-e779-11ea-8c45-4c6f40460e83.png)

**Comment by JiHong88** [comment]
Hi, @kurtmoan 
I'll add table caption at next version.
Thank you.

**Comment by ghilaslinz** [comment]
Hi, @JiHong88  @LeeJiHong  
is this feature (table caption) available ? 

Thank you for your work 
Best regards

**Comment by JiHong88** [comment]
@ghilaslinz It will support at after the v3.0.0 update.
https://github.com/JiHong88/SunEditor/milestone/14
