### ISSUE TITLE
text Drag & Drop(to over Editor or over Window) & Copy -> Paste Error Pls....:(

### ISSUE THREAD

**Issue by GaeTaeng** [JiHong88/SunEditor#485]
안녕하세요, 
먼저 좋은 에디터의 배포에 깊은 감사의 인사를 드립니다.

현재 onCopy부분 수정 중에 제 문제인가싶어 몇시간동안 찾아보다 확인하니
하단 사진과 같은 에러가 있었습니다.

1. 글자를 드래그 화면(에디터) 바깥까지 Drag&Drop 후 복사(Ctrl + C / Command + C)  
2. 이후 붙여넣기 할 시 드래그된 글자들이 사라지지않고 그 뒤로 붙여넣기가 진행됩니다.

http://suneditor.com/ 에서도 확인가능합니다.

제일 하단 캡쳐사진이 있습니다.
해당부분 확인 부탁드립니다.
감사합니다.

--------------------------------------------------------------------------------------------------
[ Conglish ] 
I Want 
   1. text Drag->Drop(Window(Editor) Over) & Copy(Ctrl + C / Command + C) -> (selection text keep state)Paste
     ::> result / (originally) Selection text deleted -> Clipboard text paste
          But    / Select Text Keep -> Clipboard Text Paste back selection Text

This can also be checked in http://suneditor.com/ .

Under is the capture.

![image](https://user-images.githubusercontent.com/41108735/91422754-8c018300-e892-11ea-9d4d-3baf0b3324c5.png)
![image](https://user-images.githubusercontent.com/41108735/91422783-9754ae80-e892-11ea-96fb-87e488f01473.png)

**Comment by JiHong88** [comment]
안녕하세요.
버그 제보해주셔서 감사합니다.
[2.33.1](https://github.com/JiHong88/SunEditor/releases/tag/2.33.1) 버전에서 수정 되었습니다.
이슈가 해결되지 않으면 이 이슈를 다시 열어주세요.
감사합니다.
