### ISSUE TITLE
Image Selection is outside editor - is it possible to keep it within the text area

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#486]
**Issue:**
Blue highlight which is shown for image resizing goes out of the editor. 

**Expected Behaviour:**
Is it possible to keep the selection within the editor by providing vertical and horizontal scroll just alone for the text editor

This looks very awkward when high resolution images are inserted. Whole screen becomes bluish. :(

PFA

![Capture](https://user-images.githubusercontent.com/26658261/91526190-ab46f180-e920-11ea-8a13-2f751347d625.PNG)

[screen-capture.zip](https://github.com/JiHong88/SunEditor/files/5140247/screen-capture.zip)

**Comment by JiHong88** [comment]
Hi @vijayaragavan95 
This is the intended behavior.
Since I can't manipulate the "z-index" outside of the editor, it would be very weird if there was a selection under the toolbar.
Please show me any other good options if you have.

**Comment by vijayaragavan95** [comment]
Hi @JiHong88 ,

Sorry for the delay in reply. I was away due to personal reasons. We tried to come up with the other possibilities but none of them seem to be suitable one.

Is it possible to contain se-resizing-container div within the text editor(sun-editor-editable) div.

Now  se-resizing-container div goes out of editor.

If you have any kindly suggest us.

Thanks in advance.

![Uploading Suggestion.png…]()

**Comment by JiHong88** [comment]
Hi @vijayaragavan95,
Sorry for the delay in reply.😢
Yes it is possible.
But then, when the photo is at the bottom, the button group should move to the top accordingly.
I'll look at the examples of other editors and think again.

**Comment by vijayaragavan95** [comment]
@JiHong88 
Sure :+1: okay thanks a lot. :)

**Comment by vijayaragavan95** [comment]
Hi @JiHong88 ,

Is there any update to this issue?

Thanks in advance.

**Comment by JiHong88** [comment]
@vijayaragavan95 It will be fix in version 3.0.0.
Much needs to be fixed.
