### ISSUE TITLE
Font size not changing

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#487]
**Description:**
Font size change working abnormally

Size not applied and when i change to another size it is getting reflected.
PFA

[screen-capture.zip](https://github.com/JiHong88/SunEditor/files/5161087/screen-capture.zip)

**Comment by JiHong88** [comment]
Hi @vijayaragavan95 
The [2.33.0](https://github.com/JiHong88/SunEditor/releases/tag/2.33.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
