### ISSUE TITLE
Undo toolbar button deletes multiple words after clicking once

### ISSUE THREAD

**Issue by BrianJVarley** [JiHong88/SunEditor#489]
hi @JiHong88, I noticed using undo toolbar buttons that it doesn't always delete the _one_ item or word that you typed after clicking undo _once_. In the case of a list it can delete multiple list item on clicking undo only _once_. Also, on clicking undo once after typing a number of words, it can delete multiple words rather than _one word_ as expected.

Are you planning to fix undo / redo functionality to only? Looking at the source it seems it replaces the content from `stack` and maybe this state is actually stale when you hit the undo button - https://github.com/JiHong88/SunEditor/blob/a6ac981997dc5d3ce00160f34ee19c5df87e172c/src/lib/history.js#L21

**How to re-create:**

A) Adding a list with 3/4 items then hitting undo or ctrl + z. Notice Multiple list items are deleted instead of one list item
after clicking undo _once_.

_Expected Outcome:_ Only one list item is deleted after clicking undo once.
_Actual Outcome:_ Three list items are deleted after clicking undo once.

B) Type a number of words, for example `hi hi hi hi hi`. Notice after clicking undo button once, it actually deletes 2/3 words rather than one word as expected.

_Expected Outcome:_  Only one word is deleted after clicking undo once.
_Actual Outcome:_ Three words are deleted after clicking undo once.

**Bug:**

Example Sun Editor Undo: (multiple items / words deleted after clicking undo once)
![sun-editor-undo](https://user-images.githubusercontent.com/6731968/92134220-2d438880-ee01-11ea-909c-e6a74d30c86b.gif)

Example Microsoft Word Undo: (one word deleted per undo)
![msoffice](https://user-images.githubusercontent.com/6731968/92134215-2c125b80-ee01-11ea-9c3a-1338b496a0de.gif)

**Comment by JiHong88** [comment]
Hi @BrianJVarley 
The history stack is saved after 400 milliseconds from the last input.
This is because it is not to use too much memory, and it is good for the user to return quickly inputted contents at once.
Other editors behave similarly.

**Comment by BrianJVarley** [comment]
@JiHong88 It makes sense from a memory standpoint. But in practice it seems undo function isn't predictable. If as a user I hit undo once I'd expect one word to be deleted. But an unknown range of the editor content is deleted instead. 

Is there any option to extend the default undo using custom plugins?

**Comment by JiHong88** [comment]
@BrianJVarley I will add an option to adjust the delay time.

**Comment by JiHong88** [comment]
The [2.33.1](https://github.com/JiHong88/SunEditor/releases/tag/2.33.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
