### ISSUE TITLE
Critical Bug: Images delete all exiting editor data on adding

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#491]
@JiHong88 In the latest release, when you try adding images twice, the first image gets replaced.

Steps to reproduce:
1. Initialize an empty editor
2. Add an image
3. Now add another image (or same image)

You will see that you still have only one image in the editor (the latest one you tried copying)

Even if you click on the enter icon on the bottom of the image and try pasting the new image, it still replaces the old image.

However, if I add a character after clicking the enter icon on the bottom of the image, the new image gets pasted fine.

**Comment by JiHong88** [comment]
The [2.33.1](https://github.com/JiHong88/SunEditor/releases/tag/2.33.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
