### ISSUE TITLE
Link not work on 2.33.0

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#492]
From release 2.33.0, the link feature not work any more.
![2020-09-05_14-58-34](https://user-images.githubusercontent.com/313189/92300839-5b070980-ef88-11ea-9d4c-7854639f22c0.gif)

**Comment by JiHong88** [comment]
The [2.33.1](https://github.com/JiHong88/SunEditor/releases/tag/2.33.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
