### ISSUE TITLE
Feature Request - Video & Audio Gallery

### ISSUE THREAD

**Issue by schamberg97** [JiHong88/suneditor#495]
Good day! Absolutely loving SunEditor! However, seeing that the SunEditor offers convenient Image Gallery functionality, it seems odd that it is not available for video and audio. Therefore, I am curious to know - are there any plans to implement it in the future? Thank you in advance for your answer 👍

**Comment by JiHong88** [comment]
Hi @schamberg97 
I didn't add it because it's not commonly used.
the "fileBrowser" module allows users to create custom plugins.
I will update the custom plugin example using a file browser later.
