### ISSUE TITLE
Question : Background and fore colour

### ISSUE THREAD

**Issue by AversaConsulting** [JiHong88/SunEditor#496]
Is there any way to style the suneditor so use the current background-color and color?

If I have a div that is black background and white text, I'd like it to show the same once I'm editing if possible. 

Many thanks!

Nick

**Comment by JiHong88** [comment]
Hi @AversaConsulting 
You can redefine a CSS class.
https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css#L9

**Comment by AversaConsulting** [comment]
Thanks - will give this a go - but had wondered if there was a property to pass in. I have multiple editors on a page, each with potentially different styles - mainly background and fore colour.

**Comment by JiHong88** [comment]
@AversaConsulting Sorry for the delay in reply.
If there is an ID in "textarea", each editor has an ID. (`suneditor_${textarea.id}`

ex:
```html
<textarea id="editor1"></textarea>
```
The ID of the created editor is `suneditor_editor1`

**Comment by AversaConsulting** [comment]
Many thanks!
