### ISSUE TITLE
Customizing auto adding font feature to element

### ISSUE THREAD

**Issue by lehuuthoct** [JiHong88/SunEditor#497]
Hello,

Is there a way for us to automatically disable adding fonts for elements in the editor. 

**Example:** 
Data preparation :  Data is taken from different sources or platforms with different format (eg: relational databases - MySQL, Postgres, Nonrelational databases : MongoDB, HBase, Cassandra, Flat files: csv - comma separated values ).

It'd be great if it's possible to remove the code auto added code 
`<strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">`

HTML Code
`<p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Data preparation</font></font></strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> :&nbsp;                   </font></font><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Data is taken from different sources or platforms with different format (eg: </font></font></span><strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">relational databases</font></font></span></strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> - MySQL, Postgres, </font></font></span><strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nonrelational databases</font></font></span></strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> : MongoDB, HBase, Cassandra, </font></font></span><strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Flat files:</font></font></span></strong><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> csv - comma separated values </font></font></span><span style="letter-spacing: -0.3px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">).</font></font></span><br>`
</p>

Thanks

**Comment by JiHong88** [comment]
Hi @lehuuthoct 
You must be extract and apply text directly from your data.
You can 'editor.setContents()' or value option
```javascript
const editor = suneditor.create("id", {
  value: ""
))
// or
editor.setContents("")
```
