### ISSUE TITLE
option.imageAccept doesn't seems to work

### ISSUE THREAD

**Issue by vn516726** [JiHong88/SunEditor#498]
Hello,

when imageFileInput turn on, it will create the following dom
- <input class="se-input-form _se_image_file" type="file" accept="image/" *="">

maybe something wrong in this line, could you help to take a look?
thanks : )

https://github.com/JiHong88/SunEditor/blob/6056388edd8fbcbc446a5ee9cc546854a4482e5b/src/plugins/dialog/image.js#L144

**Comment by JiHong88** [comment]
@vn516726 Thank you for your contribution.
I'll notify you after the version update.

**Comment by vijayaragavan95** [comment]
Hi @JiHong88 

Is this fix released ?
Kindly confirm. Because i have same issue in Suneditor react

Thank you.

**Comment by JiHong88** [comment]
@vn516726 @vijayaragavan95 
The [2.33.2](https://github.com/JiHong88/SunEditor/releases/tag/2.33.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
