### ISSUE TITLE
Reset text styling on new line/enter

### ISSUE THREAD

**Issue by CMTietgen** [JiHong88/SunEditor#5]
After entering some text I highlighted the last word and bolded it. I then placed my cursor at the end of the line and pressed enter.

When I started typing the next line was also bold, but I would think it should return to normal, since a new paragraph tag was completed.

Is this intended?

**Comment by JiHong88** [comment]
Yes, It is intended.
Other editors are all working the same way.
I thought that changing the size of the text or making it bold would work regardless of the line breaks.

**Comment by JiHong88** [comment]
I modified and committed.
Commit version : "fix : Reset text styling on new line"

**Comment by JiHong88** [comment]
This issue resolved at the v2.42.0.
You can use the `lineAttrReset` option.
