### ISSUE TITLE
Link unlink function not working

### ISSUE THREAD

**Issue by svermaak** [JiHong88/SunEditor#502]
If I go to Sun Editor, in my own code or http://suneditor.com/sample/index.html, the unlink option does not work

![image](https://user-images.githubusercontent.com/12259728/93435449-1a43b480-f8e7-11ea-9a9f-a6a0fd59eb33.png)

**Comment by JiHong88** [comment]
The [2.33.3](https://github.com/JiHong88/SunEditor/releases/tag/2.33.3) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by svermaak** [comment]
Thank you bud
