### ISSUE TITLE
Image upload figure Div size..

### ISSUE THREAD

**Issue by GaeTaeng** [JiHong88/SunEditor#510]
안녕하세요,
먼저 좋은 에디터를 제작하여 공유해주심에 깊은 감사의 인사를 드립니다.

현재 SunEditor-react 를 이용하여 에디터를 이용 중에 있는데,
이미지의 업로드 등의 상황에서는 아무런 문제가 없으나, 업로드 이후에 이미지를 감싸는 
`"<div class = "se-component se-image-container __se__float-none">"` 태그의 width 사이즈가 에디터를 꽉 채우고 있습니다
![image](https://user-images.githubusercontent.com/41108735/93973088-95590f00-fdae-11ea-9042-4f3cc8e6b839.png)

100% 75% 50%의 버튼을 이용해서는 해당 div 태그의 사이즈가 조정되고 있지만, (하단 75% 버튼 클릭 사진)
![image](https://user-images.githubusercontent.com/41108735/93974292-94c17800-fdb0-11ea-8db9-56b86fb0352a.png)

그 외의 이미지 사이즈 변경을 위한 <div class = "se-modal-resize" .. 등을 활용해서는 
상단 사진과 같이 계속 width가 꽉차있는 현상이 발생하고 있습니다.
혹 Core등에서 해당 부분에 대하여 수정할 수 있는 부분이 있을지 궁금하여 이렇게 문의드립니다.

확인부탁드립니다.
감사합니다.

하단은 웹 개발자 도구 상에서 나타나는 html 코드입니다.
```
<div class="se-component se-image-container __se__float-none" contenteditable="false" style="">
	<figure style="margin: 0px;">
		<img src="----" alt="" data-rotate="" data-proportion="true" 
		data-size="499px," data-align="none" data-file-name="1593409212440.PNG" data-file-size="0" data-origin="auto,200px" 
		style="width: 499px;" data-rotatex="" data-rotatey="" data-index="0">
	</figure>
</div>
```

**Comment by JiHong88** [comment]
안녕하세요~
이미지가 왼쪽 또는 오른쪽 정렬 상태가 아닐때는
라인 전체를 차지하도록 의도된 것 입니다.
혹시 해당 형식이 문제가 있나요

**Comment by GaeTaeng** [comment]
> 안녕하세요~
> 이미지가 왼쪽 또는 오른쪽 정렬 상태가 아닐때는
> 라인 전체를 차지하도록 의도된 것 입니다.
> 혹시 해당 형식이 문제가 있나요

위 사진 둘다 왼쪽 정렬 상태입니다.

50, 75, 100의 경우 에는 해당 이미지의 사이즈에 맞게 이미지를 감싸는  1번사진(사용자 임의 사이즈 변경)의 점선이 
2번 사진(50%)에서는 적용되지 않고있습니다.
(사용자 임의 사이즈 변경)
![image](https://user-images.githubusercontent.com/41108735/94213188-2f38cd00-ff11-11ea-8f27-3d3c0a9c86d7.png)
(50% 지정)
![image](https://user-images.githubusercontent.com/41108735/94213241-4972ab00-ff11-11ea-9de6-57582743bd68.png)

sunEditor.com  에서는 발견되지 않고있어서 제 실수인것으로 확인되지만
이 해결법을 모르겠어서 하단사진의  style을 가지고 있는 부분에
직접적으로 style 변경 할 수 있는 방법에 대하여 문의드리려합니다.
element.style 이라고 되어있는 부분이 50, 75, 100으로 수정하였을 때 입력되는것으로 보아
core 등에서 저 부분을 건드릴 수 있는지 알고싶습니다.
![image](https://user-images.githubusercontent.com/41108735/94213542-0402ad80-ff12-11ea-9116-e1074a66dca5.png)
![image](https://user-images.githubusercontent.com/41108735/94213569-1846aa80-ff12-11ea-88f3-27a32843bb7f.png)



이로인하여 사진을 담고있는 박스의 점선들이 가로를 꽉 채워 사용을 하고있습니다.

**Comment by JiHong88** [comment]
일단 업로드하신 이미지는 왼쪽정렬 상태가 아닌 것 같습니다.
정렬후 이미지를 선택하면 왼쪽, 오른쪽, 가운데, 기본 이렇게 네가지중 하나가 표시됩니다.
![image](https://user-images.githubusercontent.com/13191953/94225492-14c21c00-ff30-11ea-9f5a-4418d4b6a3cf.png)

DIV 크기를 내부 컨텐츠에 맞추려면
`.sun-editor-editable .se-component` 클래스의 `display`속성을 바꾸면 됩니다.
>>>
```css
.sun-editor-editable .se-component {
    display: inline-block;
}
```
현재 기본값은 `display:flex;` 입니다.
기본 css를 바꿀지는 다시 고려해 보겠습니다.

**Comment by GaeTaeng** [comment]
아 ,, 죄송합니다  너무 단순한 실수를 하고있었네요
왼쪽이라고 생각했던게 기본상태였었습니다.

알려주신 내용을 추가하여 기본에대한 CSS 수정 완료하였습니다.

친절하게 알려주셔서 정말 감사합니다.
