### ISSUE TITLE
Bug: Error while adding multiple images

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#511]
Hi @JiHong88 ,

Steps to reproduce the issue.

1. Try adding an image to the editor.
2. Now click on the enter symbol on the bottom of the image to add a new line. You could also use your cursor and click below the image to add new line.
3. Try repasting the same image or a new one.

The new image gets added on top of the old one.

Ideal behavior is to add where the cursor is.

When I try adding two new lines before adding the second image, the image gets added to its desired position but removes the new lines added.

**Comment by JiHong88** [comment]
The [2.34.0](https://github.com/JiHong88/SunEditor/releases/tag/2.34.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by rexpan** [comment]
@JiHong88  Try to insert multiple images, the images are inserted in various places.
![bug](https://user-images.githubusercontent.com/313189/96423744-f7792880-1223-11eb-850e-835090167676.gif)

If the current cursor in the same line, it seems work fine
![work](https://user-images.githubusercontent.com/313189/96423825-0eb81600-1224-11eb-84aa-c3dc5980a6c4.gif)
