### ISSUE TITLE
Double image after replacing result in onImageUploadBefore

### ISSUE THREAD

**Issue by svermaak** [JiHong88/SunEditor#513]
When I use onImageUploadBefore to upload an image and return new result object, I get two images in the editor, one with the updated image URL from the upload function and one that is base64. 

How do I prevent the second, base64 image from showing?

Here's a rough code example of what I am doing
```
onImageUploadBefore: async (files: File[], info: object, uploadHandler: Function) => {
let fileName = await helpers.ddddd(files[0]);
let res = {
"result": [{ "url": fileName, "name": files[0].name, "size": files[0].size },]
};
uploadHandler(res);
}
```

**Comment by JiHong88** [comment]
Are you using the "imageUploadUrl" option?

**Comment by svermaak** [comment]
I have added imageUploadUrl to prevent the double image but I can see failed upload because of this. I do not want to call a web service, I am using the function

**Comment by quanlatoi** [comment]
> Are you using the "imageUploadUrl" option?

I'm have same issue. I'm use `handleImageUpload` function and try to log all params. I'm see `handleImageUpload` run 2 times, the first time run when i click submit button, the second time run when function `uploadHandler` run in function `onImageUploadBefore` .

**Comment by JiHong88** [comment]
@svermaak @quanlatoi 
If undefined is returned, it waits until `uploadHandler` is executed.
Dont't using `async function`.
If used `async function` that the promise object is returned and the basic functions of the editor are executed.

**Comment by svermaak** [comment]
I have to use async for my upload function

**Comment by svermaak** [comment]
Thank you

I have done this to solve my issue.

I removed imageUploadUrl  and change it to synchronize with asyc function

Thank you for all your help and time
 
```
onImageUploadBefore: (files: File[], info: object, uploadHandler: Function) => {
(async () => {
let fileName = await helpers.uploadFile(files[0]);
let res = {
"result": [{ "url": fileName, "name": files[0].name, "size": files[0].size },]
};
uploadHandler(res);
})();
uploadHandler();
}
```
