### ISSUE TITLE
Applied Styles are not reflected to new line

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#514]
**Issue :** 
Applied Styles are not reflected to new line

**Steps to Reproduce:**
1. Open Suneditor (http://suneditor.com/sample/index.html)
2. Clear all contents
3. Type two or three words
4. Press enter to go to new line
5. Press CTRL+A 
6. Press CTRL +b then CTRL +i then CTRL + U
Note : Bold, Italic, Underline Icons are blue highlighted in toolbar panel
7. Now press CTRL + B
Note : All highlights get disappeared
8. Click on the new line you added and start typing
You can see applied style is not applied.

**Expected Behaviour:**
1. Highlight should maintain.
2. Style should be applied for new line also since it is also selected.

**Issue Proof:**
[Issue_New Line Style not applied.zip](https://github.com/JiHong88/SunEditor/files/5299927/Issue_New.Line.Style.not.applied.zip)

**Comment by JiHong88** [comment]
The [2.34.0](https://github.com/JiHong88/SunEditor/releases/tag/2.34.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
