### ISSUE TITLE
Feature Request (re-open) - Mentions Plugin 

### ISSUE THREAD

**Issue by moialbla** [JiHong88/suneditor#515]
Hi,

I was searching if the component has the mentions plugin and I have not seen anything about that. However, I've been seeing one feature request in 2018 about to have this plugin and you closed the issue (https://github.com/JiHong88/SunEditor/issues/27). My question is,  does suneditor have this plugin ready? if so, where can I see it?.
Thank you in advance,

**Comment by JiHong88** [comment]
Hi @moialbla 
There are plans to add the Mansion plugin, but it hasn't been added yet.
It is currently difficult to tell the exact date of the addition. :(

**Comment by NickyTope** [comment]
I have submitted a PR with a proposed mention plugin, you may test it here: https://github.com/isw-kudos/SunEditor

**Comment by bryant8888** [comment]
Hi @JiHong88 
I'm trying to figure out how to connect the mention plugin. Is he in working order at all?

**Comment by JiHong88** [comment]
@bryant8888  Please test it out.
I can't be sure, because the version has been updated a lot during that time.
It will be officially added in version 3.0.0.

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/milestone/14
I'm currently refactoring our code.
It takes a lot of time.
