### ISSUE TITLE
Balloon toolbar positioning different for keyboard and mouse

### ISSUE THREAD

**Issue by andylwelch** [JiHong88/SunEditor#517]
When I select text with the mouse in a Balloon type SunEditor, it works perfectly:

![image](https://user-images.githubusercontent.com/7505965/95528525-14dc1480-0a24-11eb-8ee8-43cc81fa68f6.png)

However, when I select text with the keyboard the toolbar goes up instead, and cant be shown in my stacking context:

![image](https://user-images.githubusercontent.com/7505965/95528560-29201180-0a24-11eb-9858-c49f2be47068.png)

It might be worth implementing something like this:
https://quilljs.com/docs/configuration/#bounds

**Comment by JiHong88** [comment]
@andylwelch The position of the toolbar is determined according to the text selection direction.
When you select text to the left direction, the toolbar is displayed at the top.
The opposite case is display below.
Adjust the "z-index" of the editor and your context.
`.sun-editor {z-index: }`

**Comment by andylwelch** [comment]
Thanks for the reply. My page is fairly complex and uses `position: relative` which changes the stacking context and therefore `z-index` cannot fix this.

I also tried the `toolbarContainer` option to attach the toolbar to the DOM higher up the tree but this doesn't seem to apply to 'balloon' editors?

I can see why you made it left/right selection causes up or down. Can we either fix the `toolbarContainer` for balloon or allow an option to customise to always use below? Thanks

**Comment by andylwelch** [comment]
So I managed to fix the issue showing the balloon toolbar. I moved an 'overflow: auto' scroll from a parent container to a sibling. It would still be great if the balloon editor could attach higher in the DOM (ie on the body) and then absolutely position itself to the target text but I will close this for now. Thanks

**Comment by JiHong88** [comment]
@andylwelch Sorry for the late reply.
Are you saying you moved the toolbar's position to the body of the DOM rather than inside the editor?

**Comment by JiHong88** [comment]
@andylwelch 
There is an option called `toolbarContainer`.
The toolbar is rendered in the DOM specified in `toolbarContainer`.

But when in "balloon" mode it won't help as it is being brought back into the editor when viewed.
I'll modify this option so that the toolbar doesn't move.
Then can you resolve it using this option?

```html
<div class="sun-editor" id="toolbar_container"></div>
```
```javascript
suneditor.create("id", {
  toolbarContainer: "#toolbar_container" // or document.getElementById("toolbar_container")
})
```

**Comment by andylwelch** [comment]
In the end I left it where it was and fixed the out of bounds issue by moving the scroll from the parent of the editor, to the sibling.

Allowing the `toolbarContainer` during balloon mode would be good, but it will require more position calculation work in the SunEditor for it to appear hovering over the text selected.

**Comment by JiHong88** [comment]
Depending on the mode, the editor may stretch without scrolling.
And the moving of the scroll may have a side effect on the position calculation of other controllers.

In the current "Balloon" mode, the toolbar calculates the position of the current editor, and if there is no more space than the height of the toolbar in the window, it is created in a downward direction.

I'll change the calculation criteria of this to the editing area of the editor.
Then the toolbar will never come out of the editor.
It seems that [ckeditor](https://ckeditor.com/ckeditor-5/demo/#balloon) also uses this method.

**Comment by nickelaos** [comment]
I can still reproduce this issue. 
Version: 
```
"suneditor": "^2.47.0",
"suneditor-react": "^3.6.1"
```
Config:
`import React, { useMemo, useRef } from "react";
import { VisualizationComponent } from "../types";
import { textHelper } from "./helper";
import { useTranslation } from "react-i18next";
import { useStore } from "effector-react";
import clsx from "clsx";
import SunEditor from "suneditor-react";
import SunEditorCore from "suneditor/src/lib/core";
import {
  $text,
  changeTextVisualizationContent
} from "@app/features/visualization/models/setup";
import { $lang } from "@app/features/core";
import "./styles.less";

export const TextVisualization: VisualizationComponent = ({ params }) => {
  const { t } = useTranslation();

  const lang = useStore($lang);

  const editor = useRef<SunEditorCore>();

  const isVisualizationPage =
    window.location.pathname.includes("/visualization/");

  const value = useStore($text);

  const editorLang = useMemo(() => {
    switch (lang) {
      case "uk":
        return "ua";
      case "ru":
        return "ru";
      case "en":
        return "en";
      default:
        return "en";
    }
  }, [lang]);

  const className = clsx({
    "text-visualization": true,
    "text-visualization--editable": isVisualizationPage,
    "text-visualization--not-editable": !isVisualizationPage
  });

  const getSunEditorInstance = (sunEditor: SunEditorCore) => {
    editor.current = sunEditor;
  };

  const handleChange = (val: string) => {
    changeTextVisualizationContent(val);
  };

  return (
    <SunEditor
      getSunEditorInstance={getSunEditorInstance}
      lang={editorLang}
      height="100%"
      setDefaultStyle={"font-family: Roboto; font-size: 14px;"}
      placeholder={t("ENTER_TEXT_PLACEHOLDER")}
      setOptions={{
        mode: "balloon",
        resizeEnable: false,
        resizingBar: false,
        buttonList: [
          ["font"],
          ["fontSize"],
          ["bold", "underline", "italic", "strike"],
          ["align"],
          ["list"],
          ["fontColor"],
          ["hiliteColor"],
          ["lineHeight"],
          ["removeFormat"]
        ],
        font: [
          "Roboto",
          "Arial",
          "Georgia",
          "Impact",
          "Tahoma",
          "Times New Roman",
          "Verdana",
          "Courier New",
          "Comic Sans MS"
        ],
        fontSize: [8, 10, 12, 14, 16, 18, 20, 22],
        lineHeights: [
          { text: "1", value: 1 },
          { text: "1.3", value: 1.3 },
          { text: "1.5", value: 1.5 },
          {
            text: "1.8",
            value: 1.8
          },
          { text: "2", value: 2 }
        ],
        minHeight: "300",
        className: className,
        toolbarContainer: "#toolbar__container"
      }}
      setContents={isVisualizationPage ? value : params.$text}
      disable={!isVisualizationPage}
      onChange={handleChange}
    />
  );
};

TextVisualization.helper = textHelper;
`

**Comment by nickelaos** [comment]
@JiHong88 Please, tell me how to fix this issue. I need to display the balloon toolbar always at the bottom (no matter how the user selects the text - left to right or right to left). Can you please add such an option?
