### ISSUE TITLE
Can I edit the ToolBar's tooltip? && Can I modify the function of the button?

### ISSUE THREAD

**Issue by GaeTaeng** [JiHong88/SunEditor#520]
![image](https://user-images.githubusercontent.com/41108735/95833764-0de03980-0d77-11eb-996b-499fa34ca3d8.png)

현재 ToolTip의 단축키 기호에서
command가 기호로 표시되고있습니다.
이 부분을 command로 수정할 필요가 있는데, 혹 수정할 수 있는 기능이 있을까요??..

----------

추가로 미리보기 버튼에 대해서 보여지는 양식에 대해서 하단과 같이 보이게끔 수정이 필요로하는데, 
해당 버튼에 대해서 커스텀이 가능한지 궁금합니다!
![image](https://user-images.githubusercontent.com/41108735/95938380-babcc400-0e14-11eb-9a16-c83df43e741b.png)

**Comment by JiHong88** [comment]
음.. 보통 기호를 사용하지 않나요?
OS가 윈도우, 맥일때 달라집니다. ('⌘' : 'CTRL')
현재 바꿀 수 있는 방법은 없습니다..

미리보기도 현재는 커스텀이 불가능 합니다.
또는 에디터 정의때 마다 소스를 직접 수정해서 사용할 수는 있습니다.
```javascript
const editor = suneditor.create()
editor.core.preview = function () {
//
}.bind(core)
```

core.js 의 preview 함수에서 `windowObject.document.write...` 부분에 추가하면 될 것 같습니다.
미리보기는 HTML을 추가할 수 있게 업데이트 하겠습니다.

**Comment by JiHong88** [comment]
[2.34.0](https://github.com/JiHong88/SunEditor/releases/tag/2.34.0) 버전이 업데이트 되었습니다.
"previewTemplate" 옵션이 추가 되었습니다.
감사합니다.

**Comment by GaeTaeng** [comment]
감사합니다.
