### ISSUE TITLE
core.js: An exception occurred while resetting the "Range" object.

### ISSUE THREAD

**Issue by BrianJVarley** [JiHong88/SunEditor#525]
Hi @JiHong88 ,

I'm using the following function to clear the editor body text. The function use's `commandHandler` to selectAll content and remove the node. But after calling this function I'm getting a warning emitted from `core.js` lib about resetting RANGE object.

Is it possible to expose a public property on SunEditor to clear the body text? Or would you suggest a different approach to my function below? 

```
 @Input() set clearText(clearText: boolean) {
    if (clearText && this.editorInstance) {
      this.editorInstance.core.commandHandler(null, 'selectAll');
      this.editorInstance.core.removeNode();
    }
  }
```

Console Error:
core.js?4e0d:1630 [SUNEDITOR.core.removeNode.exception] An exception occurred while resetting the "Range" object.

Complete Stack Trace:

![image](https://user-images.githubusercontent.com/6731968/96461468-52a71d00-121c-11eb-95c6-a9a37269e5bf.png)

**Comment by JiHong88** [comment]
Thanks for reporting.

Resets the "Range" object when deleting, inserting, or modifying a node.
This warning is displayed when the cannot be set appropriate text node to the "container" when run "removeNode" method.
But in most cases, the code runs fine.

I put a warning because it occurs in certain situations.
Can you show the HTML of the editor when outputting the warning?

**Comment by BrianJVarley** [comment]
Hi @JiHong88 ,

I've recently updated to new "suneditor": "2.34.0" package. But I noticed that our function to delete editor contents has stopped working. The function calls `commandHandler` and `removeNode` but the editor contents isn't deleted. I've attached a GIF below. 

```
      this.editorInstance.core.commandHandler(null, 'selectAll');
      this.editorInstance.core.removeNode();
```


Did you make any changes to `SunEditor.Core` API to how you can access and delete the editor content / node?

![email-editor-delete-node-bug](https://user-images.githubusercontent.com/6731968/98006993-c6cfec00-1dea-11eb-8b94-f2a570b739bd.gif)

**Comment by BrianJVarley** [comment]
I was planning to use the `editor.setContents('')` but it actually adds a `<p><p>` tag to the editor body when you try to set contents to an empty string. In our use case this makes the cursor jump to a new line which isn't correct.

**Comment by BrianJVarley** [comment]
:+1:

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by ColmShannon** [comment]
Hi, thanks, that seems to have resolved our issue.
