### ISSUE TITLE
Is it possible to change the default tags?

### ISSUE THREAD

**Issue by davetimmins** [JiHong88/SunEditor#526]
Hi,

is it possible to change the default tag used for a button? 

I am wanting to use `<s>` or `<strike>` instead of `<del>` as the `<del>` tag is not supported in Excel, so if I copy from this control and paste into Excel it loses the strikethrough formatting.

Thanks

**Comment by JiHong88** [comment]
Hi,
Tags that do not conform to the HTML5 standard are converted to tags that conform to it.

Please write down the information of the tag to be converted.
I'll add an option.

**Comment by davetimmins** [comment]
Thanks
I would like `<del>` to be converted to `<s>`

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
