### ISSUE TITLE
KaTeX CSS issue for apple devices

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#529]
There is an issue in displaying KaTeX formula. Digging deep I found the issue with this CSS code snippet
`.sun-editor-editable :not(.se-code-language .katex) span`

This does not have any issue with devices other than Apple, for all browsers on iOS and Safari for macOS. Apple supports its browser to have concatenation in `:not` whereas no other browser supports this right now. 

Removing this snippet solved the problem for me. Not sure what this code actually does.

**Comment by JiHong88** [comment]
This code was added as an improvement on this issue. #470 
Does it work normally when modified like this? `.sun-editor-editable span { ..`
