### ISSUE TITLE
To much paragraph tags

### ISSUE THREAD

**Issue by zarat** [JiHong88/SunEditor#53]
Hi, i want to use your editor in one of my project but is it possible to prevent the editor of adding `<p>` Tags? Everytime i want to edit a text, it adds one more `<p></p>` at the beginning and at the end of the document. So when i edit a text 5 times it looks like

`<p></p>`
`<p></p>`
`<p></p>`
`<p></p>`
`<p></p>`
`<p>Here is my text</p>`
`<p></p>`
`<p></p>`
`<p></p>`
`<p></p>`
`<p></p>`

i have edited

```
            if (element.value.length > 0) {
                this.contentWindow.document.body.innerHTML = '<p>' + element.value + '</p>';
            } else {
                this.contentWindow.document.body.innerHTML = '<p>&#65279</p>';
            }
```
to
```
            if (element.value.length > 0) {
                this.contentWindow.document.body.innerHTML = element.value;
            } else {
                //this.contentWindow.document.body.innerHTML = '<p>&#65279</p>';
            }
```
is there another (good practice) way?

**Comment by JiHong88** [comment]
Hi, It was a bug I knew.

But I did not know that so many P tags were generated.

I'll fix it quickly!

Thanks for finding the bug : )

**Comment by JiHong88** [comment]
I have fixed this issue : )

i have edited

           if (element.value.length > 0) {

                var tag, innerHTML = "";
                var baseHTML = element.value.split("\n");

                for (var i = 0, len = baseHTML.length; i < len; i++) {
                    tag = document.createRange().createContextualFragment(baseHTML[i]);
                    tag = (tag.children && tag.children.length > 0) ? tag.children : tag.childNodes;

                    if (!/^P$/i.test(tag[0].tagName) && baseHTML[i].trim().length > 0) {
                        baseHTML[i] = "<P>" + baseHTML[i].trim() + "</p>";
                    }

                    innerHTML += baseHTML[i];
                }

                this.contentWindow.document.body.innerHTML = innerHTML;
            } else {
                this.contentWindow.document.body.innerHTML = "<p>&#65279</p>";
            }

**Comment by zarat** [comment]
Really nice, thanks :D

**Comment by JiHong88** [comment]
Hi~
I didn't know that opened this issue..
It will work now : )

**Comment by JiHong88** [comment]
Hi~
I didn't know that opened this issue..
It will work now : )
