### ISSUE TITLE
Multiple instances of suneditor and the same dialog function

### ISSUE THREAD

**Issue by michelmar** [JiHong88/SunEditor#531]
Is it possible to have multiple suneditor instances in the same page and use the same dialog plugin ?
I'm trying to use the math plugin in some instances and everytime I call the math plugin in each instance it creates a new instance of my math plugin, but I would like to use the same, is it possible to add this functionality?

**Comment by michelmar** [comment]
I think a better call for me would have a functionality of  Multi-root editor li we see in the ck editor 5. 
[Multi-root editor](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html
)

**Comment by JiHong88** [comment]
Hi @michelmar 
It seems to be a good feature.
We will add it in version 3.0.0.
