### ISSUE TITLE
Some characters not accepted in editor

### ISSUE THREAD

**Issue by xlthor** [JiHong88/SunEditor#532]
Within the edit box, some of the characters are not accepted:

- simple quote **'**
- "Degree" sign **°**

(copying them in works, typing via keyboard doesn't work)

**Comment by JiHong88** [comment]
Hi @xlthor 
This issue is not reproduced.
Please tell me the test environment and input shortcut.
https://degreesymbolmac.com/

**Comment by xlthor** [comment]
For me it's reproducible on http://suneditor.com/sample/index.html with Fireforx 82.0.1

**Comment by JiHong88** [comment]
- simple quote '
 - "Degree" sign °

How did you enter the two symbols?

**Comment by xlthor** [comment]
ähöm ... with my keyboard as usual? Just typing it. Copying them in works. Very strange, as within Chrome or IE it's working as expected.

I will make some tests on different machines and close this one. If that's not a local problem with my PC, I'll reopen again.

**Comment by xlthor** [comment]
Need to reopen. The issue is not within Firefox and it does appear on several different machines with German Keyboards.
The diff between Chrome and FF (82.0.2) are different key codes for these keys:

FF:
' resolves to shift + keycode 163
° resolves to shift + keycode 160

Chrome:
' resolves to shift + keycode 191
° resolves to shift + keycode 220

I assume that the problem lies somewhere in the core.js and the detection of shortcut keys etc.

**Comment by JiHong88** [comment]
@xlthor There was a mistake in the code checking the keycode.
Thank you.
Can you please test at the this [url](http://suneditor.com/test/index.html)?

**Comment by xlthor** [comment]
Works! Great, Thanks!

**Comment by JiHong88** [comment]
I'll notify you after the version update.

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
