### ISSUE TITLE
Atwho (@ tagging) plugin

### ISSUE THREAD

**Issue by megamind2301** [JiHong88/suneditor#535]
Hi,

I need to implement @ feature in suneditor to reference items/users/groups via autocomplete. Somewhat like [this link](https://codepen.io/AnandAyan/pen/jrNxMb?__cf_chl_jschl_tk__=bdc3a0a0793503b42e1fc8dfbe0f53be22436f26-1603864274-0-AbQwRc8i0nQ6M7B5Xwub3EuUzwFm7tDx1MfDYTkYp5zf2KaRa3HyoblU9ogBjFeChkBesOmO7Yk9Pphq_7ZcODfq7ABhHqPiKudjXDCV8CzxjYHkOqJSHYwSC3rccmg41WpVVLTeabDKRszGzIyzghhisxJ5t544ZM1vJZLnTzGRNe1pRIcSgJDF5Kn4MpcYLyaPewLxhX2UWyObAu7EOpO2FwevqAfs2LHJXU_RW84MJ-XhWtANpkQEhU7eIgLZO8fVRvI06M4lR9O1IxdUl0fm2GrCdhD4pKT1zCRxsq6pDYUi7zsViVCZbdWn-yrnqFO_Y8Oty1GVKLzpHlJI7fnzBLg7p8Zz-7NPTwDxXpeW). 
I wanted to know if,
1. It is already provided
2. Should be implemented manually
3. AtWho can be integrated directly into SunEditor

Thanks.

**Comment by JiHong88** [comment]
Hi,
Do you need a "metion" plugin?
It is planned to be implemented in version 3.0.0.
Maybe.. It will update this year.
