### ISSUE TITLE
API to go fullscreen?

### ISSUE THREAD

**Issue by deathemperor** [JiHong88/SunEditor#536]
Is there an API to call outside SunEditor to make it go Fullscreen? like Editor.goFullScreen().

**Comment by JiHong88** [comment]
Hi

Here a example:
```javascript
const editorInstance = suneditor.create(..)
const { core } = editorInstance;

// The screen button is needed to make it smaller again or to mark the activation.
const fullScreenButton = core._styleCommandMap.fullScreen; // or core.context.tool.fullScreen;
core.commandHandler(fullScreenButton, 'fullScreen')
```

**Comment by deathemperor** [comment]
thanks for the swift reply. I should've been more specific but is it possible to access core using suneditor-react? I tried with useRef but couldn't.

**Comment by JiHong88** [comment]
@deathemperor suneditor-react is not managed by me.
As far as I know, "suneditor-react" is not provided.
Implement it directly in React with "suneditor".
