### ISSUE TITLE
New Feature Request: Newline HTML tag option defaults set to <p>

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#537]
**Description:**
By default new line is appended with paragraph tag.

**Detail**
Many editors, supports user specified option for new line like <div> <p>
It would be much helpful if you provide once such props.

Thanks in advance :)

**Comment by JiHong88** [comment]
Hi @vijayaragavan95 
I'll add related options.
Thank you.

**Comment by vijayaragavan95** [comment]
@JiHong88 ,
Okay got it. Thank you ☺️

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
