### ISSUE TITLE
mathbutton to copy 

### ISSUE THREAD

**Issue by michelmar** [JiHong88/suneditor#539]
I'm trying to make  a copy button like this:
![image](https://user-images.githubusercontent.com/60835138/97738752-8c4e1280-1abd-11eb-9086-5d7e2ee9d02e.png)
But I am struggling to pass the math element to the clipboard, 
Is there a way I can pass the this.context.math._mathExp element to the clipboard?

```
else if(/copy/.test(command)){
      if(!navigator.clipboard){
        return
      }
        try {
          navigator.clipboard.writeText(this.context.math._mathExp)
          e.target.textContent = 'Copied to clipboard'
        } catch (err) {
          console.error('Failed to copy!', err)
        }
    }
```

I saw the onCopy_wysiwyg function but it is triggered by the specific event of copy, not a button.

**Comment by JiHong88** [comment]
@michelmar Shouldn't the whole span tag be copied?
`clipboard.setData("text/html", this.context.math._mathExp.outerHTML)`

**Comment by JiHong88** [comment]
I'll add functions such as copy, cut and paste to [commandHandler](http://suneditor.com/sample/html/out/document-editor.html#commandHandler).

**Comment by michelmar** [comment]
@JiHong88 I think I can only access this clipboardData.setData method when triggered by the copy event, 
Like I saw [here](https://stackoverflow.com/questions/36270886/event-clipboarddata-setdata-in-copy-event).
If you add these functions to commandHandler. I'll just have to  use commandHandler(target, command) with target as the element to be copied and command as copy for exemple? It would be really helpful

**Comment by JiHong88** [comment]
@michelmar Copy events are also available in the current version.
```javascript
editorInstance.core.execCommand('copy');
```
The onCopy method will be called.
```javascript
editorInstance.onCopy = (event, clipboardData, core) => {
  console.log(core.context.math._mathExp)
}
```
