### ISSUE TITLE
Katex not rendering some symbols after the last release

### ISSUE THREAD

**Issue by michelmar** [JiHong88/SunEditor#541]
Try to render this latex command:
` \sqrt{\underbrace{111\ldots 111}_{2006\ vezes}-\underbrace{222\ldots 222}_{1003\ vezes}}=\sqrt{\left(\underbrace{333\dots 333}_{1003\ vezes}\right)^2}=\underbrace{333\dots 333}_{1003\ vezes}`
We would have something like :
![image](https://user-images.githubusercontent.com/60835138/97775437-5baebd00-1b3f-11eb-9f32-9de4a2942cf8.png)

But before that realease  I was already have trouble when loading content whit this equation.
![image](https://user-images.githubusercontent.com/60835138/97775403-0d99b980-1b3f-11eb-9076-0cc78c131283.png)
After I load the content I get something like:
![image](https://user-images.githubusercontent.com/60835138/97775452-7ed96c80-1b3f-11eb-8547-9a9d5907168a.png)

**Comment by JiHong88** [comment]
@michelmar This issue is resolved at the #540 
I'll notify you after the version update.

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
