### ISSUE TITLE
Error while using setContents

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#543]
Hi @JiHong88 

I am facing this issue for quite some time now, however, I am not able to figure out the root cause.

When I try to set my editor's content using `setContents()`, I get below error:
```
Uncaught TypeError: Cannot read property 'scrollTop' of null
    at Object.getOffset (util.js:1021)
    at Object.setControllerPosition (core.js:755)
    at Object.call_controller (math.js:244)
    at Object.active (math.js:215)
    at Object._applyTagEffects (core.js:5305)
    at Object._onChange_historyStack (core.js:5011)
    at h (history.js:86)
    at Object.push (history.js:109)
    at Object.setContents (core.js:4411)
    at Object.setContents (core.js:7448)
```
The same code usually works fine, but at times gives the above error.
Once this code breaks, my entire business logic in its parent function stops.

Can you help rectify this edge case?

**Comment by JiHong88** [comment]
@dgandhi1993 When is "setContents" called?
And show me the contents of "setContents".

**Comment by dgandhi1993** [comment]
`setContents` is called with an empty string long after the editor instance initialization.

Basically, I am trying to clear the editor's content.

**Comment by JiHong88** [comment]
@dgandhi1993 If you are trying to set the initial values of the editor, you should do it in one of three ways:
1. call setContents inside onload
`instance.onload = (core) => core.setContents("");`

2. value option
`suneditor.create("id", {value: ""})`

3. just empty textarea
```html
<textarea><textarea>
```

**Comment by dgandhi1993** [comment]
@JiHong88 I am using the value property. This issue appears when I am trying to change an existing editor instance value.
Also, this doesn't happen always.

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
