### ISSUE TITLE
image tags are wrapped inside figure tags

### ISSUE THREAD

**Issue by wuhi** [JiHong88/SunEditor#544]
is it possible to remove the figure tag that holds the img tag?
every image that gets inserted looks like

`<div class="se-component se-image-container __se__float-none" contenteditable="false">
    <figure style="margin: 0px;">
<img.....></figure></div>`

**Comment by JiHong88** [comment]
@wuhi This structure is for functions such as image rotation, caption, etc..
It is difficult to change the current structure.
