### ISSUE TITLE
pasteTagsWhitelist not working as expected

### ISSUE THREAD

**Issue by Backdraft2100** [JiHong88/SunEditor#545]
Hi there,

I wanted to avoid any font styling in the editor and also limit the number of allowed tags.
It seems to me the pasteTagsWhitelist is not working as expected.
When I use 'p|a|strong|em|h3|h4|h5|ul|ol|li|blockquote|table|thead|tbody|tfoot|tr|td|sup|sub' as paste whitelist, other tags not in this list are still kept including attributes not in the Fixed whitelist in the final paste result.

**Comment by JiHong88** [comment]
Hi @Backdraft2100 ,
Please show me what browser you tested, the options you used and what you pasted.

**Comment by JiHong88** [comment]
Bugs have been fixed. https://github.com/JiHong88/SunEditor/commit/f9eef5b167cb25f712856545b2dcfca4b3562f16
Thank you. :)
I'll notify you after the version update.

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by Backdraft2100** [comment]
Thank you very much!
