### ISSUE TITLE
setContents function inserts unexpected paragraph element

### ISSUE THREAD

**Issue by BrianJVarley** [JiHong88/SunEditor#546]
Hi @JiHong88,

I'm using `setContents('')` with empty string param, to clear the editor contents. But I notice it adds a hidden <p> in the editor body. I expected no extra html elements to be added to the editor body when calling setContents with an empty string.

In our use case we use the editor as a message input for a chat widget. So after the user hits send  message, we call setContent to clear the editor (message input). But what actually happens is the cursor jumps to the next line because of the extra inserted paragraph element. 

Question:

Is is it possible for you to extend setContents to allow this? In order to setContent to empty so no extra element is inserted when a null or empty string is passed as the param value.

For example `setContents(null)` or `setContents('')`.

**Comment by BrianJVarley** [comment]
#525 This linked issue is the reason we started using the remove node 'hack' to clear editor. But I think it would be better to use the user function setContents if you fix the above bug.

**Comment by JiHong88** [comment]
@BrianJVarley `<p><br><p>` is the default state of the editor.
When using `setContents(Nullish)`, I'll modify it so that it does not add basic HTML.
But even if the editor's HTML is empty, a paragraph tag will be generated if you use a function or give focus.

**Comment by BrianJVarley** [comment]
@JiHong88 that sounds like a good solution, if we can pass a `nullish` value to `setContents`. The issue was more coming from the `<br>` tag you mentioned above that caused a newline. Here is an example (which should be fixed when you patch setContents):

![Clear Text Bug](https://user-images.githubusercontent.com/6731968/98350917-e4cc6500-2013-11eb-9b34-b8f03d1c22d3.gif)

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
