### ISSUE TITLE
onImageUploadBefore is synchronous

### ISSUE THREAD

**Issue by BrucePerens** [JiHong88/SunEditor#547]
Hi,

I have a working `onImageUploadBefore` function, which uploads the image file and replaces it with its URL. This unfortunately requires synchronous HTTP requests to work, and of course JavaScript really doesn't like to be synchronous any longer. Is there a way to do this asynchronously?

Thanks

Bruce

**Comment by JiHong88** [comment]
Hi @BrucePerens 
I did not understand the question correctly.
Please tell me more detail.
And please refer to this [link](http://suneditor.com/sample/html/out/document-user.html#onImageUploadBefore).

**Comment by BrucePerens** [comment]
Hi JiHong88,

My onImageUploadBefore function ([link](http://suneditor.com/sample/html/out/document-user.html#onImageUploadBefore)) uses `XMLHttpRequest to upload the image. I must use XMLHttpRequest.open(a,b, true) for it to run synchronously, because I must use it to get the uploaded image data, which is provided to uploadHandler so that the inline image is replaced with a link.

But synchronous use of XMLHttpRequest is a deprecated feature, these days all Javascript is expected to run asynchronously and use promises or at least callbacks to receive its results.

To upload asynchronously, I would have to replace the inline image with a link to the uploaded image asynchronously. There is an API to return the list of uploaded images, but no API other than onImageUploadBefore to replace an image in that list.

Thanks

Bruce
