### ISSUE TITLE
buttonList issues

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#548]
Hi @JiHong88 

When setOptions with buttonList are not passed in to the editor during the initial setup, it throws an error below:
`Uncaught SyntaxError: Unexpected token u in JSON at position 0`
And that is due to the code below:
https://github.com/JiHong88/SunEditor/blob/6e80a5f0f26dae9017dca0c10a6ae590badaa460/src/lib/constructor.js#L497
Since JSON.stringify will return undefined,  JSON.parse just breaks the editor.

**Comment by JiHong88** [comment]
@mkhstar The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
Thank you!
