### ISSUE TITLE
insertHTML 함수 사용

### ISSUE THREAD

**Issue by oncd** [JiHong88/SunEditor#549]
먼저 에디터 공개 해 주셔서 감사합니다.
insertHTML 함수를 사용해서 html 넣을때
1. 그 줄에 해당하는 html이 사라지는 버그가 있습니다.
2. 그리고 여러번 클릭하면 동작하지 않는 버그가 있습니다.

확인 부탁합니다.
감사합니다.

**Comment by oncd** [comment]
3. 글을 써내려가다가 끝에서 insertHTML이 동작하지 않는 것을 확인했습니다.

**Comment by JiHong88** [comment]
@oncd 더 자세히 얘기해주세요.
정확히 어떤 이슈인지 잘 모르겠습니다.

1. insertHTML을 어떻게 호출하였고 어떤줄이 사라지는지..
2. 어디를 여러번 클릭하면 동작하지 않는지..
3. 글을 쓰다 insertHTML을 어디서 호출하는 건가요?

**Comment by oncd** [comment]
예 안녕하세요.
1. 글자 옆에서 inserHTML버튼 클릭하면 그 줄 글자가 사라집니다.
2. 글자 옆에서 inserHTML버튼 클릭 두번째 부터 제일 위로 추가 되어 버립니다.
3. ie11에서 파이핑 끝에서 enter 한 다음 inserHTML버튼 클릭하면 동작하지 않습니다.

**Comment by JiHong88** [comment]
이미지를 추가하신건가요?

**Comment by oncd** [comment]
예 맞습니다. 이미지 업로드 관리가 필요해서 따로 분리해서 사용할려고요. 다른 html이 추가 될 수도 있을 것 같습니다.

**Comment by oncd** [comment]
http://suneditor.com/sample/html/examples.html 제시해주신 사이트에서도 같은 현상이 나타 납니다.

**Comment by JiHong88** [comment]
insertHTML로 추가한 HTML string을 보여주실수 있나요

**Comment by oncd** [comment]
<img src='upFileName' name='img_content' class='img_content' alt='rDesc'/> 아참 그리고 추가한 class, name 속성도 없어져버립니다. 이 부분은 이미지 갤러리 plugin 할때 사용합니다.

**Comment by JiHong88** [comment]
`se-` 또는 `__se__` 로 시작하지 않는 클래스와 style, name등의 속성은 모두 제거됩니다.
class 이외의 속성을 사용하려면 [options](https://github.com/JiHong88/SunEditor#options) 에서 `attributesWhitelist` 옵션을 확인해보세요.

**Comment by oncd** [comment]
예 살펴 보겠습니다. 감사합니다.

**Comment by JiHong88** [comment]
[2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) 버전이 업데이트 되었습니다.
`insertHTML()` 메소드 버그가 수정 되었습니다.
감사합니다.

**Comment by oncd** [comment]
예 감사합니다.
