### ISSUE TITLE
Nofollow Button in link dialog

### ISSUE THREAD

**Issue by ajaymalik14** [JiHong88/SunEditor#55]
i want to add rel='nofollow' button in link dialog javascript file. I tried to add it many time but only one of attribute work either nofollow or target.

**Comment by JiHong88** [comment]
Hi~

You can add it to "link.js" file like this : )

> add: function

`
context.link.linkNewWindowCheck = link_dialog.getElementsByClassName('sun-editor-id-linkCheck')[0];
`
**↓Add to bottom line**
`
context.link.nofollow = link_dialog.getElementsByClassName('sun-editor-id-linkNofollow')[0];
`


> setDialog: function

`
... class="sun-editor-id-linkCheck" />&nbsp;' + lang.dialogBox.linkBox.newWindowCheck + '</label>' +
`
**↓Add to bottom line**
`
 '       <label class="label-check"><input type="checkbox" class="sun-editor-id-linkNofollow" />&nbsp;nofollow</label>' +
`


> function submitAction

`
oA.target = (this.context.link.linkNewWindowCheck.checked ? "_blank" : "");
`
**↓Add to bottom line**
`
 oA.rel = (this.context.link.nofollow.checked ? "nofollow" : "");
`
...
`
this.context.link._linkAnchor.target = (this.context.link.linkNewWindowCheck.checked ? "_blank" : "");
`
**↓Add to bottom line**
`
this.context.link._linkAnchor.rel = (this.context.link.nofollow.checked ? "nofollow" : "");
`


> init: function

`
this.context.link.linkNewWindowCheck.checked = false;
`
**↓Add to bottom line**
`
this.context.link.nofollow.checked = false;
`


> onClick_linkBtn: function

`
...linkNewWindowCheck.checked = (/_blank/i.test(this.context.link._linkAnchor.target) ? true...
`
**↓Add to bottom line**
`
this.context.link.nofollow.checked = (/nofollow/i.test(this.context.link._linkAnchor.rel) ? true : false);
`
