### ISSUE TITLE
Paste from MS Word on Chrome turns pasted content into an image?

### ISSUE THREAD

**Issue by snappa** [JiHong88/SunEditor#553]
If I paste content from a Microsoft Word document into the editor running on Chrome the content is turned into an image.  This does not happen on Safari.

I'm wondering if there's a configuration option to disable this.  I have been able to paste content into the editor using SHIFT+COMMAND+V and this pastes it in as text but all the formatting is gone and teaching my users to do anything with extra command sequences is not a great UX.

Any info on how to code around this problem would be appreciated.

**Comment by JiHong88** [comment]
@snappa I din't understand this mean **"the content is turned into an image"**.
Please can you tell me more detail?

**Comment by snappa** [comment]
> @snappa I din't understand this mean **"the content is turned into an image"**.
> Please can you tell me more detail?

Open a Microsoft Word document. Select some content that you want to paste into the sun editor. Right-click Copy or Command-c. 
Click in the subeditor where you want to paste the content. Right-click Paste or Command-v to paste the content in. 

The pasted in content is transformed to an image and not editable text.

**Comment by JiHong88** [comment]
@snappa I don't understand.
Did you mean a text is transformed to an image?
Can you show the content of Word?

**Comment by snappa** [comment]
Yes, the text is transformed into an image.  Attached is a zip file containing 2 videos.  One showing copy/paste from Word to the editor in Chrome using normal paste and the other is a copy paste of the same content but using "Paste and Match Style".  Notice how the video titled "copy_paste_shows_image.mov" transforms the text pasted into an image.

[copy_paste.zip](https://github.com/JiHong88/SunEditor/files/5683592/copy_paste.zip)

**Comment by JiHong88** [comment]
Sorry, for the late reply.😢
Where was the text copied from?

**Comment by snappa** [comment]
> Sorry, for the late reply.😢
> Where was the text copied from?

Microsoft Word

**Comment by JiHong88** [comment]
@snappa This issue is not reproduced.
Please tell me more about the test environment and method.

**Comment by snappa** [comment]
> @snappa This issue is not reproduced.
> Please tell me more about the test environment and method.

Sure.  MacBook Pro, OS Catalina, 10.15.7, Microsoft Word for Mac, Version 16.41, Chrome Version 87.0.4280.88 (up to date), React 16.12.0.  SunEditor React "suneditor-react": "^2.14.3".

I have the editor in an app running on Chrome on my Mac, I open a Word Doc,  select the area to be copied and right-click "copy".  I then just do a right-click "paste" into the editor and it transforms the text into an image.  As I said earlier in this thread, if I click "Paste and Match Style" this works as expected, transforming the pasted word content into HTML text.  If I just click "Paste" this is what causes the issue.

**Comment by JiHong88** [comment]
This is a bug that I don't understand right now...
If we can't fix it in the next version, we'll let you know again.

**Comment by snappa** [comment]
> This is a bug that I don't understand right now...
> If we can't fix it in the next version, we'll let you know again.

Thank you.  I traced it and tried working around it within the API and just couldn't get it to work.

**Comment by JiHong88** [comment]
The [2.35.1](https://github.com/JiHong88/SunEditor/releases/tag/2.35.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
