### ISSUE TITLE
Feature request: nonbreaking space character

### ISSUE THREAD

**Issue by kristofferlund** [JiHong88/SunEditor#554]
Hi again!
I would like to suggest this feature: **insert nonbreaking space character**

Current support now is that you can copy-paste a nonbreaking space, but there is no way of inserting it manually.
I suggest adding support for it the same way it's done in MS Word, or even with a designated button for it. 
I found [this guide](https://word.tips.net/T001081_Inserting_a_Non-Breaking_Space.html) saying that the way of doing it in word is by pressing Ctrl+Shift+Space.

**Comment by JiHong88** [comment]
@kristofferlund Thanks for the suggestion,
I have set different shortcuts for Windows and Mac,
Windows: Ctrl+Shift+Space.
Mac: Option(⌥)+Shift+Space.

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
