### ISSUE TITLE
XSS attack

### ISSUE THREAD

**Issue by Darthmineboy** [JiHong88/SunEditor#556]
First of, thanks for this library. I'm going nuts about the lack of table functionality in many of the free wysiwyg editors. This editor has good support for tables 🥇 

I have however found an XSS vulnerability in this editor. It appears the editor does filter out script tags, unfortunately that is not sufficient for all XSS attacks. 

Reproduction
* Go to http://suneditor.com/sample/index.html
* Switch to code view
* Insert `<img src="#" onerror="alert('hi')"/>`
* Switch to normal view

**Comment by JiHong88** [comment]
@Darthmineboy Thank you for your reporting.
Will be fixed in the next version.
Thank you.

**Comment by JiHong88** [comment]
The [2.34.2](https://github.com/JiHong88/SunEditor/releases/tag/2.34.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
