### ISSUE TITLE
defaultTag Option

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#564]
Hi @JiHong88  
The defaultTag option works only at where the editor is initialized. It doesn't work for setOptions. Is this a normal behaviour?

**Comment by JiHong88** [comment]
Hi @mkhstar 
As a result of checking, the "defaultTag" option is modified normally.
In what situations does it not work?


> I have confirmed a bug that does not change to the value of "defaultTag" when deleting all contents.

**Comment by JiHong88** [comment]
@mkhstar If you change the value of `defaultTag` with `setOptions()` after the default is set, you need to initialize the value by calling `setContents("")`.

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
