### ISSUE TITLE
Keep the values ​​of the IDs of the HTML elements

### ISSUE THREAD

**Issue by cacuestai** [JiHong88/SunEditor#565]
Hi:

Excellent editor. It would be convenient if the source code of the html property of the templates kept the values ​​of the IDs of the  elements.

Thanks a lot,

Carlos Cuesta

**Comment by JiHong88** [comment]
Hi, 
You can use the `attributesWhitelist` option.
```javascript
suneditor.create("", {
  attributesWhitelist: {
    "all": "id"  
  }
})
```

**Comment by cacuestai** [comment]
Hi:

Thank you very much for your prompt response and solution. Would the following be possible with data attributes?

`  attributesWhitelist: {
    "all": "data-*"
  }`

A greeting

**Comment by JiHong88** [comment]
@cacuestai You can RegExp syntax.
`ttributesWhitelist: { "all": "data-.+" }`
