### ISSUE TITLE
Question/Issue placeholder do not update

### ISSUE THREAD

**Issue by popoleeMaster** [JiHong88/SunEditor#568]
I am using this nice editor in my rect app, with the react-i18next package.

I am calling rich text editor as follow : 

```
const RichEditor = (props: RichEditorProps) => {
  const { t, i18n } = useTranslation();
  const { title, isRequired, help, note, value, error, disable, readOnly, placeholder } = props;
  
  return (
    <StyledContent disabled={disable}>
      <Label title={t(`TextForm.${title}`)} isRequired={isRequired} help={help} />
      {note && <Note title={note} />}
      <EditorContainer error={error}>
        <SunEditor
          {...props}
          setContents={value}
          placeholder={t(placeholder || '')}
          lang={i18n.language}
          disable={readOnly || disable}
          setOptions={{ buttonList: DEFAULT_BUTTON_LIST, ...props.setOptions }}
        />
      </EditorContainer>
    </StyledContent>
  );
};
```

the problem is, when the language is changed in the app, `lang={i18n.language}` this will change the button language, but `placeholder={t(placeholder || '')}` the placeholder will never change (I need to hard reload or refresh my component entirely).

I believe the Editor should update when the placeholder language is changed, and there is no content written.

I will setup a demo if needed

thanks

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by Ayub1224** [comment]
I have Installed 2.44 version of it, and still getting the same issue, passing placeholder from diff form but it is taking from the 1st form only
