### ISSUE TITLE
issues in video preview fronted 

### ISSUE THREAD

**Issue by devbrijesh** [JiHong88/SunEditor#569]
Hi,
When i insert Youtube Video from there is issues on fronted 
in this line added 
`<figure style="width: 100%; height: 56.25%; padding-bottom: 56.25%; margin: 0px;">`
**width, height, padding-bottom, margin**
we can control it with **videoWidth & videoHeight**
but not padding-bottom and it's same as videoHeight 

and now issues comes on fronted padding-bottom: 56.25%; added extra spaces from bottom (we not use your code on fronted because not want extra code ) 
so want to just know how to fix it want to remove **padding-bottom** (why we need padding because video working perfect without padding so why add extra codes )  or how we can control it like as **videoHeight** or where we can edit it or removed this line 
`<figure style="width: 100%; height: 56.25%; padding-bottom: 56.25%; margin: 0px;">`
this line not required because we already have before a **Div**

Thanks 
it's a great editor

**Comment by JiHong88** [comment]
@devbrijesh Sorry for the late reply.
That HTML structure is for rotation, percentage options, etc.

**Comment by mohit23x** [comment]
is there a way to remove that extra `padding-bottom` 
i have set `videoResizing` option to `false`

when i use the renderd html somewhere else that extra padding shows a big white space and content is shifted below.

**Comment by ArturKoziol** [comment]
Had similar issue while the library. Found a quick workaround by just styling:
```
.se-video-container {
  position: relative;
}

.se-video-container iframe {
  position: absolute;
}
```
It doesn't remove the `<figure>`, but with this the video displays normally without space on the bottom and I can use all aspects available from the dropdown.

**Comment by JiHong88** [comment]
```css
.sun-editor-editable .se-component {
 margin: 0 !important;
}
```

**Comment by devbrijesh** [comment]
hi @JiHong88 can we not removed extra html code ?

**Comment by JiHong88** [comment]
@devbrijesh The structure of the media's HTML cannot be changed.

**Comment by devbrijesh** [comment]
ok
