### ISSUE TITLE
option imageUploadUrl Not Working

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/SunEditor#572]
@JiHong88 hi
I used **imageUploadUrl**  and the request is sent to the server correctly.
And the server uploads the file correctly and sends the following response.

```
{
"errorMessage":"",
"result":{
      "url":"\/uploads\/2020\/11\/29\/5fc3409a6e52b1 MB.jpg",
       "name":"1 MB.jpg",
        "size":""
        }
}
```
Of course, the photo upload Modal closes
**But the file is not displayed in the editor**.

**Comment by Saeeed-B** [comment]
I try this result but it still does not work

```

{"result":
    {
      "url":"http:\/\/localhost:8000\/uploads\/2020\/11\/29\/5fc34358bc5a7400.jpg",
      "name":"400.jpg",
      "size":""
   }
}
```

**Comment by JiHong88** [comment]
@Saeeed-B The result attribute of the response data must be an array.
```
{
	"errorMessage": "insert error message",
	"result": [
		{
			"url": "/download/editorImg/test_image.jpg",
			"name": "test_image.jpg",
			"size": "561276"
		}
	]
}
```

**Comment by Saeeed-B** [comment]
@JiHong88 Tank you
