### ISSUE TITLE
Deleting image/video/audio style issue

### ISSUE THREAD

**Issue by ScottWager** [JiHong88/SunEditor#573]
The video below shows that when adding an image/video/audio element, then repeatedly pressing the back button to delete it, inline styling is added to the next HTML element (font size increase and background colour becomes white). I have made the default background for the editor be grey so this is noticeable.

https://streamable.com/9ddljy

Thank you!

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
