### ISSUE TITLE
text-align style removed when use setContents

### ISSUE THREAD

**Issue by adysuprianto** [JiHong88/SunEditor#576]
When initialize value with setContents, all text-align style removed.

**Comment by Calmefils** [comment]
Did you figure it out how to handle this issue? I have the same problem, 
setContents={"<p style=\"text-align: center;\">TEST</p>"} is reflecting on browser <p>TEST</p> without the style properties

**Comment by Calmefils** [comment]
Did you figure it out how to handle this issue?
