### ISSUE TITLE
imageGalleryUrl using PHP and not react.

### ISSUE THREAD

**Issue by dreamsight** [JiHong88/SunEditor#578]
hey guys I have looked over the documentation here and I don't particularly want to start the react server, instead I wish to use a PHP or Perl script within a local DIR and a script that produces the JSON output required, I have completed this part of the program and it outputs the JSON format the same as S3 and/or as expected here.

![Screenshot_2](https://user-images.githubusercontent.com/36543801/101998847-cae70780-3cce-11eb-925a-09a1f968fd92.jpg)

However, when I point the imageGalleryUrl at the PHP output URL it does not work? but switch back to your repository and it does.
Am I missing something any help would be appreciated :)

obviously blurred out URL for the demo output image above? I also should point out that I need the same image gallery for other projects (i.e. a bulletin board) with different commands, I prefer to code in either PHP or Perl and I would like to update the java files with minimal alterations to your code from time to time, if there is no other option then please let me know, the syntax of java slows me down QUITE A LOT but I am OK at a push :) my ideal is to create the gallery in PHP or Perl for a back-end process.

Paul

**Comment by dreamsight** [comment]
Note: I have also replicated the headers sent by the server to exclude gzip and chunked headers just in case.

**Comment by JiHong88** [comment]
@dreamsight Sorry, for the late reply.😢
The question did not understand well.
Could you please explain again?
I don't know PHP or Perl.

**Comment by dreamsight** [comment]
Hi thanks
I apologise :) OK, one of the settings in the config (SUNEDITOR.create) points to i.e.:
imageGalleryUrl: 'https://etyswjpn79.execute-api.ap-northeast-1.amazonaws.com/suneditor-demo', 
where JavaScript downloads a list of images and their locations in JSON format.

I want this setting to point to:
imageGalleryUrl: 'https://my-own-domain.com/my-own-script/for-my-own-image-list’,
Yet this does not work? The output from my script is exactly the same format i.e. JSON as on amazonaws.com including the headers sent by the server itself.

I may have missed something i.e. a setting in your script? For instance, Does the editor JavaScript query another port on the amazonaws.com server? is there an encrypted key i am missing?

in theory this should work?

Regards
Paul

**Comment by JiHong88** [comment]
@dreamsight It must work, if same response data.
Um.. Try write "Result" in lowercase.
```
{
 statusCode: 200,
 Result: =>> result:
  ...
}
```

**Comment by dreamsight** [comment]
Good catch something simple like a lowercase "R" :1st_place_medal: 

it's working great now............

Thanks :)
