### ISSUE TITLE
Add options, follow or nofollow for links

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/SunEditor#583]
@JiHong88 I think it is very good if it is possible to determine whether the link is a **follow or nofollow** when importing the links.
This point is important in SEO.

**Comment by s-kris** [comment]
Kindly add option for rel="noreferrer noopener"

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by s-kris** [comment]
@JiHong88 Please consider the following:
1. There's no 'follow' or 'default' or 'empty' value. Whatever is the first option in the array, it gets added.
2. There's no option to select multiple options. Ex: Whenever we use `target=_blank` on <a> tag, it is recommended to include `rel="noreferrer noopener"`. So currently,

**Comment by s-kris** [comment]
Thank you @JiHong88 but I don't see the option to select link attributes
![Screenshot 2021-03-13 at 11 42 47 AM](https://user-images.githubusercontent.com/3975305/111021294-469d4100-83f1-11eb-8ad2-a1e4972c5bb5.png)

**Comment by JiHong88** [comment]
@s-kris Please define the `linkRel` option.

**Comment by s-kris** [comment]
Sorry, I missed the linkrel option. Thank you :)

**Comment by LEMOYNE-EMMANUEL** [comment]
Good morning,
I would like to add an option in the dialog window for links.
That the person can enter or choose a class.
How to do it?
Thanks for your help.

![class-suneditor](https://github.com/user-attachments/assets/57be6c25-5cec-4003-8bac-95d2611a401d)
