### ISSUE TITLE
Create link move selected text to end of paragraph

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#584]
1. With this HTML content

```html
<p><span>using the OAuth <a href="http://suneditor.com/sample/index.html" target="">signing </a>process. Google</span><br>
</p>
```

2. Select the `OAuth signing process`. (select range should include the `<a>` link)
3. Create link with any URL
4. Result: created new link with selected range but moved to end of paragraph.

![f3s2w6kmaE](https://user-images.githubusercontent.com/313189/103149801-9f205300-479f-11eb-9683-72dc14aaa9b8.gif)

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by rexpan** [comment]
Thank you for your fix. The issue has been fixed for selected text inside the the paragraph.
But this issue is still reproduce if you select to begin of the paragraph.

![QEDVpzNJqm](https://user-images.githubusercontent.com/313189/105446560-f208ff80-5ca4-11eb-912b-429682640c19.gif)

**Comment by JiHong88** [comment]
The [2.36.0](https://github.com/JiHong88/SunEditor/releases/tag/2.36.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
