### ISSUE TITLE
[BUG] Error inserting image/horizontal rule after list

### ISSUE THREAD

**Issue by SCH93** [JiHong88/SunEditor#585]
Hello, thank you very much for the library, it is being very useful for the project I work on.

I have detected a bug when inserting images / horizontal rules after having a list of points. After finishing the list, when inserting the image / horizontal rule it is inserted after the first point of the list and not outside (where the cursor was). Would it be possible to solve it?

I leave you a video from SunEditor's own page so you can reproduce the error

Thank you very much, Oscar

https://user-images.githubusercontent.com/28402142/103212714-df044900-490b-11eb-8fbf-e9810aee5da4.mp4

**Comment by JiHong88** [comment]
@SCH93 I will notify you when it is fixed.
Thank you!

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
