### ISSUE TITLE
can we limit to insert only youtube links?

### ISSUE THREAD

**Issue by s-kris** [JiHong88/suneditor#586]

**Comment by JiHong88** [comment]
@s-kris It's impossible now.
I'll add an event function so you can inspect the url.

**Comment by s-kris** [comment]
Thank you

**Comment by JiHong88** [comment]
@s-kris Due to incompatibility with previous versions, we will add features in v3.0.0.
Override the method of the video plugin to use it.

https://github.com/JiHong88/SunEditor/blob/master/src/plugins/dialog/video.js#L504
```
plugins.video.setup_url = function () {
  ...
}
```

**Comment by s-kris** [comment]
Sure, thank you!
