### ISSUE TITLE
Custom Drop down on keypress?

### ISSUE THREAD

**Issue by jainal09** [JiHong88/suneditor#588]
Hi,
I want to add a functionality in which when a user types in @ there should a drop down appear and in it names appear just like github editor here.
For getting the name it will be a api request to backend.

I am using this [suneditor-react lib](https://github.com/mkhstar/suneditor-react) and want to achieve the following functionality with it.
Is it possible to do this?

**Comment by JiHong88** [comment]
Hi @jainal09 
This feature is in preparation and will be added in version 3.0.0.
It is expected to take two or three months to the version update.

**Comment by jainal09** [comment]
okay thanks @JiHong88
