### ISSUE TITLE
Anchor links within same page

### ISSUE THREAD

**Issue by s-kris** [JiHong88/SunEditor#593]
Hello,

Can we add anchor links to elements in same page? 

Use case:
If a person is writing a long article, they will create a table of contents to link various sections of the article. 

It can be done by using code view but it'd be helpful to non technical users if there's a gui to do it. 

Thank you :)

**Comment by JiHong88** [comment]
@s-kris I will add it in the next version. :)

**Comment by s-kris** [comment]
Thanks for your amazing work :)

**Comment by JiHong88** [comment]
The [2.35.0](https://github.com/JiHong88/SunEditor/releases/tag/2.35.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by s-kris** [comment]
Thank you!!
Can I know when 2.3.5 changes will be pushed to suneditor-react?

**Comment by JiHong88** [comment]
@s-kris suneditor-react is not managed by me.
It will probably be updated sooner or later.

**Comment by s-kris** [comment]
Ohh yeah noticed that later. I opened an issue.

**Comment by s-kris** [comment]
@JiHong88 Can you please add a way in gui to insert #id_tag to element so that the linking in same page will be seamless?

**Comment by JiHong88** [comment]
@s-kris This issue has been resolved.
Try the latest version.

**Comment by JiHong88** [comment]
@s-kris The bookmark option has already been added.
<img width="492" alt="스크린샷 2021-03-11 오후 2 40 27" src="https://user-images.githubusercontent.com/13191953/110741382-e6cf5a80-8277-11eb-83fa-a6f270f3826a.png">

**Comment by s-kris** [comment]
I noticed it @JiHong88. With this you can set the <a href="#abcd" > link on action text. 
But how to assign this id #abcd to the target element via gui?

**Comment by JiHong88** [comment]
When you click the bookmark button, "#" is added.
I don't understand the question.

**Comment by JiHong88** [comment]
@s-kris There is no such function.
I will add it in the next version.

**Comment by s-kris** [comment]
@JiHong88 Thank you so much :)

**Comment by JiHong88** [comment]
The [2.37.0](https://github.com/JiHong88/SunEditor/releases/tag/2.37.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by JiHong88** [comment]
Hi, @mustafaDabah 
A list of header tags from h1 to h6 in the current editing window is displayed and a random ID value is given when selected.
