### ISSUE TITLE
Pasting from Excel converts to an img

### ISSUE THREAD

**Issue by nagyvilmos** [JiHong88/SunEditor#597]
When I paste a table from excel it is converted to an img and not as a table.

If I copy the table into word and then copy into suneditor it copies - though cells format <td><p><span>XXX</span><p></td>, the inner tags aren't helpful, especially the <p>.

As an aside, it would be nice to be able to change the background colour of a table cell, even though I can do it by switching to html view.

**Comment by JiHong88** [comment]
The [2.35.1](https://github.com/JiHong88/SunEditor/releases/tag/2.35.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
