### ISSUE TITLE
Problem with Modals

### ISSUE THREAD

**Issue by stoneshaq** [JiHong88/SunEditor#598]
hi there. thanks so much for this great editor.!! especially the image gallery is awesome! 
i have one problem tho.. Editor works perfect in a normal page.. when i use it in modal, when i first open the modal, it works. then if i close the modal and open it again it doesnt show the editor.. how can i manage to load it again after closing and opening the modal.
thanks alot

**Comment by JiHong88** [comment]
Hi @stoneshaq 
Please show me the code in detail.

**Comment by stoneshaq** [comment]
All sorted..i was loading the script again in the modal.. all great. thanks alot

**Comment by stoneshaq** [comment]
sorry.. here is the detailed code.. I use Bootstrap 4.3.1 First modal opens fine with editor.. when i close it and reopen the modal it doesnt show the editor.

To open modal

`$('#ModalXL').on('show.bs.modal', function (e) {
    var button = $(e.relatedTarget);
    var modal = $(this);
    modal.find('.modal-body').load(button.data("remote"));
});
`

this is how icall modal
`<a href="#ModalXL" data-remote="{{ route('detail',$tour->uuid) }}" data-toggle="modal" data-target="#ModalXL" class="btn btn-primary btn-sm"> Add Stop</a>`

in Modal i have
`    const editor2 = SUNEDITOR.create('editor2', {
        display: 'block',
        width: '100%',
        height: '150px',
        charCounter: true,
        popupDisplay: 'full',
        buttonList: [
            ['undo', 'redo', 'bold', 'underline', 'italic', 'fontColor', 'hiliteColor', 'textStyle', 'outdent', 'indent', 'align', 'list', 'horizontalRule', 'link'],
        ],
        placeholder: 'Information on pickup and drop off...'
    });
    editor2.onChange = (contents, core) => {
        editor2.save()
    }
`

thanks for your time

**Comment by JiHong88** [comment]
It seem like maybe every time the modal is opened, the HTML is created anew.
Create an editor every time you open a modal and try removing it when the modal closes.

**Comment by gautam-nirala-loop** [comment]
Hi @JiHong88 ,
I am using SunEditor with NextJS
    "suneditor": "^2.44.12",
    "suneditor-react": "^3.5.0",
    "next": "^10.0.4",
    "webpack": "^4.44.1"
  
when uploading link or video if i don't provide any link and close it using cross icon on modal, it is throwing Error

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'init')

Call Stack
Object.close
webpack-internal:///./node_modules/suneditor/src/plugins/modules/dialog.js (149:43)
Object._onClick_dialog
webpack-internal:///./node_modules/suneditor/src/plugins/modules/dialog.js (88:43)

Any help would be highly appreciated. 
Thanks
