### ISSUE TITLE
editor iframe document requires re-loading of custom font faces already defined in root document styling

### ISSUE THREAD

**Issue by olewhalehunter** [JiHong88/SunEditor#6]
Issue:
Editor iframe document will not load custom local fonts.

Reproduce:
Include a local custom font in the page's root css, try applying styling to editor iframe document body.
(tested on Chrome 48.0.2564)

Fix:
Add js code for "sun_wysiwyg.contentWindow.document.head.innerHTML" style section update to include custom font definitions?

**Comment by JiHong88** [comment]
thanks for the details :)
I'll fix it

**Comment by JiHong88** [comment]
Hi, I replaced it with the "inhert" attribute that was fixed with the "Helvetica Neue" font of suneditor.css file and added property 'editorIframeFont' to change iframe font (default : 'inherit')
