### ISSUE TITLE
How can i add compositionend to the editor event

### ISSUE THREAD

**Issue by crying2812** [JiHong88/SunEditor#600]
Hi JiHong88, thanks for created great plugins. 
I'm using this editor for my project and got stuck at point: My user will typing by IME keyboard and i need to check when user finish select text on keyboard. 
How can i do that?

**Comment by JiHong88** [comment]
Hi  @crying2812,
There are input and key related events.
http://suneditor.com/sample/html/out/document-user.html#onInput

See the "isComposing" property of the key event.
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing

If not work, I'll find another way.

**Comment by crying2812** [comment]
Thanks for quick response. But seems it not quite related to my case. 
For example, i need to limit a paragraph with 20 characters then make user type on next paragraph. 
I need catch the event when user press enter ( to choose the character on IME keyboard). If i use onInput option for example, the cursor will be move to next pragraph and the character will be duplicate when user hit enter..

**Comment by JiHong88** [comment]
Um.. Can't you take advantage of the keydown event?

**Comment by crying2812** [comment]
I not sure the keydown event can solve my issue, with compoistionend event, i can check which texts user just typing before enter, for exampe: きもち with e.data
How can i do that with keyDown

**Comment by crying2812** [comment]
I found the onInput event can resolve my problem. Thanks for supporting!
