### ISSUE TITLE
Video plugin throw error on when `_update_videoCover `

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#602]
1. Init SunEditor with HTML
```html
<p>1</p>
<iframe width="100%" height="700px" src="..." data-size="100%,100%" frameborder="0" allowfullscreen="" sandbox="allow-scripts allow-same-origin"></iframe>
<p>2</p>
```
2. `fileManager.checkInfo` call back to `video._update_videoCover`, `video._update_videoCover` throw when try to call `video.applySize` with `context.video._element` is `null`.

Do you think we miss to set `context.video._element` as `oFrame` in `video._update_videoCover`?

**Comment by JiHong88** [comment]
The [2.36.0](https://github.com/JiHong88/SunEditor/releases/tag/2.36.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
