### ISSUE TITLE
The editor didn't prevent IME input

### ISSUE THREAD

**Issue by crying2812** [JiHong88/SunEditor#604]
Hi JiHong88, I realized that editor doesn't prevent user input when I preventDefault() by onKeyDown event. Is it a bug or i need to use other event to prevent that? Thanks

**Comment by JiHong88** [comment]
@crying2812 At the IME input, "keyDown" event occurs after text input.
So text input cannot be prevented with "preventDefault".

There seems to be the way to erase the entered characters.
