### ISSUE TITLE
wrong condition in submitAction

### ISSUE THREAD

**Issue by agolovinmentalstack** [JiHong88/SunEditor#605]
Please chage on ***submitAction*** on images plugin

 if (***this.functions.onImageUploadError !== 'function'*** || this.functions.onImageUploadError(err, { 'limitSize': limitSize, 'currentSize': infoSize, 'uploadSize': fileSize }, this))
 
 to this
 if (***typeof*** this.functions.onImageUploadError !== 'function' || this.functions.onImageUploadError(err, { 'limitSize': limitSize, 'currentSize': infoSize, 'uploadSize': fileSize }, this))
 
 reason:  
   - ***onImageUploadError*** is not called correctly
   
 case:  
   - set  ***imageUploadUrl***
   - set  ***imageUploadSizeLimit*** === 1  
   - try add any image to call error  
   - ***onImageUploadError*** is not called correctly

**Comment by JiHong88** [comment]
@agolovinmentalstack Thank you for finding the bug!
I will notify you after the version update.

**Comment by agolovinmentalstack** [comment]
Thank you so much @JiHong88 
I look forward to !!

**Comment by agolovinmentalstack** [comment]
@JiHong88 
I'm really sorry
But the same bug in images plugin
Could you fix it.

**Comment by JiHong88** [comment]
The [2.36.0](https://github.com/JiHong88/SunEditor/releases/tag/2.36.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
