### ISSUE TITLE
Unable to paste code into a Code block

### ISSUE THREAD

**Issue by csbarnes** [JiHong88/SunEditor#606]
Trying to paste (ctrl + v) a code snippet from GitHub (or any rich text source) into a code block on suneditor.com causes the code block to be removed and the code to be pasted with various and incorrect styles.
![SunEditor_pasting-ctrl-v](https://user-images.githubusercontent.com/1069246/105870002-71584500-5fbd-11eb-9efa-8e58870f3215.png)

Sometimes pasting doesn't remove the code block but the pasted code is heavily spaced (multiple new lines between lines, see SunEditor_pasting-ctrl-v-alt.png).
![SunEditor_pasting-ctrl-v-alt](https://user-images.githubusercontent.com/1069246/105870037-787f5300-5fbd-11eb-89b4-787ce1dd18a6.png)

**Comment by JiHong88** [comment]
@csbarnes 
The code HTML on "github" is in the form of a table.
Because the copied HTML is a table, it can't be helped.

One way, paste it into Notepad, then copy and paste again.
Thank you.

**Comment by csbarnes** [comment]
@JiHong88 This also happens when I try to paste from VSCode. 
![image](https://user-images.githubusercontent.com/1069246/106018190-e0e63700-6086-11eb-8feb-0308c63cb529.png)

Copying and pasting code seems like a really common use case, maybe there is a configuration option that could be exposed to prevent any sort of styles from applying on paste (similar to pasting with `ctrl + shift + v`)?

**Comment by arielcebulig** [comment]
issue stil active? 

please share how to fix this

**Comment by JiHong88** [comment]
I'll add pasting option `ctrl + shift + v`.
It will be update at the version 3.0.0

**Comment by JiHong88** [comment]
"`ctrl + shift + v`." The function is implemented in the browser.
