### ISSUE TITLE
wrong condition in submitAction (image plugin)

### ISSUE THREAD

**Issue by agolovinmentalstack** [JiHong88/SunEditor#607]
I'm really sorry!!
I saw you fixed this error for audio and video
Thank you
Could you do the same for images 

Please chage on submitAction on images plugin

if (this.functions.onImageUploadError !== 'function' || this.functions.onImageUploadError(err, { 'limitSize': limitSize, 'currentSize': infoSize, 'uploadSize': fileSize }, this))

to this
if (typeof this.functions.onImageUploadError !== 'function' || this.functions.onImageUploadError(err, { 'limitSize': limitSize, 'currentSize': infoSize, 'uploadSize': fileSize }, this))

reason:

    onImageUploadError is not called correctly

case:

    set imageUploadUrl
    set imageUploadSizeLimit === 1
    try add any image to call error
    onImageUploadError is not called correctly
    
    
I

**Comment by JiHong88** [comment]
@agolovinmentalstack Thank you.
This issue is fixed.
I will notify you after update version.

**Comment by JiHong88** [comment]
The [2.36.0](https://github.com/JiHong88/SunEditor/releases/tag/2.36.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
