### ISSUE TITLE
'/' added before links even if I start link with 'mailto:...'

### ISSUE THREAD

**Issue by EvgenPastushek** [JiHong88/SunEditor#608]
Hello!

When I try to paste link without protocol but with 'mailto:...' it still recognized as relative link (`http://localhost:8080//mailto:some@email.ex`)

![6e66a4374574beb25852163847ef96a1](https://user-images.githubusercontent.com/9965279/106020213-912e5c80-60d4-11eb-853f-991f4bfe77d2.png)

It seems it could be fixed in `_onLinkPreview` method for `link`

Thank you!

**Comment by JiHong88** [comment]
The [2.36.0](https://github.com/JiHong88/SunEditor/releases/tag/2.36.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by EvgenPastushek** [comment]
@JiHong88 all works perfectly! thank you!
