### ISSUE TITLE
alignment is not preserved

### ISSUE THREAD

**Issue by s-kris** [JiHong88/SunEditor#609]
When we write some text and save it to db and load it to editor, text alignment is removed.

edit: 
I used   p: 'style|text-align' to whitelist but I feel this should be inbuilt.

**Comment by JiHong88** [comment]
Yes, I have identified a problem with the current style.
Although it was improved, it was decided to apply in version 3.0.0 due to compatibility problems with the previous version.

**Comment by s-kris** [comment]
Thank you!

**Comment by JiHong88** [comment]
It has been fixed in the latest version.
The "text-align" style is maintained on lines such as P tags.

**Comment by whybein** [comment]
Text alignment is fixed but image alignment especially to the right is not working fine. It is aligned to center.
I fixed this by code below on react(NEXTjs)

```
if (typeof window !== 'undefined') {
    const { width } = document.getElementsByClassName('__se__float-right')[0].firstChild.firstChild;
    document.getElementsByClassName('__se__float-right')[0].firstChild.style.removeProperty('margin');
    document
      .getElementsByClassName('__se__float-right')[0]
      .firstChild.setAttribute('style', `width:${width}px; margin-left:auto!important;`);
}
```

and then It shows peroperly
```
<div class="... __se__float-right">
<figure style="width: 200px; margin-left:auto;">
...
```
