### ISSUE TITLE
Something seems wrong in all samples

### ISSUE THREAD

**Issue by nickbe** [JiHong88/SunEditor#615]
When trying any of the demos I always have to define the style:

 .sun-editor .se-btn-tray {
          height: auto;
  }

otherwise the toolbar has a height of 100%:
![image](https://user-images.githubusercontent.com/10890765/106364674-1ca42980-6331-11eb-8eb1-9fed6971407e.png)

**Comment by JiHong88** [comment]
Hi @nickbe 
This issue is not reproduced.
Check if other css is affecting.

**Comment by JiHong88** [comment]
CSS - "height: auto;" Will be modified.
I think this is more appropriate.

**Comment by JiHong88** [comment]
Version [2.36.1](https://github.com/JiHong88/SunEditor/releases/tag/2.36.1) has been updated.
Thank you.

**Comment by nickbe** [comment]
Thanks
