### ISSUE TITLE
How to get current node 

### ISSUE THREAD

**Issue by crying2812** [JiHong88/SunEditor#617]
Sorry to post many questions.. 
But i got trouble when get the current node, i used getSelectionNode() to get the DOM but sometimes i got only string, how can i got only p tag in my scenario?
Thanks !
![Screenshot_4](https://user-images.githubusercontent.com/7057776/106445935-391b9f80-64b2-11eb-8ba3-5b6b504d30c0.png)

**Comment by JiHong88** [comment]
`core.util.getFormatElement(core.getSelectionNode())` or `core.getSelectedElements(null)`
http://suneditor.com/sample/html/out/document-editor.html#getSelectedElements

**Comment by crying2812** [comment]
Thanks so much, it worked :D
