### ISSUE TITLE
In simple balloon editor toolbar won't show up in the end of the line

### ISSUE THREAD

**Issue by vishnuprasadkv55** [JiHong88/suneditor#624]
In the demo hosted here, [sun editor](http://suneditor.com/sample/index.html)

1. navigate to the balloon tab
2. move cursor to the end of line
3. double click in order to show up the toolbar

Expected result: toolbar must show up
Actual result: toolbar not appearing

![image](https://user-images.githubusercontent.com/31810675/107048291-cb8fac00-67ee-11eb-90bb-f1d204857f28.png)

**Comment by JiHong88** [comment]
@vishnuprasadkv55 The "Balloon" mode only displays the toolbar when range select.
You can use the "balloon-always" mode.
