### ISSUE TITLE
Cannot redefine property: SUNEDITOR

### ISSUE THREAD

**Issue by skaplun** [JiHong88/SunEditor#626]
Great tool!
using it inside of an extension that loads content script into page with the editor in a shadowroot.
Whenever a link (<a href="#" ) is clicked outside of the shadow, getting this error : "Cannot redefine property: SUNEDITOR"

Possible to explain what this is?

**Comment by JiHong88** [comment]
@skaplun Please tell me more about the test situation.

**Comment by JiHong88** [comment]
Apart from this issue,  fixed a bug that controller not working in "shadowRoot" environment.
Applicable in the next version.

**Comment by skaplun** [comment]
The issue happens on any link click, after the library is imported into the page, via the browser extension. 
Before any call to Suneditor.Create

Will attempt to produce a test.

in what you chose to push to dist, why include this? 

Object.defineProperty(window, 'SUNEDITOR', {
  ....
    value: suneditor.init({
        plugins: plugins
    })
});

**Comment by JiHong88** [comment]
Um..Now that code doesn't mean much. 
Can you show me the test code so I can see the error?

**Comment by JiHong88** [comment]
The [2.36.2](https://github.com/JiHong88/SunEditor/releases/tag/2.36.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
