### ISSUE TITLE
Ability to remove body class on preview output

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/SunEditor#629]
When you click the preview button, the class `sun-editor-editable` is always added to the body. Is there a way to remove this class? I tried setting `_editableClass` in the options, but that doesn't work unfortunately.

The reason is because the CSS of SunEditor affects the eventual output. See attached video

https://user-images.githubusercontent.com/16164800/107636959-b8a52d80-6c6d-11eb-93f8-584d02a6c619.mp4

**Comment by JiHong88** [comment]
@guido-visser If you do not include the "sun-editor-editable" class, you will get different results than editing mode of the editor.
Why should you remove the class?

**Comment by guido-visser** [comment]
Sorry for the late repsonse. I use the SunEditor as a documentation tool. So I save it's contents and display those contents elsewhere (where the `sun-editor-editable` class doesn't exist). So a preview with that class is an incorrect representation of the final result. 

All I ask for is an option to not include the class, that will solve my issue.

**Comment by JiHong88** [comment]
@guido-visser Um..Do you need a preview without the "sun-editor-editable" class?

**Comment by guido-visser** [comment]
Yes

**Comment by JiHong88** [comment]
This is an unusual option.
I will modify it possible to set the "_editableClass" option, which is an internal option value.

**Comment by guido-visser** [comment]
Thanks! Just to clarify, it should only be changing the class on the body of the preview output. Not on the rest of the SunEditor.

**Comment by JiHong88** [comment]
The [2.36.5](https://github.com/JiHong88/SunEditor/releases/tag/2.36.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
