### ISSUE TITLE
Value from string function

### ISSUE THREAD

**Issue by rakahamdi** [JiHong88/SunEditor#630]
Hi, i was using **react-rte** for my projects and using createValueFromString function. i wanna ask for that function in suneditor.

Thanks.

error like this
![image](https://user-images.githubusercontent.com/78925102/107672704-cc7d7d80-6cc7-11eb-9ace-611a570ace43.png)
code like this
![image](https://user-images.githubusercontent.com/78925102/107672572-a2c45680-6cc7-11eb-9502-165af33507e2.png)

any suggestions?

**Comment by JiHong88** [comment]
@rakahamdi You can use an "value" option.
```javascript
suneditor.create('id', {
  value: 'html'
})
```
