### ISSUE TITLE
Width adjustment in responsive is not enabled when toolbar is balloon.

### ISSUE THREAD

**Issue by scs-yoshimori** [JiHong88/SunEditor#632]
This is a fixed part in v2.35.0, but when the mode is balloon or inline and the toolbar is not always displayed, it seems that the button arrangement in responsive width is not displayed well.

https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L6674

The value is obtained using offsetWidth, but in the state of "display: none" such as balloon, it becomes undefined or 0, so I think that it is because the conditional branch is not done well.

**Comment by JiHong88** [comment]
The [2.36.2](https://github.com/JiHong88/SunEditor/releases/tag/2.36.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by scs-yoshimori** [comment]
I confirmed the correction contents.
Thank you.
