### ISSUE TITLE
Insert image modal zindex

### ISSUE THREAD

**Issue by rakahamdi** [JiHong88/SunEditor#633]
Hi!
I've done such many things from this great text editor. But, there's something bothering me when i click image icon to upload images. The image modal collapse with other text editor that i have in same page. Is there anything i can do besides edit the zindex manually from css?

Thanks

![Screen Shot 2021-02-18 at 16 31 18](https://user-images.githubusercontent.com/78925102/108336697-e6a6e680-7206-11eb-8da7-8718e106c66b.png)

**Comment by JiHong88** [comment]
Hi @rakahamdi 
Since all HTML is generated in the `.sun-editor` div, increase the `z-index` of `.sun-editor` class.
