### ISSUE TITLE
Balloon mode have a bug in Chrome

### ISSUE THREAD

**Issue by novikov1337danil** [JiHong88/suneditor#636]
In **Chrome**, if you select all the text in the editor, and without releasing the left mouse button move the cursor outside the editor window, then the pop-up menu does not appear.

But in **FireFox** its work.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/44060868/108518182-538ab100-72d9-11eb-978c-f77d5215ca76.mp4

</details>

**Comment by JiHong88** [comment]
@novikov1337danil "balloon" mode operates by detecting the mouse click event.
"chrome" doesn't seem to call the click event when it goes out of the event target.
Other editors work fine in the same situation, but currently I'm not sure how I handled the "balloon" mode.
I will resolve this issue later.

**Comment by andylwelch** [comment]
Can confirm this issue still exists
