### ISSUE TITLE
Image Link Issue

### ISSUE THREAD

**Issue by pearceMolekin** [JiHong88/SunEditor#637]
Links around images are not persistent after viewing code. This is also an issue when loading previous text to edit. 

Steps to reproduce:
1. Insert image with URL
2. Select the Link tab and link to page
3. Submit
4. Select View Code button
5. Select View Code button again
6. Edit image and select Link tab. 
7. Link is no longer available 

The `<a>` tags appear to be stripped when inside `<figure>` tags

**Comment by JiHong88** [comment]
The [2.36.4](https://github.com/JiHong88/SunEditor/releases/tag/2.36.4) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
