### ISSUE TITLE
setOptions problem

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#639]
Hi @JiHong88 
I have realized that setOptions with lang has not been working since version 2.35.0
Check out the demo at [https://codepen.io/mkhstar/pen/XWJwGYK?editors=1111](https://codepen.io/mkhstar/pen/XWJwGYK?editors=1111)

**Comment by mkhstar** [comment]
I have realized that it is not only the lang property is having an issue. The value option also looses some styles since version 2.35.0

**Comment by mkhstar** [comment]
The demo that I have presented at [https://codepen.io/mkhstar/pen/XWJwGYK?editors=1111](https://codepen.io/mkhstar/pen/XWJwGYK?editors=1111)
demonstrates that it works on version 2.34.0 but version later encouter these problems

**Comment by JiHong88** [comment]
Hi @mkhstar 
The [2.36.5](https://github.com/JiHong88/SunEditor/releases/tag/2.36.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
