### ISSUE TITLE
The horizontal line fade out when adding a video

### ISSUE THREAD

**Issue by heloan** [JiHong88/SunEditor#642]
**Issue:**
When I add a horizontal line in SunEditor and after that add a video or image, the horizontal line fade out.

**Steps to reproduce the issue:**
1.	Add horizontal line
2.	Type space (Will add a line break before the horizontal line) )
![SunEditor (1)](https://user-images.githubusercontent.com/26145301/108922436-f1ea7f80-7615-11eb-8827-1be32387ba40.gif)
![SunEditor (1)](https://user-images.githubusercontent.com/26145301/108922633-2b22ef80-7616-11eb-8f2c-d4e658e881d4.jpg)

3.	Type the directional key top (This will change the teg hr into a p)
 ![SunEditor (2)](https://user-images.githubusercontent.com/26145301/108922642-2eb67680-7616-11eb-92b5-83d2395ccc13.gif)
![SunEditor (2)](https://user-images.githubusercontent.com/26145301/108922743-4beb4500-7616-11eb-889a-df45755a44d9.jpg)

 
4.	Add a video or an image
![SunEditor (3)](https://user-images.githubusercontent.com/26145301/108922767-56a5da00-7616-11eb-9ae1-90711523aacf.gif)

**Comment by JiHong88** [comment]
The [2.36.5](https://github.com/JiHong88/SunEditor/releases/tag/2.36.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
