### ISSUE TITLE
Indent icon for lists not enabled after 2 levels 

### ISSUE THREAD

**Issue by davetimmins** [JiHong88/SunEditor#646]
Hi,

if you start a new list then add an item, indent it, add another item then you can no longer indent it again. Can this be changed to allow as many levels of nesting as the user wants? In the image the indent should be enabled when the cursor is at the c. node

![image](https://user-images.githubusercontent.com/1118347/109578526-34ebac00-7b5c-11eb-9963-e431be8563b2.png)

**Comment by JiHong88** [comment]
Hi,
There seems to be a bug in the disabled state of the button. 
You can indent up with the "tab" key.

**Comment by JiHong88** [comment]
The [2.36.5](https://github.com/JiHong88/SunEditor/releases/tag/2.36.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
