### ISSUE TITLE
Save to file example

### ISSUE THREAD

**Issue by oleteacher** [JiHong88/SunEditor#65]
Have been trying to use in my classroom for example project.

Cannot for life of me get content to save to a text file which is loaded into a simple blog via PHP include (or file get contents)..

Would be be possible to bother you for working example? Simply need to save to a text (txt) file.

Thanks in advance.

Susan

**Comment by JiHong88** [comment]
Hi~

It is easy to bring contents.

You can use the getContents method.

Here is an example. ([example page](http://suneditor.com/sample/html/examples.html))

`const editor = SUNEDITOR.create('example')`
`const contents = editor.getContents()`

Please tell me if you have any more questions. : -)

**Comment by oleteacher** [comment]
Thank you for reply.

Yes, I have seen the getContents method on example page. No luck but will try and find some help to use correct PHP on my side.
