### ISSUE TITLE
How to disable double click event on pargraph

### ISSUE THREAD

**Issue by crying2812** [JiHong88/SunEditor#651]
Hi JiHong, like the title, i want to disable double click event to prevent some actions unexpected. How can i do that? Thanks

**Comment by JiHong88** [comment]
@crying2812 Where do you want to prevent double click? 
There are currently no settings for double click.

Register the event yourself like this: 
```javascript
const instance = suneditor.create(..);

instance.onload = (core) => {
  const wysiwygArea = core.options.iframe ? core._ww : core.context.element.wysiwyg;
  const toolbar = core.context.element.toolbar;
  const modal = core.context.dialog.modalArea;

  wysiwygArea.addEventListener('dblclick', (event) => {
    //
  });
}
```

**Comment by crying2812** [comment]
Thanks for quick response, i want to prevent double click on each paragaph, i will try your way first :D

**Comment by crying2812** [comment]
I tried your way but sadly it's not working, is there other way to bind custom event listener ?

**Comment by JiHong88** [comment]
@crying2812 It may not be possible if you are trying to block the range selection by double click. 
It is not blocked by `event.preventDefault()`.
