### ISSUE TITLE
removeFormat on the way out or after paste

### ISSUE THREAD

**Issue by jesben** [JiHong88/SunEditor#652]
Hi awesome editor thank you!

I have a question, I want to execute removeFormat on all content before I "save data" or after user paste content from external source. Any hooks for paste?

I have tried this, but only selectAll works. When I click the button "removeFormat" it works! "Angular app"
```
save() {
    this.editor.core.execCommand('selectAll');
    this.editor.core.execCommand('removeFormat');
    
    let content = this.editor.getContents(true);
```
Furthermore, I want to remove class attributes and script tags from content, think I will do it with regex, what will you do?

**Comment by JiHong88** [comment]
You must be use the `commandHandler` method.
```javascript
this.editor.core.commandHandler('selectAll');
this.editor.core.commandHandler('removeFormat');
```

paste event funtion: http://suneditor.com/sample/html/out/document-user.html#onPaste
If it returns string, it changing the paste value.
```javascript
this.editor.onPaste = (e, cleanData, maxCharCount, core) => {

}
```
