### ISSUE TITLE
How do I set a default font-size of 1.5 for Math plugin?

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#653]
Currently, the default font-size is set to 1. How do I change it so that the default value becomes 1.5 (or anything that I set)
![image](https://user-images.githubusercontent.com/50414962/110316212-6b2f9c80-8030-11eb-82c6-843e2cf1718e.png)

**Comment by JiHong88** [comment]
@dgandhi1993 Currently, It's impossible.
I'll add a 'mathFontSize` option.

**Comment by JiHong88** [comment]
The [2.37.0](https://github.com/JiHong88/SunEditor/releases/tag/2.37.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
