### ISSUE TITLE
Bearer token with image gallery

### ISSUE THREAD

**Issue by chemarf** [JiHong88/SunEditor#654]
Hi
I had the bearer token on header for upload image with **imageUploadHeader** but the header isn't sended on image gallery request. 
I have not see the good option ?

Thanks for your help.

**Comment by JiHong88** [comment]
@chemarf  There is currently no option to set the header of the image gallery.
I will notify you after adding.

**Comment by JiHong88** [comment]
The [2.37.0](https://github.com/JiHong88/SunEditor/releases/tag/2.37.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
