### ISSUE TITLE
Realtive links

### ISSUE THREAD

**Issue by AversaConsulting** [JiHong88/SunEditor#66]
Is there a way of having relative links 

e.g. /info/contactus

instead of it changing it to http://info/contactus

Thanks

**Comment by JiHong88** [comment]
Hi

Relative paths are not supported.

When you insert "info/contactus", it is automatically appended to "http: //"

Thanks : )

**Comment by AversaConsulting** [comment]
Is it planned as a feature? Not a major worry - just while testing and running locally it’s adding localhost as the domain, which obviously doesn’t work live. Great bit of kit though so many thanks!

**Comment by JiHong88** [comment]
Removed the default "http: //" string of link plugin.

Available in version [2.5.3](https://github.com/JiHong88/SunEditor/releases/tag/2.5.3).

It seems that the correct behavior is to have a relative path available.

Thanks : )

**Comment by AversaConsulting** [comment]
fantastic thanks!

**Comment by gryzzly** [comment]
Hi @JiHong88, using the latest version I have the same problem.

If I add set link path to `/foo` I get the current hostname prepended. I want a relative link to be constructed. Is that possible somehow? 

Thanks!

**Comment by JiHong88** [comment]
@gryzzly Can you show me an example of "input" and "output" that should work?

**Comment by gryzzly** [comment]
@JiHong88 I expect input of `/cv` to produce a link like `<a href="/cv">CV</a>` – it’s a CMS for a blog, so I’d love to be able to link to other pages of this blog. Thanks for looking into it!

**Comment by JiHong88** [comment]
@gryzzly Sorry, for the late reply.
Set option `linkProtocol: "/"` and enter "cv" in the input box.
If you type "/" and write an address, "/" will be appended to the end of the current address.
If there is a slightly more intuitive way, please tell me.
