### ISSUE TITLE
Tab key causing uncaught error

### ISSUE THREAD

**Issue by peter-chow** [JiHong88/SunEditor#660]
Hello,

I'm experiencing an issue where pressing the tab key in the editor doesn't insert a tab but instead causes an uncaught error (this is through the suneditor-react module):

Uncaught TypeError: Cannot read property 'toString' of undefined
at Object.getByteLength (main.js:947)
at Object.getCharLength (main.js:2206)
at Object.checkCharCount (main.js:2200)
at Object.insertNode (main.js:1921)
at HTMLDivElement.onKeyDown_wysiwyg (main.js:2308)

This error occurs when you specify a value for: maxCharCount, and set the charCounterType to: byte-html.  If you set, charCounterType to: char or byte, no error is thrown.

This is using version 2.36.5.

Regards,
Peter

**Comment by JiHong88** [comment]
@peter-chow The issue is not reproduced.
Please tell me about the other options you have used and the test environment.

**Comment by peter-chow** [comment]
@JiHong88, the following options have been specified:

{
  buttonList: [['undo', 'redo'], ['formatBlock'], ['bold', 'underline', 'italic', 'removeFormat'], ['outdent', 'indent', 'align'], ['link', 'list', 'table']],
  formats: ['p', 'h1', 'h2', 'h3', 'blockquote'],
  resizingBar: false,
  showPathLabel: false,
  maxCharCount: 100, 
  charCounterType: 'byte-html' 
}

The issue can also be reproduced on the SunEditor Option page (http://suneditor.com/sample/html/options.html) by specifying a maxCharCount and setting the charCounterType to "byte-html".  This occurs on Edge, Chrome and Firefox,

**Comment by JiHong88** [comment]
The [2.37.0](https://github.com/JiHong88/SunEditor/releases/tag/2.37.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by peter-chow** [comment]
Thanks @JiHong88.  I'll give it a test.
