### ISSUE TITLE
use editor's styles for content copied from html sources

### ISSUE THREAD

**Issue by s-kris** [JiHong88/suneditor#661]
When we copy content from other sources like google docs or a webpage and paste it into suneditor, how to make sure that the pasted content will use styles of the suneditor?

Thank you!

**Comment by JiHong88** [comment]
@s-kris All content is modified for "suneditor" style.

**Comment by s-kris** [comment]
Sorry, I tried copying from medium, google docs, other websites etc.. the pasted content retains the original style.
Is there a config variable?

**Comment by JiHong88** [comment]
Paste it here http://suneditor.com/sample/index.html
Are there any differences?

**Comment by s-kris** [comment]
Yes. I tested this. 

http://suneditor.com/sample/index.html --> pasted content's styles are changed to suneditor's

but for my editor, they remain the same.

**Comment by JiHong88** [comment]
Show me the options you are using.

**Comment by s-kris** [comment]
<SunEditor
            setDefaultStyle=""
            placeholder="Word your thoughts here..."
            setOptions={{
                minHeight: 500,
                height: 'auto',
                buttonList: [
                    ['formatBlock', 'bold', 'italic', 'underline', 'list'],
                    ['link', 'image', 'video'],
                    ['align', 'horizontalRule'],
                    ['undo', 'redo'],
                ],
                imageAccept: 'image/.jpg, .jpeg, .png, .gif',
                imageUrlInput: false,
                showPathLabel: false,
                formats: [
                    {
                        tag: 'p',
                        name: 'Normal',
                        command: 'replace',
                        class: '',
                    },
                    {
                        tag: 'h2',
                        name: 'Heading',
                        command: 'replace',
                        class: '',
                    },
                    {
                        tag: 'h3',
                        name: 'Subheading',
                        command: 'replace',
                        class: '',
                    },
                    'blockquote',
                    'pre',
                ],
                linkRel: ['nofollow'],
                attributesWhitelist: {
                    img: 'alt',
                    p: 'style|text-align',
                },
            }}
            onChange={handleEditorChange}
            disable={props.readonly}
            setContents={props.postContent}
            onImageUploadBefore={(files, info, uploadHandler) => {
              // img-uploader
            }}
        />

**Comment by JiHong88** [comment]
Try it to below options
```
attributesWhitelist: {
  img: 'alt',
  p: 'text-align',
},
```

**Comment by s-kris** [comment]
Awesome, this converts content pasted from medium and substack to suneditor's format.
But content from google docs and few other websites, keeps original format.

**Comment by JiHong88** [comment]
It is correct that the accepted format is maintained.
Please show me the example.

**Comment by s-kris** [comment]
## Google docs

![Screenshot 2021-03-13 at 11 54 15 PM](https://user-images.githubusercontent.com/3975305/111040116-b0503600-8457-11eb-83c5-9224ab747101.png)

## suneditor

![Screenshot 2021-03-13 at 11 56 56 PM](https://user-images.githubusercontent.com/3975305/111040207-d70e6c80-8457-11eb-9c4c-c0ccf4501577.png)

## Medium

![Screenshot 2021-03-13 at 11 57 39 PM](https://user-images.githubusercontent.com/3975305/111040228-f6a59500-8457-11eb-9577-4341b741b821.png)

## suneditor

![Screenshot 2021-03-13 at 11 59 08 PM](https://user-images.githubusercontent.com/3975305/111040258-2359ac80-8458-11eb-94d5-4eb6f11ee18d.png)

I want to convert content copied from google docs also to suneditor's format. :)

**Comment by JiHong88** [comment]
@s-kris Sorry, I don't understand.
How do I have to change it?
Can you share the Google file?

**Comment by s-kris** [comment]
Apologies. When content is copied from medium page and pasted in the editor, text is converted to suneditor's format.
But when the content is copied from google docs and pasted in the editor, text is NOT converted to suneditor's format.

Please find word doc attached below
[word doc] (https://github.com/JiHong88/SunEditor/files/6141563/Copy.of.Tips.to.increase.fashion.store.sales.docx)

**Comment by JiHong88** [comment]
Paste is well worked.
It removes the disallowed tags, but nothing is transformed into another tag. 
What exactly does the suneditor format mean?

**Comment by s-kris** [comment]
Thanks!
I meant, if we copy-paste something from word doc or other sources - text size, font style etc should look according to default styles of the editor.

**Comment by JiHong88** [comment]
Yes All styles are currently being removed. 
Does mean that all text should be marked with a P tag?

**Comment by s-kris** [comment]
Yes. 
Right now, font-sizes and colors are retained.

**Comment by JiHong88** [comment]
The style of the span tag is preserved.
You can remove the "span" tag when pasting with the "pasteTagsWhitelist" option setting, but the "span" tag will disappear even when you paste text in the editor.
Currently, it cannot be applied differently by determining whether it is an external source or an internal source when pasting.
In version 3.0.0, I will add a method to customize this part. 
```
suneditor.create('..', {
  pasteTagsWhitelist: 'br|p|div|pre|blockquote|h[1-6]|ol|ul|li|hr|figure|figcaption|img|iframe|audio|video|source|table|thead|tbody|tr|th|td|a|b|strong|var|i|em|u|ins|s|strike|del|sub|sup|code|svg|path'
})
```

**Comment by s-kris** [comment]
That's fantastic! Thank you 🙏🏻
