### ISSUE TITLE
Pagination support in SunEditor?

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/suneditor#662]
@JiHong88 Thank you for the amazing editor.
I want to implement pagination with the size of the "A4" sheet. is there any idea or way to implement pagination?

Reference:
https://ckeditor.com/docs/ckeditor5/latest/features/pagination.html#demo

Thanks in Advance.

**Comment by JiHong88** [comment]
@gopal1996 It will be added in version 3.0.0.

**Comment by Braweria** [comment]
That sounds awesome. Will this feature also make the editor look like pages? Similar to what you see in Google Docs.

**Comment by JiHong88** [comment]
@Braweria If you modify the style, it will be quite possible.

**Comment by Braweria** [comment]
> @Braweria If you modify the style, it will be quite possible.

Do you mean with the current version or with version 3 this will be possible?

**Comment by JiHong88** [comment]
"pagination" is available in version 3.0.0, but the "document" style is available in CSS in the current version. 
You can change the CSS by modifying it.

**Comment by Braweria** [comment]
> "pagination" is available in version 3.0.0, but the "document" style is available in CSS in the current version.
> You can change the CSS by modifying it.

any specific classes I can select in my stylesheet for this to work? or is this basically trial and error?

**Comment by Braweria** [comment]
`se-wrapper-inner se-wrapper-wysiwyg sun-editor-editable` is what I see, but I don't see an option to design it to look like pages.

**Comment by JiHong88** [comment]
There are no options.
You will need to edit the CSS yourself.

**Comment by Braweria** [comment]
> There are no options.
> You will need to edit the CSS yourself.
> ex)
> 
> ```
> .se-wrapper {
>   padding:20px;
>   background: #ccc;
> }
> ```

Right, but I wanted to do something like on the right, currently the editor is like on the left:
![image](https://user-images.githubusercontent.com/62669899/115010139-5eaf2700-9ead-11eb-8521-dd755d9b4feb.png)

**Comment by JiHong88** [comment]
@Braweria OK, I'll notify you know when this features are added.

**Comment by emmannyyy** [comment]
hi!
Thanks so much for maintaining this amazing repo, it is rly awesome. 


May I know if what @wiktoriavh suggested for the pages has been accomplished? If so, how may I configure my suneditor to achieve this so it mimics something like Google Docs? 

Thank you in advance

**Comment by emmannyyy** [comment]
Hello @JiHong88 ,

Once again, thank you for creating and maintaining this awesome editor. 
Regarding the commits you've made for the documentType and pageNavigator, how do we properly instantiate it? 

I've installed V3, but can't quite figure out how to handle paging and pageNavigation. 

Here is how I've tried to instantiate the sunEditor instance. 

```  javascript
const editor = suneditor.create(element, {
    plugins: plugins, //(I've included all plugins)
    buttonList: [...
    ],
    

// Document type configuration - critical for pagination
    documentType: 'A4', // A4 page size
    typeOptions: ['page', 'header'], // Enable both page and header features
   
    // Content settings
    contenteditable: true,
    focus: true,
    hideToolbar: false
  });
``` 

Also, wondering if there's any ability to add Headers and Footers? 

If there isn't, I'll be happy to code out a plugin for Header and Footer support for A4 documents, but not quite sure how to get started. 

Hope to hear from you :)

**Comment by JiHong88** [comment]
@emmannyyy 
Try this:
```js
const editor = suneditor.create(element, {
 type: 'document:header,page',
})
```
There is no function to add header and footer. 
Can you give me an example of what format it would be?
