### ISSUE TITLE
Add Inline Style for Table tag

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/suneditor#663]
Hi,

I am getting HTML content from the onChange function and sending those HTML data to the server to generate PDF.
Since table uses sunEditor class to apply styles. not able to captures the style details from onChange.
so, while generating PDF, the table loses the style and it coming as text.

Is there any way I can configure to apply inline styles to the table tag?

please find below the attached screenshot for reference

<img width="1775" alt="Screenshot 2021-03-14 at 1 19 30 AM" src="https://user-images.githubusercontent.com/22369081/111042425-56556d80-8463-11eb-8a68-b2de5d49d16d.png">

PDF Generated based on HTML data from SunEditor:
<img width="799" alt="Screenshot 2021-03-14 at 1 20 47 AM" src="https://user-images.githubusercontent.com/22369081/111042454-843ab200-8463-11eb-9e47-76780ca25a56.png">

Thank you in Advance

**Comment by JiHong88** [comment]
@gopal1996 I'll try find a way.

**Comment by pengzj** [comment]
Not only the PDF, but also sometimes we need to export the html content to other users, like api, they don't have the css file but we need to show original appearance .

THANK YOU FOR YOUR PERFECT JOB.

**Comment by AbdiasMichael** [comment]
@JiHong88 is this added in the latest version? I'm using the latest version but I don't see inline styles of table or any other element.
