### ISSUE TITLE
Blacklist for tags

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/SunEditor#664]
The options have an `addTagsWhitelist` and  a `pasteTagsWhitelist`. I don't really care what the users paste (as long as it's not custom javascript in a script tag). So is it possible to add options for `tagsBlacklist` and `pasteTagsBlacklist`?

The idea is the same as the existing whitelist options, but does the opposite: it removes the tags in finds in the string.

An example could be:

```js
const options = {
   pasteTagsBlacklist: "script|link", //Removes script and link tags on paste,
   tagsBlacklist: "script|link" //Removes the tags when inserted via HTML editor
}
```

**Comment by JiHong88** [comment]
@guido-visser Good idea.
I will update it in addition to next version.

**Comment by JiHong88** [comment]
The [2.37.0](https://github.com/JiHong88/SunEditor/releases/tag/2.37.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by guido-visser** [comment]
Thanks @JiHong88, now it's up to @mkhstar to update the release version in the suneditor-react package
