### ISSUE TITLE
List alignment...

### ISSUE THREAD

**Issue by cacuestai** [JiHong88/SunEditor#666]
Hello:

A great editor! 
Could this visual enhancement be implemented in the lists?

![solicitud-suneditor](https://user-images.githubusercontent.com/2236441/111560116-d4658d00-875f-11eb-90c8-2522f47a9cf3.jpg)

Greetings

**Comment by JiHong88** [comment]
From the screenshot, you can't tell which tag you put the style in.
All styles of the editor edit area are defined here. https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css
Implement it by overriding css.

**Comment by cacuestai** [comment]
Hello:
Try in your demo a list element with a very long character string so that you see the alignment on the left side.
Greetings

**Comment by JiHong88** [comment]
The [2.37.2](https://github.com/JiHong88/SunEditor/releases/tag/2.37.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
