### ISSUE TITLE
How to insert content where the cursor?

### ISSUE THREAD

**Issue by Q-bick** [JiHong88/SunEditor#67]
Hello,
How to insert HTML content where the cursor? (For example, insert a picture from the my gallery)

Function "appendContent" inserts at the end of the article.

P.s. sry for my eng.

**Comment by JiHong88** [comment]
Hi,

You can use the "insertHTML" function.

Added to version [2.5.2](https://github.com/JiHong88/SunEditor/releases/tag/2.5.2)

[Example](http://suneditor.com/sample/html/examples.html#functions) and [documents](http://suneditor.com/sample/html/out/document-user.html#insertHTML)

Thanks : )

**Comment by Q-bick** [comment]
Oh Thx. You are best!
