### ISSUE TITLE
Can't reposition image with dragging

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/suneditor#670]
It appears that trying to reposition the image by dragging doesn't work. Is this intentional, or is this supposed to work? 

https://user-images.githubusercontent.com/16164800/111647616-ec421d00-8802-11eb-92e0-43bf5a41d5ce.mp4

**Comment by JiHong88** [comment]
Image dragging is currently not supported.
It will be added in version 3.0.0.

**Comment by guido-visser** [comment]
@JiHong88 Cool! Do you have an indication on when 3.0.0 will be released? I see it has lots of promising features :)

**Comment by JiHong88** [comment]
@guido-visser I expecting about 2 months..

**Comment by Dzoukr** [comment]
Hi @JiHong88, please do you have any update on version 3 🙏 Btw, thanks for the amazing work!
