### ISSUE TITLE
Bug: Insert image using a link doesn't work

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/SunEditor#676]
When you want to insert an image via a link, it doesn't get inserted.

It's reproducable:
https://user-images.githubusercontent.com/16164800/112161410-6996d480-8beb-11eb-9b5c-654407296b57.mp4

**Comment by JiHong88** [comment]
@guido-visser Enter the image path in the "image url" input.
"Url to link" input is wraps the image with an "a" tag.

**Comment by guido-visser** [comment]
Sorry for raising this. You're right, I used the wrong field 😅
