### ISSUE TITLE
Can we exclude tags from being wrapped in `defaultTag`?

### ISSUE THREAD

**Issue by changyeamoon** [JiHong88/SunEditor#679]
I have the defaultTag set to div. 

I don't want to wrap `< br/ >` elements. Is there a way to exclude them from being wrapped?

**Comment by JiHong88** [comment]
@changyeamoon Enter the image path in the "image url" input.
"Url to link" input is wraps the image with an "a" tag.

**Comment by JiHong88** [comment]
@changyeamoon If you don't use `div` or `p` and you want to separate the lines by `br`, that's not possible.

**Comment by changyeamoon** [comment]
@JiHong88 thanks!
