### ISSUE TITLE
Does it work with Meteor js?

### ISSUE THREAD

**Issue by SaulSilver** [JiHong88/SunEditor#68]
Thanks for the cool work!

I have tried installing suneditor with `npm` and use it in my `Meteor` app by importing it like
```
import { Template } from 'meteor/templating';

import 'suneditor/dist/css/suneditor.min.css';
import suneditor from 'suneditor';

Template.rich_text_editor.onRendered(function() {
  const editor = suneditor.create('sample');
});
```
But the project breaks on the browser (Chrome and Firefox) and I believe it breaks in the `importing` line.
 
[![Image from Gyazo](https://i.gyazo.com/8965c2dce88c826bb9b9710c2a4daa26.png)](https://gyazo.com/8965c2dce88c826bb9b9710c2a4daa26)

This issue could not be related to suneditor but just wondering if you have any idea what the solution would be or if it's even meant to be working with `Meteor`?

Thank you!

**Comment by rousos87** [comment]
@SaulSilver I think the problem is not related with suneditor. I am not familiar with meteor but i think the issue could be from a a package or you need to update meteor. Please check this [https://github.com/meteor/meteor/issues/8693](url).

Thanks

**Comment by JiHong88** [comment]
Hi,

I have not used Meteor js, so it seems difficult to answer correctly now..

I'm sorry. : (

**Comment by hkennyv** [comment]
Hi @SaulSilver, I had this same issue and fixed it by running `meteor update` on my project.

**Comment by SaulSilver** [comment]
thank you very much all for the help! I'll go ahead and close this issue since it's out of scope of suneditor
