### ISSUE TITLE
On Pasting From Notepad losing new line property

### ISSUE THREAD

**Issue by vijayaragavan95** [JiHong88/SunEditor#681]
When I copy and paste three lines from notepad to Suneditor its getting pasted on the same line

Please check the attachment

Thanks in advance

https://user-images.githubusercontent.com/26658261/112515647-74ed2a00-8dbc-11eb-9eb2-1ffc4af6eb65.mp4

**Comment by JiHong88** [comment]
The [2.37.2](https://github.com/JiHong88/SunEditor/releases/tag/2.37.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
