### ISSUE TITLE
Image Upload not working properly

### ISSUE THREAD

**Issue by TutanRamon** [JiHong88/SunEditor#685]
Thanks for this wonderful editor.

I am struggling with the imageUpload function.

For test purposes, I have 1 simple method in my imageUploadController:

    public function upload(Request $request)
    {
        //ignore the request, just return a test image that exists on the server
      
        return response()->json(['result' => ['url' => '/images/test.jpg', 'name' => 'test.jpg', 'size' => '10000']]);
    }

The image exists on my server. 

However, when I use the imageUploadDialog and select a random image file on my computer, I expect that the json above will be returned. That's the case. This is the result:

    {"result":{"url":"\/images\/test.jpg","name":"test.jpg","size":"10000"}}

The mediaUploadUrl also returns a 200 OK status, but the image is not showing up in my editor.

What am I missing here?

**Comment by JiHong88** [comment]
@TutanRamon `result` is must be array type.
`{"result":["url":"\/images\/test.jpg","name":"test.jpg","size":"10000"]}`

**Comment by TutanRamon** [comment]
@JiHong88 Unbelievable :-)

Thanks for the prompt reply. It's working now. 

Can you also update your answer @ https://github.com/JiHong88/SunEditor/issues/369#issuecomment-626702667

**Comment by JiHong88** [comment]
@TutanRamon I didn't write that comment.🤣

**Comment by TutanRamon** [comment]
@JiHong88 Haha, sorry. Thanks again for the help.
