### ISSUE TITLE
setContents on an inline editor shows the toolbar

### ISSUE THREAD

**Issue by NickyTope** [JiHong88/SunEditor#686]
Hi, I can't be certain which version this started in but when I call setContents on an inline editor it makes the toolbar show, is this behaviour expected?

I am using a `toolbarContainer` to show the toolbar above the title of the document in my app and the toolbar now hides the title on opening any existing document.

I have started manually calling toolbar.hide() to get around this but wanted to raise it as an issue.

This can easily be replicated by setting the mode of the `ss` editor to `inline` in suneditor_build_test.js

Great work on this editor btw, we love it!!

**Comment by JiHong88** [comment]
The [2.37.3](https://github.com/JiHong88/SunEditor/releases/tag/2.37.3) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by NickyTope** [comment]
Thanks for the quick update however unfortunately this still happens in 2.37.3.

Setting `mode: 'inline'` in the `ss` editor in the test still replicates this issue.

Not sure if this is intended (or new?) but setContents always seems to set focus at the end of the content, can we possibly add a parameter to specify if focus is needed? `setContents(content, focus=true)` or something similar?

I don't have permission to reopen this issue, happy to resubmit if needed?

**Comment by JiHong88** [comment]
Use the `focus` method.
```javascript
editorInstance.setContents(content);
editorInstance.focus();
```

**Comment by NickyTope** [comment]
In my setup (and when I run the test locally) calling setContents automatically sets the focus, this is undesired.

You are correct however, this does not happen in the example page, I will try to recreate from a simple instance and get back to you, thanks for looking at this so quickly again!

**Comment by nuanda744** [comment]
I have the same problem. When I load the page it scrolls down to the editor if I use setContents...

**Comment by JiHong88** [comment]
@nuanda744 Are you using the latest version? 
Please explain in detail how you did the test and the status.

**Comment by nuanda744** [comment]
I'm using the latest version (2.37.4) inside a form rendered by a Google Apps Script Web App. The editor is working well. The only problem is it gets focus (scrolling down in the page) as soon as I load the page.
This is the init:
SUNEDITOR.create('firma',{
        font : [
            'Arial', 'Courier New', 'Impact',
            'Georgia','tahoma', 'Trebuchet MS', 'Verdana'
        ],
        fontSize : [
            8, 10, 14, 18, 24, 36
        ],
        colorList: [
            ['#ccc', '#dedede', 'OrangeRed', 'Orange', 'RoyalBlue', 'SaddleBrown'],
            ['SlateGray', 'BurlyWood', 'DeepPink', 'FireBrick', 'Gold', 'SeaGreen']
        ],
        width: '100%',
        height : 'auto',
        imageWidth : 150,
        popupDisplay: 'local',
        resizingBar: false,
        buttonList : [
        ['bold', 'underline', 'italic', 'strike', 'formatBlock', 'font', 'fontSize',
            'fontColor', 'hiliteColor'],
        ['link'],
        ['removeFormat', 'fullScreen', 'codeView', 'showBlocks']
        ],
    });

**Comment by JiHong88** [comment]
@nuanda744 Are there any event functions in use?

**Comment by nuanda744** [comment]
After the SUNEDITOR.create I only use editor.setContents(variable). The variable contains simple html code.
The code appear correctly rendered inside the editor. The only problem is that the textarea gets focus :-(

**Comment by JiHong88** [comment]
@nuanda744  If you delete `editor.setContents(variable)` code then is working nomally?

**Comment by nuanda744** [comment]
Yes. No focus problem without setContents...

**Comment by JiHong88** [comment]
@nuanda744 What is the test environment?

**Comment by JiHong88** [comment]
@NickyTope @nuanda744
The [2.38.0](https://github.com/JiHong88/SunEditor/releases/tag/2.38.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by nuanda744** [comment]
Thank you so much JiHong, it works :-)
