### ISSUE TITLE
Google docs text indentation

### ISSUE THREAD

**Issue by raulhinojosa** [JiHong88/SunEditor#687]
Hello, I've noticed an issue. 

I have a document in Google Docs - with many different forms to indent paragraphs. When I'm pasting it into `SunEditor`, the last paragraph doesn't get the indent (when you select all then this last one does not highlight that indent). 
This behavior only happens with this kind of indent since the value onPaste or the value itself get's no relevant HTML like spaces or spans with spaces.

I've searched for similar issues but can't find anything about it.

Link to Google Doc: https://docs.google.com/document/d/1dsg3T9CXqqurP0sOO2ITRslkzAaq13ueRXGyexL1faE/edit?usp=sharing
Video: https://www.loom.com/share/6f798ed7a26e4b4697b734c4fdc9edfd

Best regards,

Raul

**Comment by JiHong88** [comment]
The [2.37.3](https://github.com/JiHong88/SunEditor/releases/tag/2.37.3) version has been updated.

You must be using the `attributesWhitelist` option.
```
attributesWhitelist: {
  all: "style",
}
```

If this issue has not been resolved, please reopen this issue.
Thank you.
