### ISSUE TITLE
Idea: add search form to imageGallery

### ISSUE THREAD

**Issue by TutanRamon** [JiHong88/suneditor#689]
I love how the imageGallery works out of the box.  Most developer who will use it, will certainly create an json api for the call to retrieve the images. 
I would be great if we can add an option like 'imageGallerySearchUrl'. When set, a search bar needs to be shown in the gallery. 

So, I now have 
    imageGalleryUrl: "/admin/media/list/latest",

New attribute:
    imageGallerySearchUrl:  'admin/media/list/search?term='

My frontend js skills are not good enough to make a PR myself. Thanks in advance.

**Comment by JiHong88** [comment]
@TutanRamon Good Idea.
I'll add this feature at the v3.0.0

**Comment by ifielder** [comment]
This feature would be amazing! 

Or even a pagination option on the end of a scroll.

For example, I'm using Unsplash as my image gallery, and when the user scrolls to the bottom of the gallery, it would be awesome to load more images! 😁

Whatever you do, this is an awesome project and has saved me so much headache. 

Cheers.
