### ISSUE TITLE
Problem when pasting text containing HTML

### ISSUE THREAD

**Issue by cacuestai** [JiHong88/SunEditor#691]
Hello:

When pasting text with html tags in the normal editor, not in "source code" mode, this text is interpreted and should not be interpreted. Try pasting the following text and you will notice that it is interpreted before pasting:

`<div>, <p>, <h2>, <ul>, <ol>, <li>, <table>, <tr>, <td>, <dl>, <dd>, <dt>`

Greetings,

Carlos

**Comment by JiHong88** [comment]
<div>abc</div>

**Comment by cacuestai** [comment]
> The [2.38.0](https://github.com/JiHong88/SunEditor/releases/tag/2.38.0) version has been updated.
> If this issue has not been resolved, please reopen this issue.
> Thank you.

Fixed problem!
