### ISSUE TITLE
Suneditor crashes when 2 empty image links are set as source

### ISSUE THREAD

**Issue by Backdraft2100** [JiHong88/SunEditor#694]
When the textarea the suneditor is created for contains 2 or more image links with blank src reference then the editor crashes. If you test this with one image with blank src then no errors occurs.

Exception: image.js:763 Uncaught TypeError: Cannot read property 'replaceChild' of null

The file [report.txt](https://github.com/JiHong88/SunEditor/files/6263315/report.txt) includes a basic repro case html page for the issue.

**Comment by Backdraft2100** [comment]
Thank you

Op vr 9 apr. 2021 om 08:49 schreef JiHong.Lee ***@***.***>:

**Comment by JiHong88** [comment]
The [2.38.0](https://github.com/JiHong88/SunEditor/releases/tag/2.38.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
