### ISSUE TITLE
Is there a way to set a print template?

### ISSUE THREAD

**Issue by wmhartl** [JiHong88/SunEditor#696]
I cannot find an exposed printTemplate similar to previewTemplate - is one available? If not, adding one would be much appreciated. I'm looking for the template to be applied prior to the print.

Thank you for your great editor!

**Comment by JiHong88** [comment]
The [2.38.0](https://github.com/JiHong88/SunEditor/releases/tag/2.38.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
