### ISSUE TITLE
The expression of an export assignment must be an identifier or qualified name in an ambient context.

### ISSUE THREAD

**Issue by DouglasOGarrido** [JiHong88/SunEditor#698]
Hi, I'm using Angular/Typescript with SunEditor and I have this error.

ERROR in node_modules/suneditor/src/plugins/index.d.ts(30,16): error TS2714: The expression of an export assignment must be an identifier or qualified name 
in an ambient context.

I think Typescript changed how export modules, look at that: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts.

I forked this repository and made a simple change to this file `index.d.ts`:
```
import { Plugin } from './Plugin';

// other's imports...

declare const _plugins: Plugin[]; 

export { blockquote, align, font, fontSize, fontColor, hiliteColor, horizontalRule, list, table, formatBlock, lineHeight, template, paragraphStyle, textStyle, link, image, video, audio, math, imageGallery };
export default _plugins;
```

I don't know if this was the best change, but if you or someone else could have a better approach, I appreciate it. Thank you!

**Comment by JiHong88** [comment]
@DouglasOGarrido If it works, please send a PR.
I will reflect it in the next version. :)
