### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by winverse** [JiHong88/SunEditor#70]
방금전에 사용해보려고 했는데 기본 witdth값이 정해져 있지 않나 봅니당
![image](https://user-images.githubusercontent.com/40335396/47849206-236f2980-de14-11e8-9762-1c8acf7cf320.png)
또 공홈에서 width와 height에 대한 설명이 바뀐거 같습니다!
![image](https://user-images.githubusercontent.com/40335396/47849241-397cea00-de14-11e8-8d7a-45ff30b0c1b2.png)

**Comment by JiHong88** [comment]
안녕하세요!

한글로 쓰니까 너무 좋네요ㅎ

기본 width 값은 정해져 있지 않았었습니다.

width, height 각각 '100%', 'auto' 로 수정하여 다음버전에 적용됩니다.

설명도 같이 수정했습니다.

아마 내일쯤 올릴것 같습니다.

감사합니다^^

**Comment by JiHong88** [comment]
[2.7.0 버전](https://github.com/JiHong88/SunEditor/releases/tag/2.7.0) 에서 수정되었습니다.
