### ISSUE TITLE
Autolinking?

### ISSUE THREAD

**Issue by MACscr** [JiHong88/suneditor#703]
It doesn't appear to automatically link typed in or pasted URLs. Also, when highlighting an email address or phone number to try to create tel: or mailto: links, it appears to create relative urls instead. Am i missing something?

**Comment by JiHong88** [comment]
@MACscr "Autolinking" feature will update at the 3.0.0 version.


>Also, when highlighting an email address or phone number to try to create tel: or mailto: links, it appears to create relative urls instead. Am i missing something?

`mailto:links` is working current version.
`tel:` will be added in the next version.

**Comment by MACscr** [comment]
Thanks! I see that tel: is already working in the public demo.

**Comment by MACscr** [comment]
Is 3.0 still being worked on? really want a tinymce alternative, but I need autolinking support with the amount of content that is being written every day.

**Comment by JiHong88** [comment]
I haven't been able to work on it for a while due to various reasons.
It takes several months. sorry.
