### ISSUE TITLE
z-index issues with editor sub menu and toolbar

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#706]
@JiHong88 When I have two editor instances one above the other with the above instance being initialized later, the submenu of the above instance gets hidden by the toolbar of the next one.

Any specific reason?

![image](https://user-images.githubusercontent.com/50414962/114300772-7f5b3380-9adf-11eb-9dd9-e73aa9c40fec.png)

**Comment by JiHong88** [comment]
You must be give the styles `z-index` and `position: relative`. 
Find the generated ID(`suneditor_[textarea ID]`) value and give it a style.

**Comment by JiHong88** [comment]
The [2.38.1](https://github.com/JiHong88/SunEditor/releases/tag/2.38.1) version has been updated.
You can also define "z-index" and "position" it like this: 
```javascript
suneditor.create('id', {
  defaultStyle: "position: relative; z-index:1;"
})
```
Thank you.
