### ISSUE TITLE
KaTeX rendering seems to be broken

### ISSUE THREAD

**Issue by dgandhi1993** [JiHong88/SunEditor#707]
@JiHong88 Please visit the main editor page. The Math formula isn't being rendered correctly.
![image](https://user-images.githubusercontent.com/50414962/114300888-e24cca80-9adf-11eb-804a-871c2ba6a479.png)

**Comment by JiHong88** [comment]
The [2.38.1](https://github.com/JiHong88/SunEditor/releases/tag/2.38.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
