### ISSUE TITLE
Google docs paste text with images

### ISSUE THREAD

**Issue by raulhinojosa** [JiHong88/SunEditor#709]
Hello again, I've noticed a new issue.

I have a document in Google Docs - with many images with different sizes or position. When I'm pasting it into `SunEditor`, some images are not displayed or have a different size or position.

I've searched for similar issues but can't find anything about it.

Link to Google Doc: https://docs.google.com/document/d/1STLTXw8-C_BcQQmxdF6HM4dy0PibKWf-9bsYZJ8zMTw/edit?usp=sharing
Video: https://www.loom.com/share/0553ea7b775348609a2d1b203bc2f079

Best regards,

Raul

**Comment by JiHong88** [comment]
The [2.38.2](https://github.com/JiHong88/SunEditor/releases/tag/2.38.2) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by raulhinojosa** [comment]
> The [2.38.2](https://github.com/JiHong88/SunEditor/releases/tag/2.38.2) version has been updated.
> If this issue has not been resolved, please reopen this issue.
> Thank you.

Hi @JiHong88 the solution works, but when I have many images on the same line, only the first image is copied / displayed in the editor.

Link to Google Doc: https://docs.google.com/document/d/1EfU3ynxeHgDq1QjMuwE-PoAeKt8mkHN2yEsBNqxDx0w/edit?usp=sharing
Video: https://www.loom.com/share/9730488de9514c458ce68407bff225a3

Thank you.

**Comment by JiHong88** [comment]
The [2.38.7](https://github.com/JiHong88/SunEditor/releases/tag/2.38.7) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
