### ISSUE TITLE
Pasting from Excel looses styling (colors)

### ISSUE THREAD

**Issue by matthiasg** [JiHong88/SunEditor#712]
Currently pasting an excel table causes it to loose all styles (especially colors). Is this a possibility in the future or is this considered not desirable ?

**Comment by JiHong88** [comment]
All except the styles controlled by the editor are deleted.
You can use the "attributesWhitelist" option. 
```
attributesWhitelist: {
        all: 'style'
},
```

**Comment by matthiasg** [comment]
Thanks for the feedback
