### ISSUE TITLE
Support addTagsWhitelist with dash (-) in tag name

### ISSUE THREAD

**Issue by johnnyoshika** [JiHong88/SunEditor#716]
`addTagsWhitelist` works well for custom tags when there are no dashes.

Works well:
```
addTagsWhitelist: 'xfoo'
```

However, when there's a dash in the tag name, it's being ignored by the editor.

Does not work:

```
addTagsWhitelist: 'x-foo'
```

`<x-foo>test</x-foo>` becomes `test`.

Can you add support for dashes in tag names?

**Comment by JiHong88** [comment]
Available after the 3.38.3 update. 
I'll notify you.
---
And if you want to use `<x-foo>` as a format line, you need to define it in the "formats" option. 
But currently, other tags cannot be used when verifying tags in the editor.
You need to add a class name. 
```javascript
addTagsWhitelist: 'x-foo',
formats: [
    'p', 'div', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    {
        tag: 'x-foo',
        name: 'x-foo',
        command: 'replace',
        class: '__se__format__replace_x_foo',
    }
],
```
This issue will be improved in version 3.0.0.

**Comment by johnnyoshika** [comment]
Thank you so much for the quick turnaround! 👍

Can you please explain this next comment?

> But currently, other tags cannot be used when verifying tags in the editor.

What do you mean by other tags cannot be used when verifying tags?

Thank you, this is a great editor!

**Comment by JiHong88** [comment]
That means if you use the "formats" option, it means you need the class.

**Comment by JiHong88** [comment]
The [2.38.3](https://github.com/JiHong88/SunEditor/releases/tag/2.38.3) version has been updated.
Thank you.

**Comment by johnnyoshika** [comment]
@JiHong88 Amazing! Thank you so much for the quick fix. Thank you also for explaining the `formats` option.

**Comment by johnnyoshika** [comment]
@JiHong88 I just tried 2.38.3 and it still doesn't work. I'm using `suneditor-react`, but I made sure suneditor 2.38.3 is used. Here's my package-lock.json:

```
    "suneditor": {
      "version": "2.38.3",
      "resolved": "https://registry.npmjs.org/suneditor/-/suneditor-2.38.3.tgz",
      "integrity": "sha512-B9v7GpAcVStTxG/ORe1745dSdhfegNMYD9Q1mj5KoVf7srwGf8kzzKHvGdHp1GQ9lmOtZfR/BihGlbwKCh9Ohg=="
    },
    "suneditor-react": {
      "version": "2.16.2",
      "resolved": "https://registry.npmjs.org/suneditor-react/-/suneditor-react-2.16.2.tgz",
      "integrity": "sha512-U9DwcTEsJGfjtATCS8LXLYhO+ng8awZAyvf7iCvPQ0ywVck7sgFUKDuUuG2FRccOdN6yezZRYWTnjJC9XEvzLw==",
      "requires": {
        "prop-types": "^15.7.2",
        "suneditor": "^2.37.4"
      }
    },
```

SunEditor adds the custom tag with dash in it without any trouble through my custom plugin, but as soon as I reload the browser and load HTML into SunEditor with my custom tag, it strips it out.

Add to SunEditor:

```
<p>hello <x-param data-id="test">world</x-param>​</p>
```

After reload:

```
<p>hello world​</p>
```

Here's my config:

```
          addTagsWhitelist: 'x-param',
          attributesWhitelist: { 'x-param': 'data-id' },
```

Do you know what I'm doing wrong?

**Comment by johnnyoshika** [comment]
I think I found the problem while debugging in dev tools. This is so bizarre, but it looks like I'm still running version 2.38.1, as `convertContentsForEditor` is showing the old code from 2.38.1:

![image](https://user-images.githubusercontent.com/504505/115131371-8802ac80-9fac-11eb-9d04-11392ffbe325.png)

I'll have to look into it. Thanks again for your help.

**Comment by johnnyoshika** [comment]
It turns out that it's a problem with `suneditor-react`. Even though package-lock.json is referencing suneditor 2.83.3, suneditor-react is pre-packaging suneditor and loading an older version.

From my `node_modules` folder:

![image](https://user-images.githubusercontent.com/504505/115131590-027ffc00-9fae-11eb-8d04-51a9ee8258eb.png)
