### ISSUE TITLE
Override endOffset?

### ISSUE THREAD

**Issue by johnnyoshika** [JiHong88/SunEditor#719]
I'm using something similar to your custom `customLink` dialog plugin from here: http://suneditor.com/sample/html/customPlugins.html#dialog

I've got an interesting problem. When Windows uses double click a word, they select the word + any spaces after it. So for example, if the text is this:

```
foo bar test
```

...and a Windows user double clicks `bar`, s/he will select `bar ` (including the space after 'bar'). Uusing the customLink plugin, the results will be (with the space after `bar` in the wrong place):

```
foo <a href="something">bar </a>test
```

What I would like to do is trim the selection so that the result will be:

```
foo <a href="something">bar</a> test
```

However, if I trim the selection inside my plugin, the result is actually:

```
foo <a href="something">bar</a>test
```

In order to achieve what I want, I would need access to customize `endOff` here: https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L1580

Is there any way I can customize that value?

**Comment by JiHong88** [comment]
I don't know which browser you tested, but it's probably different from browser to browser.

http://suneditor.com/sample/html/out/document-editor.html#getRange
http://suneditor.com/sample/html/out/document-editor.html#setRange
```javascript
const range = editor.core.getRange();

const sc = range.startContainer;
const ec = range.endContainer;
const so = range.startOffset;
const eo = range.endOffset;
const cc = range.commonAncestorContainer;

// Reset "range" after checking text and offset.
// This is a simple example. 
editor.core.setRange(sc, so, ec, eo - 1);
```

**Comment by johnnyoshika** [comment]
Thank you @JiHong88, but I'm having trouble getting this to work. This is from your sample `customLink` plugin:

```
            if (!this.context.dialog.updateModal) {
                const oA = this.util.createElement('A');
                oA.href = url;
                oA.textContent = anchorText;
                oA.target = contextLink.targetSelect.selectedOptions[0].value;

                const selectedFormats = this.getSelectedElements();
                if (selectedFormats.length > 1) {
                    const oFormat = this.util.createElement(selectedFormats[0].nodeName);
                    oFormat.appendChild(oA);
                    this.insertNode(oFormat);
                } else {
                    this.insertNode(oA);
                }

                this.setRange(oA.childNodes[0], 0, oA.childNodes[0], oA.textContent.length);
            }
```

Even if I reduce the length here: `this.setRange(oA.childNodes[0], 0, oA.childNodes[0], oA.textContent.length);`, it seems like it's too late, as `this.insertNode(oA);` above calls this code: https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L1580

```
const endOff = range.endOffset;
```

Which seems to set the range. Can you suggest how I can fix this?

**Comment by JiHong88** [comment]
You must use the "setRange" method after "insertNode". 
```javascript
this.insertNode(oA);
this.setRange(oA.childNodes[0], oA.textContent.length, oA.childNodes[0], oA.textContent.length)
```

**Comment by johnnyoshika** [comment]
@JiHong88 `setRange` is being called after `insertNode`, as I'm testing with the demo code you provide in your example.

```
            if (!this.context.dialog.updateModal) {
                const oA = this.util.createElement('A');
                oA.href = url;
                oA.textContent = anchorText;
                oA.target = contextLink.targetSelect.selectedOptions[0].value;

                const selectedFormats = this.getSelectedElements();
                if (selectedFormats.length > 1) {
                    const oFormat = this.util.createElement(selectedFormats[0].nodeName);
                    oFormat.appendChild(oA);
                    this.insertNode(oFormat);
                } else {
                    this.insertNode(oA);
                }

                this.setRange(oA.childNodes[0], 0, oA.childNodes[0], oA.textContent.length);
            }
```

Here's a video of what I'm experiencing. Even if I reduce the length of the 4th parameter to `setRange`, it doesn't seem to change the selection range: https://recordit.co/7WuSw0jdCG

Here's the codesanbox that I used for the demo: https://codesandbox.io/s/suneditor-custom-dialog-xx7he

**Comment by JiHong88** [comment]
@johnnyoshika  There is the same code in the `else` section.
If the text is preselected, the `else` clause is executed.
Please correct that division as well.

**Comment by johnnyoshika** [comment]
@JiHong88 Do you mean the `else` that gets executed when modifying the custom link? I tested it and it doesn't execute when creating a new link. Here's the recording: http://recordit.co/it9R8qji4V

Code: https://codesandbox.io/s/suneditor-custom-dialog-xx7he?file=/src/customLink.js

**Comment by JiHong88** [comment]
Try it `this.setRange(oA.childNodes[0], 0, oA.childNodes[0], oA.textContent.length - 2);`
Spaces are also included in "textContent".

if you want "setRange" at the before create `<a>` tag.
Run this code before running `this.insertNode(oFormat);`

```javascript
const range = this.getRange()
const ls = range.startContainer.textContent.substr(range.startOffset).match(/^\s+/);
const rs = range.endContainer.textContent.substr(0, range.endOffset).match(/\s+$/).match(/^\s+/);
this.setRange(
  range.startContainer, 
  ls ? range.startOffset + ls[0].length : range.startOffset,
  range.endContainer,
  ls ? range.endOffset - rs[0].length : range.endOffset
)
```

**Comment by johnnyoshika** [comment]
@JiHong88 That worked perfectly, thank you!

Here's the final result: https://codesandbox.io/s/suneditor-custom-dialog-xx7he?file=/src/customLink.js:7023-7532
