### ISSUE TITLE
Override editor bg-color

### ISSUE THREAD

**Issue by AntoRin** [JiHong88/SunEditor#724]
I have been trying to find a way to change the default white background of the editor. I am aware of the fact that including the SunEditor css file will give me some default classes that I can override, but is there any way to configure specific instances of the editor by using custom stylesheets?

**Comment by gopal1996** [comment]
@AntoRin you can use **defaultStyle** option

```
{
	"mode": "classic",
	"defaultStyle": "background: red",
	"imageGalleryUrl": "https://etyswjpn79.execute-api.ap-northeast-1.amazonaws.com/suneditor-demo",
}
```

**Comment by AntoRin** [comment]
Appreciate the help!
