### ISSUE TITLE
core.functions.insertHTML() is not inserting content at current position

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#725]
Hello,

**core.functions.insertHTML()** is not inserting content at current position. It's creating a new line and then inserting the content.

**core.functions.insertHTML()** was working fine in 2.38.2 version

**Comment by gopal1996** [comment]
@JiHong88 can you please help me with this?

**Comment by JiHong88** [comment]
@gopal1996 Please show me the content when useing `core.functions.insertHTML()`

**Comment by gopal1996** [comment]
Once the user hits enter, it should insert content to the suneditor.

```javascript
useEffect(() => {
        editor.current.onKeyDown = (event, core) => {

            if(event.keyCode === 40 ) {
                if(isSuggestionOpen) {
                    console.log("Run")
                    event.preventDefault()
                    setCurrentIndex(prev => prev === suggestionList.length - 1 ? 0 : prev + 1)
                    currentRef.current = currentRef.current + 1

                }
            } else if(event.keyCode === 38) {
                if(isSuggestionOpen) {
                    event.preventDefault()
                    setCurrentIndex(prev => prev === 0 ? suggestionList.length - 1 : prev - 1)
                    currentRef.current = currentRef.current - 1

                }
            } else if(event.keyCode === 13) {
                if(isSuggestionOpen) {

                    event.preventDefault();
                    setSuggestion(false)
                    core.functions.insertHTML(suggestionList[currentRef.current])
                }
            }
        }
    }, [currentIndex, isSuggestionOpen])
```

**Comment by JiHong88** [comment]
"suggestionList[currentRef.current]" is string type?
Does the work normally if I run it after selecting the range?

**Comment by gopal1996** [comment]
1 - yes, it is a string type.
2 - am not sure about the range. I am just using insertHTML.

**Comment by JiHong88** [comment]
Line breaks working on whether it is in line format. 
`insertHTML('<div>test</div>')` it is create new  line.
`insertHTML('test')` it is not create new  line.

**Comment by gopal1996** [comment]
@JiHong88  both creating a new line

**Comment by JiHong88** [comment]
This issue is not reproduced.
When inserting text, get me know the text to be inserted and the  HTML of the editor area and the information of the "range" object. 

Other issues:
And a bug that creates a new line when inserted in the middle of the string has been confirmed. 
It will fix the next version.

**Comment by JiHong88** [comment]
The [2.38.4](https://github.com/JiHong88/SunEditor/releases/tag/2.38.4) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by gopal1996** [comment]
Hi @JiHong88 ,

Sorry for the late response.
The issue is not resolved. but I think I found the root cause.
I am binding the keyboard event, when the user hit **Enter**, it should block that event

```javascript
useEffect(() => {
    editor.current.onKeyDown = (event, core) => {
      console.log(event.keyCode);
      if (event.keyCode === 40) {
        if (isSuggestionOpen) {
          console.log("Run");
          event.preventDefault();
          setCurrentIndex((prev) =>
            prev === suggestionList.length - 1 ? 0 : prev + 1
          );
          currentRef.current = currentRef.current + 1;
        }
      } else if (event.keyCode === 38) {
        if (isSuggestionOpen) {
          event.preventDefault();
          setCurrentIndex((prev) =>
            prev === 0 ? suggestionList.length - 1 : prev - 1
          );
          currentRef.current = currentRef.current - 1;
        }
      } else if (event.keyCode === 13) {
        // if (isSuggestionOpen) {
        console.log("Enter");
        event.preventDefault();

        //   setSuggestion(false);
        //   core.functions.insertHTML("<span>test</span>");
        // }
      }
    };
  }, [currentIndex, isSuggestionOpen, suggestionList.length]);
```

If you see the above code, I am preventing the **Enter** key event `if (event.keyCode === 13) { event.preventDefault(); }`
but in the editor, in the middle of the string, if I hit **Enter**, its not preventing the event. It inserting a new Line.

I have created a sample sandbox for your reference. please find the link below
[https://codesandbox.io/s/suneditor-8exq4?file=/src/App.js:2266-3282](https://codesandbox.io/s/suneditor-8exq4?file=/src/App.js:2266-3282)

Video demo:
[https://www.loom.com/share/aa435bcc507442dcaabf338a90dbe223](https://www.loom.com/share/aa435bcc507442dcaabf338a90dbe223)

I think **event.preventDefault** is not working in the middle of the string.
can you please help me with this.

Thank you
