### ISSUE TITLE
Typescript build fails

### ISSUE THREAD

**Issue by SkeDoodle** [JiHong88/SunEditor#727]
Hi!

We're using the SunEditor with the suneditor-react, typescript v3.8 and node version v14.5.0

Everything works fine, except the build.

We get an error in node_modules\suneditor\src\plugins\index.d.ts

```bash
node_modules/suneditor/src/plugins/index.d.ts:29:27 - error TS7008: Member 'blockquote' implicitly has an 'any' type.

29 declare const _default: { blockquote, align, font, fontSize, fontColor, hiliteColor, horizontalRule, list, table, formatBlock, lineHeight, template, paragraphStyle, textStyle, link, image, video, audio, math, imageGallery };
                             ~~~~~~~~~~
```

If we import each plugin types separately, we can fix the build:

```javascript
declare const _default: { blockquote: CommandPlugin, align: SubmenuPlugin, font: SubmenuPlugin, ... };
```

![image](https://user-images.githubusercontent.com/9872645/116058187-dd5f4d80-a67f-11eb-83dd-db10b55d04ff.png)

**Comment by SkeDoodle** [comment]
Wow that was fast! Thank you very much @JiHong88 :)

**Comment by JiHong88** [comment]
The [2.38.4](https://github.com/JiHong88/SunEditor/releases/tag/2.38.4) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
