### ISSUE TITLE
Font colour bug

### ISSUE THREAD

**Issue by ScottWager** [JiHong88/SunEditor#729]
If the default text colour is overwritten using the `.sun-editor-editable` class, the colour picker still uses the colour `#333333` instead of the actual colour.

In the video below I used red to help show the problem, using a css class of ‘.sun-editor-editable { color: red!important }’. In my app I use a different shade of black and then a white for dark mode.

Potential solution: Use `getComputedStyle` on the selected text to get it’s colour. https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

https://user-images.githubusercontent.com/51394257/116184484-bf452c00-a717-11eb-9f2d-daaa73230678.mov

**Comment by JiHong88** [comment]
The [2.38.4](https://github.com/JiHong88/SunEditor/releases/tag/2.38.4) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
