### ISSUE TITLE
Text color and background reset button issue

### ISSUE THREAD

**Issue by alichampion** [JiHong88/SunEditor#732]
**In this video you can see the as soon as i write text and apply color and background color it works fine and i can reset the color and background color however if i apply font size after applying color and background color, now it does not let me reset the color and background color.**

https://user-images.githubusercontent.com/38204661/116360811-bc326480-a819-11eb-8f16-ba0aec3d92a8.mov

**Comment by JiHong88** [comment]
The [2.38.5](https://github.com/JiHong88/SunEditor/releases/tag/2.38.5) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by alichampion** [comment]
Thanks, @JiHong88 it's fixed now.
