### ISSUE TITLE
Attirbutes getting removed automatically

### ISSUE THREAD

**Issue by pinal-r** [JiHong88/SunEditor#735]
I assigned html which has table 

<table style="border-style:double;border-width: 8px;border-color: black;font-family: Verdana, Arial, Helvetica, sans-serif;color:#000;" width="100%">

when I assign this to suneditor it automatically removed width due to this I am facing the issue.

**Comment by JiHong88** [comment]
@pinal-r Try it.

```javascript
attributesWhitelist" {
  all: 'style', // or table: 'style'
}
```
