### ISSUE TITLE
event.preventDefault() of KeyDown is not working

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#736]
Hi @JiHong88 ,

This issue is a continuation of #725 
I am binding the keyboard event, when the user hit **Enter**, it should block that event

```javascript
useEffect(() => {
    editor.current.onKeyDown = (event, core) => {
      console.log(event.keyCode);
      if (event.keyCode === 40) {
        if (isSuggestionOpen) {
          console.log("Run");
          event.preventDefault();
          setCurrentIndex((prev) =>
            prev === suggestionList.length - 1 ? 0 : prev + 1
          );
          currentRef.current = currentRef.current + 1;
        }
      } else if (event.keyCode === 38) {
        if (isSuggestionOpen) {
          event.preventDefault();
          setCurrentIndex((prev) =>
            prev === 0 ? suggestionList.length - 1 : prev - 1
          );
          currentRef.current = currentRef.current - 1;
        }
      } else if (event.keyCode === 13) {
        // if (isSuggestionOpen) {
        console.log("Enter");
        event.preventDefault();

        //   setSuggestion(false);
        //   core.functions.insertHTML("<span>test</span>");
        // }
      }
    };
  }, [currentIndex, isSuggestionOpen, suggestionList.length]);
```

If you see the above code, I am preventing the **Enter** key event `if (event.keyCode === 13) { event.preventDefault(); }`
but in the editor, in the middle of the string, if I hit **Enter**, its not preventing the event. It inserting a new Line.

I have created a sample sandbox for your reference. please find the link below
[https://codesandbox.io/s/suneditor-8exq4?file=/src/App.js:2266-3282](https://codesandbox.io/s/suneditor-8exq4?file=/src/App.js:2266-3282)

Video demo:
[https://www.loom.com/share/aa435bcc507442dcaabf338a90dbe223](https://www.loom.com/share/aa435bcc507442dcaabf338a90dbe223)

I think **event.preventDefault** is not working in the middle of the string.
can you please help me with this?

Thank you

**Comment by andylwelch** [comment]
I too am experiencing this issue. Thanks

**Comment by JiHong88** [comment]
@gopal1996 @andylwelch 
The [2.38.6](https://github.com/JiHong88/SunEditor/releases/tag/2.38.6) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by andylwelch** [comment]
Thanks @JiHong88 
Unfortunately the issue still occurs with 2.38.6

```
editor.onKeyDown = (e) => {
   const { key, shiftKey } = e;
   const keyCode = e.which || e.keyCode;
   if (key === 'Enter' || keyCode === 13) {
     console.log('preventing');
     e.preventDefault();
     return false;
   }
})
```

Typing 456 then enter produces the following output. I see the log "preventing" in the console.

![image](https://user-images.githubusercontent.com/7505965/117077871-34e67300-ad7c-11eb-80cb-db7dba8859c7.png)

/open

**Comment by JiHong88** [comment]
The [2.38.7](https://github.com/JiHong88/SunEditor/releases/tag/2.38.7) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by andylwelch** [comment]
Fantastic. Confirmed working. Thank you @JiHong88 !

**Comment by andylwelch** [comment]
Turns out I can no longer paste text with new line characters. Not sure if related to this?

**Comment by JiHong88** [comment]
```
editor.onKeyDown = (e) => {
   const { key, shiftKey } = e;
   const keyCode = e.which || e.keyCode;
   if (key === 'Enter' || keyCode === 13) {
     console.log('preventing');
     e.preventDefault();
     return false;
   }
})
```
This code is always called `e.preventDefault` and `return false`.
Add appropriate conditions.
