### ISSUE TITLE
Regarding Popover icon change

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#738]
Hi @JiHong88 

is it possible to change the below icons?

<img width="190" alt="Screenshot 2021-05-03 at 1 12 06 PM" src="https://user-images.githubusercontent.com/22369081/116852122-64c53780-ac11-11eb-9746-fe6f532e49da.png">

Thanks.

**Comment by JiHong88** [comment]
@gopal1996 You can use the icons option.
```
icons: {
  bold: '<span class="se-icon-text">B</span>',
  table: '<i class="xx xxx></i>',
  insert_row_above: '<svg></svg>'
}
```
https://github.com/JiHong88/SunEditor/blob/master/src/assets/defaultIcons.js
