### ISSUE TITLE
Pasting content containing new lines removes the new lines

### ISSUE THREAD

**Issue by andylwelch** [JiHong88/SunEditor#743]
I can no longer paste content over several lines. For example pasting the following text

```
line1
line2
line3
```

Appears as:

![image](https://user-images.githubusercontent.com/7505965/117249244-9b56b880-ae84-11eb-9ae6-dd586d09c220.png)

**Comment by JiHong88** [comment]
The [2.38.8](https://github.com/JiHong88/SunEditor/releases/tag/2.38.8) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by andylwelch** [comment]
Hello, unfortunately the issue still exists. Now the new lines are shown as <br> tags

![image](https://user-images.githubusercontent.com/7505965/117375593-abb57480-af12-11eb-8367-be7a49f9e975.png)

/open

**Comment by JiHong88** [comment]
@andylwelch This issue is not reproduced.
Please tell me more detail.

**Comment by andylwelch** [comment]
I have tested latest version, this issue still exists. I can even reproduce it on your demo site http://suneditor.com/sample/index.html

Copy the lines, then paste appears like this. I can reproduce on 2 different computers, in both Firefox and Chrome:

![image](https://user-images.githubusercontent.com/7505965/117911677-8add8c80-b321-11eb-8f32-9a4cfee9c0a2.png)

**Comment by andylwelch** [comment]
Are you on a Mac? My colleague just tested in Chrome for Mac and it produces a different result. Line endings work fine, but leading whitespace is not preserved.

Here is how the source appears when pasted on your sample website:

![image](https://user-images.githubusercontent.com/7505965/117912081-2f5fce80-b322-11eb-96ca-5ee79bf11129.png)

**Comment by JiHong88** [comment]
>I have tested latest version, this issue still exists. I can even reproduce it on your demo site http://suneditor.com/sample/index.html
Copy the lines, then paste appears like this. I can reproduce on 2 different computers, in both Firefox (linux) and Chrome (windows):

Where was the text copied from?
I tested it on windows, but it still doesn't reproduced.

**Comment by andylwelch** [comment]
The issue occurs when copying simple multi-line text from Notepad and Notepad++.

I just tested from VSCode and Word (on Windows) and it works fine from there. I guess they have a different format of text with colours etc.

**Comment by JiHong88** [comment]
The [2.39.0](https://github.com/JiHong88/SunEditor/releases/tag/2.39.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
