### ISSUE TITLE
Placeholder does not scale with fontSize

### ISSUE THREAD

**Issue by sm3sher** [JiHong88/SunEditor#744]
When I modify the editors font-size by setting the `defaultStyle` option, the placeholder does not scale.
It keeps its default `font-size` and I can't find a way to set the placeholders `font-size`.

If I set the font-size to `24px` the placeholder looks like this:

<img width="274" alt="Bildschirmfoto 2021-05-06 um 09 00 14" src="https://user-images.githubusercontent.com/39101755/117314604-3a7caf80-ae87-11eb-912b-5627d6b92eb1.png">

Which is way to big compared to the cursor and the `font-size` the editor is using:

<img width="274" alt="Bildschirmfoto 2021-05-06 um 09 00 40" src="https://user-images.githubusercontent.com/39101755/117314630-3f416380-ae87-11eb-927e-d81b717196cf.png">

Is there any way to modify the placeholder?

**Comment by JiHong88** [comment]
@sm3sher This feature is many use a resource.
I think there is no efficiency compared to the resources used.

**Comment by sm3sher** [comment]
Thank you very much
