### ISSUE TITLE
Issue with Bold, Italic, Underline text

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/suneditor#747]
Hi @JiHong88 ,

Copy Bold or Italic or Underline Text from google docs and paste into suneditor, then select the pasted text and apply bold, italic, or underline in suneditor. It does not change.

Please find the reference video.

[https://www.loom.com/share/68254bf7389942c18664b98aa9fbafae](https://www.loom.com/share/68254bf7389942c18664b98aa9fbafae)

Can you please help me with this?

Thanks

**Comment by JiHong88** [comment]
When pasting, the "style" attribute is removed by default, but the style of the "span" tag is preserved.
When pasting, you need to remove styles such as "font-weight" and replace them with "strong" tags, but this is different for different editors.
EX) https://froala.com/wysiwyg-editor/ , https://ckeditor.com/ckeditor-5/demo/#document
There is a compatibility problem with the existing function, so we will implement it in version 3.0.0.
