### ISSUE TITLE
Font Size, Font Family button default text 

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#748]
Hi @JiHong88 ,

Thank you for the amazing editor. Finally, Suneditor is going production in our application.

Our UI/UX team raised a concern, is it possible to give default font size, font family on the toolbar button?

Instead of showing font, size text. I am trying to display the default font value. eg: 14px, Arial
![Group 4](https://user-images.githubusercontent.com/22369081/117695593-059d8f00-b1de-11eb-922d-08c3e94cc33c.png)

The reason behind this is, people will know the default font size, font when they start writing.

Reference:
<img width="441" alt="Screenshot 2021-05-10 at 10 16 37 PM" src="https://user-images.githubusercontent.com/22369081/117695893-57deb000-b1de-11eb-88a4-220085c39daf.png">
<img width="802" alt="Screenshot 2021-05-10 at 10 16 21 PM" src="https://user-images.githubusercontent.com/22369081/117695904-5b723700-b1de-11eb-974c-bad5adfd2f5f.png">

Is there any way to do that? Please let me know.

Thank you very much :)

**Comment by JiHong88** [comment]
The [2.38.10](https://github.com/JiHong88/SunEditor/releases/tag/2.38.10) version has been updated.
Thank you.

**Comment by s-kris** [comment]
can you add the default value to 'Formats' as well?
Thank you.

**Comment by JiHong88** [comment]
@s-kris It does not a default value, it is the current value.
It's already applied to "Formats".

**Comment by s-kris** [comment]
Ohh but in the new version, 'Formats' is shown by default instead of "Normal".

**Comment by JiHong88** [comment]
@s-kris When there is no focus, the current format is not displayed.

**Comment by s-kris** [comment]
Thanks, @JiHong88, I wanted to confirm that.

**Comment by s-kris** [comment]
@JiHong88 I updated to the latest version of suneditor and suneditor-react in my nextjs app (imported as ssr:false). 
The 'Formats' won't update the current type at all. 

https://user-images.githubusercontent.com/3975305/119772646-26076200-bedd-11eb-8bfa-cab481507006.mov

**Comment by s-kris** [comment]
I'm using three event functions:`onChange` `onKeyDown` `onImageUploadBefore`

**Comment by JiHong88** [comment]
@s-kris Are you using "e.preventDefault" in your event?

**Comment by s-kris** [comment]
I'm using this in this way.
```
 onKeyDown={(event) => {
                if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
                    event.preventDefault();
                    const linkButton = document.querySelector(
                        'button[data-command=link]',
                    ) as HTMLElement | null;
                    if (linkButton) {
                        linkButton.click();
                    }
                }
            }}
```

However, even if I remove this event completely the bug persists.

**Comment by JiHong88** [comment]
@s-kris Please show me all options you have used.

**Comment by s-kris** [comment]
Sure @JiHong88 
```
import dynamic from 'next/dynamic';
const SunEditor = dynamic(() => import('suneditor-react'), {
    ssr: false,
});

type EditorProps = {
    readonly: boolean;
    postContent: string;
};

function CustomEditor(props: EditorProps): React.ReactElement {
    const handleEditorChange = (content: string) => {
        editorStore.setPostContent(content);
    };
    return (
        <SunEditor
            setDefaultStyle=""
            placeholder="Word your thoughts here..."
            setOptions={{
                minHeight: '500px',
                height: 'auto',
                plugins: [plugin_separator, plugin_summary],
                buttonList: [
                    ['formatBlock', 'bold', 'italic', 'underline', 'list'],
                    ['link', 'image', 'video'],
                    ['align', 'custom_seperator', 'summary'],
                    ['undo', 'redo'],
                ],
                imageAccept: '.jpg, .jpeg, .png, .gif',
                imageUrlInput: false,
                showPathLabel: false,
                mediaAutoSelect: false,
                formats: [
                    {
                        tag: 'p',
                        name: 'Normal',
                        command: 'replace',
                        class: '',
                    },
                    {
                        tag: 'h2',
                        name: 'Heading',
                        command: 'replace',
                        class: '',
                    },
                    {
                        tag: 'h3',
                        name: 'Subheading',
                        command: 'replace',
                        class: '',
                    },
                    'blockquote',
                    'pre',
                ],
                linkRel: ['nofollow'],
                attributesWhitelist: {
                    img: 'alt',
                    p: 'text-align',
                    h2: 'id',
                    h3: 'id',
                },
                pasteTagsBlacklist: 'span', //TODO: modify this in suneditor-3.0.0 https://github.com/JiHong88/SunEditor/issues/661#issuecomment-799513902
            }}
            onChange={handleEditorChange}
            disable={props.readonly}
            setContents={props.postContent}
            onImageUploadBefore={(files, info, uploadHandler) => {
             //upload image to server
            }}
           onKeyDown={(event) => {
                if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
                    event.preventDefault();
                    const linkButton = document.querySelector(
                        'button[data-command=link]',
                    ) as HTMLElement | null;
                    if (linkButton) {
                        linkButton.click();
                    }
                }
            }}
        />
    );
}
```

**Comment by JiHong88** [comment]
@s-kris This issue is not reproduced.
Can you show me the contents of the editor in code view mode? 
And

**Comment by s-kris** [comment]
Sure, here it is
![Screenshot 2021-05-27 at 4 35 49 PM](https://user-images.githubusercontent.com/3975305/119815847-9fb54500-bf09-11eb-8cbc-d77693471d3c.png)

**Comment by JiHong88** [comment]
@s-kris This issue is still not reproduced.
Also other buttons like "fontsize", "bold" etc are not showing active?
Please check if an error occurs in the console.

If all is ok, please check if it is the same when using "SunEditor" package rather than "suneditor-react".

**Comment by s-kris** [comment]
@JiHong88 All other buttons are working fine. I'll try to create a minimal reproduction repo.
Apologies for the delay.
