### ISSUE TITLE
Resize event

### ISSUE THREAD

**Issue by johnnyoshika** [JiHong88/SunEditor#753]
Is there  a way to get a resize event when the user resizes the editor using the resizingBar? Ideally it would contain the editor height, as I'd like to persist the height of the editor for the user and reinitialize the editor with the previously saved height.

**Comment by johnnyoshika** [comment]
@JiHong88 Fantastic, thank you!

**Comment by JiHong88** [comment]
The [2.39.0](https://github.com/JiHong88/SunEditor/releases/tag/2.39.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by johnnyoshika** [comment]
Many thanks!
