### ISSUE TITLE
TS2304: Cannot find name 'TimerHandler'

### ISSUE THREAD

**Issue by IngressoDev** [JiHong88/SunEditor#754]
First of all, your editor is great.

Now to my problem.
I want to create a little wrapper to use your editor with react.
But now when i try to transpile my project i get the following errors:

```
node_modules/suneditor/src/lib/util.d.ts(440,44): error TS2304: Cannot find name 'TimerHandler'.
node_modules/suneditor/src/lib/util.d.ts(453,43): error TS2304: Cannot find name 'TimerHandler'.
node_modules/suneditor/src/lib/util.d.ts(597,52): error TS2304: Cannot find name 'TimerHandler'.
```

I'm using:
- React 15.4.2 (i know old shit but for my projekt i need to use this version)
- TypeScript 2.4.2
- NodeJS 8.17.0

Is TimerHandler something global or only is this type definition missing?

**Comment by IngressoDev** [comment]
I added "skipLibCheck: true" to my tsconfig.json file.

**Comment by JiHong88** [comment]
The [2.39.0](https://github.com/JiHong88/SunEditor/releases/tag/2.39.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
