### ISSUE TITLE
editor disabled or enabled functions not reactive

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#757]
Hi @JiHong88 
The editor doesn't react to the disabled or enabled function after it is initially setup.
Example if the editor was enabled initially and you disable it by calling editor.disabled() it will not work and vice versa. This is unlike hide,  show, toolbar.disabled and toolbar.enabled()

**Comment by mkhstar** [comment]
I have realized that the editor itself works but the toolbar is not disabled

**Comment by JiHong88** [comment]
Hi @mkhstar 
This issue is not reproduced. [(example)](http://suneditor.com/sample/html/examples.html#functions)
Please tell me more detail like envirement, browser, etc.

**Comment by mkhstar** [comment]
Sorry @JiHong88,
I had a bug in my code
