### ISSUE TITLE
When call setContents() with null or '' argument, text input looses focus.

### ISSUE THREAD

**Issue by TrueYork** [JiHong88/SunEditor#758]
Hello,
To clear text input completely I'm using editorInstance.setContents(null). (the same happens when use editorInstance.setContents(null))
After that, placeholder appears and text area looks in focus, but I'm unable to type anything, as far there is no caret.
As a W/A I'm using editorInstance.core.focus() after setContents call.
Please, clarify, is it nominal behavior for setContents to loose the focus after input empty value?

**Comment by JiHong88** [comment]
Yes, `setContents()` replaces all content, so it also deletes the old "selection" object.
So the existing caret position cannot be used.
It is correct to use the `focus()` method.

**Comment by TrueYork** [comment]
Thanks a lot for a quick response!
