### ISSUE TITLE
way to add custom shortcuts

### ISSUE THREAD

**Issue by s-kris** [JiHong88/SunEditor#760]
Transforming the text with plugins is possible now.
Is it possible to invoke the editor functions? For example how to add `cmd + k ` to trigger the 'Insert Link' modal?

Thank you!

**Comment by JiHong88** [comment]
@s-kris Please refer to this https://github.com/JiHong88/SunEditor/issues/736#issuecomment-833546563

**Comment by s-kris** [comment]
Thank @JiHong88, I was asking how to invoke the editor's functions. For example to invoke the 'Insert Link' modal.
I checked in the documentation, found the method `callPlugin`. But using that to trigger 'link' plugin didn't trigger the modal.

So, I just used native js to click the 'link' button. Now it is triggered.
