### ISSUE TITLE
Valid attributes are being sanitized

### ISSUE THREAD

**Issue by coolicz** [JiHong88/SunEditor#761]
Table cell's (**td**) attribute **width** is being sanitized when initializing Suneditor (also when using **editor.setContent**).
Is there a way to change the sanitation rules? editor.setContent can receive only one attribute (html string).
E.g. `<td width="20%">cell</td>` becomes `<td>cell</td>`

**Comment by JiHong88** [comment]
@coolicz You can use the `attributesWhitelist` option.

```javascript
attributesWhitelist: {
 td: 'width'
}
```

**Comment by coolicz** [comment]
I haven't noticed that. Thank you!
