### ISSUE TITLE
TS2749: 'core' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by bliny** [JiHong88/SunEditor#763]
Hello,

I've just started to use SunEditor and I found this error in the latest build, 2.38.10 works fine.

```
ERROR in node_modules/suneditor/src/lib/core.d.ts:877:64 - error TS2749: 'core' refers to a value, but is being used as a type here.

877     onResizeEditor: (height: number, prevHeight: number, core: core) => {};
```

Thanks

**Comment by JiHong88** [comment]
The [2.40.0](https://github.com/JiHong88/SunEditor/releases/tag/2.40.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
