### ISSUE TITLE
Toolbar and Inline option

### ISSUE THREAD

**Issue by juliodee** [JiHong88/SunEditor#766]
I'm having an app developed where I'd like be able to write rich text in an expanding container. I like SunEditor Inline option because toolbar sits on the relevant container (I'll be having multiple containers on the screen), out of the way but easily accessible.

However, I notice that in an expanding container that grows greater than the screen height, the SunEditor toolbar eventually disappears. Here's a video of what I mean: [https://www.loom.com/share/985730cf6d0546eda642d2ae33391165](url)

Is it possible for the SunEditor to be sticky at the top of the screen when it gets to the top? 

ps. GREAT editor! Thank you for a wonderful editor and under MIT license. All goes ahead with my app, donation without doubt.

**Comment by JiHong88** [comment]
The [2.40.0](https://github.com/JiHong88/SunEditor/releases/tag/2.40.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
