### ISSUE TITLE
Issue with list and bold menu option

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#771]
**Describe the bug**
In Bullet mode, if you start to type something with bold mode and then toggle the bold menu, and type again. Bolded text is not changed to normal text 

**To Reproduce**
1. remove the content in the editor
2. click bullet
3. click bold or **cmd + B**
4. type something
5. again click bold or **cmd + B**
6. type something
7. bold text is not changing in list type

**Expected behavior**
the bolded text should change to normal text

**Screenshots**
[https://www.loom.com/share/692e2d06438b4675ab17fb6047017733](https://www.loom.com/share/692e2d06438b4675ab17fb6047017733)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version 91

**Additional context**

**Comment by JiHong88** [comment]
The [2.40.0](https://github.com/JiHong88/SunEditor/releases/tag/2.40.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
