### ISSUE TITLE
Bold, italic, and Underline does not replace custom format (heading)

### ISSUE THREAD

**Issue by ghilaslinz** [JiHong88/SunEditor#779]
Hi @JiHong88 

I have a little question, when i change the format of a paragraph to a heading that's work perfectly, but when i select the heading text and click on underline for example, it does not replace the heading text but add an underline to this heading text.
My goal is not to add an underline to the heading, but just replace it.

This issue explains almost the same thing #190, but i was not able to apply the solution in my case.

Is there a solution that can help me, please

Best regards

**Comment by JiHong88** [comment]
Hi @ghilaslinz 
>My goal is not to add an underline to the heading, but just replace it.
What does it mean exactly? What does it mean exactly? 
"underline" button is added the "em" tag to the selection text.

**Comment by ghilaslinz** [comment]
Hi @JiHong88,
Thanks for your answer.
I mean when the selected text is a heading and we click in the button underline, the result that i want is :
 delete the heading style (so transform it into a paragraph), and after that apply the underline style

I don't want to apply the underline style to the heading text, so if the user want to apply underline the heading text, this last will lost his heading style and will be replaced with underline style.

Do you understand what i mean ?

**Comment by JiHong88** [comment]
Yes I understand what you mean.
But It is normal behavior for bold, italic and underlined not to replace formatting.
After adding the underscore, you need to change the format to "paragraph".

You must be create custom plugins.
There are currently no direct methods related to formatting.
Please refer to the following code. 
https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/formatBlock.js#L159

**Comment by ghilaslinz** [comment]
@JiHong88,
Thanks for you answer, i will start to work on this custom plugin
