### ISSUE TITLE
HTML source is incorrectly converted between HTML source and WYSIWYG mode when using tags defined using addTagsWhitelist

### ISSUE THREAD

**Issue by anthomus** [JiHong88/SunEditor#781]
**Describe the bug**
I have configured SunEditor to honor extra HTML5 tags using addTagsWhitelist.  When using source code mode to paste in properly formatted HTML5, the HTML is incorrectly restructured when returning to the WYSIWYG mode.

**To Reproduce**
1. Configure suneditor using:
```
        addTagsWhitelist: 'details|summary',
        attributesWhitelist: {'details': 'open'},  // html5 <details open="">..</details>
```

2. Click on '</>' source mode

3. Paste in the following HTML (also provided in attached .txt file)
```
<div>These gorgeous boots are made from high-quality leather and have a shimmering metallic finish to add extra sparkle in your life! With them you will take a stroll on the wild side and see what fashion looks like!</div>
<br>
<details open=""><summary><span class="headline">FEATURES</span><span class="sub-headline"> Learn more about the features</span></summary>
<div class="indent-content">
<div>High Quality and Vegetable Tanned Leather Upper</div>
<div>Decorative Black Beads on the Upper</div>
<div>Smooth Synthetic Rubber Bottom</div>
<div>1.5" inch Heel with Fashion Metal Studs</div>
<div>Genuine Leather Lining on the Interior</div>
<div>Soft Leather Footbed</div>
<div>Made in Italy</div>
</div>
</details><details open=""><summary><span class="headline">PRODUCT DETAILS</span> <span class="sub-headline"> Details for the Boot</span> </summary>
<div class="indent-content">Features: Dress, Leather<br>Boot Type: Ankle &amp; Short Boots<br>Style: Side Zip<br>Toe Style: Almond Toe<br>Heel Height: 1-2"<br>Color: BLUE-0001</div>
</details>
```

4. Switch back to WYSIWYG mode and then back to code view

Note that the [div] elements within the first [detail] element are moved above the [detail] element.  Also, there are extraneous and unnecessary [p] elements.
```
<div>These gorgeous boots are made from high-quality leather and have a shimmering metallic finish to add extra sparkle in your life! With them you will take a stroll on the wild side and see what fashion looks like!</div>

<p><br>
</p>

<div>High Quality and Vegetable Tanned Leather Upper</div>

<div>Decorative Black Beads on the Upper</div>

<div>Smooth Synthetic Rubber Bottom</div>

<div>1.5&quot; inch Heel with Fashion Metal Studs</div>

<div>Genuine Leather Lining on the Interior</div>

<div>Soft Leather Footbed</div>

<div>Made in Italy</div>
<p></p><details open=""><summary><span class="headline">FEATURES</span><span class="sub-headline"> Learn more about the features</span></summary></details><p></p>
<div class="indent-content">Features: Dress, Leather<br>
Boot Type: Ankle &amp; Short Boots<br>
Style: Side Zip<br>
Toe Style: Almond Toe<br>
Heel Height: 1-2&quot;<br>
Color: BLUE-0001</div>
<p></p><details open=""><summary><span class="headline">PRODUCT DETAILS</span><span class="sub-headline"> Details for the Boot</span></summary></details><p></p>
```

**Expected behavior**
It is expected that suneditor will not restructure the DOM and not insert extraneous elements in valid HTML.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 2.40.0 (latest and all prior versions)

**Comment by JiHong88** [comment]
You must be add "__se__tag" class.
In the current version, "details" tag should be registered in "format" format, but it is not supported.
"__se__tag" will be modified to not check "format" at the next version. 
```
<details open="" class="__se__tag">
```

Editor removes disallowed attributes and fix formats that don't fit.
Please refer below links.
https://github.com/JiHong88/SunEditor/issues/412#issuecomment-648065274
https://github.com/JiHong88/SunEditor/issues/397
https://github.com/JiHong88/SunEditor/issues/594#issuecomment-758641952

In version 3.0.0, almost everything will be modified to be customizable.

**Comment by JiHong88** [comment]
"details", "summary" tags will be added as default tags in next version.

**Comment by JiHong88** [comment]
The [2.41.0](https://github.com/JiHong88/SunEditor/releases/tag/2.41.0) version has been updated.
Thank you.
