### ISSUE TITLE
How to host image using `onImageUploadBefore`

### ISSUE THREAD

**Issue by changyeamoon** [JiHong88/SunEditor#782]
Hey there, I'm trying to understand how I can start hosting images. I've looked around and saw that I can use `onImageUploadBefore` to hit an api that returns a url, but I am not sure what to pass back. I was expecting to see an encoded64 string but I do not see anything on the `File` object

I've provided a codesandbox with a console log to show what I'm saying. 

## Version
suneditor-react: 2.16.5

## Additional context
https://codesandbox.io/s/sunedtior-react-host-image-p7ydw?file=/src/App.tsx

**Comment by JiHong88** [comment]
https://github.com/mkhstar/suneditor-react#about-core
In "suneditor-react", there is no "core" object in the argument value. 
`onImageUploadBefore={(files, info, uploadHandler) => {`

**Comment by changyeamoon** [comment]
> https://github.com/mkhstar/suneditor-react#about-core
> In "suneditor-react", there is no "core" object in the argument value.
> `onImageUploadBefore={(files, info, uploadHandler) => {`

I'm a little confused. What does the core object have to do with my question? Does it contain the encoded64 string? I'm wondering what I need from the File object to host the image

**Comment by JiHong88** [comment]
Um.. "base64" is the default.
Do not use the "imageUploadBefore" event to if you want render the image as "base64".

**Comment by changyeamoon** [comment]
@JiHong88 I think I am just confused and lacking knowledge. What am I using in the `File` object to save the image in my server API? 

On line 17 in my code sandbox: `const hostedUrl = apiToHostImage(files[0]);` . What am I actually using in the `File` object to save the image?

**Comment by JiHong88** [comment]
If you want to upload a file to the server,  just use the `imageUploadUrl` [option](https://github.com/JiHong88/SunEditor#options).
Just upload a file to the server and send a response in the specified format. 

`imageUploadBefore` is used in a special case. https://github.com/JiHong88/SunEditor/issues/782

**Comment by changyeamoon** [comment]
@JiHong88 I don't see how I can use that to do my server call. These are the threads that I'm referring to: 
https://github.com/JiHong88/SunEditor/issues/414#issuecomment-660418723
https://github.com/JiHong88/SunEditor/issues/551 
https://github.com/mkhstar/suneditor-react/issues/128

**Comment by JiHong88** [comment]
Without using "imageUploadBefore", you can simply use "imageUploadUrl" to upload an image to the server.
Is there any reason why I can't use "imageUploadUrl"?

**Comment by changyeamoon** [comment]
@JiHong88 Maybe an example can clear up what you're trying to suggest. From what you've linked me, `imageUploadUrl` only accepts a string that maps to the url (honestly not entirely sure how to use it either). 

Where do I do the server call to get the url back after uploading the image from my files with `imageUploadUrl`?

**Comment by JiHong88** [comment]
@changyeamoon  Create upload api or use aws, etc your self.
You must be set image upload api url to the "imageUploadUrl" .
And set response data at the API.
```
request format: {
  "file-0": File,
  "file-1": File
}

response format: {
  "errorMessage": "insert error message",
  "result": [
    {
      "url": "/download/editorImg/test_image.jpg",
      "name": "test_image.jpg",
      "size": "561276"
    }
  ]
}
```

**Comment by changyeamoon** [comment]
@JiHong88 I'm using a special api mechanism for salesforce so I don't think I can use this approach with the upload api. I just ended building a custom plugin to better suit my needs. Thank you for the help!

Closing as my question was answered here (https://github.com/mkhstar/suneditor-react/issues/128#issuecomment-863564684)

**Comment by roker15** [comment]
> 

Can't read file-0 from request object with typescript. how to do this? where is this? In body? Please write few line of codes.
