### ISSUE TITLE
Does SunEditor prevents the dangerous code and JS Codes?

### ISSUE THREAD

**Issue by okandavutosf** [JiHong88/SunEditor#784]
Hi, first of all thanks for this editor. Its great and really works good.

And i want to ask is suneditor preventing the dangerous code for example html injection or js code inside of html?

## Version
Latest

**Comment by JiHong88** [comment]
Hi @okandavutosf 
Yes Script tags or JS codes are removing the inputable properties.
XSS attack related issues are being updated whenever they are found.

**Comment by okandavutosf** [comment]
Thanks for your answer

**Comment by okandavutosf** [comment]
@JiHong88  For iframes dowe have any option for the prevent js code?

![image](https://user-images.githubusercontent.com/77776340/123410282-cffb0c80-d5b7-11eb-8a54-e6bda14cdbe9.png)

**Comment by JiHong88** [comment]
The [2.41.1](https://github.com/JiHong88/SunEditor/releases/tag/2.41.1) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
