### ISSUE TITLE
wysiwyg onclick error

### ISSUE THREAD

**Issue by mostafacs** [JiHong88/SunEditor#79]
Hi,
I put source code button of editor to

```
 <div style="text-align:center;"><strong><span style="font-size:x-large;">Playmobil Fashion Boutique Carrying Case</span></strong></div>
<div style="text-align:center;"><strong><span style="font-size:x-large;">New Factory Sealed</span></strong></div>
<div style="text-align:center;"><strong><span style="font-size:x-large;"><br></span></strong></div>
<div style="textalign:center;"><strong><span style="font-size:x-large;">Ages 4+</span></strong></div>
```

and when click on editor i got this error which make all other scripts not work.

`suneditor.min.js:1 Uncaught TypeError: Cannot read property '0' of null
    at Object._findButtonEffectTag (suneditor.min.js:1)
    at HTMLDivElement.onClick_wysiwyg (suneditor.min.js:1)`

**Comment by mostafacs** [comment]
Thanks for your quick fix. I create Angular 7 Wrapper for the library. Wrapper will make it easy to integrate with angular 2+. How can i share with you?

**Comment by JiHong88** [comment]
Please  share to my email or "PR" : -)

Thank you so much!
