### ISSUE TITLE
setDisabledButtons util function buttonList is null at some point

### ISSUE THREAD

**Issue by mkhstar** [JiHong88/SunEditor#791]
**Describe the bug**
The setDisabledButtons util function buttonList is null at some point. Due to this i get this error while trying to implement the readOnly mode. `Cannot read property 'length' of null`. I think the buttonList argument must be an array by default.
Here is the defintion.
https://github.com/JiHong88/SunEditor/blob/4d4397281a07c95e93f78b5dbd3f6e293c04ce87/src/lib/util.js#L1183

I think this is where it would be an array for the first time. But up to that point it might be too late if the readOnly method is called
https://github.com/JiHong88/SunEditor/blob/4d4397281a07c95e93f78b5dbd3f6e293c04ce87/src/lib/core.js#L5214-L5217

Here is where the resizingDisabledButtons is defined initially. I think it must be an array instead
https://github.com/JiHong88/SunEditor/blob/4d4397281a07c95e93f78b5dbd3f6e293c04ce87/src/lib/core.js#L210

**Comment by JiHong88** [comment]
@mkhstar Thank you.
I'll update the version.
