### ISSUE TITLE
How to add custom inline balloon component

### ISSUE THREAD

**Issue by changyeamoon** [JiHong88/SunEditor#794]
Is there a way to add custom inline balloon to a custom plugin? Something like the image balloon toolbar in the video

## Version
suneditor-react: 2.16.5

## Additional context

https://user-images.githubusercontent.com/30943398/123689224-fc659180-d820-11eb-82fc-964f18e3a73c.mov

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/blob/master/src/plugins/dialog/math.js#L247
Please refer this link. 

You must create your own controller.
And call the "core.setControllerPosition" and "core.controllersOn" methods in order. 
http://suneditor.com/sample/html/out/document-editor.html#controllersOn

**Comment by changyeamoon** [comment]
Perfect, thanks for all you do @JiHong88  😄
