### ISSUE TITLE
Suneditor Error with 'setStart' on 'Range' - Setting Caret's Position

### ISSUE THREAD

**Issue by Le-Phuong-Linh** [JiHong88/SunEditor#795]
Hi @JiHong88 
I have a question about changing caret's position. 
Context: Suneditor is used in our project in input text that exceeds limit. The span tag is used for styling and afterwards - insertHTML that returns a single string. The thing is that the pointer's position is always at the end of the input field every time the input content is edited. So I wanted to use getRange and setRange to customize the pointer's position. However, setRange has an error: Failed to execute 'setStart' on 'Range' : There is no child at offset [startOffset] and subsequently the pointer is not set at the proper position. 
Could you please help me out with this? 
Thanks! 
![Suneditor error](https://user-images.githubusercontent.com/63165221/123825242-48cad300-d8ee-11eb-859f-08c23b0944ed.png)

**Comment by JiHong88** [comment]
Hi @Le-Phuong-Linh 
What insert do you insert with "insertHTML"?
If it's one node, it might be easier to use "InsertNode".

**Comment by Le-Phuong-Linh** [comment]
@JiHong88 
So this is how insertHTML is used in the project: 
editorInstance.insertHTML(`${someText}<span style="color: red">${redText}</span>`);

I've tried insertNode, but it did not work. Could you please tell me how to use insertNode in this line or how to implement it in any other way? 
Thanks!

**Comment by JiHong88** [comment]
ex: "insertHTML"
```javascript
editorInstance.insertHTML(${someText}<span style="color: red">${redText}</span>);
const range = editorInstance.getRange();
// range.startContainer == Inserted Last Edge Node 
// range.startContainer == `<span style="color: red">${redText}</span>`;
const el = range.startContainer;
```

"insertNode" inserts an element.
After inserting, you can specify the range of the element using "setRange". 
```javascript
const el = document.createElement("span");
el.textContent = "sample";
editorInstance.core.insertNode(el);
```

"setRange": setting the cursor position.
```javascript
editorInstance.core.setRange(el, 0, el, 1);
```
