### ISSUE TITLE
Do we have access to suneditor icons?

### ISSUE THREAD

**Issue by changyeamoon** [JiHong88/SunEditor#797]
When creating a custom plugin I want to be able to reuse the suneditor icons like the image or video icon. I see in the docks that we can use  `<i class="xx xxx"></i>` but don't see a list of class name we can use

## Version
suneditor-react: 2.16.5

## Additional context
<img width="215" alt="Screen Shot 2021-06-30 at 2 27 46 PM" src="https://user-images.githubusercontent.com/30943398/124012640-601dc500-d9af-11eb-93e2-c36e848818e5.png">

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/blob/master/src/assets/defaultIcons.js

`editorInstance.core.icons.redo`
or
```
import icons from "suneditor/assets/defaultIcons.js";
icons.redo
```
