### ISSUE TITLE
Googledoc copy paste content issue

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#798]
**Describe the bug**
When copying the content from google doc and paste it into suneditor. some text is misplaced at last.

**To Reproduce**
1. Go to 'https://docs.google.com/document/d/1y2TSDvb14JQ2uhVQxuWgASKF31YPdJ7mLWnzNAxkPcA/edit?usp=sharing'
2. copy the whole content
3. paste into suneditor
4. some text content is misplaced at last

**Expected behavior**
all content should be in correct order after pasting

**Screenshots**
https://www.loom.com/share/8e9736d9b96b48a493ec5c4aa8fa82d5

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - BrowserChrome
 - Version 2.41.0

**Comment by gopal1996** [comment]
And copy-paste content issue is happening in all the doc

**Comment by JiHong88** [comment]
The [2.41.3](https://github.com/JiHong88/SunEditor/releases/tag/2.41.3) version has been updated.
Thank you.
