### ISSUE TITLE
Can you modularize sun editor to reduce file size?

### ISSUE THREAD

**Issue by drnkwati** [JiHong88/SunEditor#8]
This editor looks promising but I wanted to make a few suggestions
Modularize  each of the heavyweight functions such as 
file upload, image etc into seperate files that way we can include only the functions we want
Alot of the html embeded in javascript increases the file size for functionality we might not use

**Comment by JiHong88** [comment]
Thanks for the advice.
I agree with your suggestion.
I will proceed with modularization.

**Comment by geonanorch** [comment]
I had something similar in mind: I would like the editor to be more open and generic, modularity being then a side-benefit. 

Example use case: when a user click to add an image, I would like to open my own dialog (linked to a specific stock repository). In other words I would need somehow to replace the default `context.dialog.image` and have a clear view on what inputs/outputs I have to handle.

All those dialogs which add new content are then just modules / plug-ins to support specific content types (images, videos, calendar, whatever!).

@JiHong88 are you planning to ship modularization in the coming days? If yes and if you are interested, I would then fork and send you a pull request.

(@drnkwati I also find this editor great --did a pretty exhaustive survey of editors a few months ago--, I am surprised that it does not get more stars)

**Comment by JiHong88** [comment]
Hi, Thanks for thinking good about suneditor.
@geonanorch I agreed your opinion, it is good idea!
I`m going to ship modularization as soon as possible.

**Comment by JiHong88** [comment]
Hi @drnkwati , @geonanorch 
Modularization is complete.
I added customization and document menu to the sample and demo site.

**Comment by drnkwati** [comment]
Nice work man. I will check it tomorrow.
But I just noticed the examples on the main site are not working properly.
`http://suneditor.com/sample/html/index.html`
The font, format and drop downs specifically are not working.
Please can you investigate the issue
thanks

**Comment by JiHong88** [comment]
The bug has been fixed.
thanks :)

**Comment by geonanorch** [comment]
Thank you @JiHong88, I'm sure that it meant quite a bit of work...
Can't look into it right now, but I will let you know once I get there.

**Comment by JiHong88** [comment]
yup, thanks @geonanorch :)
