### ISSUE TITLE
Feature request: Add Save-Button with custom callback

### ISSUE THREAD

**Issue by Gundolf68** [JiHong88/SunEditor#80]
Hi,

I think that nearly everyone needs a save-button - it would be great to have a out-of-the-box solution ...

Regards

**Comment by JiHong88** [comment]
Hi,

Thank you for your feedback : )

I'll add features.

**Comment by Gundolf68** [comment]
Hi,

thank you for your great work! 
I have made a german translation:

[de.js.zip](https://github.com/JiHong88/SunEditor/files/2868773/de.js.zip)

**Comment by JiHong88** [comment]
Thank you so much!!! @Gundolf68 : )

I Added that language translation and save button.

Updated in [v2.10.0](https://github.com/JiHong88/SunEditor/releases/tag/2.10.0)

**Comment by Gundolf68** [comment]
Sorry, there is a little error in de.js:
Please change the line

submitButton: 'Absenden',
to
submitButton: 'Übernehmen',

**Comment by JiHong88** [comment]
yup,

Fixed in [v2.10.1](https://github.com/JiHong88/SunEditor/releases/tag/2.10.1)

Thank you : )
