### ISSUE TITLE
Remove Position Radio Buttons

### ISSUE THREAD

**Issue by David-Grass-Feria** [JiHong88/SunEditor#802]
Hello JiHong. For the images and videos i remove all things.
`videoResizing: false,
     videoHeightShow: false,
     videoHeight: false,
     videoRatioShow: false,
     videoResizing: false,
     imageResizing: false,
     imageHeightShow: false,
     imageWidth: false,
     imageHeight: false,`

It works! But how i can remove the positions radio buttons? I mean "standard", "left", "center", "right" ? Many thanks :) The option "Standard" is allways checked. I like only "standard".

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
