### ISSUE TITLE
I can't enable scrolling = "no" for iframe :(

### ISSUE THREAD

**Issue by aleksaav** [JiHong88/SunEditor#804]
Hi **@JiHong88**,
How can I enable **scrolling = "no"** when paste iframe, because the editor does not recognize it?
Editor recognizes allowfullscreen and frameborder but scrolling = "no" can't, **is there a way to fix it?**
I would be very grateful for an answer :)

**Comment by aleksaav** [comment]
@JiHong88 Thanks a lot for the help, but I made a mistake. I need this, but for React. I hope it will be useful to someone. :)

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
