### ISSUE TITLE
problem with setting fontSize toolbar value / ways to get current options

### ISSUE THREAD

**Issue by curious-curie** [JiHong88/SunEditor#805]
To make it easier for us to help you, please include as much useful information as possible.
안녕하세요.
2.41.3 버전 + suneditor-react 3.2.0을 사용하고 있습니다.

fontSize를 바꾸면 선택된 se-btn-list의 button에 active 클래스가 붙는데요
toolbar의 글씨크기 설정 버튼은 계속 '크기' 로 보여지는 문제를 겪고있습니다.
혹시 이 부분을 해결하는데 도움 주실 수 있을까요? 
![image](https://user-images.githubusercontent.com/47528556/125068593-9c100300-e0f0-11eb-91bc-c68713fe2ce5.png)

관련해서 fontSize 등 옵션을 바꿀 때 발생여부를 알 수 있는 이벤트나,
현재 선택 된 fontSize 옵션을 알 수 있는 방법이 있을까요?
혹은 onChange 이벤트 발생 시 선택된 옵션을 알 수 있는 방법이 있을까요? 
감사합니다. 

## Version
Write the version of the Editor you are currently using.
2.41.3

**Comment by JiHong88** [comment]
안녕하세요~
현재 크기가 나오는게 정상적인 동작인데, 뭔가 커스텀 하신게 있나요?
소스 전체를 보여주시면 더 좋을 것 같습니다.

**Comment by curious-curie** [comment]
안녕하세요. 답변 감사합니다~

커스텀한 부분에 문제가 있는 것 같아 
기본 suneditor-react 예시 코드랑 같게 바꾸어서 테스트 해보았구요, 
```js
import SunEditor, { buttonList } from "suneditor-react";
import "suneditor/dist/css/suneditor.min.css"; // Import Sun Editor's CSS File
function App() {
  return (
    <div className="App">
      <SunEditor
        setOptions={{
          height: 200,
          buttonList: buttonList.complex, // Or Array of button list, eg. [['font', 'align'], ['image']]
          // Other option
        }}
      />
    </div>
  );
}

export default App;

```

두 가지 버전 테스트해보았습니다. 

```json
    "suneditor": "2.41.3",
    "suneditor-react": "3.2.0",
```

```json
    "suneditor": "2.40.0",
    "suneditor-react": "3.1.2",
```

둘 다 똑같이 font size 가 계속 size 로만 디스플레이 됩니다.

![ezgif-6-ff88846fbc9c](https://user-images.githubusercontent.com/47528556/125214583-cdf0b780-e2f2-11eb-9200-37a4f8f32d24.gif)

혹시 다른 버전을 사용하면 해결될까요?

**Comment by JiHong88** [comment]
음.. 폰트, 사이즈, 포맷까재 바뀌는게 정상인데.. 
에러 콘솔은 출력이 안되나요?

**Comment by curious-curie** [comment]
@JiHong88 넵 에러 콘솔은 출력되는게 없었구요
suneditor-react 사용하지 않고 suneditor 모듈만 사용해서 구현하니 재현되지 않고 정상 작동하는 것 확인 했습니다. 
suneditor-react 모듈 문제인 것 같아요. ㅠ 
빠른 답변 감사드립니다~!
