### ISSUE TITLE
Empty content

### ISSUE THREAD

**Issue by peter-chow** [JiHong88/SunEditor#807]
When the editor has no content, it still has an underlying markup in the form (using the default settings): `<p><br></p>`.

It would be ideal if the markup is an empty string to reflect what is observed in the editor by the user.

Setting the property, defaultTag, to an empty string seems to break the editor.

**Comment by peter-chow** [comment]
Hi @JiHong88,

I'm not sure that the referenced commit fulfills the enhancement.  It looks like it prevents the defaultTag from being an empty string, but will there also be an update that makes the markup an empty string if there is no content in the editor?

**Comment by JiHong88** [comment]
@peter-chow It is currently structurally impossible to remove all tags when there is no content in the editor.
The editor should always have a default format.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
