### ISSUE TITLE
Whitespace is sometimes removed where it should be kept when pasting from MS Word.

### ISSUE THREAD

**Issue by svpetry** [JiHong88/SunEditor#808]
When I paste a text like this from MS Word (Text1 is bold, Text2 is underlined):
![image](https://user-images.githubusercontent.com/13044003/125641697-0efe06ec-6ec4-436a-9d3d-966b84e9cf4e.png)

Then the whitespace between both words is removed:
![image](https://user-images.githubusercontent.com/13044003/125643048-3c7fc931-ad4c-435a-bfcc-d8e19d7a18a9.png)

This happens because in the cleanHTML function util.htmlRemoveWhiteSpace is called.

Before:
![image](https://user-images.githubusercontent.com/13044003/125642039-d932731d-04e7-4903-9b71-d35740eb42f4.png)

After:
![image](https://user-images.githubusercontent.com/13044003/125642108-72eb9568-b9fe-47e8-a238-ddc59e196a09.png)

You can see that the whitspace between the tags should be kept but it was removed.

This is working in older versions of SunEditor that I could find as online demos.

**Comment by svpetry** [comment]
Maybe a solution could be to modify htmlRemoveWhiteSpace so that all whitespace is removed but one single space is kept. But I don't know if this would have any negative side effects.

Apart from this the editor is great btw. :-)

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
