### ISSUE TITLE
Editor converts whitespace to a new line

### ISSUE THREAD

**Issue by alex-safian** [JiHong88/SunEditor#809]
**Describe the bug**
The editor breaks a line of string into several lines if it is not wrapped with an HTML tag.

**To Reproduce**
1. Set value of Textarea to `Hi <span>Alex</span>`

[Demo](https://jsfiddle.net/alireza_safian/v23e6dxh/)

**Expected behavior**
The output must be 
`Hi Alex`
not 
```
Hi
Alex
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8412286/125712165-2f823100-aff5-49dd-a9ed-b6044ad112c3.png)

**Additional context**
The editor should wrap the string with a tag to prevent the breaking string to several lines.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
