### ISSUE TITLE
Different structure under UL unordered list

### ISSUE THREAD

**Issue by thomaskovo** [JiHong88/SunEditor#814]
When manually written html ul the output is wrong

1. In editor write any unordered list with li child tags
2. On the same level add image so the input looks like this
```
<ul>
  <li>Pasting from Microsoft Word and Excel.</li>
  <li>Custom table selection, merge and split.</li>
  <li>Media embed, images upload.</li>
  <img src="https://www.w3schools.com/html/pic_trulli.jpg" height="333">
  <li>Can use CodeMirror, KaTeX.
    <ul>
      <li>And.. many other features :)</li>
    </ul>
  </li>
</ul>
```
3. And the output is:
```
<ul>
  <li>Pasting from Microsoft Word and Excel.</li>
  <li>Custom table selection, merge and split.</li>
  <li>Media embed, images upload.</li>
  <li></li>
  <li>Can use CodeMirror, KaTeX.
    <ul>
      <li>And.. many other features :)</li>
    </ul>
  </li>
</ul>
```
4. So the image tag is replaced with li and the image is not preset

Note:
tested on latest versions
`"suneditor": "^2.41.3",`
`"suneditor-react": "^3.2.0",`

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
