### ISSUE TITLE
 how do I initialize the editor with existing content?

### ISSUE THREAD

**Issue by oldcastlehq** [JiHong88/SunEditor#815]
Hi,

First, thank you for your plugin. It's great!

I am able to save the content in my database and I can retrieve it. So, my question is how to load/show the content on the editor?

For example, I have two PHP pages. One is add.php and the other is edit.php. With the add.php I can save the content that I created in my DB. Now, I want to be able to show that content, on the edit.php page, so the user can edit the content. My issue, is how do I initialize the editor with the content that I got from the DB?

## Version
v2.41.3

**Comment by JiHong88** [comment]
```javascript
const editorInstance = suneditor.create({
  value: "contents"
});

// or use the method of the editorInstance
editorInstance.setContents("contents");
```
