### ISSUE TITLE
Editor changing the font color by itself

### ISSUE THREAD

**Issue by togrul-topal** [JiHong88/SunEditor#817]
When typing the text, editor sometimes changes the color of the text in the background (creates a new span with  <span style="color: rgb(51, 51, 51); font-family: "). This happens randomly and reproducing is not possible (i.e., if you delete text and type in the exact same text, error won't happen).

**Comment by JiHong88** [comment]
Maybe it's because of pasting text.
There is no code to add span tag during text input.
If you have an test case, please re-register the issue.
