### ISSUE TITLE
Empty A tag is removed from markup

### ISSUE THREAD

**Issue by guido-visser** [JiHong88/SunEditor#818]
**Describe the bug**
Use case: Writing documentation where you want to add # jumps. With this premise, you need `<a name="helloworld"></a>` in the code, to jump to that part. However, as soon as I go back into Wysiwyg-mode, the `a` tag is removed (likely because it's empty, it seems to stay when I add content eq: `<a name="helloworld">Hello World</a>`)

**To Reproduce**
1. Open the source mode
2. Add `<a name="helloworld"></a>`
3. Go back into Wysiwyg mode
4. Open source again, the `a` tag is gone

**Expected behavior**
I expect the `a` tag to still exist, especially if it has a `name` or `class` attribute on it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 92.0.4515.107

**Comment by guido-visser** [comment]
Thanks for the fix! Much appreciated!

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
