### ISSUE TITLE
SUNEDITOR.create.fail [React]

### ISSUE THREAD

**Issue by Sio5** [JiHong88/SunEditor#82]
Hello everyone,

is there maybe a issue with React ? Because in Fiddle it sems to work fine.

```
`import React, { Component } from 'react'

import 'suneditor/dist/css/suneditor.min.css'
import suneditor from 'suneditor';

suneditor.create('sample', {
 // insert options
});
export default class Editor extends Component {
  render() {
    return (
      <div>
    <textarea id="sample" className="sample">Hi</textarea>
      </div>
    )
  }
}

```

![FireShot Capture 012 - React App - localhost](https://user-images.githubusercontent.com/46957417/54308115-98761b00-45cd-11e9-8a3b-2f17b952d10a.png)

**Comment by JiHong88** [comment]
Hi, @Sio5 

Suneditor takes an ID or DOM element as its argument value.

It seems that the creation failed because the "textarea" has not yet been rendered.

Call suneditor.create function after the "textarea" is rendered.

**Comment by Sio5** [comment]
Hey , JinHong88

Thanks for Reply.

Yea figured it yesterday out aswell. 

componentDidMount did the job, all fine.
