### ISSUE TITLE
Setting font-family to a font with space in name not working (e.g. "Courier New")

### ISSUE THREAD

**Issue by anmo1967** [JiHong88/SunEditor#822]
**Describe the bug**
If you set a selected text to a font with space in the name (e.g. "Courier New") the generated HTML code uses nested "", what is not allowed and will be filtered out at a later reload of the HTML code.

![image](https://user-images.githubusercontent.com/63302833/126908751-61f1e222-67ff-46eb-b9c2-59e4d11451f9.png)
![image](https://user-images.githubusercontent.com/63302833/126908825-2ad4260c-ce09-49c7-b3a2-beba8698310f.png)

Better use single quotes or leave the quotes out at all - what is not a problem in css at all.

**Comment by JiHong88** [comment]
This is a phenomenon that occurs at the browser level when setting fonts.
I can't control it. :(
For example, in Firefox, quotes are not included.

**Comment by anmo1967** [comment]
At the browser level, the generated html uses escaping (&quote;) and this is send and fetched back to/from the server:
![image](https://user-images.githubusercontent.com/63302833/127087572-a7cbc9da-a88f-4d5f-890f-12c7ff440cf0.png)
So, after refresh, the server generates a html document with a textarea-tag including the &quote; escapes. I guess, when you take over the text from the textarea to your div, this happens...

**Comment by JiHong88** [comment]
Even if you don't refresh, the tag containing the escapes will be created.
What problem does this cause?

**Comment by anmo1967** [comment]
The escapes themselves do not cause any problems, but they have been translated in the wrong position. So, html basis is e.g.
![image](https://user-images.githubusercontent.com/63302833/127111194-8986d6fb-f063-45f6-b51c-04cf67b58563.png)
but after creating the SUNEditor on top of the <textarea>, the resulting html is as follows:
![image](https://user-images.githubusercontent.com/63302833/127111655-6b5f2131-fd09-4153-9084-5d9cc227141c.png)
So, the double quote before the Courier was decoded and interpreted as end of the style attribute.

**Comment by JiHong88** [comment]
@anmo1967 I can't reproduce this issue :(
Please tell me more detail for the test case.

**Comment by anmo1967** [comment]
@JiHong88 OK, I now have prepared a complete example, that you can easily execute:
Let's start with creating some text containing Currier New - I used your demo-editor from your web site (http://suneditor.com/sample/index.html):
![image](https://user-images.githubusercontent.com/63302833/128607615-0f5dc84d-7c1a-499e-82c5-b34d4a78d442.png)
The resulting html now is:
![image](https://user-images.githubusercontent.com/63302833/128607699-2706dbb2-d0c1-49a7-97b9-b88f54e8304b.png)
So far no problem, just the preparation. But if I now take the resulting html and put it into the textarea element for your editor, the problem occures, see this minimal example:
`<html><head>
<link href="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/css/suneditor.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/suneditor.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/suneditor@latest/src/lang/en.js"></script>
</head><body>
<textarea id="sample" style="width: 100%;">**<p>sdfjsad<span style="font-family: &quot;Courier New&quot;;">jflsaldjflsadlfasldjflas</span>jdlkfasdf</p>**</textarea>
<script>
const editor = SUNEDITOR.create('sample',{
    lang: SUNEDITOR_LANG['en']
});
</script>
</body></html>`
If I run this, the result doesn't contain the Courier New format anymore!:
![image](https://user-images.githubusercontent.com/63302833/128607925-2eddb367-fbd0-47bd-a954-884ebf5dc940.png)
And the html looks as follows:
![image](https://user-images.githubusercontent.com/63302833/128607960-a759b1ec-8fac-4142-a1bf-fa17aa0c079a.png)
Hope, this helps you.
Andreas

**Comment by anmo1967** [comment]
@JiHong88 Unfortunately, my last comment, starting with the "minimal example", was screwed up by the system. you can find the minimal example as an attachment:
[testsuneditor.html.txt](https://github.com/JiHong88/SunEditor/files/6949463/testsuneditor.html.txt)
If I run this, the result doesn't contain the Courier New format anymore!:
![image](https://user-images.githubusercontent.com/63302833/128608299-df78653c-9bba-4a5a-8b96-72d33d2160ed.png)
And the resulting html is:
![image](https://user-images.githubusercontent.com/63302833/128608320-e30ce9ad-b41b-43b7-a690-0d741f5635ad.png)
You see, no Courier New any more. Thats the problem!
I hope this helps you.
Andreas

**Comment by JiHong88** [comment]
@anmo1967 Yes I understand what you mean.

Putting an initial value in `<textarea></textarea>` is a secondary means.
Please use the `value` option or `core.setContents` as below. 
```
suneditor.create("#id", {
  value: `<p>sdfjsad<span style="font-family: &quot;Courier New&quot;;">jflsaldjflsadlfasldjflas</span>jdlkfasdf</p>`
})
```
