### ISSUE TITLE
formats are not reflecting to some word in the selection sentence

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#827]
**Describe the bug**
when changing the text font family of long paragraphs, some of the paragraph's last words are not changing.

**To Reproduce**
1. Type some long sentence
2. select all sentence
3. change font family
4. last some words in the sentence won't have any effect

please find the recorded screen.
https://www.loom.com/share/3ee1a0ddd64348d8b38b1ea5a66e46bc

**Expected behavior**
the selected text should change the font family

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
