### ISSUE TITLE
Suneditor crash when assigning a default value

### ISSUE THREAD

**Issue by gopal1996** [JiHong88/SunEditor#828]
**Describe the bug**
when assigning a default value to suneditor with specific tag, suneditor gets crashed

**To Reproduce**
1. set **value** to `<figure style="margin: auto; width: 490px;"><img class="se-custom-tag" src="https://1.bp.blogspot.com/-mhdYXV7RykU/Xls3b-1qM1I/AAAAAAAAnqM/ke6nHNve0twL_s-uNcAuI4tMf8y0VEDYQCLcBGAsYHQ/s1600/Happy-birthday-messages-and-Happy-birthday-wishes%2B%25281%2529-min.jpg" alt="" data-proportion="true" data-size="490px,490px" data-align="justify" data-index="3" data-file-name="Happy-birthday-messages-and-Happy-birthday-wishes%2B%25281%2529-min.jpg" data-file-size="0" origin-size="500,500" data-origin="490px,490px" style="width: 490px; height: 490px;"></figure>`
2. suneditor gets crashed

**Expected behavior**
it should load the content with an image in the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/22369081/127032611-70890a5e-4884-4183-816d-5ae431a5b4ad.png)

**Codesandbox**
https://codesandbox.io/s/suneditor-8exq4?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: Macos Big sur
 - Browser : Chrome
 - Version : 91

**Comment by JiHong88** [comment]
Did you manually edit the tag attributes?
The cause of the error is the "data-align" attribute. 
`data-align="justify"` => `data-align="center"`
It will be added exception handling at the next version.

**Comment by gopal1996** [comment]
not sure how it was added, but we are inserting the image using insertHTML function with `<img src="..." />`

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
