### ISSUE TITLE
Youtube player parameters

### ISSUE THREAD

**Issue by realdigger** [JiHong88/SunEditor#83]
Hi.
Can you add new editor option to set params string for all youtube embed videos. It will be useful to have ability add something like "?rel=0&modestbranding=1" to embed videos.

**Comment by JiHong88** [comment]
Hi, @realdigger 

Thank you for your feedback  : )

It's Updated in [v2.11.1](https://github.com/JiHong88/SunEditor/releases/tag/2.11.1)

**Comment by realdigger** [comment]
Thank you for SunEditor and it's features.
