### ISSUE TITLE
Typescript build error - Cannot find name 'resizing'

### ISSUE THREAD

**Issue by TakoOu** [JiHong88/SunEditor#830]
**Describe the bug**
Typescript build return an error for component.d.ts

**To Reproduce**
Import suneditor to your typescript project and start a build.

**Expected behavior**
The project should build without error

**Screenshots**
![image](https://user-images.githubusercontent.com/24452494/127147197-f0f3f4ec-53c2-48f1-a6c9-63592ea2a49e.png)

**Additional context**
I think it's a simple copy/paste error, line 25 of component.d.ts should be
`export default component;`
instead of
`export default resizing;`

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
