### ISSUE TITLE
Non-video embed iframe is always treated as a video embed

### ISSUE THREAD

**Issue by rwaldron** [JiHong88/SunEditor#831]
**Describe the bug**

I have users that expect to be able to embed things like Google Forms or Qualtrics Surveys via iframe. When doing so, the `<iframe>` markup is treated as a video embed and subsequently wrapped in the video embed markup. 

**To Reproduce**

1. Using an editor that has code view, click the code view icon. 
2. Select all and paste the following: 
```html
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdeRUNjzg9b276CGcT0gHWzrp1bRdx6ssfWU0Pje9K3dCCeJQ/viewform?usp=sf_link" style="width: 1920px; height: 1080px;"></iframe>
```
3. Click the code view button again to see the rendered frame
4. Click the code view button _again_ to see the modified markup
```html
<div class="se-component se-video-container __se__float-none" contenteditable="false">
  <figure style="height: 1080px; padding-bottom: 1080px; margin: 0px; width: 1920px;">
    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdeRUNjzg9b276CGcT0gHWzrp1bRdx6ssfWU0Pje9K3dCCeJQ/viewform?usp=sf_link" style="width: 1920px; height: 1080px;" frameborder="0" allowfullscreen="" data-size="1920px,1080px" data-align="none" data-index="1" data-file-name="viewform?usp=sf_link" data-file-size="0" data-origin="1920px,1080px"></iframe>
  </figure>
</div>
```

**Expected behavior**

My users expect their `<iframe ...></iframe>` to be left alone, _however_ I would argue that such an expectation is not yet defined, but probably should be, ie. there should be some way to signal to SunEditor that it must leave a given iframe alone. 

I can think of two possible ways to handle this, (though I'm sure you have more and better ideas 😄 ): 

1. Only create the wrapper markup when the actual SunEditor Video embed plugin is used. This is probably too drastic.
2. Create a special `data-*` attribute that can be used by "power users" to override the video wrapper, ie. `<iframe data-se-video-embed="false" src="..."></iframe>`

**Comment by s-kris** [comment]
@JiHong88 

For me, In addition to the issue mentioned by @rwaldron, the `src` attribute is removed. I whitelisted the attribute but still, the `src` is removed.

```
 attributesWhitelist: {
                    iframe: 'src',
                },
```

Am I missing something here? 

Thank you!

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
