### ISSUE TITLE
ToolbarButtons code and functionality enhancements

### ISSUE THREAD

**Issue by SystemChanger** [JiHong88/SunEditor#835]
Suggestions from https://github.com/JiHong88/SunEditor/pull/832 pull-request:

1. Why "se-resizing-enabled" class and the corresponding array "resizingDisabledButtons" are called so?
This is super strange, They should be called something like "se-readonly-enabled" and "readOnlyDisabledButtons".
Version 3.0.0 ? :)
2. I think that it is better to copy all properties of previous toolbar buttons to the new ones in "setToolbarButtons()" method, cause in the future there could be some basic stuff besides read-only, fullscreen or code-view (or is already there) and also custom buttons.
We have this code for restoring the buttons css'es:
```Javascript
if (core._variable.isCodeView) util.addClass(core._styleCommandMap.codeView, 'active');
if (core._variable.isFullScreen) util.addClass(core._styleCommandMap.fullScreen, 'active');
```
But I think that it'll be better to store (in core map) all styles (and other properties like "disabled") of ALL previously created (or deleted) buttons (custom ones too) to be able to restore them when they will be created again, so we won't have to insert the code like above. On each recreate, properties should be updated.
It might look something like this to store and update:
```Javascript
if (!this.allCommandsButtonsMap) this.allCommandsButtonsMap = new Map();
const currentButtons = context.element._buttonTray.querySelectorAll('.se-menu-list button[data-display]');
for (let i = 0, element, command; i < currentButtons.length; i++){
    element = currentButtons[i];
    command = element.getAttribute('data-command');
    this.allCommandsButtonsMap.set(command, element);
}
```
And like this to restore:
```Javascript
if (core.allCommandsButtonsMap) {
    const currentButtons = context.element._buttonTray.querySelectorAll('.se-menu-list button[data-display]'); 
    for (let i = 0, button, command, oldButton; i < currentButtons.length; i++){
        button = currentButtons[i]; 
        command = button.getAttribute('data-command');
        oldButton = core.allCommandsButtonsMap.get(command);
        if (oldButton) {
            button.parentElement.replaceChild(oldButton, button);
        }
    }
}
```
But the problem in my example is that there are some variable-stored buttons (e.g. "_styleCommandMap", "bold", "underline") and the code dependent on them.
Also, I don't understand some parts of the code in "setToolbarButtons()", so it is better to change this method by you (some weird things are done there, looks like it could be simplified).

UPD: I tried to handle it myself, made some changes and created a pull-request for it (https://github.com/JiHong88/SunEditor/pull/839).
@JiHong88, It passed my functional testing, but, anyway, please check that everything is working as it should.

**Comment by JiHong88** [comment]
> 1. Why "se-resizing-enabled" 

This variable was created before "readonly" mode came out.
It became common while developing the "readonly" mode.
