### ISSUE TITLE
text direction button 

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/SunEditor#838]
@JiHong88 hi
Please add the ability to adjust the direction of the text.   It is very, very necessary.
It's very simple, it should have exactly the same function as direction in css, for more information, refer to the link below.

[https://www.w3schools.com/cssref/pr_text_direction.asp](https://www.w3schools.com/cssref/pr_text_direction.asp).

In addition, this feature must be adjustable by the user, like other buttons, it must have a button to adjust.

This is exactly the capability in Microsoft Office :
[https://getproofed.com/writing-tips/changing-direction-text/](https://getproofed.com/writing-tips/changing-direction-text/)

**Comment by JiHong88** [comment]
@Saeeed-B You can use the "rtl" option.
`{ rtl: true }`

**Comment by Saeeed-B** [comment]
@JiHong88 
I asked this question once again.
But I think you are wrong.
The rtl option only rtl the Toolbar. I want there to be a button that rtl the text and the output is rtl.
However, the rtl option does not rtl the text. And the output of the editor is not rtl.

**Comment by Saeeed-B** [comment]
@JiHong88 
On the other hand, the direction feature must be changeable by the user who uses the editor.
Because the user may want to write in several languages such as English and Arabic, so he should be able to change the direction at any time.

**Comment by Saeeed-B** [comment]
@JiHong88 
This is very simple, just as changing the font size has a button and is customizable, the direction must also have a button and be customizable

**Comment by Saeeed-B** [comment]
@JiHong88 
I have repeatedly checked the output of the editor. If the rtl option is enabled, the output does not have the rtl direction style.

**Comment by Saeeed-B** [comment]
@JiHong88  ?

**Comment by JiHong88** [comment]
When using "rtl" mode, text is "rtl" direction. 
<img width="553" alt="스크린샷 2021-08-07 오후 5 10 09" src="https://user-images.githubusercontent.com/13191953/128594326-662f1c45-0852-4d24-a6d2-d4c5a88ee68e.png">

I'll add the text "direction" button.

**Comment by Saeeed-B** [comment]
@JiHong88 
We look forward to this feature.
Because the user must also be able to change the direction .
Thankful

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
