### ISSUE TITLE
Loose Styling in New Line after deleting all letters

### ISSUE THREAD

**Issue by ScriptType** [JiHong88/suneditor#841]
**Describe the bug**
When you create a new Line with a set styling and write a letter and remove the letter you loose your styling.

**Expected behavior**
Even when you delete all letters of the new Line the Styling should still be retained. (Basicly every editor handles it like this google docs, word)

**Desktop (please complete the following information):**
 - Linux Manjaro
 - Chrome, Firefox

**Additional context**
The problem is that you delete empty Span's which is correct when there are 2 or more Spans in one Paragraph/Div but when there is only 1 Span you shouldn´t delete the Span when its empty that way you would retain the Styling.

**Comment by JiHong88** [comment]
@ScriptType This is the intended behavior.
Other web editors work the same.
I'll add related options.
