### ISSUE TITLE
ways to prevent indentation overflow

### ISSUE THREAD

**Issue by curious-curie** [JiHong88/SunEditor#843]
To make it easier for us to help you, please include as much useful information as possible.

안녕하세요. sunEditor 정말 잘 사용하고 있습니다.
사용 중 궁금한 점이 있어 이슈 남깁니다.
indent를 계속 누를 경우 - 화면이 좁으면 저런 식으로 에디터 밖으로 scroll 되게 넘어가는데요
혹시 이부분을 제어할 방법이 있을까요? (Indent가 특정 수치 이상으로는 되지 않도록 하거나, margin-left 의 max값을 정하거나...)
width, maxWidth 설정과는 관련이 없는 것 같고, 고민하다 해결방법이 떠오르지 않아 여쭤봅니다.
항상 감사합니다.~
![ezgif-2-4db042458316](https://user-images.githubusercontent.com/47528556/127984971-438ed877-0b26-41bc-9841-783badd79b48.gif)

## Version
Write the version of the Editor you are currently using.
2.40.0

**Comment by JiHong88** [comment]
맥스값을 주어도 텍스트 길이에 따라 다른거라 답이 없네요..
가로스크롤을 숨길수는 있지만 마진 값을 제어하긴 힘듭니다.
```css
.sun-editor .se-wrapper .se-wrapper-inner { overflow-x: hidden; }
```
