### ISSUE TITLE
Text gets cut off after the "<" sign

### ISSUE THREAD

**Issue by togrul-topal** [JiHong88/SunEditor#845]
**Describe the bug**
I have a specific text. I type it in, save to the database in HTML. When I load this HTML into the SunEditor, the SunEditor cuts off everything after the "<" sign. This happened several types, every time after the "<" sign.

**To Reproduce**
1. Paste as HTML: 
```
<p>Let $\Omega$ be the underlying randomness space. In this case, the variables $X^-$ and $X^+$ collapse to $U$. To see why, pick an arbitrary $\omega \in \Omega$:<br>\begin{align*}X^-(\Omega) = \sup\left\{y\in [0,1]: F(y)&lt;U(\omega)\right\} =&nbsp;\sup\left\{y\in [0,1]: P(U\leq y)&lt;U(\omega)\right\} =&nbsp;\sup\left\{y\in [0,1]: y&lt;U(\omega)\right\} = U(\omega).\end{align*}<br></p>
```
2. Save
3. Open again, then you get:
```
<p>Let $\Omega$ be the underlying randomness space. In this case, the variables $X^-$ and $X^+$ collapse to $U$. To see why, pick an arbitrary $\omega \in \Omega$:<br>
\begin{align*}X^-(\Omega) = \sup\left\{y\in [0,1]: F(y)</p>
```

**Expected behavior**
Most of the times HTML is loaded exactly as it is from the database and SunEditor makes no changes to the text.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: latest

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
