### ISSUE TITLE
`convertContentsForEditor` cannot parse `style="font-size: 'Courier New'"`

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#846]
**Describe the bug**
`convertContentsForEditor` cannot parse `style="font-size: 'Courier New'"`

**To Reproduce**
1. Set the contents as below HTML
```html
<p><span style="font-size: 'Courier New'">aaa bbb ccc</span></p>
```

```js
editor.core.setContents(`<p><span style="font-size: 'Courier New'">aaa bbb ccc</span></p>`);
```

2. In `convertContentsForEditor`

```js
// after
contents = this._deleteDisallowedTags(this._parser.parseFromString(contents, 'text/html').body.innerHTML).replace(/(<[a-zA-Z0-9\-]+)[^>]*(?=>)/g, this._cleanTags.bind(this, false));

// the contents value is
"<p><span style="font-size: '>aaa bbb ccc</span></p>"
```

**Expected behavior**
Should correctly parse `style="font-size: 'Courier New'"`

**Screenshots**

https://user-images.githubusercontent.com/313189/128361770-20268f23-1657-4e94-8157-1a09f3e9a57a.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Additional context**

**Comment by JiHong88** [comment]
This issue is already resolved.
I'll notify you after version update.

**Comment by rexpan** [comment]
@JiHong88 Any plan to release the fix soon?

**Comment by JiHong88** [comment]
@rexpan Sorry, The work was delayed..
I will update it as soon as possible.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by rexpan** [comment]
@JiHong88 Thank you for the update.
The new version works fine with the *double quote*.
```html
<p><span style='font-family: "Courier New"'>font-family: "Courier New"</span></p>
```

But there is still issue with *single quote*
```html
<p><span style="font-family: 'Courier New'">font-family: 'Courier New'</span></p>
```
Could you check if fixing the `single quote` is feasible. Thank you.

https://user-images.githubusercontent.com/313189/149647932-cc3574fa-0ae8-4931-8605-9d4bb59c5ee2.mp4
