### ISSUE TITLE
Video attribute controls always true, how can it be removed

### ISSUE THREAD

**Issue by zt1983811** [JiHong88/SunEditor#847]
Video attribute controls always true, I tried to remove it in html code but when I switch back to editor mode or save it back to controls=true. how can it be removed when I don't need controls of video or audio ?

I checked the code 
https://github.com/JiHong88/SunEditor/blob/6d4414ba476c843001da97e326c48c54cf60734a/src/plugins/dialog/video.js#L222
it seems we force it to be true, is there any reason why we did that?  And How can I override the behavior  ?

## Version
2.41.3

## Additional context
![image](https://user-images.githubusercontent.com/2559543/128645838-083ef637-fd27-42f4-8610-692a38979530.png)

**Comment by SystemChanger** [comment]
@zt1983811 You can "preview" the video, disabling the editor (```suneditor.disable()```).
I made for these purposes the button which toggles edit/preview modes in my project (by enabling and disabling read-only)

```Javascript
function overrideSuneditorFunctions() {
  const baseReadOnlyFunction = suneditor.readOnly;
  suneditor.readOnly = ((value) => {
    baseReadOnlyFunction.call(suneditor, value);

    tweakEditorElementDependingOnReadOnly();
  });
}

function tweakEditorElementDependingOnReadOnly() {
  const { core } = suneditor;
  if (core.isReadOnly) {
    suneditor.wysiwyg.disable();
  } else {
    suneditor.wysiwyg.enable();
  }
}
```

But the code above needs changes from the currently active pull-requests.
P.S. After the current pr's will be merged, I'll suggest the read-only enhancements above to JiHong.

**Comment by zt1983811** [comment]
@SystemChanger Thanks for reply me but I am not sure I understand it because lack of knowledge of the SunEditor code. Therefore correct me if I have misunderstood the stuff:

1. your will disable wysiwyg editor when user modify the html code and make a preview button. Like that it won't change the html back to the default one in code
2. Currently you are waiting for PR to be merge so that we can apply this?

**Comment by SystemChanger** [comment]
@zt1983811 No, I just gave you a suggestion how we can easily switch editor to "html-content preview" and back to editor mode, so you can get access to iframe content, because I think that it is what you are looking for. Maybe I am wrong, and you want to hide the controllers for other purposes? We need them to be able to resize the video block.
Try adding some video on this page: http://suneditor.com/sample/html/examples.html.
Then press the "disabled" button, and you will see what I was talking about.

I am waiting for PR to make this process easier, so we can later add the mode switch button right on the toolbar.

**Comment by zt1983811** [comment]
@SystemChanger  Oh thanks I see. In fact my question is more on if I can remove `controls=true` in HTML code. Reason is I am building a page and using Video as background, I don't want the controls bar to show. 
![image](https://user-images.githubusercontent.com/2559543/128907295-cc727258-c3f4-43bd-b4f8-5b0d98335fd6.png)

When I edit the html and switch back to editor, it add back controls=true property. My question is if there is a way I can disable this behavior ?

**Comment by SystemChanger** [comment]
@zt1983811 Sorry, I have misunderstood you.
If you are sure that this is the result of ```_setTagAttrs(element)`` function (you can test this using debugger)  maybe we can override this function (like in example I pointed out in my first answer)?

**Comment by SystemChanger** [comment]
@zt1983811 
I have tried to add video on the http://suneditor.com/sample/html/examples.html
![image](https://user-images.githubusercontent.com/9049617/128920641-43674266-3754-49b6-b144-0be9a782c465.png)
Video started playing immediately and there are no controls:
![image](https://user-images.githubusercontent.com/9049617/128920797-c37c159a-304b-4dfc-9020-f8476de02139.png)

**Comment by zt1983811** [comment]
Hi @SystemChanger 

I think you use iframe but I am using html editor to add video tag natively 
Could you try go html editor add following code
```
<div class="se-component se-video-container __se__float-none" contenteditable="false" style="width: 100%;">
  <figure style="width: 100%; height: 42.85%; padding-bottom: 42.85%; margin: 0px;">
    <video contenteditable="true" data-percentage="100%,42.85%" data-size="100%,42.85%" data-align="none" data-file-size="0" data-origin="100%,56.25%" src="https://drive.google.com/uc?export=download&amp;id=15AadCtUFryptW_MoWY2GoXVaGpTEf5hr" type="video/mp4" data-file-name="uc?export=download&amp;id=15AadCtUFryptW_MoWY2GoXVaGpTEf5hr" data-proportion="false" style="width: 100%; height: 100%" data-index="4"></video>
  </figure>
</div>
```

As you can see we don't have `controls=true` in the video tag
When you switch to Editor mode and switch back to Html view you will see the `control=true` added

My question is how to get it removed. I have videoTagAttrs, but this one only allow me permanently set  `control=false` but sometimes I may want it. Also to remove the controller I have to remove this property.

**Comment by SystemChanger** [comment]
@zt1983811 Aww... I tried adding video on my other device and get the same result as you (non-playing video, but with iframe).
Your example also resulted in "controls" tag appearing.

It looks like we have to modify the code if you want this tags to appear/disappear on certain actions.

**Comment by zt1983811** [comment]
@SystemChanger  Thanks for trying. I am not sure why you get iframe but I don't LOL. Did you just paste the HTML code in html mode? I did it in http://suneditor.com/sample/html/examples.html but I don't get iframe convert back. Check this out
![image](https://user-images.githubusercontent.com/2559543/128931144-12ac0f4a-e8e1-475e-9ff7-0bb280cea4bc.png)

then I switch to editor mode
![image](https://user-images.githubusercontent.com/2559543/128931178-319cef6c-6422-4d1a-b42f-12b348db01ab.png)

Then I go back
![image](https://user-images.githubusercontent.com/2559543/128931213-ad099e58-971a-4100-95aa-bd16c11e0d8b.png)


I don't really see iframe convert maybe because I didn't try to use editor mode to change video?

But you are right I guess we need to change the code to not force `controls=true` 
If I understand correctly it's just matter of remove this line of the code 
https://github.com/JiHong88/SunEditor/blob/6d4414ba476c843001da97e326c48c54cf60734a/src/plugins/dialog/video.js#L222
or add some condition to not force it.

If you want I can change the code in my local and report you if remove this line is working or not then we can wrap up a PR soon to fix it?

**Comment by SystemChanger** [comment]
@zt1983811 No, no, I got an iframe using the "video" button. But on different (windows) devices I am getting the different results: on my PC video is auto-playing and on laptop it is not.
I get the same result as you when I paste your code in html editor mode.

Dunno, can we just remove this line, lol. It is required to study the code in more detail to find the correct decision.

**Comment by SystemChanger** [comment]
@zt1983811 I have inspected the "toggleCodeView" function via debugger and ended on the same line you mentioned.
https://github.com/JiHong88/SunEditor/blob/6d4414ba476c843001da97e326c48c54cf60734a/src/plugins/dialog/video.js#L222
Removing this line fixed the problem for code-view mode (now it takes the "controls" attribute from the code-view), but I think that we need further testing how it will affect the other ways to add videos.
I have tested with the videos from the iframes, and it is working well.

**Comment by SystemChanger** [comment]
@zt1983811 I think that you can create a PR for this and if everything is ok, Ji Hong will apply it (In the end, this is your victory).
If not - we'll have to come up with something :)
It will take time for these changes to come to the release version, so I can recommend you to use your fork version or create a button that will add/remove tags to the videos. 
You can get the videos elements using ```YOUR_EDITOR_VARIABLE.core.context.video._infoList[YOUR_VIDEO_INDEX].element``` or ```YOUR_EDITOR_VARIABLE.core.context.element.wysiwyg.querySelectorAll('video')[YOUR_VIDEO_INDEX]``` and use ```setAttribute('controls', true)``` / ```removeAttribute('controls')``` on them.

I was just trying to help, got confused and have no privileges in this repository xD

**Comment by zt1983811** [comment]
Hi @SystemChanger : really appreciated your help and advice here. I have propose a PR above for remove default controls attribute. Also I will try your solution tomorrow in my code before the version get release and post back here if I got some code work around. Thanks so much

**Comment by SystemChanger** [comment]
@zt1983811 I have a better solution for you! Dunno why I have forgotten my first advice - just override the method after the editor initialization!
```Javascript
const { core } = YOUR_EDITOR_VARIABLE;
core.plugins.video._setTagAttrs = ((element) => {
  const attrs = core.options.videoTagAttrs;
  if (!attrs) return;

  for (const key in attrs) {
    if (!core.util.hasOwn(attrs, key)) continue;
    element.setAttribute(key, attrs[key]);
  }
});
```

**Comment by zt1983811** [comment]
@SystemChanger  
I think `_setTagAttrs` is not part of Plugin type
![image](https://user-images.githubusercontent.com/2559543/129077070-81b1814c-ed29-4193-a271-c73eafe8a0a1.png)

**Comment by SystemChanger** [comment]
@zt1983811 Yes, you're right, it is more like a 'private' method, but you can still access to it. This worked for me

**Comment by zt1983811** [comment]
@SystemChanger  I think it's because I am using Typescript instead of JS. I put  `// @ts-ignore` so that no TS check then it works. Thanks so much!

In fact, after few problem I met, I am wonder if we can create a button / option to force HTML code to save instead of always try to convert . Like that if user would like just write pure clean HTML code they can just save it without a lot of annoying override.  @SystemChanger  @JiHong88  ? Thanks in advance.

**Comment by JiHong88** [comment]
@zt1983811 HTML may not work properly in WYSIWYG mode without proper conversion.

**Comment by zt1983811** [comment]
@JiHong88  yes I agreed with your point but my perspective is to make an option to force it not convert so that user could decide to use it or not. If they choose to use it then they should know what they are doing, they still could upload images but they will know the WYSIWYG mode may not display their HTML page correctly. 

Why I am thinking of it, for example, I am using this editor to develop a CMS, for most of the time the user could be non-developer so that they maybe want WYSIWYG to fix for them. However, sometimes they maybe having problem to adjust the content position or having bugs, that will involved some developer help. And for developer, it maybe easy to just use pure html to solve the problem fast. They could just disable  WYSIWYG for one of the Post and use their html/css expertises to fix the problem. 

My Suggestion is make a switcher in this SunEidtor to enable/disable WYSIWYG conversion so that we leave user to decide either they would like to use it or not. 

Let me know if this's making sense or not. Thanks for your time and effort to creating this amazing tool for us.

**Comment by JiHong88** [comment]
@zt1983811 Sorry for the late reply.
You can redefine related methods.

It's easy to create a button that doesn't override HTML.
But the Script tag will not be available.
And HTML saved like this will not work properly in WYSIWIG mode.

```javascript
editorInstance.core._setCodeDataToEditor = function () { }.bind(editorInstance.core);
editorInstance.core.toggleCodeView = function () { }.bind(editorInstance.core);
```

```javascript
_setCodeDataToEditor: function () {
    const code_html = this._getCodeView();

    if (options.fullPage) {
        const parseDocument = this._parser.parseFromString(code_html, 'text/html');
        const headChildren = parseDocument.head.children;

        for (let i = 0, len = headChildren.length; i < len; i++) {
            if (/^script$/i.test(headChildren[i].tagName)) {
                parseDocument.head.removeChild(headChildren[i]);
                i--, len--;
            }
        }

        let headers = parseDocument.head.innerHTML;
        if (!parseDocument.head.querySelector('link[rel="stylesheet"]') || (this.options.height === 'auto' && !parseDocument.head.querySelector('style'))) {
            headers += util._setIframeCssTags(this.options);
        }

        this._wd.head.innerHTML = headers;
        this._wd.body.innerHTML = parseDocument.body.innerHTML

        const attrs = parseDocument.body.attributes;
        for (let i = 0, len = attrs.length; i < len; i++) {
            if (attrs[i].name === 'contenteditable') continue;
            this._wd.body.setAttribute(attrs[i].name, attrs[i].value);
        }
        if (!util.hasClass(this._wd.body, 'sun-editor-editable')) {
            const editableClasses = options._editableClass.split(' ');
            for (let i = 0; i < editableClasses.length; i++) {
                util.addClass(this._wd.body, options._editableClass[i]);
            }
        }
    } else {
        context.element.wysiwyg.innerHTML = code_html.length > 0 ? code_html : '<' + options.defaultTag + '><br></' + options.defaultTag + '>';
    }
},
```
```javascript
toggleCodeView: function () {
    const isCodeView = this._variable.isCodeView;
    this.controllersOff();
    util.setDisabledButtons(!isCodeView, this.codeViewDisabledButtons);

    if (isCodeView) {
        this._setCodeDataToEditor();
        context.element.wysiwygFrame.scrollTop = 0;
        context.element.code.style.display = 'none';
        context.element.wysiwygFrame.style.display = 'block';

        this._variable._codeOriginCssText = this._variable._codeOriginCssText.replace(/(\s?display(\s+)?:(\s+)?)[a-zA-Z]+(?=;)/, 'display: none');
        this._variable._wysiwygOriginCssText = this._variable._wysiwygOriginCssText.replace(/(\s?display(\s+)?:(\s+)?)[a-zA-Z]+(?=;)/, 'display: block');

        if (options.height === 'auto' && !options.codeMirrorEditor) context.element.code.style.height = '0px';
        
        this._variable.isCodeView = false;
        
        if (!this._variable.isFullScreen) {
            this._notHideToolbar = false;
            if (/balloon|balloon-always/i.test(options.mode)) {
                context.element._arrow.style.display = '';
                this._isInline = false;
                this._isBalloon = true;
                event._hideToolbar();    
            }
        }

        this.nativeFocus();
        util.removeClass(this._styleCommandMap.codeView, 'active');

        // history stack
        // this.history.push(false);
        this.history._resetCachingButton();
    } else {
        this._setEditorDataToCodeView();
        this._variable._codeOriginCssText = this._variable._codeOriginCssText.replace(/(\s?display(\s+)?:(\s+)?)[a-zA-Z]+(?=;)/, 'display: block');
        this._variable._wysiwygOriginCssText = this._variable._wysiwygOriginCssText.replace(/(\s?display(\s+)?:(\s+)?)[a-zA-Z]+(?=;)/, 'display: none');

        if (options.height === 'auto' && !options.codeMirrorEditor) context.element.code.style.height = context.element.code.scrollHeight > 0 ? (context.element.code.scrollHeight + 'px') : 'auto';
        if (options.codeMirrorEditor) options.codeMirrorEditor.refresh();
        
        this._variable.isCodeView = true;

        if (!this._variable.isFullScreen) {
            this._notHideToolbar = true;
            if (this._isBalloon) {
                context.element._arrow.style.display = 'none';
                context.element.toolbar.style.left = '';
                this._isInline = true;
                this._isBalloon = false;
                event._showToolbarInline();
            }
        }
        
        this._variable._range = null;
        context.element.code.focus();
        util.addClass(this._styleCommandMap.codeView, 'active');
    }

    this._checkPlaceholder();
    if (this.isReadOnly) util.setDisabledButtons(true, this.resizingDisabledButtons);

    // user event
    if (typeof functions.toggleCodeView === 'function') functions.toggleCodeView(this._variable.isCodeView, this);
},
```

**Comment by JiHong88** [comment]
Images, videos, etc. sometimes change HTML even with actions such as clicking and moving the cursor.
Adding this feature will take a little more thought.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
