### ISSUE TITLE
How to reset attributes on enter (new line)?

### ISSUE THREAD

**Issue by Braweria** [JiHong88/SunEditor#848]
Related: https://github.com/JiHong88/SunEditor/issues/5

In my editor, each paragraph and heading is given a `data-id` attribute, but when I press enter, the next element gets the same attribute, instead of starting out empty. I can't generate new IDs for new paragraphs, because they will get the previous' ID.

So my question is: How to have an element with no attributes when the user presses <kbd>Enter</kbd> ?

In the documentation I wasn't able to find anything related to that.

## Version
```json
    "suneditor": "^2.41.3",
    "suneditor-react": "^3.3.0"
```

## Additional context
![image](https://user-images.githubusercontent.com/62669899/128711659-221bb527-90a9-49e9-87df-75443328f3fa.png)

My defaultTag is also set to `p`.

**Comment by Braweria** [comment]
I have created a Sandbox to show what I mean:  
https://codesandbox.io/s/suneditor-issue-3bf68?file=/src/App.js

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
