### ISSUE TITLE
Undo/redo is not working properly

### ISSUE THREAD

**Issue by juliocd** [JiHong88/SunEditor#85]
Undo/Redo is not worwing properly when you do a lots modifications in the text field.

**Comment by JiHong88** [comment]
Hi, @juliocd 

Thank you for your feedback. : )

I will fix it and add to the next version.

**Comment by JiHong88** [comment]
Hi, @juliocd 

Updated in [v2.13.0](https://github.com/JiHong88/SunEditor/releases/tag/2.13.0)

Thank you : )
