### ISSUE TITLE
Action affect line under selected

### ISSUE THREAD

**Issue by Max0nyshchenko** [JiHong88/SunEditor#852]
**Describe the bug**
When you select a line with a triple mouse click and press ctrl-i, for example, it selects and modifies the line under it too.

**To Reproduce**
1. Go to http://suneditor.com/sample/index.html
2. Triple click on the line "The SunEditor is based..."
3. Press ctrl-i or ctrl-b
4. See line "SunEditor is a lightweight..." modified too

**Expected behavior**
To modify only the selected line

**Desktop (please complete the following information):**
 - OS: MacOS, Ubuntu
 - Browser : Chrome
 - Version: 92.0.4515.107 (Official Build) (64-bit)

**Comment by JiHong88** [comment]
@Max0nyshchenko I already know of this issue.
But I haven't found a solution yet. :(
I'll notify you know when it's resolved.

**Comment by Max0nyshchenko** [comment]
@JiHong88 Thank you for your response, I was trying to fix it, but all in vain after 5hours of work. If I find time I'll get back to it.

**Comment by Max0nyshchenko** [comment]
@matteocollina So I see you didnt push fixes? I didn't have time to work on it since

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
