### ISSUE TITLE
FullScreen CodeView unscrollable when using suneditor option "height: 'auto'"

### ISSUE THREAD

**Issue by SystemChanger** [JiHong88/SunEditor#853]
**Describe the bug**
When using **codeView** in **fullScreen** mode and suneditor created with ```height: 'auto'``` in `SunEditorOptions` object scrollbar is totally broken and content can't be scrolled.

**To Reproduce**
1. Go to http://suneditor.com/sample/html/examples.html#groups
2. Scroll down to 'Char count, Button groups, toolbar container' sub-title (#anchor to it added in url above)
3. Click 'Full screen' button
4. Add lines to text-area so the vertical scrollbar appear
5. Click 'Code view' button
6. See the totally broken and unusable vertical scrollbar.

**Expected behavior**
Totally serviceable and usable vertical scrollbar and scrolling :)

**Screenshots**
![image](https://user-images.githubusercontent.com/9049617/129466550-7a1760e9-a6c6-45c4-8452-25f141087edd.png)
![image](https://user-images.githubusercontent.com/9049617/129466571-e4167694-bdee-4cdc-8730-4699c8b140ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: latest

**Additional context**
It looks like the problem is in this line:
https://github.com/JiHong88/SunEditor/blob/00b9eff22be0f7385e8588218230c79b2d4c0df1/src/lib/core.js#L4277

It sets the text-area element height to be higher than the parent's.
Looks like we should use some other height there. Why can't we just not change it and leave it at "100%"?

**Possible solutions**
1) Use the appropriate height (where can we get it?)
2) Provide the correct value in `context.element.code.scrollHeight` (where can we get it?)
3) Do we really need this line? (lol)
4) Add `!fullscreen` condition.
I tested this way, and it works for this issue, but I am not sure if this is the correct solution in general, so without pull-request right now.
```Javascript
 if (options.height === 'auto' && !options.codeMirrorEditor && !this._variable.isFullScreen) context.element.code.style.height = context.element.code.scrollHeight > 0 ? (context.element.code.scrollHeight + 'px') : 'auto';
 ```
 P.S. this line is too complicated.
 
 Maybe you should also check other places that use this height.

**Comment by mvoorberg** [comment]
This issue applies to more than just the full-screen code view.  The textarea containing the code view has overflow-hidden style applied to it directly. Removing overflow hidden corrects the behaviour. 

Add the following to your page CSS
```    
// Sidestep a bug in the editor code view, where it has no scrollbars!
.sun-editor .se-wrapper .se-wrapper-code {  
  overflow: auto !important;
}
```

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
