### ISSUE TITLE
Custom Toolbar

### ISSUE THREAD

**Issue by TheDarkStrix** [JiHong88/SunEditor#854]
Hey Guys,

I wanted to know, if its possible to create a custom toolbar, outside the component and hook on to the editor using refs ?
If it possible example of this implementation ?
@JiHong88

Thanks

**Comment by sdraper69** [comment]
can you not set the container in the options?

![image](https://user-images.githubusercontent.com/25779335/129614813-cf61be79-d967-46c0-9349-df5dd48f75b6.png)
