### ISSUE TITLE
Question - Reacting to font change so I can load fonts on the fly

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/suneditor#858]
I want to give the users a big list of fonts (in my case google fonts) however I don't want to have to load them all on the page beforehand - especially when someone is just viewing the content of the editor (e.g. not actually editing it).

What is the recommended way to react to the font change?

**Comment by JiHong88** [comment]
I will add events of plugins in version 3.0.0.
You will be able to add it dynamically when you change the font.

**Comment by sdraper69** [comment]
That's great, your work on this is absolutely fantastic.

As version 3 will be a little way off, is there any recommendations for what i can do for now?

**Comment by JiHong88** [comment]
You can redefine plugin's method.
```
editorInstance.onload = (core) => {
  core.plugins.font.pickup = ()=>{..}
}
```
https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/font.js#L113

**Comment by JiHong88** [comment]
`const value = e.target.getAttribute('data-value');`
"value" is font-family value.
Please refer this code.
https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/font.js#L113
