### ISSUE TITLE
import/export 모듈 미사용 문의

### ISSUE THREAD

**Issue by Leejoohyoung** [JiHong88/SunEditor#86]
안녕하세요.

SUNEDITOR 라이브러리 사용 중 문의 사항이 있어서 이슈 등록합니다.

라이브러리 기능 사용 중, 툴바에 커스텀 버튼을 만들고자 할 때 plugins을 import 해서 쓰도록 가이드가 나와있습니다. 

라이브러리 사용 개발 환경 상, 구현 해 놓으신 import/export modules 패턴을 사용하기 제한되는데 혹시 각 import module이 모두 하나의 파일에 통합된 상태로 사용하는 방법 혹은 module을 사용하지 않고 해당 기능을 사용할 수 있는 방법 가이드 문의 드립니다.

감사합니다.

**Comment by JiHong88** [comment]
안녕하세요~

혹시 import/export modules 패턴 사용이 제한된다는 말이..

전체 개발환경에서 import/export modules 패턴을 사용하기 제한된다는 거라면

"./dist/suneditor.min.js" 파일을 로드하면 window.SUNEDITOR 오브젝트에 plugin 이 모두 통합된 객체가 생성됩니다.

이게 아니고, plugins 만을 import 하기가 제한된다는 얘기면

똑같이 ./dist/suneditor.min.js 을 import 했을때 plugin 이 모두 통합된 객체가 로드되어야 하나

현재는 export 되고 있지 않습니다.

두번째 문제라면 이 부분은 바로 수정해서 업로드 해드리겠습니다.

감사합니다 : )

**Comment by Leejoohyoung** [comment]
답변 감사드립니다.

제가 문의 드린 사항은 말씀하신 내용 중 첫 번째 내용입니다. suneditor.min.js 파일을 로드하면, window.SUNEDITOR 객체를 통해 plugin 기능도 사용 가능하다는 말씀이신가요?
홈페이지의 submenu plugin도 사용 가능한 것인지 확인 부탁 드립니다.

감사합니다.

**Comment by JiHong88** [comment]
네 모든 플러그인이 포함된 객체라, 기능 다 사용가능합니다.

[include](https://github.com/JiHong88/SunEditor/blob/master/README.md#getting-started) 참고해주시면 됩니다.
 
submenu plugin 이 [customPlugin](http://suneditor.com/sample/html/customPlugins.html)을 얘기 하는거라면 홈페이지 안내대로 구현시 똑같이 사용가능합니다.

홈페이지에 빠져있는 부분이 있는데 구현한 custom plugin 을 plugins 속성에 포함시켜주고

버튼리스트에 추가해야 합니다.
`const editor = SUNEDITOR.create({
    plugins: [custom_plugin_submenu]...`

감사합니다.

**Comment by Leejoohyoung** [comment]
customPlugin의 경우도 import/export 없이 사용 가능하다고 하셨는데, 홈페이지 예제의 경우는 import/export 사용 예제인 것 같습니다. SUNEDITOR.create 할 때 plugins: [], buttonList:[]에 각각 추가 할 때 plugins에 들어갈 custom menu명은 따로 어느 부분에서 정의해야 하는지 확인 부탁 드립니다.

**Comment by JiHong88** [comment]
export 로 object 하나만 내보내기 때문에
똑같이 object 객체에 넣어주시면 됩니다.
```js
const customPluginObject = {
    // 플러그인의 이름
    name: 'custom_plugin_submenu',

    // 플러그인 최초 호출시 실행
    // HTML, event 등 추가
    // arguments - (core : core object, targetElement : clicked button element)
    add: function (core, targetElement) {
        // core 의 context에 캐싱되어야 하는 정보들을 넣어 사용합니다.
        const context = core.context;
        context.custom = {
            textElement: null
        };

        // HTML 랜더링
        let listDiv = eval(this.setSubmenu(core.lang));

        // Input 태그 캐싱
        context.custom.textElement = listDiv.getElementsByTagName('INPUT')[0];

        // 이벤트 등록시 "core" object 를 항상 바인딩 해줘야 합니다.
        /** add event listeners */
        listDiv.getElementsByTagName('BUTTON')[0].addEventListener('click', this.onClick.bind(core));

        // HTML 추가
        targetElement.parentNode.appendChild(listDiv);
    },

    setSubmenu: function () {
        const listDiv = document.createElement('DIV');

        listDiv.className = 'sun-editor-submenu layer_editor layer_align';
        listDiv.style.display = 'none';
        listDiv.innerHTML = '' +
            '<div class="inner_layer">' +
            '   <ul class="list_editor">' +
            '       <li><input type="text" placeholder="insert text" style="width: 100%; border: 1px solid #CCC;" /></li>' +
            '       <li><button type="button" class="btn_editor" title="Append text">Append text</button></li>' +
            '   </ul>' +
            '</div>';

        return listDiv;
    },

    onClick: function () {
        // Get Input value
        const value = document.createTextNode(this.context.custom.textElement.value);

        // insert
        this.insertNode(value);

        // focus
        this.focus();
    }
};
```

그리고 object를 plugins 에 포함시켜 줍니다.
두번째로 버튼 리스트에 아래와 같이 추가해 줍니다.
```js
SUNEDITOR.create(document.getElementById('ex_submenu'), {
    plugins: [customPluginObject],
    buttonList: [
        ['undo', 'redo'],
        [
            // 이 object 형식으로 커스텀 버튼을 추가합니다.
            {
                // 정의한 플러그인의 name 속성과 같아야 합니다.
                name: 'custom_plugin_submenu', 
                // name 속성과 같아야 합니다.
                dataCommand: 'custom_plugin_submenu',
                // 버튼의 클래스 ( "btn_editor"클래스가 등록되면 기본 버튼 클릭 CSS가 적용됩니다.) 
                buttonClass:'btn_editor', 
                // 노출되는 버튼의 타이틀 입니다.
                title:'Custom plugin of the submenu', 
                // 플러그인의 종류 입니다. submenu, dialog, command
                dataDisplay:'submenu',
                // dialog 플러그인 일때만 적용
                displayOption:'',
                // 버튼안에 들어갈 HTML 입니다. icon 이 들어가면 됩니다.
                innerHTML:'<div class="icon-map-pin"></div>'
            }
        ]
    ]
});
```

홈페이지의 예제와 아주 조금 다릅니다.

감사합니다 : )

**Comment by Leejoohyoung** [comment]
답변 감사드립니다.

추가 문의 사항 있으면 이슈로 문의 드리겠습니다.

이 이슈는 종료해주셔도 될 것 같습니다.

감사합니다.

**Comment by JiHong88** [comment]
커스텀 플러그인 생성시에 버튼 아이콘이 안보이는 버그가 있었습니다.

[v2.12.4](https://github.com/JiHong88/SunEditor/releases/tag/2.12.4) 버전에서 수정되었으니 홈페이지와 같이 참고해주세요.

**Comment by Leejoohyoung** [comment]
네, 업데이트 후 사용하겠습니다.

감사합니다.
