### ISSUE TITLE
Iframe in plugin

### ISSUE THREAD

**Issue by pazicb** [JiHong88/SunEditor#862]
Hello,
can you help me please?
I have a plugin, plugintest that calls iframe
```
setSubmenu: function (core) {
        const listDiv = core.util.createElement('DIV');
        listDiv.className = 'se-list-layer';
        listDiv.innerHTML = '' +
            '<div style="width: 500px; height: 500px;">' +
            '<iframe id="myFrame" src="fileManager.html></iframe>';
        '</div>';
        return listDiv;
    }
```
In iframe I need a link that calls onclick from the plugin.
Unfortunately, when I call parent.plugintest.onclick from iframe.

In Onclick not working
this.submenuOff();

I get this mistake
Uncaught TypeError: this.submenuOff is not a function

**Comment by JiHong88** [comment]
You will probably have to access it from the parent window. 

```
const editor = sunedior.create();
editor.core.submenuOff();
```
