### ISSUE TITLE
The "show blocks" feature does not work if the "fullPage" parameter is set to true

### ISSUE THREAD

**Issue by matteocollina** [JiHong88/SunEditor#863]
suneditor: v2.41.3
suneditor-react: v3.3.0

![Schermata 2021-08-26 alle 09 01 58](https://user-images.githubusercontent.com/8715726/130916627-ab8be44b-90db-4b4b-b400-1b34f9f8b70c.png)

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
