### ISSUE TITLE
Support for 1 toolbar multiple editors

### ISSUE THREAD

**Issue by TheDarkStrix** [JiHong88/SunEditor#871]
I am making an app (migrating from quilljs to sun as its causing a lot of issues)

What i want to do exactly

         Toolbar                    
```
 Editor no.1
```
```                          
 Editor no.2
```
```                          
Editor no.3
```
```                          
 Editor no.4
```
```                         
 Editor no.5
```                         
.
.
.
Want to use a common toolbar with all these editors, should refresh on focusing on any editor having context of that editor. I was able to do the same in Quilljs using the toolbarContainer property and stick it into a stateful variable. can something similar be done with this?

Better Example using quilljs - https://codesandbox.io/s/hungry-pine-o8oh9?file=/src/App.js

**Comment by JiHong88** [comment]
@TheDarkStrix I'll add this feature in the "3.0.0" version.
It will probably take some time.
