### ISSUE TITLE
Remove Edit Button on Image toolbar

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#872]
I have made my own asset browser/gallery for the user to insert images, videos etc.

Due to this, I would like the user not to have an edit button when clicking on an image, as that bypasses my own gallery. I would like all the other buttons

![image](https://user-images.githubusercontent.com/25779335/132730896-1f9bc61a-6c1e-4b91-a5ff-9a39f1cc84fa.png)

Is it possible to remove that?

Alternately I could live with disabling URL and file inputs in the edit box that appears, however it looks as though you have to have at least one of them.

**Comment by JiHong88** [comment]
@sdraper69 Sorry, for the late answer.
You can prevent it with the code below.

```javascript
editorInstance.showController = (currentControllerName, controllerArray, core) => {
    if (currentControllerName === "image") {
        controllerArray[1].querySelector('[data-command="update"]').style.display = "none";
    }
}
```

**Comment by sdraper69** [comment]
Great thanks! Solved
