### ISSUE TITLE
Copy and paste image

### ISSUE THREAD

**Issue by anhto87** [JiHong88/SunEditor#879]
**Describe the bug**

**To Reproduce**
1. Go to copy a content has been included images
2. Click on editor and paste
3. Go inspect element of image
![image](https://user-images.githubusercontent.com/13975102/134707298-b3f8facd-8b7d-4271-844f-e9f64e1ef430.png)

  |  
-- | --
 
As you see the image after pasted was embed to another tags img, also the size width, height is not like original content. Can you check that?

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
