### ISSUE TITLE
Bug resizing left, center, or right aligned videos.

### ISSUE THREAD

**Issue by jsmil112** [JiHong88/SunEditor#880]
**Describe the bug**
There is unexpected behaviour when is video is aligned left, center, or right (not basic alignment) and then resized. Resizing does not have to occur directly after being aligned. It happens anytime a left, center, or right aligned video is resized. 

Left and Right aligned videos will collapse to a thin line and center aligned videos will align left. By pressing the same alignment button again on the video it will return to the correct position and newly resized size. 

What I believe to be causing the issue is that the <figure> tag within the video div is losing its width after resizing. By resizing the width is removed and the bug occurs, then by pressing again align in the same direction the width is added and the video is shown correctly. 

**To Reproduce**
1. Go to http://suneditor.com/sample/html/examples.html
2. Add a video in any of the examples.
3. Align the video left, right, or center. 
3. Resize the video
4. Video is either collapsed for left and right aligned videos, or left aligned for centered videos. 

**Expected behavior**
Resizing a left, center, or right aligned video will resize the video and maintain its alignment. 

**Screenshots**
![Screen Shot 2021-09-28 at 20 31 55](https://user-images.githubusercontent.com/47541670/135179325-76b42060-bcee-45e2-8287-16c9985b47bb.png)
Here is what happens when a right aligned video is resized.

**Additional context**
This has been reproduced in local environments as well as on the http://suneditor.com/sample/html/examples.html website. And also on both PC and Mac computers.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
