### ISSUE TITLE
Option for resizingBar to be displayed but fixed at bottom of DIV?

### ISSUE THREAD

**Issue by 500Foods** [JiHong88/SunEditor#883]
**Is your feature request related to a problem? Please describe.**
I've got a page with SunEditor where I want it to fill the area of a div, with the toolbar fixed at the very top and ideally the resizing bar fixed at the bottom so I can see the showPathLabel and charCounterLabel, but I don't want the resizing bar to be used for resizing.  I'd also like the SunEditor to fill the div completely and show scrollbars only in the editor portion and scroll only the editor portion, not the toolbar or the resizing bar.

**Describe the solution you'd like**
An option for 'resizingBarPosition': 'bottom' or something like that, or perhaps set it up like the toolbarContainer in its own div?

**Describe alternatives you've considered**
I've made good use of the toolbarContainer to put that in a div and the editor in a separate div, and used flex/flex-direction:column to get the toolbar and the editor to flow as desired, even resizing the toolbar as the dimensions of the overall div that the editor is in changes.  All works great! But the resizingBar needs to be enabled to see the PathLabel and the CounterLabel, and it scrolls off the bottom of the page when the content of the editor is longer than the visible area or appears higher up the page when the content is short.

**Additional context**
Happy to supply more context if this isn't already clear.

**Comment by JiHong88** [comment]
I'll add `resizingEnable` and `resizingBarContainer` at the next version.

**Comment by 500Foods** [comment]
Thanks!

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by 500Foods** [comment]
Works great, thanks!
