### ISSUE TITLE
How to refresh the font list dynamically? Solved

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#885]
My list of available fonts can change dynamically - the list is the user's favourites, so they can add and remove them from it.

What is the best method for updating the font list shown in the editor? I tried just setting

editor..core.options.font = [new array];

but the actual editor didn't update.

I would appreciate any guidance

**Comment by JiHong88** [comment]
```javascript
editorInstance.setOptions({
  font: [new array]
})
```

**Comment by sdraper69** [comment]
cheers, sorry i missed that
