### ISSUE TITLE
When enable imageMultipleFile, only last image is inserted

### ISSUE THREAD

**Issue by rexpan** [JiHong88/SunEditor#890]
**Describe the bug**
When enable imageMultipleFile, SunEditor will only insert last image.
The previous image `<figure>` will be removed, leaving an empty `<div class="se-component se-image-container __se__float-none">`.
Because when call `insertComponent()` for 2nd image, `this.removeNode();` will removed the `<figure>` of the first inserted image.

**To Reproduce**
1. Go to http://suneditor.com/sample/html/options.html and enable `imageMultipleFile` options
2. Try to insert 2 or more images
3. the last image is inserted, but the previous images only empty dev remain.

**Expected behavior**
Multiple images inserted sucessfully.

**Screenshots**

https://user-images.githubusercontent.com/313189/140924796-25edd464-0040-4213-b92e-f03eb5e364f6.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 98

**Comment by JiHong88** [comment]
I'm aware of this issue.
It will be fixed in the next version.
I will update it as soon as possible.
