### ISSUE TITLE
Right click does not update the position until after context menu closes

### ISSUE THREAD

**Issue by tr12345** [JiHong88/SunEditor#891]
**Describe the bug**
If I right click and choose paste the clipboard is pasted to the last location the cursor was at before right clicking instead of where the right click was performed.

**To Reproduce**
1. Type in a random sentence into the editor.
2. Copy the first word to the clipboard
3. Left click at the beginning of the sentence to set the cursor position to the beginning
4. Right click at the end of the sentence and before you choose paste it will look like the cursor has been updated but once you choose paste you will see the contents paste to the previous cursor location

**Expected behavior**
Cursor position is updated on right click before the context menu displays

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome / Internet Explorer
 - Version 95.0.4638.69 / 11.719.18362.0

**Comment by Saeeed-B** [comment]
@JiHong88 We look forward to closing this issue. For version 2.42 to be released. Thankful

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by tr12345** [comment]
This issues appears to still be happening.  Would someone be able to reopen the issue?
