### ISSUE TITLE
Remove trailing whitespace from selected creating link

### ISSUE THREAD

**Issue by Backdraft2100** [JiHong88/SunEditor#894]
**What's going on**
When editors select a word using double click the word and any trailing spaces are selected.
When converting the selected text into a hyperlink using the link action the full text including white spaces are moved into the “Text to display” portion of the link editor.

**What is requested**
It would be more productive if the trailing spaces automatically trimmed when created from a selected text portion.
Now the links appear a bit awkward if editors forget to remove the trailing white space manually.
_image example:_
![image](https://user-images.githubusercontent.com/26526193/141976809-6cdbe678-7fb7-4729-b083-d3fd5cfaaf1c.png)

**Additional context**
I believe the trimming should only occur when the “Text to display” is automatically populated from selected text.
If editors manually enter data in the “Text to display” field any whitespace should be preserved.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
