### ISSUE TITLE
How can I programatically insert a video or audio?

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#897]
I want my user to be able to press one button and a video will get inserted into the editor, and then press another button and an audio URL will get inserted. (both will already know the URL to the video/audio)

What is the best way to go about doing this? There doesn't appear to be an insertAudio or insertVideo function

**Comment by JiHong88** [comment]
You can call a plugin method.

```javascript
// video
editorInstance.core.plugins.video.submitAction.call(editorInstance.core, files);
// audio
editorInstance.core.plugins.audio.submitAction.call(editorInstance.core, files);
```

**Comment by sdraper69** [comment]
Thanks for getting back to me. Can you point me in the direction of what the "files" arguments is? All I have is a URL

I thought one of the following may work but clearly I am missing something..

editorInstance.core.plugins.video.submitAction.call(editorInstance.core, url);
editorInstance.core.plugins.video.submitAction.call(editorInstance.core, {videoUploadUrl:url});

**Comment by JiHong88** [comment]
It's complicated, but you can do it this way: 

Current version
```javascript
//image
editorInstance.core.context.image._v_src._linkValue = "url"
editorInstance.core.plugins.image.onRender_imgUrl.call(ss.core);
// video
editorInstance.core.context.video._linkValue = "url"
editorInstance.core.plugins.video.setup_url.call(editorInstance.core);
// audio
editorInstance.core.plugins.audio.setupUrl.call(editorInstance.core, "url");
```

After the v2.42.0 update.
```javascript
//image
editorInstance.core.plugins.image.onRender_imgUrl.call(ss.core, "url");
// video
editorInstance.core.plugins.video.setup_url.call(editorInstance.core, "url");
// audio
editorInstance.core.plugins.audio.setupUrl.call(editorInstance.core, "url");
```

**Comment by sdraper69** [comment]
Great thanks that did the trick. To insert images I have been using 

`editorInstance.insertHTML("<img data-size='100%' data-align='center' data-percentage='100,' style='height:100%' src='" + src+ "'/>"`

Is there any reason not to do it that way and instead do the method you mention above? (it seems to work fine for me)

Thanks for all your help this is a great tool

**Comment by JiHong88** [comment]
Of course, you can also use the "InsertHTML" method.
