### ISSUE TITLE
Can I make links always open in a new window?

### ISSUE THREAD

**Issue by Poroot4ik** [JiHong88/SunEditor#898]
Hi!
Is it possible to make all created links in the editor target = "_blank", or so that the checkbox as in the screenshot is always checked?
![Screenshot_84](https://user-images.githubusercontent.com/50859491/144064073-aba5452a-be1b-4f2e-b4e8-e591edb79c7c.png)

**Comment by JiHong88** [comment]
You can use "`linkTargetNewWindow: true`" option after the version update.
I'll notify you after the version update.

**Comment by Poroot4ik** [comment]
Tanks you!

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
