### ISSUE TITLE
IE 환경에서 복/붙이 잘 안되는 현상이 있어서 제보드립니다.

### ISSUE THREAD

**Issue by kimshinelove** [JiHong88/SunEditor#899]
**Describe the bug**
만들어 주신 에디터 잘 사용하고 있는데
전체선택 -> 붙여넣기 가 잘 안되는 현상이 있어서 제보드립니다.
(특정 상황에서 붙여넣기가 잘 안됨)

구현상 문제가 있는지 확인해봤는데 suneditor 예제에서도 동일한 현상이 발생하네요.

**To Reproduce**
1. http://suneditor.com/sample/index.html 진입 
2. 샘플로 있는 내용 Ctrl + A 로 전체선택
3. Ctrl + X 로 잘라내기
4. 그대로 Ctrl + V 로 붙여넣기

**Expected behavior**
전체선택 후 잘라내기 했으니 그대로 붙여넣으면 붙어야 할 것 같아요.
참고로 한칸 띄어쓰기 후 붙여넣기 하면 정상적으로 붙습니다.(추측으로는 완전 비어있을 경우 붙여넣기가 잘 안되는 듯 하네요.)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE 11
 - suneditor 2.40

**Additional context**
추가적으로 아래 문자열을 복사해서 전부 지운후 붙여넣기 해도 안붙네요.  (태그는 변하는 거 보면 내부에서html 구조가 꼬이는 것 같습니다.)

예시문장)
An angry-red face with a black bar and white grawlixes covering its mouth, indicating it's swearing or being vulgar. ... representing swear words or obscenities. Often used to convey an outburst of anger, frustration, or rage. Most platforms feature

구조를 살펴보니 아래 font-family 에 내용이 들어가면서 dom 이 깨진 것 같아보이네요.
![paste-error](https://user-images.githubusercontent.com/1567151/144219248-2c2c17ae-6a2a-4163-b741-aa24b3fb7664.PNG)

**Comment by Saeeed-B** [comment]
@JiHong88 We look forward to closing this issue. For version 2.42 to be released. Thankful

**Comment by JiHong88** [comment]
@kimshinelove IE는 항상 문제가 생기네요..ㅋㅋ
버전 업데이트 후에 알려드리겠습니다.
