### ISSUE TITLE
Empty folder for gallery

### ISSUE THREAD

**Issue by capetrel** [JiHong88/SunEditor#900]
Hi, i had implement the galley feature and it works well. But if the destination folder for the gallery is empty, there's an Uncaught error in console [SUNEDITOR.fileBRowser.drawlist.fail]. i don't find a way in core, utils or oher to catch this error or manage a way to display a message in the blank modale
![uncaught-error-empty-gallery](https://user-images.githubusercontent.com/18441194/145183743-41f3e1a5-6943-4c0f-98d2-8dac4b46094e.png)

**Comment by JiHong88** [comment]
Even for an empty value, respnse must be of the form: 
```javascript
{
  "result": []
}
```

I'll update the null message.
```javascript
{
  "result": [] or "",
  "nullMessage" : Text string or HTML string
}
```

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by LEMOYNE-EMMANUEL** [comment]
Good morning, my name is "Manu" i'm French.
I am testing suneditor javascript.
I'm not in CMS (presta or Wordpress).
I can't get the image gallery to work, I have a blank page. I created a "gallery" directory at the same level as the .html file, but it doesn't work.
What must be done to make the photo gallery work?
THANKS :
PS: This project is great!
i have this message :
Mixed Content: The page at 'https://xxxxx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxx'. This request has been blocked; the content must be served over HTTPS.
Why ?
Thank's
