### ISSUE TITLE
Links with pictures not showing, and formatting it wrong

### ISSUE THREAD

**Issue by changyeamoon** [JiHong88/SunEditor#902]
**Describe the bug**
I have a pre-made html template but it wont show on the Editor correctly

**To Reproduce**
The data is already laid out in the codesandbox

**Expected behavior**
Formatting and pictures should show

<img width="700" alt="Screen Shot 2021-12-09 at 3 44 18 PM" src="https://user-images.githubusercontent.com/30943398/145472893-51b31669-d952-421a-bc84-28f04c6babfc.png">

**CodeSandbox**
https://codesandbox.io/s/suneditor-react-table-links-2p4yz?file=/src/App.tsx

**Comment by JiHong88** [comment]
It seems image and text colors are white.
Give the color at the table.
<img width="593" alt="스크린샷 2021-12-11 오후 1 21 12" src="https://user-images.githubusercontent.com/13191953/145663553-04342692-de4d-45a1-8e21-9a69f2e383c7.png">

**Comment by changyeamoon** [comment]
@JiHong88 AH okay, what about the formatting?

**Comment by JiHong88** [comment]
Make your own by editing the CSS and HTML.

**Comment by changyeamoon** [comment]
@JiHong88 It looks like the RTE doesn't like the `bgcolor` `table` attribute. Is there a way we can make it work?

**Comment by JiHong88** [comment]
@changyeamoon Sorry, I don't understand well.
Currently, not supported "bgcolor" button.
