### ISSUE TITLE
How can I get the template selection event?

### ISSUE THREAD

**Issue by roman7722** [JiHong88/SunEditor#903]
I want to know which template is currently selected.

## Version
2.41.3

**Comment by JiHong88** [comment]
`editorInstance.context.template.selectedIndex; // selected template index`
I'll notify you after version update.

**Comment by roman7722** [comment]
> `editorInstance.context.template.selectedIndex; // selected template index` I'll notify you after version update.

Thank you very much, I'll be waiting for the update! Your editor is the best! )

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
