### ISSUE TITLE
Proposal: let image gallery show thumbnail images

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#908]
It would be great if image gallery API could support URLs for two variants of an image in gallery: 
- url to a thumbnail resolution to be used for display in the image gallery and, 
- url to a full resolution to be used for picked/selected image. 
The benefit is that this would reduce traffic a lot when many images are listed in gallery.

**Comment by JiHong88** [comment]
The [2.42.0](https://github.com/JiHong88/SunEditor/releases/tag/2.42.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
