### ISSUE TITLE
Working inside tables

### ISSUE THREAD

**Issue by DeZZar** [JiHong88/SunEditor#91]
Hi,

Great plugin - especially like that it is plan JS without dependencies - great work!

I just have one item to raise - and although the undo button can be used in the following situation I think it is worth considering a change to the code to cater for this. When a user has the cursor placed inside a table cell without any content and the backspace key is pressed the cell is removed from the HTML and although the border styling sometimes remains making it look as though a cell exists the user cannot place the cursor back inside the cell or restore the cell without clicking undo. If the user then starts to add rows or columns in an attempt to fix the issue it only gets worse and eventually the table has to be deleted. This doesnt occur when the cell contains text. Perhaps trap the keystroke and check if the cursor is inside an empty cell to avoid accidental removal of cells?

This is of course in the context of a user who is not familiar with HTML and cannot inspect and correct the issue themselves (a large part of the target end user audience I assume).

By way of an enhancement it would also be good to be able to fix the width of the table or columns so that dont jump around as you start to add text to them. Perhaps via an additional couple of buttons in the table pop-up menu?

**Comment by JiHong88** [comment]
Hi @DeZZar ,

Thank you for your feedback!

Fixed in [v2.14.0](https://github.com/JiHong88/SunEditor/releases/tag/2.14.0) : )

**Comment by DeZZar** [comment]
@JiHong88 - fantastic - works as expected!
