### ISSUE TITLE
What could be stopping the toolbar from displaying the font and format?

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#910]
Can you tell me where/how the toolbar updates to show the font size and font of the current selection?

As you can see in the below, other options such as bold are working, it's just the font size and font itself that dont update in teh toolbar. Interestingly the font does get highlighted in the drop down, just not in the main toolbar

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/25779335/147882811-f189ab43-a206-43b9-9c67-4a2082d99c34.gif)

for the both these functions I am doing my own custom code when the font or font size is changed, so I'm sure it is me messing it up, but if you could point me to what could be breaking it, and how it updates the toolbar in the first place I would appricate it.

If it helps here's my code to change font size...

```
 editor.core.plugins.fontSize.pickup = function (e) {
            if (!/^BUTTON$/i.test(e.target.tagName)) return false;

            e.preventDefault();
            e.stopPropagation();

            const value = thisObj.editorGetFontSizeFromValue(e.target.getAttribute('data-value'));

            if (value) {
                const newNode = this.util.createElement('SPAN');
                newNode.style.fontSize = value;
                this.nodeChange(newNode, ['font-size'], null, null);
            } else {
                this.nodeChange(null, ['font-size'], ['span'], true);
            }

            this.submenuOff();
        }

```

**Comment by JiHong88** [comment]
This issue doesn't seem to have anything to do with custom methods.
Would you like to update the version?
Or is there another method you have modified?

**Comment by sdraper69** [comment]
Unfortunately I just tried with the latest and still get the same behavior as well as the font size function shown above, i also have the following:

```
  editor.core.plugins.font.pickup = function (e) {
            if (!/^BUTTON$/i.test(e.target.tagName)) return false;

            e.preventDefault();
            e.stopPropagation();

            const value = e.target.getAttribute('data-value');
            if (value == "*Customise List*") {
                modal_fonts.openModal(thisObj);
                return;
            }
            if (value) {
                const newNode = this.util.createElement('SPAN');
                newNode.style.fontFamily = value;
                this.nodeChange(newNode, ['font-family'], null, null);
            } else {
                this.nodeChange(null, ['font-family'], ['span'], true);
            }

            this.submenuOff();

        }
```

What actually updates the toolbar to show the correct font/font size?

**Comment by JiHong88** [comment]
Sorry for my belated reply.
More information please.
This issue is not reproduced.

**Comment by sdraper69** [comment]
It would be good to know what sets the toolbar to display the font size and font when clicking in the editor, is there a function I can call? As shown in the gif in my original post, the size always just displays "size" and the font always shows font. I have changed how the fonts and sizes work, very minimally, font size was in my previous post, size is below.


```
 this.editor.core.plugins.fontSize.pickup = function (e) {
            if (!/^BUTTON$/i.test(e.target.tagName)) return false;

            e.preventDefault();
            e.stopPropagation();

            const value = thisObj.editorGetFontSizeFromValue(e.target.getAttribute('data-value'));

            if (value) {
                const newNode = this.util.createElement('SPAN');
                newNode.style.fontSize = value;
                this.nodeChange(newNode, ['font-size'], null, null);
            } else {
                this.nodeChange(null, ['font-size'], ['span'], true);
            }

            this.submenuOff();
        }
```

**Comment by JiHong88** [comment]
For font size, the comments below may be helpful.
https://github.com/JiHong88/SunEditor/issues/855

Is the font using the "font" option?

**Comment by sdraper69** [comment]
"Is the font using the "font" option?" - I'm not sure what you mean by this, could you explain?

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/issues/855
Doesn't this help?

**Comment by sdraper69** [comment]
If I use that code, and keep the name as fontSize, then i can't get it to work as the default font size controls just get used. If I give it a unique name, I couldn't get it to display as a drop-down menu in the toolbar, so couldn't test it fully. Clearly, I am doing something stupid so any guidance would be appreciated.

if the [examples ](http://suneditor.com/sample/html/customPlugins.html)on the website display: 'submenu', isn't a dropdown. Is there something else I should use?

**Comment by sdraper69** [comment]
If you could let me know what actually sets the text you see in the toolbar I would appriciate it i thought it was in the activate function:
fontSize:

```
 active: function (element) {
        if (!element) {
            this.util.changeTxt(this.context.fontSize.targetText, this.hasFocus ? this.wwComputedStyle.fontSize : this.lang.toolbar.fontSize);
        } else if (element.style && element.style.fontSize.length > 0) {
            this.util.changeTxt(this.context.fontSize.targetText, element.style.fontSize);
            return true;
        }

        return false;
    },
```

Font:
```
    active: function (element) {
        const target = this.context.font.targetText;
        const tooltip = this.context.font.targetTooltip;

        if (!element) {
            const font = this.hasFocus ? this.wwComputedStyle.fontFamily : this.lang.toolbar.font;
            this.util.changeTxt(target, font);
            this.util.changeTxt(tooltip, this.hasFocus ? this.lang.toolbar.font + ' (' + font + ')' : font);
        } else if (element.style && element.style.fontFamily.length > 0) {
            const selectFont = element.style.fontFamily.replace(/["']/g,'');
            this.util.changeTxt(target, selectFont);
            this.util.changeTxt(tooltip, this.lang.toolbar.font + ' (' + selectFont + ')');
            return true;
        }

        return false;
    },
```


but if I go through and debug, both those functions seem to do what it should be, e.g. the changeTxt gets a valid string,  but the toolbar just doesn't get updated - are these functions even doing what I think they are?

**Comment by JiHong88** [comment]
Isn't the first argument value of "this.util.changeTxt" wrong? (target, tooltip)

**Comment by sdraper69** [comment]
I just copied that from the official fontSize.js, it matches line 64[ of this](https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/fontSize.js)

**Comment by JiHong88** [comment]
Have you checked that "target" is an element of the correct toolbar?

**Comment by sdraper69** [comment]
Yes, I believe so.

Are they even the correct code that sets the menu? When I click in the editor what actually sets the font in the menu toolbar?

**Comment by JiHong88** [comment]
`this.util.changeTxt(this.context.fontSize.targetText, element.style.fontSize);`
Set the text "fontSize" in the "targetText" element.
Check that these two values are correct and that the code that deletes these two values is called.
https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/fontSize.js#L64

**Comment by sdraper69** [comment]
as you can see I have got it so the drop down menu changes, it's just not the actual text on the toolbar

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25779335/160290105-9bd09beb-c3f0-4ca7-ae32-ceeac8e17c3c.gif)

For the target text I am passing a span, how can i tell if its the right thing?

**Comment by JiHong88** [comment]
https://github.com/JiHong88/SunEditor/issues/910#issuecomment-1079956881
```javascript
// Here's the code to change.
this.util.changeTxt(this.context.fontSize.targetText, element.style.fontSize);

"this.context.fontSize.targetText" // Make sure this is a button on your toolbar.
FontMap["element.style.fontSize"] // Please enter the characters determined according to the fontsize.

```
