### ISSUE TITLE
I am making something Huge with this editor, Please address my following queries if it is currently possible or take is as improvement suggesion?

### ISSUE THREAD

**Issue by roker15** [JiHong88/suneditor#913]
Improvement is suggested --

1.  provide a shorcut to type katex (In MS word Alt+= is the shorcut to write maths)

1. Give editor **toolbar modern look**, like quill editor.
2. Increase Katex writing Input panel size automatically when typing. or **Increase height of input panel of Katex**. Also increase default font size of Katex input text. I need to manually strech it to increase height. ### **If possible provide Katex input box inline **
3. Provision to **save some standard katex that user uses frequently.** I want to extend my notes to chemistry/physics people.
4. **Provision of Text Box** Where i can write some notes inside text box and have capability to change color of background. (It is very important fetaures inside a note)
5. In ballon mode toolbar is showing when something is selected otherwise not. Expected behavious is toolbar should popup on double click or something is selected.
6. Voice typing.
7. Efficient index linking inside document. So that a 50 page note inside editor should behave like a book. and user could navigate easily from one heading to other. Currently this working in PDF form but not in webiste.
8. Will it work efficiently if i write over 50 page notes inside single suneditor instance?

**Comment by roker15** [comment]
> can't you already do #5?
> 
> From my point of view, SunEditor is great but has some basic things that need addressing. Since development is slow due to it seemingly being 1 person (not a criticism) I wouldn't say that #7/#8/#9 are particularly important. #6 you can workaround very easily yourself but I agree probably should be an option out of the box.

Indeed its greatest in the market, u should accelerate it's development. Could u provide hint at least how to address 5 & 6? And what about 1&2

**Comment by sdraper69** [comment]
I am not a developer, just a user. I guess you could contribute with money or development if you want to accelerate its development

**Comment by JiHong88** [comment]
#5 This issue resolved at the v2.42.0.
You can use the `lineAttrReset` option.

**Comment by JiHong88** [comment]
[1]: will be applied in the next version.
[2]: I will improve it in version 3.0.0.
[3,4,5, and 6] Please create a new issue.
[8]: Please let me know if you have a good example.

**Comment by JiHong88** [comment]
For number 4, please give me an example formula that can be used for testing. I will implement it in version 3.1.0.
