### ISSUE TITLE
Can you provide a span with class="notranslate" <span class="notranslate"></span>? Because Google does not translate if you format a text using this class. This will be unique to SUNEDITOR.

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#914]
Can you provide a span with class="notranslate" <span class="notranslate"></span>? Because Google does not translate if you format a text using this class. This will be unique to SUNEDITOR.
see here--

https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website#:~:text=164-,According,-to%20Google%20instructions

You can suggest some workaround till u provide this feature

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by JiHong88** [comment]
I misunderstood the issue.
This issue can be solved with a custom plugin.
http://suneditor.com/sample/html/customPlugins.html#command
```
action: function () {
        if (!this.util.hasClass(this.context.customCommand_2.targetButton, 'active')) {
            const newNode = this.util.createElement('span');
            newNode.className = 'notranslate';
            this.nodeChange(newNode, ['.notranslate'], null, null);
        } else {
            this.nodeChange(null, ['.notranslate'], ['span'], true);
        }
    }
```
