### ISSUE TITLE
Disable hash bookmarks

### ISSUE THREAD

**Issue by seri0zha** [JiHong88/SunEditor#919]
I have some troubles when I try to add a new link which contains a hash symbol. It's structured like **localhost:8080/#/user**. After the link creation I hover it and press edit button. And what I see is that the link domain name was erased and there is only a string which contains the rest of the url after the has symbol.

So, is it possible to disable such behavior? The point is that my app's router is based on this hash symbol, so I can't just remove it from the url.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
