### ISSUE TITLE
se-rtl not set in document created by suneditor

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/SunEditor#921]
@JiHong88 hi

The `se-rtl`  class is set in the editor and works well.
But there is no editor `output in the content`. And prevents rtl from being applied to` the content display`.

This image shows that the `se-rtl`  class is applied correctly in the editor : 

![image](https://user-images.githubusercontent.com/36485982/149625932-6e8df6af-f140-4555-ba7d-fa91ca9063a7.png)

But the image below, which is related to the display of content, clearly shows that the se-rtl class is not set at all.

![image](https://user-images.githubusercontent.com/36485982/149626191-6dff5b41-f484-4505-9d7f-74154b789256.png)

As a result, the text is displayed correctly in the editor and is from right to left.
But the screen is not right and from left to right.

**Comment by Saeeed-B** [comment]
@JiHong88 
Until now, I have been manually giving the output document to the right-to-left class, but I can not continue because I need to create left-to-right documents as well.
So it has to work right.

**Comment by Saeeed-B** [comment]
@JiHong88 Maybe I'm using the wrong method to get the output of the editor.
Do I have to use the getContents method to get the output of the editor?
I use getContents.
?
?

**Comment by Saeeed-B** [comment]
@JiHong88 hi ?!

**Comment by Saeeed-B** [comment]
@JiHong88 hi Please Gaide me , tanks

**Comment by JiHong88** [comment]
@Saeeed-B Sorry for the late reply. 
In the meantime, I haven't been paying attention because of a lot of things.
Getting the content with "getContents" is correct.
However, there is currently no function to import "div" containing class "se-rtl".
Use the "core.options.rtl" option to save the state yourself.

**Comment by Saeeed-B** [comment]
@JiHong88  how please example ,
tank you for answer

**Comment by Saeeed-B** [comment]
@JiHong88 
My site is multilingual and of course some documents are `rtl `and some documents are `ltr`.
I should normally be able to change this for each document

**Comment by Saeeed-B** [comment]
@JiHong88 
You added the change direction button in version[ 2.42](https://github.com/JiHong88/SunEditor/issues/838), and thank you for that.
But these buttons only work in the editor environment and have no effect on the output document.

**Comment by JiHong88** [comment]
@Saeeed-B Do you want to get content with "rtl" option like below? 
```html
<div class="se-rtl">
  <p>....</p>
</div>
```

**Comment by Saeeed-B** [comment]
@JiHong88 direction button
I want the output document to be rtl whenever I rtl it with the [direction button](https://github.com/JiHong88/SunEditor/issues/838).

If you remember added a button for DIRECTION:
[https://github.com/JiHong88/SunEditor/issues/838](https://github.com/JiHong88/SunEditor/issues/838)

**I want this button to work exactly in the output document and in fact the output document is rtl
Of course, this should be the case with all editors.
But this is not the case and this is a bug.**

**Comment by JiHong88** [comment]
For the output document to be "rtl", the class of the parent "div" must be "se-rtl".
How do you create an output document?

**Comment by Saeeed-B** [comment]
@JiHong88 
I want to tell you exactly
It may even be one ltr and the other line rtl.
And the direction of each line must be adjustable with a button. Like a button that changes color.
Of course, it must work correctly in the output document and set the direction in the output document

**Comment by JiHong88** [comment]
@Saeeed-B 
I don't know exactly what you want.
"se-rtl" sets the document orientation of the current editor.
Do you want to make two versions of the output document "rtl" and "ltr"?

**Comment by Saeeed-B** [comment]
@JiHong88
Suppose we have two documents with two different languages
1) Document in English
2) A document in Arabic
  English document must be ltr.
And the Arabic document must be rtl.
Now how do I create these two documents with different directions with one editor?

**Comment by Saeeed-B** [comment]
@JiHong88
In shor@JiHong88
In short
I expect this button, set `rtl` in the output rtl document.
Without I need to give the `se_rtl` class to div. 

My reason is that if I give div to the class `se_rtl`, documents that are in English and ltr,  will not be displayed correctly.

**In fact, your editor is not flexible right now,
And its output must be either rtl at all or ltr at all.**

And this is not true, 
the editor must also set `rtl` class for `rtl` documents, and it must also set `ltr` class for ltr documents.

With this Feature , I can write both rtl and ltr documents.

Could I say what I meant?t
I expect this button, set `rtl` in the output rtl document.
Without I need to give the `se_rtl` class to div. 

My reason is that if I give div to the class `se_rtl`, documents that are in English and ltr,  will not be displayed correctly.

**In fact, your editor is not flexible right now,
And its output must be either rtl at all or ltr at all.**

And this is not true, 
the editor must also set `rtl` class for `rtl` documents, and it must also set `ltr` class for ltr documents.

With this Feature , I can write both rtl and ltr documents.

Could I say what I meant?

**Comment by Saeeed-B** [comment]
> For the output document to be "rtl", the class of the parent "div" must be "se-rtl". 

In short
I expect this button, set rtl in the output rtl document.
Without I need to give the se_rtl class to div.

My reason is that if I give div to the class se_rtl, documents that are in English and ltr, will not be displayed correctly.

In fact, your editor is not flexible right now,
And its output must be either rtl at all or ltr at all.

And this is not true,
the editor must also set rtl class for rtl documents, and it must also set ltr class for ltr documents.

With this Feature , I can write both rtl and ltr documents.

Could I say what I meant?t

**Comment by Saeeed-B** [comment]
@JiHong88 no i dont want two (rtl & ltr) version of one document .

But I want to change the `DIRECTION ` document, so if I want to set the `Direction` to  `RTL`, and if I want to set the `Direction` to `LTR`.
I'm talking about one document in one editor.

**Comment by Saeeed-B** [comment]
@JiHong88 and i want , this changing , set with [this  button ](https://github.com/JiHong88/SunEditor/issues/838).

@JiHong88  Now this button does not affect the output document.

**Comment by JiHong88** [comment]
@Saeeed-B 
What exactly does "output document" mean?
How are you making this?

**Comment by Saeeed-B** [comment]
@JiHong88 
The scenario is very simple. There are two modes

1) If we hit the button and the RTL editor, the SE_RTL class is set in the output document. As a result, the output document is also RTL.
2) But if the button was in the LTR mode, the Se_RTL class output is set. As a result, the output document is also LTR

**Comment by Saeeed-B** [comment]
@JiHong88 
I mean the output document, when we want to display the content of the editor somewhere else.
For example, in the blog, we create a post in the editor. I mean from the output document, **when we want to display that so on the blog**

**Comment by JiHong88** [comment]
I am not an English speaker either. :)

Is there a problem with getting the rtl content with "getContents"? 
I checked that "rtl" is not applied in "print" and "preview".

**Comment by Saeeed-B** [comment]
@JiHong88 
I mean from the output document, the amount I get from the `getContents` function.

**Comment by Saeeed-B** [comment]
@JiHong88 The vlue that gives the `getContents` function does not include `RTL class`. Also does not include `LTR class`

**Comment by Saeeed-B** [comment]
> Is there a problem with getting the rtl content with "getContents"?
> I checked that "rtl" is not applied in "print" and "preview".

Yes, exactly . 
rtl and ltr not in :

1. print 
2. preview
3. value of `getContents `

**Comment by Saeeed-B** [comment]
@JiHong88 
Probably `print `and `preview `outgoing are value of `getContents`.

**Comment by JiHong88** [comment]
I'll fix the "print", "privew" bug.

All content in the editor must be in `<div class="sun-editor-editable">`.
If "rtl" mode, this `<div>` should contain the "se-rtl" class (`<div class="sun-editor-editable se-rtl">`).
https://github.com/JiHong88/SunEditor#3-contents-display

"getContents()" gets the content inside the `<div>`. 
You need to put the content you get with "getContents()" inside a `<div>`.

**Comment by Saeeed-B** [comment]
> 

oh No :( 

@JiHong88 the editor should set `se-rtl` if is `rtl mode`

**Comment by JiHong88** [comment]
simple example 
```
<div class=`sun-editor-editable ${options.rtl ? "se-rtl" : ""}`>
 {getContents()}
</div>
```

**Comment by Saeeed-B** [comment]
@JiHong88 the editor should set se-rtl if is rtl mode ,, not me.

Because some of the documents may be `Ltr`. **I can't change the DIV for each document**

**This is bound by the editor**

**Comment by JiHong88** [comment]
Currently: getContents() => `<p>...</p><p>...</p>`

what you want: getContents() => `<div class="sun-editor-editable se-rtl"><p>...</p><p>...</p></div>`

do you mean this?

**Comment by Saeeed-B** [comment]
> simple example
> 
> ```
> <div class=`sun-editor-editable ${options.rtl ? "se-rtl" : ""}`>
>  {getContents()}
> </div>
> ```

@JiHong88 
I do not have access to `option ` , unless I save the `RTL mode`  in the database.
That doesn't work right
Should be the output of the editor containing `se-rtl` if rtl

**Comment by Saeeed-B** [comment]
> Currently: getContents() => `<p>...</p><p>...</p>`
> 
> what you want: getContents() => `<div class="sun-editor-editable se-rtl"><p>...</p><p>...</p></div>`
> 
> do you mean this?

@JiHong88 
All editors work as like this , Unlike your editor.
So this is a bug in your editor

**Comment by Saeeed-B** [comment]
@JiHong88 I am in a few months.
Thank you if solve this.

Thank you very much for your follow up.
**Be sure when you submit documentation for programmers, I will help you in development and debug.**

**Comment by Saeeed-B** [comment]
@JiHong88 `rtl mode` should change with this button.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
