### ISSUE TITLE
Blockquote button active error

### ISSUE THREAD

**Issue by skadiD** [JiHong88/SunEditor#923]
**Describe the bug**
When clicking a quoted block, top menu `blockquote` will be active, but when clicking others, the status doesn't move
It only happens when the editor already has content
**To Reproduce**
1. Go to [here](http://suneditor.com/sample/index.html)
2. Click blockquote
3. Click other blocks

**Expected behavior**
Status should be reset

**Screenshots**
![image](https://user-images.githubusercontent.com/50161715/150132455-a009941c-93a6-443b-8528-ef880a451e35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge
 - Version 2.42.0

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
