### ISSUE TITLE
Question: <figcaption> not contenteditable

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#924]
After saving an image with image description, description is not editable after opening the editor again.
This is likely not  a fault in Suneditor but a config/setup error by me. However, do you have a hint why contenteditable
is not set to 'true' in figcaption tag when opening the editor and by clicking within the field or image? No contentediable is found in figcaption tag. I am using editor in inline mode.

## Version
2.42.0
I believe I have had this problem for a while so likely not related to 2.42.0

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
