### ISSUE TITLE
How To add content at the cursor position?

### ISSUE THREAD

**Issue by AliBayatMokhtari** [JiHong88/SunEditor#925]
How to put text at the cursor position programmatically without inserting any new line? (Not just appending text to the end of the text area)

## Version
2.41.3

**Comment by SIMHANSOL** [comment]
try it.

insertHTML('text', false, false, false);

http://suneditor.com/sample/html/out/document-user.html#insertHTML

**Comment by AliBayatMokhtari** [comment]
Thanks. That was great ✅🌸
