### ISSUE TITLE
Formatting combinations is not disabled

### ISSUE THREAD

**Issue by kapraltv** [JiHong88/SunEditor#927]
**Describe the bug**
The formatting doesn`t work as it is supposed to.

**To Reproduce**
1. Go to 'Options' tab of the SunEditor site
2. Click on the shortcutsDisable parameter
3. Create a new configuration
4. Write text and click on formatting [combinations]

**Expected behavior**
If shortcutsDisable array contains formatting features ('bold', 'underline', 'italic', 'undo'), the font of the text should not be changed.

[**Screenshots**]
![bolditalicunderlineundo](https://user-images.githubusercontent.com/69194044/151352198-af0f4bb7-1a35-4a06-be05-ab444a624fed.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: [97.0.4692.99]

**Additional context**
I would like to add that ctrl + shift + s and ctrl + [ or ] combinations works correctly. If it is not a bug, could you please provide some information how to fix it? Thanks!

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
