### ISSUE TITLE
drag out of editor or drag on pasted text

### ISSUE THREAD

**Issue by SIMHANSOL** [JiHong88/suneditor#928]
안녕하세요!
에디터 1년간 사용중입니다.

굵기가 적용된 텍스트를 드래그 하여 에디터 안에서 드래그를 해제하면 문제가 없는데
에디터 밖으로 드래그를 해제하면 툴바에 굵기 적용이 갱신되지 않는 문제가 있습니다.
대다수 사람들이 문장 전체를 드래그 할 때 밖으로 해제하기 때문에 의도치 않은 작동을 합니다.
에디터를 아예 풀스크린으로 두지 않는 이상 해결 방법이 없습니다.

https://user-images.githubusercontent.com/59974669/151505021-23d1ca47-f31a-402c-9cba-b1bd8c94b567.mp4

<br/>
<hr>
<br/>

굵기가 적용된 텍스트쪽으로 드래그를 끝내고 다시 글 작성하기 위해 맨 뒤를 클릭하면 
작성한 텍스트에 굵기가 적용되지 않지만 툴바엔 굵기가 active 상태라서 사용자에게 혼란을 줍니다.
툴바의 적절한 갱신이 필요한 것 같습니다.

https://user-images.githubusercontent.com/59974669/151662640-8c802ba5-ce35-4406-801e-d9859cc93978.mp4

<br/>
<hr>
<br/>

붙여넣기 이후 문자 스타일을 변경하려고 할 때 발생하는 문제입니다.
드래그 위치에 따라 스타일이 변경되거나 변경되지 않습니다.

https://user-images.githubusercontent.com/59974669/151506310-bd204529-a816-4027-8ca6-9ec82d325682.mp4

<br/>
<hr>
<br/>

붙여넣고 텍스트 입력시 앞글자 하나가 제대로 정상 입력이 되지 않는 문제입니다.

https://user-images.githubusercontent.com/59974669/151516891-6f156137-12b8-4d0b-96e6-a48211f513d5.mp4

<br/>
<hr>
<br/>

이외에 이놈의 붙여넣기가 문제가 많습니다.
붙여넣기 이후에 커서 방향이 이상한 곳을 보고 있다거나, 드래그가 안된다거나, 
본문에 적용한 스타일이 삭제된다거나, 본문 글이 모두 없어지는 경우 등...
문제가 많이 있었는데 발생 원인을 찾아내면 작성하겠습니다. ㅠ

그리고 붙여넣기 관련해서 불편한 점이 있는데 
보통 사람들이 에디터 안에서 복사 붙여넣기를 많이 하시더라고요.
근데 에디터에서는 강제로 줄바꿈 처리를 하게 되었어서
\<br> 을 제거해봤는데 붙여넣기 할때마다 \<span> 안에 \<span>, 또 그 안에 \<span> 식으로
쌓이기가 되서 스타일 적용시 부분만 적용되거나 의도하지 않게 오작동하는 문제가 발생하더군요.

![span](https://user-images.githubusercontent.com/59974669/151511770-80a428cf-d1bb-4614-b9ae-ed66b11d0670.JPG)

네이버 블로그처럼 에디터 안에서 복사 / 붙여넣기를 하면 줄바꿈없이 한줄로 처리가 가능할까요?
개선이 필요합니다. 👍 
사랑합니다.

브라우저: chrome

**Comment by JiHong88** [comment]
안녕하세요!
늦게 확인했더니 동영상이 안보이는것 같네요ㅠ
붙여넣기는 큰작업이라 3.0.0버전에서 개선할 예정입니다.
드래그 이슈는 크로미움 웹 브라우저에서 생기는 문제인데.. 해결이 어렵네요ㅠ

일단 붙여넣기는 3.0.0버전에서 개선 예정이지만, 
드래그는 확답을 드리기가 어렵지만, 같이 해결해 보겠습니다.
