### ISSUE TITLE
Feature: Indentation on tables

### ISSUE THREAD

**Issue by DeZZar** [JiHong88/SunEditor#93]
Hi @JiHong88,

Just looking at the indentation functionality and found that when you put the cursor on the left side of a table and click indent it selects and indends all other content and not the table.

This might not be an issue in your original implementation as you had tables as full width.  I've modified this slightly to allow table width to be auto, max-width 100 and set the cell width to a minimum.  Tables now grow appropriately based on content.  However, if the user wants to indent the table to align the content it wont indent (doesnt apply margin-left to tables).

Is there any change you might be able to make an update to apply the same margin to tables with the indent tool?

- Derrick

**Comment by JiHong88** [comment]
Hi @DeZZar 

I'll upgrade a this feature soon.

Tabkey behavior is easy to implement.

If you have modified the table plugin, is there any code I can refer to?

**Comment by JiHong88** [comment]
Hi @DeZZar 

Fixed in [v2.15.0](https://github.com/JiHong88/SunEditor/releases/tag/2.15.0).

Thank you :)

**Comment by JiHong88** [comment]
Hi @DeZZar 

When the cursor is on the left side of the table, the window's selection object will bring the entire area of the editor.

So I modified it to not update the selection object in that situation.

Now, when you use the tab key on the left side of the table, the indent will be applied to the position of the previous cursor position.

Updated in [v2.15.0](https://github.com/JiHong88/SunEditor/releases/tag/2.15.0).

Thank you :)

**Comment by DeZZar** [comment]
@JiHong88 thanks again mate!

**Comment by JiHong88** [comment]
There was a critical bug in version 2.15.0.

Fixed in [v2.15.1](https://github.com/JiHong88/SunEditor/releases/tag/2.15.1).

Thank you.

**Comment by JiHong88** [comment]
HI @DeZZar ,

Fixed again [v2.15.2](https://github.com/JiHong88/SunEditor/releases/tag/2.15.2)
