### ISSUE TITLE
Applying Font size to list should remove all child font sizes

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#930]
**Describe the bug**
I have applied a font size to a piece of text. In my case it is in % but could be anything. When you then turn it into a list and change the font size it is applied twice resulting in wrong size.

**To Reproduce**
1. type two lines of text
2. Set a font size
3. look in developer tools you'll see style="font-size: xx" to the paragraph

![image](https://user-images.githubusercontent.com/25779335/152873478-8f0b1e63-c23c-4ead-91d4-23ef231bd417.png)

4. highlight all the text, turn them into a list
5. highlight all the text and apply a font size - it can be the same size
5. you will now see the list item has a font size AND the child does. I don't believe this is correct behavior. In my case ive got something that is 200% the size of something already 200% - which is not what I want.

![image](https://user-images.githubusercontent.com/25779335/152873573-7864f1af-efc1-44ae-b069-d4138d4679fb.png)

**Expected behavior**
I would expect when you have everything selected and apply a font size to a list, it removes any child font sizes that are there. 

If you could point me to a work around I would be very grateful

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version latest

**Additional context**
I am applying % based font sizes, but this can still be a problem for "normal" font units too

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
