### ISSUE TITLE
Ability to control several editors at once via a single controller/toolbar

### ISSUE THREAD

**Issue by sdraper69** [JiHong88/SunEditor#931]
I have several editors on my page, it would be great to be able to have a single controller that when I have 1 item selected just applies changes to that, but if I have multiple selected it applies to them all.

It would not only save on the overhead of having lots of individual toolbars. It would be extremely user-friendly. At the moment, the end-user has to go in and edit each item in turn if they want (for example) all the text to be a bigger size.

https://github.com/JiHong88/SunEditor/issues/916 this would also help but slightly different work flow

**Comment by JiHong88** [comment]
It would be better to implement this function yourself. 
```javascript
for (let i = 0; i < editors.length; i++) {
editors[i].core.commandHandler(null, "selectAll");
editors[i].core.commandHandler(null, "STRONG");
}
```
The related functions will be considered in version 3.0.0, which supports multi-mode.
