### ISSUE TITLE
Bullet point list bug

### ISSUE THREAD

**Issue by DeZZar** [JiHong88/SunEditor#94]
Hi @JiHong88,

I have identified a bug with the bullet list.  To reproduce:

1) Inset some normal text at the top of the editor
2) Start a bullet point list (bullets or numbers)
3) Fill in the list to contain say "Item1, Item 2, Item 3, Item 4" as bullet points
4) Place the cursor at the start of Item 4 (between the bullet and the letter 'I') and press backspace

Expected behaviour: List item 4 removes the bullet point, and continues to backspace normally until it joins the end of list item 3 and the rest of the bullet list remains in place (refer say the same behaviour in an email editor)

Actual behaviour: List item 4 is added to the end of whatever line of text preceeds the bullet list and the bullet items 1 through 3 are now presented in reverse order as paragraphs without bullet points

**Comment by DeZZar** [comment]
setup to reproduce:
![image](https://user-images.githubusercontent.com/6326508/57276926-455ca800-70e6-11e9-819a-a804c6097772.png)

result:
![image](https://user-images.githubusercontent.com/6326508/57276974-64f3d080-70e6-11e9-8fce-b4f285649b22.png)

**Comment by JiHong88** [comment]
Hi @DeZZar 

Thanks for the detailed explanation.

Fixed in [v2.15.0](https://github.com/JiHong88/SunEditor/releases/tag/2.15.0).

Thank you :)

**Comment by DeZZar** [comment]
@JiHong88 thank you for the support.  Tested in v2.15.0 and working as expected!

**Comment by JiHong88** [comment]
There was a critical bug in version 2.15.0.

Fixed in [v2.15.1](https://github.com/JiHong88/SunEditor/releases/tag/2.15.1).

Thank you.

**Comment by JiHong88** [comment]
HI @DeZZar ,

Fixed again [v2.15.2](https://github.com/JiHong88/SunEditor/releases/tag/2.15.2)
