### ISSUE TITLE
Copy and Pasting does not follow default font after disabling font size/font in the buttons. 

### ISSUE THREAD

**Issue by mvqwerty** [JiHong88/SunEditor#944]
Disabled font size/ font 
when i copy and paste a font different from the default font, it will not follow the default font. Am I allowed to enable only one type of font/font size?

**Comment by JiHong88** [comment]
Version 3.0.0 has been released.
Thank you for your engagement with the project.
This issue has been resolved for version 3.0.0.
If the problem persists or if you believe this issue is still relevant,
please open a new issue referencing this one.
