### ISSUE TITLE
Print functionality stopped working after updating chrome to 99.0.4844.51 today. It is working in Microsoft edge and It was working in previsous version of chrome.

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#947]
To make it easier for us to help you, please include as much useful information as possible.

## Version
Write the version of the Editor you are currently using.

**Comment by roker15** [comment]
Ok i got the source of problem , i am using this extension of voice typing 

https://chrome.google.com/webstore/detail/voice-in-voice-typing/pjnefijmagpdjfhhkpljicbbpicelgko?hl=en

when i disable this extension print is working. What can i do ? this is important extension for me.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
