### ISSUE TITLE
editor height ("onResizeEditor")

### ISSUE THREAD

**Issue by abvas** [JiHong88/SunEditor#948]
## Additional context
Hey!

Thanks for the great plugin.

But I have a problem.
I need to dynamically track changes in editor height.
But I can't figure out how to do it.
I tried to use the "onResizeEditor" event. Doesn't react in any way to changing the height of the editor.

Here's an example:
[https://codepen.io/abvas/pen/xxPBjqK?editors=0010](https://codepen.io/abvas/pen/xxPBjqK?editors=0010)

Tell me what am I doing wrong?

Thanks.

**Comment by JiHong88** [comment]
Do you need an event when the height changes due to a line break?

**Comment by abvas** [comment]
It is necessary to track the change in the height of the entire editor or container (in my example it is class="sun-editor" id="suneditor_sample" or maybe class="se-container").

It is necessary to track the change in height, regardless of the cause. This can be due to a line break, inserting data, inserting a video or image, changing the screen width and changing the height of the toolbar, hiding or showing the toolbar, and so on.

Thanks.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
