### ISSUE TITLE
Set background-color for table rows/cells

### ISSUE THREAD

**Issue by Sch-Tim** [JiHong88/suneditor#954]
Is it possible to add a custom background color to table cells and/or table rows? 
I know the hilite-text feature, but I want to set the background for the whole area, not only the text. 
If not, are there any plans to add it?

## Version
^2.42.0

**Comment by Sch-Tim** [comment]
I'd like to add: 
Setting the border style and a fixed width would be a great feature too. Originally I wanted to create a second issue for that, but it may be better to add it here since it's all table related.

**Comment by JiHong88** [comment]
This feature is update at the v3.0.0.
It will take several months..

**Comment by agcyphers** [comment]
https://github.com/JiHong88/SunEditor/issues/889
