### ISSUE TITLE
SetContents: Table and List in HTML: List not displayed

### ISSUE THREAD

**Issue by DanielMertins** [JiHong88/SunEditor#957]
**Describe the bug**
I try to load html content for a simple ul or li list with table included. **But List is missing in editor**.

**To Reproduce**
Use this Strings with "editor.setContents(html)". Also try with "value" in options.

List is Missing - _This is the bug_:
`<h2>Test head II<br></h2><ul><li>Simple List<ul><li>deep<br></li></ul></li></ul> <table><tbody><tr><td><div>asd<br></div></td><td><div>asd<br></div></td></tr><tr><td><div>asd<br></div></td><td><div>asd<br></div></td></tr></tbody></table>`

Check (just removed the table in code) - _This is working_:
`<h2>Test head II<br></h2><ul><li>Simple List<ul><li>deep<br></li></ul></li></ul>`

How to reproduce by yourself:

1. Load the Editor
2. Write a headline, a simple list, a table
3. Save the String with `editor.getContents(false)` (also tried with true)
4. Use this String with setContents

**Expected behavior**
Should show list AND table.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 98.0

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
