### ISSUE TITLE
Cursor position error addRange / setRange when try to add a list

### ISSUE THREAD

**Issue by cub** [JiHong88/SunEditor#961]
**Describe the bug**
Cursor goto at position 0 when you try to add a list (`ul` or `ol`) after an unstyled text.

**To Reproduce**
1. Go to [http://suneditor.com/sample/index.html](http://suneditor.com/sample/index.html)
2. Remove all content of the wysiwyg 
3. Write a simple word without style
4. Press <kbd>Enter</kbd> for a new line
5. Try to add a list
6. The cursor went to start, and error in console appear :
```
addRange(): The given range isn't in document.
setRange @ core.js:1084
pickup @ list.js:440
```

**Expected behavior**
Cursor stay at his position to write content in the list.

**Desktop (please complete the following information):**
 - Chromium
 - Version 99.0.4844.51 (Official Build) snap (64-bit)

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
