### ISSUE TITLE
Responsive without browser resize / zoom

### ISSUE THREAD

**Issue by Wyzix33** [JiHong88/SunEditor#974]
## Version
"suneditor": "^2.42.0",
## Additional context
Hi, 
thank you for this great editor, just started integrating it into my project and I have noticed that the responsive feats only work when resizing / loading / zooming my browser window, but I have my forms inside a [Split.js](https://github.com/nathancahill/split/tree/master/packages/splitjs) container that can be resized by user.
My question is how can I trigger the resize function manually to let the editor know that the form width has changed so it can recalculate what buttons should be visible based on the editor width.
Here is a screenshot  how the editor looks when changing the width by browser resize and element resize.

I can set a ResizeObserver on my form to catch all resizes, just need a way to let the editor know it's width changed. 

![browser-resize](https://user-images.githubusercontent.com/13553412/161525658-44364d37-c0fc-4273-9666-76ac03db585a.jpg)
![element-resize](https://user-images.githubusercontent.com/13553412/161525660-60d57370-b8c9-4102-a00c-c97011631da2.jpg)

Thanks

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.
