### ISSUE TITLE
How to have a good style in the dark mode?

### ISSUE THREAD

**Issue by Saeeed-B** [JiHong88/suneditor#978]
@JiHong88 hi
I implemented Dark mode for my site.
But the editor is not compatible with Dark mode.

this is result of editor in dark mode :
![image](https://user-images.githubusercontent.com/36485982/162672962-3bd91f61-af49-4e6f-99a6-7908fbb1a8e4.png)

**There must be a way to manage colors in the dark.**
I think we should be able to choose the equivalent of each color in the dark mode.
Or we can customize the styles

**Comment by JiHong88** [comment]
https://huro.cssninja.io/components-plugins-editor-sun.html
Please refer to this site using "suneditor".
In 3.0.0, I plan to improve it so that you can easily change the user theme.

**Comment by Saeeed-B** [comment]
@JiHong88 What is the status of version 3?
I think we should start and solve the problems one by one

**Comment by booellean** [comment]
@JiHong88, I would be happy to make a pull request to implement this functionality. It would be a simple matter of adding native variables to the css; then a user could update those variables to match their custom light and dark themes.

**Comment by melloware** [comment]
+1 for Dark Theme mode.
