### ISSUE TITLE
Placeholder no longer works in v2.43.0

### ISSUE THREAD

**Issue by andylwelch** [JiHong88/SunEditor#983]
**Describe the bug**
The placeholder property no longer works.

**To Reproduce**
1. Go to the samples
http://suneditor.com/sample/index.html

2. Delete all the content in the text area
3. Click out of the input

**Expected behavior**
See the placeholder text "Start typing something"

**Screenshots**
![image](https://user-images.githubusercontent.com/7505965/165196756-41970429-18e8-45cc-9777-abbf23411961.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 100.0.4896.127 (latest)

**Additional context**
This is a breaking change and badly impacts on the user experience

**Comment by JiHong88** [comment]
Thanks for reporting this issue.
The [2.43.1](https://github.com/JiHong88/SunEditor/releases/tag/2.43.1) version has been updated.
Thank you.

**Comment by andylwelch** [comment]
Thank you! I can confirm it is fixed.
