### ISSUE TITLE
Incorrect behavior when typing in Japanese

### ISSUE THREAD

**Issue by Dimarione** [JiHong88/suneditor#984]
**Describe the bug**
I am using SunEditor as text input field for chat.
I encountered strange behavior when typing in Japanese.
Japanese Microsoft IME package installed on Windows 10 operating system

When entering the first character from the syllable of the hieroglyph
I capture the onInput event of inserting a hieroglyph into a text field
And immediately after it I observe the second event that removes this hieroglyph from the field.

After reloading the browser page, this behavior is observed only when the first character is entered.
If any character is already present in the input field, this behavior is not observed.

Similar behavior can be reproduced by opening the "example" page from the SunEditor repository.
If you delete the text from the example text editor 

![suneditro text example not deleted](https://user-images.githubusercontent.com/43163128/165258747-092e8170-ec4b-44b6-97c2-c3856a17f2fc.png)

![suneditro text example deleted](https://user-images.githubusercontent.com/43163128/165258804-c45e74e1-8f4e-434e-8810-62810284abda.png)

And start writing in Japanese.
When the first character is entered, a double onInput event will also be observed.
But due to other text editor setup from the SunEdior example.
The second event does not delete the first character, but shifts the text input cursor one character back.

![suneditor reproduse issue](https://user-images.githubusercontent.com/43163128/165258896-96430545-c548-462a-ab4e-b3206b9052e7.gif)

![suneditor not reproduse issue](https://user-images.githubusercontent.com/43163128/165260764-a54ac198-e4ce-4ebf-b07d-23d01776d773.gif)

**To Reproduce**
1. Download the SunEditor repo
2. Go to 'sample/html/examples.html'
3. Open examples.html in code editor
4. remove text inside <p> from line 167
5. Open examples.html in browser
6. move on the page to User Functions text editor example.
7. try typing in Japanese

**expected behavior**
when you enter the first character of a Japanese syllable into an empty text input field, 
only one onInput event fires

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome]
 - Version [100.0.4896.127]

**Comment by JiHong88** [comment]
This issue is not  reproduced.
Please tell me exactly how to enter it..

**Comment by RonanMcCaffrey** [comment]
I can quickly recreate this issue using codesandbox.ie, at the following link:
https://codesandbox.io/s/8exq4

Where i change my keyboard to Japanese, type "yamaha" into the editor (it appears correctly), press enter to go to a new line
type "yamaha" again, this time and any subsequent time it appears in hiragana as、i believe,  "amaha", where the first character is missing, due to some input event seemingly messing with the character conversion.

Please see attached gif for the process, i just refresh the browser and change my windows language off screen at the start of the gif before typing.

![codeSandboxJapanaseCharacter](https://user-images.githubusercontent.com/4432512/166942271-fc08c79e-03c8-453e-834f-852ac880ee2d.gif)

**Comment by RonanMcCaffrey** [comment]
Did the above code sample help highlight the issue?

**Comment by Dimarione** [comment]
Hi, @JiHong88 
Could you try to reproduce the problem again?

**Comment by JiHong88** [comment]
@RonanMcCaffrey @Dimarione 

https://user-images.githubusercontent.com/13191953/168423875-70f49db7-8941-4e51-958c-c99f0e5ba630.mov

Am I not testing properly?
Japanese option too. 😢

**Comment by RonanMcCaffrey** [comment]
Our above two examples were on a windows machine. So this looks like it could be a windows specific issue, I've now confirmed that it doesn't appear to happen on Macs. Do you have access to a windows machine which could help highlight the issue?

**Comment by Dimarione** [comment]
Hi, @JiHong88 
we still need you to reproduce this issue.
Do you have access to a windows machine which could help highlight the issue?

**Comment by JiHong88** [comment]
@Dimarione Yes, I will try to reproduce it today.
I'll give you feedback again.

**Comment by Dimarione** [comment]
Hi @JiHong88 
Could you tell?
When you start typing in a textarea field,
Do you start typing in an empty field or do you delete the text first and then start typing in Japanese?

the main criterion for reproducing the issue
so that the text field after the first rendering does not have a single typed character inside

**Comment by JiHong88** [comment]
@Dimarione 
I erased the existing character and entered it.
Do I have to input when there is no character from the beginning?

**Comment by RonanMcCaffrey** [comment]
Yes, you need to start the text editor completely blank, and then start typing to notice the character conversion issue. It doesn't happen when you manually clear out a textbox and start typing

**Comment by Dimarione** [comment]
@JiHong88 
"Do I have to input when there is no character from the beginning?"
Yes, it is necessary.

The text field must not contain a template string

**Comment by Dimarione** [comment]
@JiHong88

**Comment by JiHong88** [comment]
I reproduced the problem.

**Comment by JiHong88** [comment]
This issue is reproduced only at this [link](https://codesandbox.io/s/8exq4).
It will take some time to solve the problem :(

**Comment by JiHong88** [comment]
@Dimarione @RonanMcCaffrey 
The [2.43.10](https://github.com/JiHong88/SunEditor/releases/tag/2.43.10) version has been updated.
Can you test if the problem is solved?

**Comment by RonanMcCaffrey** [comment]
Thanks for that @JiHong88 , i will get to test that out this week and will confirm if all is okay!

**Comment by RonanMcCaffrey** [comment]
Apologies for the delay @JiHong88 , I've tested that change out now and all appears to be fine, thanks for fixing it!

**Comment by aburd** [comment]
Perhaps this issue can be closed?

**Comment by Dimarione** [comment]
Sorry for taking so long to close this issue.
