### ISSUE TITLE
React custom plugins error (커스텀 버튼 에러 및 etc)

### ISSUE THREAD

**Issue by KimseungMoo** [JiHong88/SunEditor#989]
To make it easier for us to help you, please include as much useful information as possible.

## Version
"suneditor": "^2.42.0",
"suneditor-react": "^3.4.0",

## Additional context

1. 커스텀 버튼 사용 시 

display option이 container일 때는 add function이 최초 1회만 실행,

command일 때는 실행되지 않고 아래와 같은 에러가 발생합니다.

- display option command
<img width="698" alt="스크린샷 2022-05-02 오후 4 39 16" src="https://user-images.githubusercontent.com/77320847/166434169-75706cc1-55b6-488d-80a8-185bfeacb36e.png">

- display option container
<img width="436" alt="스크린샷 2022-05-03 오후 6 47 39" src="https://user-images.githubusercontent.com/77320847/166434175-2ec511de-42c4-4447-b114-8f78f1187711.png">

```
setOptions={{
buttonList:[[{
                name: 'USER',
                dataDisplay: 'command',
                title: "USER",
                innerHTML: '<span>USER</span>'
              },]]
}}


const user = {
    name: "USER",
    display: 'command',
    title: "USER",
    innerHTML: '<span>USER</span>',
    buttonClass: "'',
    add: ({ core, targetElement }: any) => {
      insertTag("USER")
      setTagName("USER")
    },
    // active: () => { },
    // action: () => { },
  }

```

2. 붙여넣기 했을 때 (onPaste) 내용이 하나의 <p>태그에 통째로 들어가서 리스트 적용 시 같이 묶입니다.

행마다 개별로 스타일을 적용하고 싶습니다.

<img width="1454" alt="스크린샷 2022-05-03 오후 8 02 28" src="https://user-images.githubusercontent.com/77320847/166442168-ad19606d-46e8-49ad-a3df-595e639fd1a6.png">

3. senContents method 사용하면 insertHTML로 삽입한 컨텐츠의 background-image 값이 사라집니다.
```
원본
<span class="og-image" contenteditable="false" data-image="${image url}" style="display: block !important; background-image: url('${image url}'); background-position: 50% !important; background-size: cover !important; background-repeat: no-repeat !important; width: 100px !important; height: 100px !important;"></span>
<div class="close-outer" style="display: none;">
  <span class="og-close"></span>
</div>

결과물
<span class="og-image" contenteditable="false" style="display: block !important; background-image: url('></span> <div class=" close-outer"=""></span>
``` 

직접 개발을 해야하는 부분인지 썬에디터 내장 method로 해결 가능한지 궁금합니다.

**Comment by JiHong88** [comment]
1. `add: ({ core, targetElement }: any)` => `add: (core: any, targetElement: Element | null)`
2. [onPaste](http://suneditor.com/sample/html/out/document-user.html#onPaste) 함수에서 HTML을 직접 수정해야 합니다.
3. 기본적으로 허용된 태그와 스타일외에는 삭제 됩니다.
    `attributesWhitelist: {all: "style"}` 옵션을 추가해야 합니다.

**Comment by KimseungMoo** [comment]
1. 말씀하신대로 수정해보았으나, 동일에러 발생합니다. add function에 현재 console.log만 1줄 있습니다. active와 action은 사용하지 않았습니다.
3. 옵션 추가로 스타일은 적용되었습니다. insertHTML에서 img태그는 포함시킬 수 없나요? 빠진 상태로 들어가네요.

**Comment by JiHong88** [comment]
img 태그는 기본 허용이라 옵션 안넣어도 됩니다.
insertHTML로 넣은 내용을 볼수있을까요

**Comment by KimseungMoo** [comment]
이미지 넣었을 때 추가되는
<div class="se-component se-image-container __se__float-"> 삭제했었는데 img태그를 포함하고 있었네요. 

추가적으로 태그가 <span /> 이런 형태로 들어갔을 때 문제가 생겨서 <span></span> 이렇게 수정하니까 괜찮아졌습니다.
