### ISSUE TITLE
Insert link text with Font Awesome

### ISSUE THREAD

**Issue by redone80** [JiHong88/SunEditor#99]
Hi,

I have used your editor. It works well, 
But I got an issue. I have inserted icon font like Font Awesome via link button. The text is '<i class="fab fa-youtube"></i>' but I got result: '&lt;i class="fab fa-youtube"&gt;&lt;/i&gt;'
So web browser renders incorrect.

**Comment by JiHong88** [comment]
Hi @redone80 :)

The Link button is a button that only accepts URL addresses.

There is no button to enter an icon tag in the editor.

Do you need that function?

**Comment by redone80** [comment]
Hi @JiHong88,

It is simple display text of anchor tag is what user inputs.
And if you have free time please take a look Trumbowyg editor.
Thank you

**Comment by JiHong88** [comment]
Hi @redone80 

I reviewed your feedback.
It was not difficult to apply right away, but there were other side effects.
So I think I need some time.
I'm going to update to the next version.
Thank you :)
